import{NextResponse}from'next/server';import{createClient}from'@/lib/supabase/server';
const stripePost=async(path:string,secret:string,form:URLSearchParams)=>{const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});const body=await r.json() as any;if(!r.ok)throw new Error(body?.error?.message||'Stripe request failed.');return body};
const nullableDate=(v:any)=>String(v||'').trim()||null;
async function sendExternalLeadNotices(s:any,businessId:string,leadId:string){const[{data:p},{data:l},{data:b}]=await Promise.all([s.from('business_lead_programs').select('email_delivery_notifications,sms_delivery_notifications,notification_email,notification_phone,billing_email').eq('business_id',businessId).maybeSingle(),s.from('leads').select('service,city').eq('id',leadId).maybeSingle(),s.from('businesses').select('name').eq('id',businessId).maybeSingle()]);const result:any={};const site=process.env.NEXT_PUBLIC_SITE_URL||'https://central-il-local-pros.vercel.app',subject=`New lead delivered to ${b?.name||'your business'}`,body=`A ${l?.service||'local service'} lead in ${l?.city||'your service area'} was delivered to your Lead Inbox. Review the lead securely at ${site}/business-portal/leads?business=${encodeURIComponent(businessId)}. Lead billing is based on delivery under your agreement, not whether the lead closes.`;
 if(p?.email_delivery_notifications){const key=process.env.RESEND_API_KEY,from=process.env.LEAD_NOTIFICATION_FROM_EMAIL,to=p.notification_email||p.billing_email;if(key&&from&&to){try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,text:body})});result.email=r.ok?'sent':`error_${r.status}`}catch{result.email='error'}}else result.email='provider_not_configured'}
 if(p?.sms_delivery_notifications){const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,from=process.env.TWILIO_FROM_NUMBER,to=p.notification_phone;if(sid&&token&&from&&to){try{const f=new URLSearchParams();f.set('To',to);f.set('From',from);f.set('Body',body);const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:f});result.sms=r.ok?'sent':`error_${r.status}`}catch{result.sms='error'}}else result.sms='provider_not_configured'}return result}
export async function POST(req:Request){try{const body=await req.json() as any;const s=await createClient();const action=String(body.action||'');
 if(action==='configure'){
  const model=String(body.billing_model||'pay_per_lead'),saleMode=String(body.lead_sale_mode||'exclusive'),cadence=String(body.auto_invoice_cadence||'manual');
  const{data,error}=await s.rpc('configure_business_lead_program_v2',{p_business_id:body.business_id,p_featured_addon_enabled:Boolean(body.featured_addon_enabled),p_billing_model:model,p_per_lead_price_cents:model==='pay_per_lead'?Math.round(Number(body.per_lead_price_cents||0)):null,p_bundle_lead_count:model==='lead_bundle'?Number(body.bundle_lead_count||0):null,p_bundle_price_cents:model==='lead_bundle'?Math.round(Number(body.bundle_price_cents||0)):null,p_due_days:Number(body.due_days??7),p_billing_email:body.billing_email||null,p_notes:body.notes||null,p_status:body.status||'active',p_agreement_started_on:nullableDate(body.agreement_started_on),p_agreement_ends_on:nullableDate(body.agreement_ends_on),p_max_leads_per_month:Number(body.max_leads_per_month||0)>0?Number(body.max_leads_per_month):null,p_lead_sale_mode:saleMode,p_max_buyers_per_lead:saleMode==='shared'?Number(body.max_buyers_per_lead||2):1,p_auto_invoice_enabled:Boolean(body.auto_invoice_enabled),p_auto_invoice_cadence:cadence,p_stop_delivery_on_open_balance:Boolean(body.stop_delivery_on_open_balance),p_stop_delivery_on_overdue:Boolean(body.stop_delivery_on_overdue),p_overdue_grace_days:Number(body.overdue_grace_days||0),p_manual_delivery_hold:Boolean(body.manual_delivery_hold),p_delivery_hold_reason:body.delivery_hold_reason||null,p_notify_on_delivery:body.notify_on_delivery!==false,p_notify_on_invoice:body.notify_on_invoice!==false});
  if(error)throw error;const{error:prefError}=await s.from('business_lead_programs').update({email_delivery_notifications:Boolean(body.email_delivery_notifications),sms_delivery_notifications:Boolean(body.sms_delivery_notifications),notification_email:String(body.notification_email||'').trim()||null,notification_phone:String(body.notification_phone||'').trim()||null}).eq('business_id',body.business_id);if(prefError)throw prefError;return NextResponse.json({ok:true,program_id:data});
 }
 if(action==='deliver'){const{data,error}=await s.rpc('deliver_billable_lead',{p_lead_id:body.lead_id,p_business_id:body.business_id,p_route_reason:body.route_reason||'Paid lead delivery',p_route_rank:Number(body.route_rank||0)});if(error)throw error;const notifications=await sendExternalLeadNotices(s,String(body.business_id),String(body.lead_id));return NextResponse.json({ok:true,recipient_id:data,notifications});}
 if(action==='create_invoice'){const{data,error}=await s.rpc('create_lead_invoice',{p_business_id:body.business_id,p_notes:body.notes||null});if(error)throw error;return NextResponse.json({ok:true,invoice_id:data});}
 if(action==='mark_paid'||action==='void'){const status=action==='mark_paid'?'paid':'void';const{error}=await s.rpc('set_lead_invoice_status',{p_invoice_id:body.invoice_id,p_status:status,p_stripe_invoice_id:null,p_hosted_url:null,p_pdf_url:null});if(error)throw error;return NextResponse.json({ok:true,status});}
 if(action==='review_credit'){const amount=body.approved_credit_cents==null||body.approved_credit_cents===''?null:Math.round(Number(body.approved_credit_cents));const{data,error}=await s.rpc('review_lead_credit_request',{p_request_id:body.request_id,p_decision:body.decision,p_approved_credit_cents:amount,p_staff_notes:body.staff_notes||null});if(error)throw error;return NextResponse.json({ok:true,result:data});}
 if(action==='send_invoice'){
  const secret=process.env.STRIPE_SECRET_KEY;if(!secret)return NextResponse.json({error:'Stripe billing is not connected.'},{status:503});
  const{data:inv,error:invErr}=await s.from('lead_invoices').select('id,invoice_number,business_id,lead_count,bundle_count,billing_model,subtotal_cents,credit_applied_cents,amount_due_cents,status,due_at,hosted_invoice_url,stripe_invoice_id').eq('id',body.invoice_id).maybeSingle();if(invErr||!inv)return NextResponse.json({error:'Lead invoice not found.'},{status:404});if(inv.status==='paid'||inv.status==='void')return NextResponse.json({error:`Invoice is already ${inv.status}.`},{status:400});if(Number(inv.amount_due_cents)<=0)return NextResponse.json({error:'This invoice has no balance due after credits.'},{status:400});if(inv.status==='sent'&&inv.hosted_invoice_url)return NextResponse.json({ok:true,url:inv.hosted_invoice_url,reused:true});
  const[{data:biz},{data:program},{data:subs}]=await Promise.all([s.from('businesses').select('name').eq('id',inv.business_id).maybeSingle(),s.from('business_lead_programs').select('billing_email,stripe_customer_id,due_days').eq('business_id',inv.business_id).maybeSingle(),s.from('subscriptions').select('provider_customer_id,status,updated_at').eq('business_id',inv.business_id).in('status',['active','trialing','past_due']).order('updated_at',{ascending:false}).limit(1)]);
  let customer=program?.stripe_customer_id||subs?.[0]?.provider_customer_id||'';if(!customer){if(!program?.billing_email)return NextResponse.json({error:'Add a billing email before sending this invoice.'},{status:400});const f=new URLSearchParams();f.set('name',biz?.name||'Central Illinois Local Pros Business');f.set('email',program.billing_email);f.set('metadata[business_id]',inv.business_id);f.set('metadata[source]','central_il_local_pros_lead_billing');const c=await stripePost('customers',secret,f);customer=c.id;await s.from('business_lead_programs').update({stripe_customer_id:customer}).eq('business_id',inv.business_id);}
  const days=Math.max(0,Math.min(90,Number(program?.due_days??7)));const invoiceForm=new URLSearchParams();invoiceForm.set('customer',customer);invoiceForm.set('collection_method','send_invoice');invoiceForm.set('days_until_due',String(days));invoiceForm.set('auto_advance','false');invoiceForm.set('description',`Central Illinois Local Pros lead delivery invoice ${inv.invoice_number}. Charges are based on delivered leads, not whether a lead closes.`);invoiceForm.set('metadata[internal_invoice_id]',inv.id);invoiceForm.set('metadata[business_id]',inv.business_id);invoiceForm.set('metadata[billing_model]',inv.billing_model);const stripeInvoice=await stripePost('invoices',secret,invoiceForm);
  const item=new URLSearchParams();item.set('customer',customer);item.set('invoice',stripeInvoice.id);item.set('amount',String(inv.amount_due_cents));item.set('currency','usd');const creditText=Number(inv.credit_applied_cents)>0?` · ${(Number(inv.credit_applied_cents)/100).toFixed(2)} credit already applied`:'';item.set('description',inv.billing_model==='lead_bundle'?`${inv.bundle_count} lead bundle${inv.bundle_count===1?'':'s'} · ${inv.lead_count} delivered lead${inv.lead_count===1?'':'s'}${creditText}`:`${inv.lead_count} delivered lead${inv.lead_count===1?'':'s'} · pay-per-lead billing${creditText}`);await stripePost('invoiceitems',secret,item);
  const finalized=await stripePost(`invoices/${stripeInvoice.id}/finalize`,secret,new URLSearchParams());const sent=await stripePost(`invoices/${stripeInvoice.id}/send`,secret,new URLSearchParams());const url=sent.hosted_invoice_url||finalized.hosted_invoice_url||null,pdf=sent.invoice_pdf||finalized.invoice_pdf||null;const{error:updateErr}=await s.rpc('set_lead_invoice_status',{p_invoice_id:inv.id,p_status:'sent',p_stripe_invoice_id:stripeInvoice.id,p_hosted_url:url,p_pdf_url:pdf});if(updateErr)throw updateErr;return NextResponse.json({ok:true,url,invoice_pdf:pdf,stripe_invoice_id:stripeInvoice.id});
 }
 return NextResponse.json({error:'Unknown lead billing action.'},{status:400});
}catch(e:any){const raw=e?.message||'Unable to complete lead billing action.';const friendly:Record<string,string>={monthly_lead_cap_reached:'Monthly lead cap reached for this business.',lead_delivery_on_manual_hold:'Lead delivery is manually paused for this business.',delivery_blocked_open_balance:'Lead delivery is blocked until the open balance is cleared.',delivery_blocked_overdue_balance:'Lead delivery is blocked because an invoice is overdue.',exclusive_lead_already_delivered:'This exclusive lead has already been delivered to another business.',shared_lead_buyer_limit_reached:'This shared lead has reached its buyer limit.',lead_agreement_not_started:'This lead agreement has not started yet.',lead_agreement_ended:'This lead agreement has ended.',lead_already_delivered_to_business:'This lead has already been delivered to this business.'};const key=Object.keys(friendly).find(k=>raw.includes(k));const m=key?friendly[key]:raw;return NextResponse.json({error:m},{status:raw.includes('insufficient_privilege')||raw.includes('authentication_required')?403:400});}}
