import{NextResponse}from'next/server';import{createClient}from'@/lib/supabase/server';
const stripePost=async(path:string,secret:string,form:URLSearchParams)=>{const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});const body=await r.json() as any;if(!r.ok)throw new Error(body?.error?.message||'Stripe request failed.');return body};
export async function POST(req:Request){try{const body=await req.json() as any;const s=await createClient();const action=String(body.action||'');
 if(action==='configure'){const model=String(body.billing_model||'pay_per_lead');const{data,error}=await s.rpc('configure_business_lead_program',{p_business_id:body.business_id,p_featured_addon_enabled:Boolean(body.featured_addon_enabled),p_billing_model:model,p_per_lead_price_cents:model==='pay_per_lead'?Math.round(Number(body.per_lead_price_cents||0)):null,p_bundle_lead_count:model==='lead_bundle'?Number(body.bundle_lead_count||0):null,p_bundle_price_cents:model==='lead_bundle'?Math.round(Number(body.bundle_price_cents||0)):null,p_due_days:Number(body.due_days??7),p_billing_email:body.billing_email||null,p_notes:body.notes||null,p_status:body.status||'active'});if(error)throw error;return NextResponse.json({ok:true,program_id:data});}
 if(action==='deliver'){const{data,error}=await s.rpc('deliver_billable_lead',{p_lead_id:body.lead_id,p_business_id:body.business_id,p_route_reason:body.route_reason||'Paid lead delivery',p_route_rank:Number(body.route_rank||0)});if(error)throw error;return NextResponse.json({ok:true,recipient_id:data});}
 if(action==='create_invoice'){const{data,error}=await s.rpc('create_lead_invoice',{p_business_id:body.business_id,p_notes:body.notes||null});if(error)throw error;return NextResponse.json({ok:true,invoice_id:data});}
 if(action==='mark_paid'||action==='void'){const status=action==='mark_paid'?'paid':'void';const{error}=await s.rpc('set_lead_invoice_status',{p_invoice_id:body.invoice_id,p_status:status,p_stripe_invoice_id:null,p_hosted_url:null,p_pdf_url:null});if(error)throw error;return NextResponse.json({ok:true,status});}
 if(action==='send_invoice'){
  const secret=process.env.STRIPE_SECRET_KEY;if(!secret)return NextResponse.json({error:'Stripe billing is not connected.'},{status:503});
  const{data:inv,error:invErr}=await s.from('lead_invoices').select('id,invoice_number,business_id,lead_count,bundle_count,billing_model,amount_due_cents,status,due_at,hosted_invoice_url,stripe_invoice_id').eq('id',body.invoice_id).maybeSingle();if(invErr||!inv)return NextResponse.json({error:'Lead invoice not found.'},{status:404});if(inv.status==='paid'||inv.status==='void')return NextResponse.json({error:`Invoice is already ${inv.status}.`},{status:400});if(inv.status==='sent'&&inv.hosted_invoice_url)return NextResponse.json({ok:true,url:inv.hosted_invoice_url,reused:true});
  const[{data:biz},{data:program},{data:subs}]=await Promise.all([s.from('businesses').select('name').eq('id',inv.business_id).maybeSingle(),s.from('business_lead_programs').select('billing_email,stripe_customer_id,due_days').eq('business_id',inv.business_id).maybeSingle(),s.from('subscriptions').select('provider_customer_id,status,updated_at').eq('business_id',inv.business_id).in('status',['active','trialing','past_due']).order('updated_at',{ascending:false}).limit(1)]);
  let customer=program?.stripe_customer_id||subs?.[0]?.provider_customer_id||'';if(!customer){if(!program?.billing_email)return NextResponse.json({error:'Add a billing email before sending this invoice.'},{status:400});const f=new URLSearchParams();f.set('name',biz?.name||'Central Illinois Local Pros Business');f.set('email',program.billing_email);f.set('metadata[business_id]',inv.business_id);f.set('metadata[source]','central_il_local_pros_lead_billing');const c=await stripePost('customers',secret,f);customer=c.id;await s.from('business_lead_programs').update({stripe_customer_id:customer}).eq('business_id',inv.business_id);}
  const days=Math.max(0,Math.min(90,Number(program?.due_days??7)));const invoiceForm=new URLSearchParams();invoiceForm.set('customer',customer);invoiceForm.set('collection_method','send_invoice');invoiceForm.set('days_until_due',String(days));invoiceForm.set('auto_advance','false');invoiceForm.set('description',`Central Illinois Local Pros lead delivery invoice ${inv.invoice_number}. Charges are based on delivered leads, not whether a lead closes.`);invoiceForm.set('metadata[internal_invoice_id]',inv.id);invoiceForm.set('metadata[business_id]',inv.business_id);invoiceForm.set('metadata[billing_model]',inv.billing_model);const stripeInvoice=await stripePost('invoices',secret,invoiceForm);
  const item=new URLSearchParams();item.set('customer',customer);item.set('invoice',stripeInvoice.id);item.set('amount',String(inv.amount_due_cents));item.set('currency','usd');item.set('description',inv.billing_model==='lead_bundle'?`${inv.bundle_count} lead bundle${inv.bundle_count===1?'':'s'} · ${inv.lead_count} delivered lead${inv.lead_count===1?'':'s'}`:`${inv.lead_count} delivered lead${inv.lead_count===1?'':'s'} · pay-per-lead billing`);await stripePost('invoiceitems',secret,item);
  const finalized=await stripePost(`invoices/${stripeInvoice.id}/finalize`,secret,new URLSearchParams());const sent=await stripePost(`invoices/${stripeInvoice.id}/send`,secret,new URLSearchParams());const url=sent.hosted_invoice_url||finalized.hosted_invoice_url||null,pdf=sent.invoice_pdf||finalized.invoice_pdf||null;const{error:updateErr}=await s.rpc('set_lead_invoice_status',{p_invoice_id:inv.id,p_status:'sent',p_stripe_invoice_id:stripeInvoice.id,p_hosted_url:url,p_pdf_url:pdf});if(updateErr)throw updateErr;return NextResponse.json({ok:true,url,invoice_pdf:pdf,stripe_invoice_id:stripeInvoice.id});
 }
 return NextResponse.json({error:'Unknown lead billing action.'},{status:400});
}catch(e:any){const m=e?.message||'Unable to complete lead billing action.';return NextResponse.json({error:m},{status:m.includes('insufficient_privilege')||m.includes('authentication_required')?403:400});}}
