import{NextResponse}from'next/server';import{createClient}from'@/lib/supabase/server';import{getClaims}from'@/lib/auth';import{getBusinessPlanAccess,effectivePlanIs}from'@/lib/business-plan';import{TENANT_ID}from'@/lib/constants';
const clean=(v:any,n:number)=>String(v??'').trim().slice(0,n);const url=(v:any)=>{const s=clean(v,500);if(!s)return'';try{const u=new URL(s);return['http:','https:'].includes(u.protocol)?u.toString():''}catch{return''}};const day=(v:any)=>/^\d{4}-\d{2}-\d{2}$/.test(clean(v,10))?clean(v,10):'';
export async function POST(req:Request){try{const claims=await getClaims();if(!claims?.sub)return NextResponse.json({error:'Sign in is required.'},{status:401});const body=await req.json() as any;const businessId=clean(body.business_id,80);if(!businessId)return NextResponse.json({error:'Business is required.'},{status:400});const s=await createClient(),uid=String(claims.sub);const{data:owner}=await s.from('business_owners').select('business_id').eq('business_id',businessId).eq('user_id',uid).maybeSingle();if(!owner)return NextResponse.json({error:'You are not authorized to edit this business.'},{status:403});const access=await getBusinessPlanAccess(s,businessId);if(!effectivePlanIs(access,'pro'))return NextResponse.json({error:'Pro plan access is required for the Pro mini-site editor.'},{status:403});const{data:pending}=await s.from('business_edit_requests').select('id').eq('business_id',businessId).eq('requested_by',uid).eq('request_type','pro_profile_update').eq('status','pending').limit(1);if(pending?.length)return NextResponse.json({error:'A Pro profile update is already pending staff review.'},{status:409});
 const services=(Array.isArray(body.services)?body.services:[]).slice(0,12).map((x:any)=>({name:clean(x?.name,80),description:clean(x?.description,280)})).filter((x:any)=>x.name);const faqs=(Array.isArray(body.faqs)?body.faqs:[]).slice(0,8).map((x:any)=>({question:clean(x?.question,160),answer:clean(x?.answer,600)})).filter((x:any)=>x.question&&x.answer);const social:any={};for(const k of['facebook','instagram','linkedin','tiktok','youtube','x']){const u=url(body.social_links?.[k]);if(u)social[k]=u}
 const title=clean(body.offer?.title,120),offer=title?{title,details:clean(body.offer?.details,500),code:clean(body.offer?.code,60),cta_label:clean(body.offer?.cta_label,50)||'Learn More',cta_url:url(body.offer?.cta_url),expires_on:day(body.offer?.expires_on)}:{};
 const announcements=(Array.isArray(body.announcements)?body.announcements:[]).slice(0,3).map((x:any)=>({title:clean(x?.title,120),body:clean(x?.body,500),starts_on:day(x?.starts_on),ends_on:day(x?.ends_on)})).filter((x:any)=>x.title&&x.body);
 const packages=(Array.isArray(body.packages)?body.packages:[]).slice(0,8).map((x:any)=>({name:clean(x?.name,100),description:clean(x?.description,400),price_label:clean(x?.price_label,80),cta_label:clean(x?.cta_label,50)||'Learn More',cta_url:url(x?.cta_url)})).filter((x:any)=>x.name);
 const holiday_hours=(Array.isArray(body.holiday_hours)?body.holiday_hours:[]).slice(0,20).map((x:any)=>({date:day(x?.date),label:clean(x?.label,80),hours:clean(x?.hours,100),closed:Boolean(x?.closed)})).filter((x:any)=>x.date&&(x.closed||x.hours));
 const cta={primary_label:clean(body.cta?.primary_label,50),primary_url:url(body.cta?.primary_url),secondary_label:clean(body.cta?.secondary_label,50),secondary_url:url(body.cta?.secondary_url)};
 const proposed={services,faqs,social_links:social,offer,announcements,packages,holiday_hours,cta};const{error}=await s.from('business_edit_requests').insert({tenant_id:TENANT_ID,business_id:businessId,requested_by:uid,request_type:'pro_profile_update',proposed_changes:proposed,status:'pending'});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,message:'Expanded Pro profile update submitted for staff review.'})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to submit Pro profile update.'},{status:400})}}