import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { TENANT_ID } from '@/lib/constants'
import { requireAdmin } from '@/lib/auth'

export const dynamic = 'force-dynamic'
function related(value:any){return Array.isArray(value)?value[0]:value}
function money(cents:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((cents||0)/100)}
function date(value:string|null|undefined){if(!value)return '—';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value))}
function activeToday(row:any,today:string){return row.active&&(!row.starts_on||row.starts_on<=today)&&(!row.ends_on||row.ends_on>=today)}
function placementLabel(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}

export default async function RevenuePage(){
  await requireAdmin('/admin/revenue');const s=await createClient()
  const [subsQ,sponsorsQ,plansQ,hooksQ,locationsQ,categoriesQ]=await Promise.all([
    s.from('subscriptions').select('id,business_id,plan_id,provider,provider_customer_id,provider_subscription_id,status,billing_interval,current_period_end,starts_at,ends_at,updated_at,businesses(name,slug),plans(name,slug,monthly_price_cents,annual_price_cents)').eq('tenant_id',TENANT_ID).order('updated_at',{ascending:false}).limit(250),
    s.from('sponsorships').select('id,business_id,market_location_id,category_id,placement,page_path,starts_on,ends_on,active,priority,sort_order,origin,provider,provider_subscription_id,created_at,businesses(name,slug)').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(500),
    s.from('plans').select('id,slug,name,monthly_price_cents,annual_price_cents,is_active').eq('tenant_id',TENANT_ID).eq('is_active',true).order('sort_order',{ascending:true}),
    s.from('stripe_webhook_events').select('event_id,event_type,status,received_at,processed_at').eq('tenant_id',TENANT_ID).order('received_at',{ascending:false}).limit(50),
    s.from('locations').select('id,name').eq('tenant_id',TENANT_ID).eq('is_active',true),
    s.from('categories').select('id,name').eq('tenant_id',TENANT_ID).eq('is_active',true),
  ])
  const subscriptions=(subsQ.data??[]) as any[],sponsorships=(sponsorsQ.data??[]) as any[],plans=(plansQ.data??[]) as any[],hooks=(hooksQ.data??[]) as any[]
  const locationNames=new Map((locationsQ.data??[]).map((x:any)=>[x.id,x.name])),categoryNames=new Map((categoriesQ.data??[]).map((x:any)=>[x.id,x.name]))
  const active=subscriptions.filter(r=>['active','trialing'].includes(r.status)),pastDue=subscriptions.filter(r=>r.status==='past_due'),monthly=active.filter(r=>r.billing_interval==='monthly'),annual=active.filter(r=>r.billing_interval==='annual'),today=new Date().toISOString().slice(0,10)
  const activeSponsors=sponsorships.filter(r=>activeToday(r,today)),homepage=activeSponsors.filter(r=>r.placement==='homepage_featured'),sidebars=activeSponsors.filter(r=>String(r.placement).includes('sidebar')||['sitewide','city','category','search'].includes(r.placement)),reviewHooks=hooks.filter(r=>['needs_review','error'].includes(r.status)),unknownCadence=active.filter(r=>!r.billing_interval).length
  const soon=new Date(Date.now()+30*86400000).toISOString().slice(0,10),endingSoon=activeSponsors.filter(r=>r.ends_on&&r.ends_on>=today&&r.ends_on<=soon)
  const monthlyEquivalent=active.reduce((sum,row)=>{const p=related(row.plans)||{};return sum+(row.billing_interval==='annual'?Math.round((p.annual_price_cents||0)/12):(p.monthly_price_cents||0))},0)
  const planMix=new Map<string,number>();for(const row of active){const p=related(row.plans);const key=p?.name||'Unassigned';planMix.set(key,(planMix.get(key)||0)+1)}
  const sponsorByBusiness=new Map<string,any[]>();for(const row of activeSponsors){if(!sponsorByBusiness.has(row.business_id))sponsorByBusiness.set(row.business_id,[]);sponsorByBusiness.get(row.business_id)!.push(row)}
  const inventory=new Map<string,{label:string;count:number;cap:number}>();for(const row of activeSponsors){let scope='';if(row.market_location_id)scope+=locationNames.get(row.market_location_id)||'Market';if(row.category_id)scope+=`${scope?' · ':''}${categoryNames.get(row.category_id)||'Category'}`;if(row.page_path)scope+=`${scope?' · ':''}${row.page_path}`;const key=`${row.placement}:${row.market_location_id||''}:${row.category_id||''}:${row.page_path||''}`,label=`${placementLabel(row.placement)}${scope?` — ${scope}`:''}`,cap=row.placement==='homepage_featured'?6:4;const current=inventory.get(key);inventory.set(key,{label,count:(current?.count||0)+1,cap})}
  const inventoryRows=[...inventory.values()].sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label))
  return <>
    <div className="admin-page-head"><div><div className="kpi">Private Revenue Operations</div><h1>Revenue & Featured Inventory</h1><p className="muted">Central money dashboard for recurring plans, Sponsored inventory, capacity and billing health. Paid placement remains separate from verification and organic ranking.</p></div><span className="badge sponsored">Admin only</span></div>
    <div className="stat-grid"><div className="stat">Active Paid Subscriptions<strong>{active.length}</strong></div><div className="stat">Monthly-Equivalent Revenue<strong>{money(monthlyEquivalent)}</strong></div><div className="stat">Active Sidebar Advertisers<strong>{sidebars.length}</strong></div><div className="stat">Needs Attention<strong>{pastDue.length+reviewHooks.length+endingSoon.length}</strong></div></div>
    <div className="featured-inventory-grid" style={{marginTop:14}}><div className="admin-card"><div className="kpi">Billing Cadence</div><strong>{monthly.length} monthly · {annual.length} annual</strong><p className="small muted">{unknownCadence} active subscription{unknownCadence===1?'':'s'} awaiting cadence sync.</p></div><div className="admin-card"><div className="kpi">Homepage Inventory</div><strong>{homepage.length} / 6 active</strong><div className="inventory-meter"><span style={{width:`${Math.min(100,homepage.length/6*100)}%`}}/></div></div><div className="admin-card"><div className="kpi">Sidebar Inventory</div><strong>{sidebars.length} active placements</strong><p className="small muted">Global, city, category, market, guide, profile and vertical inventory.</p></div><div className="admin-card"><div className="kpi">Ending Soon</div><strong>{endingSoon.length}</strong><p className="small muted">Sponsored placements ending in the next 30 days.</p></div></div>
    <div className="admin-card" style={{marginTop:18}}><div className="kpi">Stripe + Directory State</div><h2>Billing state stays auditable</h2><p className="muted">Live checkout and subscription records are separate from business verification. Stripe-originated placements can be inspected by provider subscription ID; Super Admin retains final advertising placement control.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><Link className="btn btn-primary" href="/admin/sponsorships">Manage Featured Placements</Link><Link className="btn btn-light" href="/admin/subscriptions">Subscription Manager</Link><Link className="btn btn-light" href="/admin/pricing">Pricing & Plans</Link></div></div>
    <div className="section-head admin-quick-head"><div><h2>Plan Mix</h2><p className="muted">Active/trialing subscription assignments; annual values are normalized to one-twelfth of annual catalog price.</p></div></div><div className="grid grid-4 admin-quick-grid">{plans.map((p:any)=><div className="admin-card" key={p.id}><div className="kpi">{p.slug}</div><strong>{p.name}</strong><p className="small muted">{money(p.monthly_price_cents)}/mo · {money(p.annual_price_cents)}/yr</p><span className="badge neutral">{planMix.get(p.name)||0} active</span></div>)}</div>
    <div className="section-head admin-quick-head"><div><h2>Featured Inventory Capacity</h2><p className="muted">Homepage capacity is 6; sidebar scopes use a working capacity of 4. More eligible advertisers can exist, but public selection rotates deterministically within priority tiers.</p></div><Link href="/admin/sponsorships">Manage inventory →</Link></div><div className="featured-inventory-grid">{inventoryRows.length?inventoryRows.slice(0,16).map((row,i)=><div className="admin-card" key={`${row.label}-${i}`}><strong>{row.label}</strong><p className="small muted">{row.count} / {row.cap} active slots</p><div className="inventory-meter"><span style={{width:`${Math.min(100,row.count/row.cap*100)}%`}}/></div></div>):<div className="admin-card"><strong>No active Featured inventory</strong><p className="small muted">Sponsored sales cards remain available publicly until advertisers are assigned.</p></div>}</div>
    <div className="section-head admin-quick-head"><div><h2>Paid Customers</h2><p className="muted">Subscription state plus current Sponsored placement footprint. Payment never grants verification.</p></div><Link href="/admin/subscriptions">Open manager →</Link></div><div className="admin-card" style={{overflowX:'auto'}}>{subscriptions.length===0?<p className="muted">No paid subscriptions yet.</p>:subscriptions.slice(0,40).map((row:any)=>{const b=related(row.businesses),p=related(row.plans),spots=sponsorByBusiness.get(row.business_id)||[];return <div className="paid-customer-grid" key={row.id}><div><strong>{b?.name||'Business'}</strong><div className="small muted">{row.provider||'manual'}</div></div><div>{p?.name||'Unassigned'}</div><div><span className="badge neutral">{row.status}</span></div><div>{row.billing_interval||'pending'}</div><div>{spots.some(x=>x.placement==='homepage_featured')?'Yes':'—'}<div className="small muted">Homepage</div></div><div>{spots.filter(x=>String(x.placement).includes('sidebar')).length}<div className="small muted">Sidebar</div></div><div className="small muted">{date(row.current_period_end||row.ends_at)}</div></div>})}</div>
    <div className="section-head admin-quick-head"><div><h2>Billing & Webhook Health</h2><p className="muted">Private operational state. These diagnostics are never exposed on public pages.</p></div></div><div className="grid grid-4 admin-quick-grid"><div className="admin-card"><strong>{pastDue.length}</strong><p className="small muted">Past-due subscriptions</p></div><div className="admin-card"><strong>{reviewHooks.length}</strong><p className="small muted">Webhook events needing review</p></div><div className="admin-card"><strong>{hooks.filter(r=>r.status==='processed').length}</strong><p className="small muted">Processed events in recent ledger</p></div><div className="admin-card"><strong>{endingSoon.length}</strong><p className="small muted">Placements ending within 30 days</p></div></div>
  </>
}
