const SUPABASE_URL='https://vbhmdvxfghriygxjkdtv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_tSF8tFEkSS7QOA_q0W4quw_7DcO_8Kl';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const cloud={session:null,authReady:false,loaded:false};
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const strengthFromScore=n=>!n?'none':n<60?'weak':n>=80?'strong':'average';
const freshnessFromMonths=n=>n==null?'unknown':n>30?'stale':n>18?'aging':'fresh';
function dbToLead(r){const wa=r.website_audit||{},gd=r.gbp_data||{},sd=r.social_data||{};return{id:r.id,placeId:r.google_place_id||'',name:r.business_name||'',address:r.address||'',city:r.city||'',state:r.state||'',area:r.county_area||'',niche:r.discovery_niche||'',keyword:r.discovery_keyword||'',phone:r.phone||'',website:r.website||'',email:r.business_email||'',decisionMaker:r.decision_maker_name||'',title:r.decision_maker_title||'',rating:Number(r.google_rating||0),reviews:Number(r.review_count||0),gbpClaimed:r.gbp_claimed,mapRank:r.maps_rank,webScore:Number(wa.score??(r.website_strength==='strong'?88:r.website_strength==='weak'?48:r.website_strength==='none'?0:68)),webAgeMonths:Number(wa.estimated_age_months??(r.website_freshness==='stale'?40:r.website_freshness==='aging'?24:r.website_freshness==='fresh'?6:18)),analytics:r.has_analytics,metaPixel:r.has_meta_pixel,adsTracking:r.has_google_ads_tracking,schema:r.has_schema,ctaStrong:r.cta_strength==='strong',socialMissing:Number(sd.missing_count??0),socialInactive:Boolean(sd.inactive),lastSocial:sd.last_activity_label||'Unknown',lastGbp:gd.last_activity_label||'Unknown',stage:r.stage||'New',notes:r.notes||'',followUp:r.follow_up_at?String(r.follow_up_at).slice(0,10):'',deepScanned:r.deep_scan_status==='complete'||r.deep_scan_status==='partial',createdAt:r.created_at,score:Number(r.opportunity_score||0),temp:r.temperature||'COLD',breakdown:Array.isArray(r.score_breakdown)?r.score_breakdown:[],savedAt:r.created_at}}
function leadToDb(l){return{user_id:cloud.session.user.id,stage:STAGES.includes(l.stage)?l.stage:'New',business_name:l.name,normalized_name:norm(l.name),address:l.address||null,normalized_address:l.address?norm(l.address):null,city:l.city||null,state:l.state||null,county_area:l.area||null,google_place_id:l.placeId||null,phone:l.phone||null,normalized_phone:l.phone?l.phone.replace(/\D/g,''):null,website:l.website||null,normalized_domain:l.website?domain(l.website):null,business_email:l.email||null,professional_email:Boolean(l.email),decision_maker_name:l.decisionMaker||null,decision_maker_title:l.title||null,google_rating:l.rating||null,review_count:Number.isFinite(+l.reviews)?+l.reviews:null,gbp_claimed:l.gbpClaimed,map_pack_top3:l.mapRank!=null?l.mapRank<=3:null,maps_rank:l.mapRank==null?null:+l.mapRank,website_strength:strengthFromScore(l.webScore),website_freshness:freshnessFromMonths(l.webAgeMonths),has_analytics:l.analytics??null,has_meta_pixel:l.metaPixel??null,has_google_ads_tracking:l.adsTracking??null,has_schema:l.schema??null,cta_strength:l.ctaStrong?'strong':'weak',opportunity_score:l.score||0,temperature:l.temp||'COLD',score_breakdown:l.breakdown||[],website_audit:{score:l.webScore||0,estimated_age_months:l.webAgeMonths??null,analytics:l.analytics??null,meta_pixel:l.metaPixel??null,google_ads_tracking:l.adsTracking??null,schema:l.schema??null,cta_strong:l.ctaStrong??null},gbp_data:{last_activity_label:l.lastGbp||'Unknown'},social_data:{missing_count:l.socialMissing||0,inactive:Boolean(l.socialInactive),last_activity_label:l.lastSocial||'Unknown'},notes:l.notes||null,follow_up_at:l.followUp?new Date(l.followUp+'T12:00:00Z').toISOString():null,last_deep_scan_at:l.deepScanned?new Date().toISOString():null,deep_scan_status:l.deepScanned?'complete':'not_scanned',discovery_niche:l.niche||null,discovery_keyword:l.keyword||null,discovery_city:l.city||null,discovery_state:l.state||null,discovery_area:l.area||null,discovery_context:{source:'demo',city:l.city||null,state:l.state||null,area:l.area||null,niche:l.niche||null,keyword:l.keyword||null}}}
function identifierRows(l){if(!isUuid(l.id)||!cloud.session)return[];const u=cloud.session.user.id,out=[];if(l.placeId)out.push({user_id:u,lead_id:l.id,identifier_type:'google_place_id',identifier_value:l.placeId});if(l.website&&domain(l.website))out.push({user_id:u,lead_id:l.id,identifier_type:'domain',identifier_value:domain(l.website)});if(l.phone&&l.phone.replace(/\D/g,''))out.push({user_id:u,lead_id:l.id,identifier_type:'phone',identifier_value:l.phone.replace(/\D/g,'')});if(l.name&&l.address)out.push({user_id:u,lead_id:l.id,identifier_type:'name_address',identifier_value:norm(l.name)+':'+norm(l.address)});return out}
async function syncIdentifiers(l){const rows=identifierRows(l);if(!rows.length)return;const {error}=await sb.from('lead_identifiers').upsert(rows,{onConflict:'user_id,identifier_type,identifier_value',ignoreDuplicates:true});if(error)console.warn(error.message)}
async function loadCloud(){const [lr,hr,ar]=await Promise.all([sb.from('leads').select('*').eq('status','active').order('created_at',{ascending:false}),sb.from('search_history').select('*').order('created_at',{ascending:false}).limit(100),sb.from('lead_activity').select('id,lead_id,activity_type,message,created_at,leads(business_name)').order('created_at',{ascending:false}).limit(500)]);if(lr.error)throw lr.error;if(hr.error)throw hr.error;if(ar.error)throw ar.error;state.saved=(lr.data||[]).map(dbToLead);state.history=(hr.data||[]).map(h=>({id:h.id,date:h.created_at,niche:h.niche||'',businessName:h.business_name||'',cities:h.cities||[],state:h.state||'',area:h.area||'',keyword:h.maps_keyword||'',resultCount:h.result_count||0}));state.activity=(ar.data||[]).map(a=>({id:a.id,lead:a.leads?.business_name||'',leadId:a.lead_id,type:a.activity_type,text:a.message,date:a.created_at}));cloud.loaded=true}
function authView(){return`<div style="min-height:100vh;display:grid;place-items:center;padding:20px;background:radial-gradient(circle at 20% 0,#16213a 0,transparent 28%),var(--bg)"><div class="panel" style="width:min(460px,96vw);padding:28px"><div class="eyebrow">LEAD INTELLIGENCE CRM</div><h1 style="margin:8px 0 6px">Private CRM Sign In</h1><p class="sub" style="margin-bottom:20px">Your leads, notes, stages, follow-ups and history are stored securely in Supabase.</p><label class="field"><span>Email</span><input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com"></label><label class="field" style="display:block;margin-top:12px"><span>Password</span><input id="authPassword" type="password" autocomplete="current-password" placeholder="At least 6 characters" onkeydown="if(event.key==='Enter')signIn()"></label><div style="display:flex;gap:8px;margin-top:16px"><button class="btn primary" onclick="signIn()">Sign In</button><button class="btn" onclick="signUp()">Create Account</button></div><div class="notice" style="margin-top:18px;margin-bottom:0">Demo prospect discovery remains enabled. CRM storage is cloud-backed and isolated by signed-in user.</div></div></div>`}
async function signIn(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||!password)return toast('Enter your email and password.');const {error}=await sb.auth.signInWithPassword({email,password});if(error)toast(error.message)}
async function signUp(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||password.length<6)return toast('Enter an email and a password with at least 6 characters.');const {data,error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);if(!data.session)toast('Account created. Check your email to confirm, then sign in.')}
async function signOut(){await sb.auth.signOut();state.results=[];state.selected=null}
const baseRender=render;
render=function(){if(!cloud.authReady){document.getElementById('app').innerHTML='<div class="empty" style="padding-top:20vh">Connecting securely…</div>';return}if(!cloud.session){document.getElementById('app').innerHTML=authView();return}baseRender();document.querySelectorAll('.prov').forEach(x=>{if(x.textContent.includes('CRM Storage'))x.innerHTML='<span>CRM Storage</span><b style="color:var(--green)">SUPABASE</b>'});const eyebrow=document.querySelector('.top .eyebrow');if(eyebrow)eyebrow.textContent='PRIVATE CLOUD PREVIEW';const topP=document.querySelector('.top p');if(topP)topP.textContent='Demo prospect discovery with private cloud CRM persistence. HOT means digital-marketing opportunity, not confirmed buying intent.';const pill=document.querySelector('.top .pill');if(pill)pill.textContent='● DEMO DISCOVERY';const topActions=document.querySelector('.top>div:last-child');if(topActions&&!document.getElementById('signOutBtn'))topActions.insertAdjacentHTML('beforeend',' <span class="tag good">☁ CLOUD CRM</span> <button id="signOutBtn" class="btn" onclick="signOut()">Sign Out</button>');const notice=document.querySelector('.main>.notice');if(notice)notice.textContent='CRM data now syncs securely to Supabase. Prospect discovery and Deep Scan remain in demo mode until the live provider APIs are connected.';const pipe=document.querySelector('.panel .eyebrow');if(state.view==='pipeline'&&pipe&&pipe.textContent.includes('PERSISTENT'))pipe.textContent='CLOUD CRM';if(state.view==='pipeline'){document.querySelectorAll('.panel .sub').forEach(e=>{if(e.textContent.includes('localStorage'))e.textContent='Stored in Supabase and isolated to your signed-in account. Browser storage is only a local backup.'})}}
persist=function(){if(!cloud.session)return;const uid=cloud.session.user.id;localStorage.setItem(LS.leads+'_'+uid,JSON.stringify(state.saved));localStorage.setItem(LS.history+'_'+uid,JSON.stringify(state.history));localStorage.setItem(LS.activity+'_'+uid,JSON.stringify(state.activity))}
const baseLog=log;
log=function(l,type,text){baseLog(l,type,text);if(cloud.session&&l&&isUuid(l.id))sb.from('lead_activity').insert({user_id:cloud.session.user.id,lead_id:l.id,activity_type:type,message:text,metadata:{source:'web'}}).then(({error})=>{if(error)console.warn(error.message)})}
const baseGenerate=generate;
generate=async function(){baseGenerate();if(cloud.session){const f=state.form,cities=f.cities.split(',').map(x=>x.trim()).filter(Boolean);const {error}=await sb.from('search_history').insert({user_id:cloud.session.user.id,niche:f.niche||null,business_name:f.businessName||null,cities,state:f.state||null,area:f.area||null,maps_keyword:f.keyword||null,request_payload:{...f,cities},result_count:state.results.length,source:'demo'});if(error)console.warn(error.message)}}
mergeLead=function(old,n){const m={...old,...n,id:isUuid(old.id)?old.id:(n.id||old.id),stage:old.stage||n.stage||'New',notes:old.notes||n.notes||'',followUp:old.followUp||n.followUp||'',deepScanned:old.deepScanned||n.deepScanned,decisionMaker:n.decisionMaker||old.decisionMaker,email:n.email||old.email,website:n.website||old.website};Object.assign(m,score(m));return m}
saveLead=async function(l,silent=false){let hit=findSaved(l);if(hit){let merged=mergeLead(hit,l);if(isUuid(hit.id)){const payload=leadToDb(merged);delete payload.user_id;const {data,error}=await sb.from('leads').update(payload).eq('id',hit.id).select().single();if(error)return toast('Could not update lead: '+error.message);merged=dbToLead(data);await syncIdentifiers(merged)}state.saved=state.saved.map(x=>same(x,hit)?merged:x);if(!silent)toast('Existing lead updated without losing enrichment.')}else{let n={...l,stage:'New',savedAt:new Date().toISOString()};const {data,error}=await sb.from('leads').insert(leadToDb(n)).select().single();if(error)return toast('Could not save lead: '+error.message);n=dbToLead(data);await syncIdentifiers(n);state.saved.unshift(n);log(n,'saved','Lead saved to CRM');if(!silent)toast('Lead saved to CRM.')}persist();if(!silent)render()}
removeLead=async function(l){if(!confirm('Remove '+l.name+' from CRM?'))return;const hit=findSaved(l);if(hit&&isUuid(hit.id)){const {error}=await sb.from('leads').delete().eq('id',hit.id);if(error)return toast('Could not remove lead: '+error.message)}state.saved=state.saved.filter(x=>!same(x,l));state.activity=state.activity.filter(a=>a.leadId!==hit?.id);state.selected=null;persist();render();toast('Lead removed from CRM.')}
deepScan=async function(l,silent=false){let s=findSaved(l)||l,seed=hash(s.name+'deep'),r=rng(seed),n={...s,deepScanned:true,decisionMaker:s.decisionMaker||['Morgan Reed','Jordan Ellis','Casey Parker'][Math.floor(r()*3)],email:s.email||`hello@${domain(s.website)||norm(s.name)+'.com'}`,lastSocial:r()>.4?'5 days ago':'4 months ago',lastGbp:r()>.3?'8 days ago':'5 months ago'};if(n.website){n.webScore=Math.max(n.webScore,Math.round(35+r()*50));n.analytics=r()>.45;n.metaPixel=r()>.6;n.adsTracking=r()>.7;n.schema=r()>.5;n.ctaStrong=r()>.45}Object.assign(n,score(n));const hit=findSaved(s);if(hit){let merged=mergeLead(hit,n);const payload=leadToDb(merged);delete payload.user_id;const {data,error}=await sb.from('leads').update(payload).eq('id',hit.id).select().single();if(error)return toast('Deep Scan save failed: '+error.message);merged=dbToLead(data);await syncIdentifiers(merged);state.saved=state.saved.map(x=>same(x,hit)?merged:x);n=merged}state.results=state.results.map(x=>same(x,s)?mergeLead(x,n):x);state.selected=n;log(n,'deep_scan','Demo Deep Scan completed');persist();if(!silent)render();if(!silent)toast('Deep Scan completed in demo mode.')}
bulkSave=async function(){for(const l of visible())await saveLead(l,true);render();toast('Filtered leads saved to cloud CRM.')}
bulkScan=async function(){for(const l of visible().slice(0,10))await deepScan(l,true);render();toast('Deep Scan completed for top 10 visible leads.')}
setStage=async function(l,stage){if(!STAGES.includes(stage))return toast('Invalid CRM stage.');const hit=findSaved(l);if(!hit)return;const {error}=await sb.from('leads').update({stage}).eq('id',hit.id);if(error)return toast('Stage update failed: '+error.message);state.saved=state.saved.map(x=>same(x,hit)?{...x,stage}:x);state.activity.unshift({id:'local_'+Date.now(),lead:hit.name,leadId:hit.id,type:'stage_changed',text:`Stage changed to ${stage}`,date:new Date().toISOString()});persist();render()}
saveDrawer=async function(){let l=state.selected,s=findSaved(l);if(!s){await saveLead(l,true);s=findSaved(l)}const notes=document.getElementById('notes').value,follow=document.getElementById('follow').value,stage=document.getElementById('stage').value;if(!STAGES.includes(stage))return toast('Invalid CRM stage.');const {error}=await sb.from('leads').update({notes:notes||null,follow_up_at:follow?new Date(follow+'T12:00:00Z').toISOString():null,stage}).eq('id',s.id);if(error)return toast('CRM update failed: '+error.message);await sb.from('lead_activity').insert({user_id:cloud.session.user.id,lead_id:s.id,activity_type:'crm_update',message:'Notes and follow-up updated',metadata:{follow_up:follow||null}});state.saved=state.saved.map(x=>same(x,s)?{...x,notes,followUp:follow,stage}:x);state.selected={...s,notes,followUp:follow,stage};state.activity.unshift({id:'local_'+Date.now(),lead:s.name,leadId:s.id,type:'crm_update',text:'Notes/follow-up/stage updated',date:new Date().toISOString()});persist();render();toast('CRM details saved to cloud.')}
const baseCsv=csv;
csv=function(){let source=state.view==='pipeline'?visible():state.saved,original=state.saved;state.saved=source;try{baseCsv()}finally{state.saved=original}}
async function initCloud(){try{const {data:{session}}=await sb.auth.getSession();cloud.session=session;cloud.authReady=true;if(session)await loadCloud()}catch(e){cloud.authReady=true;console.error(e);toast('Cloud connection error: '+e.message)}render();sb.auth.onAuthStateChange(async(_event,session)=>{cloud.session=session;cloud.authReady=true;if(session){try{await loadCloud()}catch(e){toast('Could not load cloud CRM: '+e.message)}}else{state.saved=[];state.history=[];state.activity=[];cloud.loaded=false}render()})}
initCloud();
