// Growth OS core: full research, confidence, command center, proposals, follow-up, watchlist, clients, revenue, keywords, citations, assets.
(function(){
  if(typeof state==='undefined')return;
  state.growth=state.growth||{section:'command',loaded:false,loading:false,busy:false,busyText:'',researchRuns:[],engagements:[],sequences:[],proposals:[],watchlist:[],assets:[],clients:[],keywords:[],citations:[],visual:null,visualBusy:false,keywordForm:{name:'',niche:'',city:'',state:'',seed:''},citationLeadId:'',proposalLeadId:''};
  const G=state.growth;
  const ge=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const now=()=>new Date().toISOString();
  const uuid=v=>typeof isUuid==='function'?isUuid(v):/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(String(v||''));
  const leadBy=id=>(state.saved||[]).find(x=>x.id===id)||(state.results||[]).find(x=>x.id===id)||null;
  const savedBy=id=>(state.saved||[]).find(x=>x.id===id)||null;
  async function ensureSaved(l){if(!l)return null;let s=typeof findSaved==='function'?findSaved(l):savedBy(l.id);if(!s){await saveLead(l,true);s=typeof findSaved==='function'?findSaved(l):savedBy(l.id)}return s||null}
  function socials(l){return Object.values(l?.socials||{}).filter(Boolean).length}
  function serviceScores(l,seo=null){let s={};try{s=typeof p15ServiceScores==='function'?p15ServiceScores(l):{}}catch{};if(seo?.scores){s.seo={score:Number(seo.scores.seoOpportunity??s.seo?.score??0),confidence:'verified',why:(seo.scores.issues||[]).slice(0,5).map(x=>x.text)};if(seo.scores.conversionHealth!=null)s.funnel={score:Math.max(Number(s.funnel?.score||0),100-Number(seo.scores.conversionHealth)),confidence:'verified',why:[...(s.funnel?.why||[]),'SEO audit conversion/funnel health reviewed']}}
    const labels={website:'Web Design',seo:'SEO',funnel:'Funnel Design',social:'Social Media',ppc:'PPC / Tracking',gbp:'Google Business Profile / Local SEO'};const core=new Set(['website','seo','funnel']);const rank=Object.entries(s).filter(([k,v])=>labels[k]&&v&&v.score!=null).sort((a,b)=>(Number(b[1].score)+(core.has(b[0])?5:0))-(Number(a[1].score)+(core.has(a[0])?5:0)));s.best=rank[0]?{key:rank[0][0],label:labels[rank[0][0]],score:Number(rank[0][1].score)}:s.best||null;s.secondary=rank[1]?{key:rank[1][0],label:labels[rank[1][0]],score:Number(rank[1][1].score)}:null;return s}
  function techFrom(l,site){const t=site?.technologies||l?.technologyStack?.technologies||l?.technology_stack?.technologies||[];return{checked:Boolean(site||l?.technologyStack||l?.technology_stack),technologies:[...new Set(t)],generators:site?.generators||[],signals:site?.signals||{},checkedAt:site?.checkedAt||now(),source:site?.source||'saved'} }
  function adFrom(l,site){if(site?.advertisingReadiness)return{...site.advertisingReadiness,checked:true,checkedAt:site.checkedAt||now()};const a={hasAnalytics:l.analytics===true,hasTagManager:false,hasAds:l.adsTracking===true,hasMeta:l.metaPixel===true,hasLeadCapture:l.ctaStrong===true||l.funnelIntel?.checked===true,hasCallTracking:false};const known=[l.analytics,l.adsTracking,l.metaPixel,l.ctaStrong].filter(v=>v!==undefined&&v!==null).length;if(!known)return{checked:false,score:null,why:['Advertising readiness not fully checked']};const yes=[a.hasAnalytics,a.hasAds||a.hasMeta,a.hasLeadCapture].filter(Boolean).length;return{checked:true,score:Math.round(yes/3*100),why:[a.hasAnalytics?'Analytics detected':'Analytics not detected',a.hasAds||a.hasMeta?'Advertising tracking/pixel detected':'Advertising tracking/pixel not detected',a.hasLeadCapture?'Lead capture path detected':'Lead capture path not detected'],checkedAt:now()}}
  function researchMetrics(l,seo=null){const audit=l.auditChecked===true||Boolean(l.websiteAuditData||l.website_audit),funnel=Boolean(l.funnelIntel?.checked||l.funnelIntel?.manualConfirmed||l.funnel_intelligence?.checked),age=typeof ageYears==='function'?ageYears(l):l.estimatedYearsInBusiness,google=Boolean(l.googleReal||l.googleOwnership||l.gbp_data?.google_places),site=Boolean(l.technologyStack?.checked||l.technology_stack?.checked),soc=l.freeContactChecked===true||socials(l)>0,seoChecked=Boolean(seo||l.latestSeoAudit);
    let completeness=0;completeness+=l.website?8:4;completeness+=l.phone?8:0;completeness+=l.email?8:0;completeness+=l.decisionMaker?8:0;completeness+=age!=null?8:0;completeness+=audit?15:0;completeness+=seoChecked?15:0;completeness+=funnel?10:0;completeness+=soc?5:0;completeness+=google?8:0;completeness+=site?7:0;completeness=Math.min(100,completeness);
    let confidence=0,den=0;const add=(w,ok)=>{den+=w;if(ok)confidence+=w};add(20,audit);add(18,seoChecked);add(15,funnel);add(10,site);add(10,google);add(8,age!=null&&String(l.businessAgeConfidence||'').toLowerCase()!=='low');add(8,Boolean(l.phone||l.email));add(6,Boolean(l.decisionMaker));add(5,soc);confidence=den?Math.round(confidence/den*100):0;return{confidence,completeness,label:confidence>=85?'High Confidence':confidence>=70?'Good Confidence':confidence>=50?'Moderate Confidence':'Needs More Research'}}
  function verifiedProblems(l,seo=null,site=null){const a=[];if(!l.website)a.push('No website recorded');if(l.auditChecked===true){if(Number(l.webScore)<45)a.push(`Website quality ${Math.round(Number(l.webScore||0))}/100 · poor`);else if(Number(l.webScore)<65)a.push(`Website quality ${Math.round(Number(l.webScore||0))}/100 · weak`);if(l.schema===false)a.push('Schema markup not detected');if(l.analytics===false)a.push('Analytics not detected');if(l.metaPixel===false)a.push('Meta Pixel not detected');if(l.adsTracking===false)a.push('Google Ads conversion tracking not detected');if(l.ctaStrong===false)a.push('Weak or missing call-to-action / lead capture')}
    const f=l.funnelIntel||l.funnel_intelligence;if(f?.status==='NO_FUNNEL_FOUND')a.push('No funnel or lead magnet found on checked sources');if(f?.status==='BASIC_FORM_ONLY')a.push('Only a basic contact/lead form was found');if(seo?.scores){if(Number(seo.scores.technicalHealth)<65)a.push(`Technical SEO health ${seo.scores.technicalHealth}/100`);if(Number(seo.scores.onPageHealth)<65)a.push(`On-page SEO health ${seo.scores.onPageHealth}/100`);if(Number(seo.scores.localHealth)<65)a.push(`Local SEO health ${seo.scores.localHealth}/100`);if(Number(seo.scores.conversionHealth)<65)a.push(`Conversion/funnel health ${seo.scores.conversionHealth}/100`)}
    if(site?.advertisingReadiness?.score!=null&&Number(site.advertisingReadiness.score)<60)a.push(`Advertising readiness ${site.advertisingReadiness.score}/100`);return [...new Set(a)].slice(0,10)}
  function commandCenter(l,seo=null,site=null){const svc=serviceScores(l,seo),problems=verifiedProblems(l,seo,site),rm=researchMetrics(l,seo),lh=typeof lowHangingScore==='function'?lowHangingScore(l):{score:l.lowHangingScore||0,grade:'—'},need=typeof primeNeedScore==='function'?primeNeedScore(l):null;const urgency=problems.length>=6?'High':problems.length>=3?'Medium':'Review';return{generatedAt:now(),bestService:svc.best||null,secondaryService:svc.secondary||null,serviceScores:svc,verifiedProblems:problems,research:rm,priority:{lowHanging:lh.score,grade:lh.grade,verifiedNeed:need?.score??null,temperature:typeof hcvTemp==='function'?hcvTemp(l):l.temp||l.temperature||'—'},contact:{phone:l.phone||'',email:l.email||'',decisionMaker:l.decisionMaker||'',title:l.title||''},urgency,nextAction:problems.length?'Contact prospect with the strongest verified problem and one clear outcome.':'Run additional research before pitching.',opening:problems[0]?`I noticed ${problems[0].toLowerCase()} and wanted to share a couple of practical ways I would improve it.`:'I reviewed the public digital presence and wanted to share a few improvement ideas.',packageHint:svc.best?.label||'Growth Package'}}
  async function loadAll(force=false){if(!cloud?.session||G.loading||G.loaded&&!force)return;G.loading=true;try{const uid=cloud.session.user.id;const qs=await Promise.all([
      sb.from('research_runs').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(100),sb.from('sales_engagements').select('*').eq('user_id',uid).order('happened_at',{ascending:false}).limit(500),sb.from('followup_sequences').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('proposals').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('lead_watchlist').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('sales_assets').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('clients').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('keyword_projects').select('*').eq('user_id',uid).order('updated_at',{ascending:false}).limit(200),sb.from('citation_checks').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(200)]);const k=['researchRuns','engagements','sequences','proposals','watchlist','assets','clients','keywords','citations'];qs.forEach((q,i)=>{if(!q.error)G[k[i]]=q.data||[]});G.loaded=true}catch(e){console.warn('Growth OS load',e)}finally{G.loading=false;render()}}
  window.goLoadAll=loadAll;
  function mergeState(original,n){state.saved=state.saved.map(x=>x.id===n.id?n:x);state.results=state.results.map(x=>(x.id===original.id||(typeof same==='function'&&same(x,original)))?{...x,...n}:x);if(state.selected&&(state.selected.id===original.id||(typeof same==='function'&&same(state.selected,original))))state.selected=n;try{persist()}catch{}}
  async function latestSeo(l){if(!cloud?.session||!l?.website)return null;const {data}=await sb.from('seo_audits').select('*').eq('user_id',cloud.session.user.id).eq('business_name',l.name).order('created_at',{ascending:false}).limit(1);return data?.[0]?.result||null}
  async function runResearch(id,includeGoogle=false){if(G.busy)return;let original=leadBy(id)||state.selected;if(!original)return toast('Choose a lead first.');let s=await ensureSaved(original);if(!s)return toast('Could not save the lead before research.');G.busy=true;G.busyText='Starting full research…';render();const checks={},errors=[];let n={...s},seo=null,site=null;try{
      if(n.website){G.busyText='Crawling website, contacts, socials and business age…';render();try{const {data,error}=await sb.functions.invoke('free-prospect-enrich',{body:{leads:[{id:n.id,name:n.name,website:n.website}]}});if(error)throw error;const r=data?.results?.[0];if(r&&typeof afeApply==='function')n=afeApply(n,r);checks.freeEnrich=r?.status||'ok'}catch(e){errors.push('Free enrichment: '+(e?.message||e));checks.freeEnrich='error'}
        G.busyText='Detecting website technology and advertising readiness…';render();try{const {data,error}=await sb.functions.invoke('site-intelligence',{body:{website:n.website}});if(error)throw error;if(data?.error)throw new Error(data.error);site=data;checks.siteIntelligence='ok'}catch(e){errors.push('Site intelligence: '+(e?.message||e));checks.siteIntelligence='error'}
        G.busyText='Checking funnel and lead magnet presence…';render();try{const {data,error}=await sb.functions.invoke('funnel-detect',{body:{website:n.website,businessName:n.name}});if(error)throw error;if(data?.error)throw new Error(data.error);n.funnelIntel={...data,checkedAt:data.checkedAt||now(),source:'full_research'};checks.funnel='ok'}catch(e){errors.push('Funnel: '+(e?.message||e));checks.funnel='error'}
        G.busyText='Running SEO sales audit…';render();try{const {data,error}=await sb.functions.invoke('seo-audit',{body:{website:n.website,businessName:n.name,city:n.city,state:n.state,targetKeyword:n.keyword||n.niche||'',googleBusinessUrl:n.googleReal?.googleMapsUrl||'',competitorUrls:''}});if(error)throw error;if(data?.error)throw new Error(data.error);seo=data;checks.seo='ok';const sc=data.scores||{};await sb.from('seo_audits').insert({user_id:cloud.session.user.id,website_url:data.website||n.website,final_url:data.finalUrl||n.website,business_name:data.businessName||n.name,city:data.city||n.city,state:data.state||n.state,target_keyword:data.targetKeyword||n.keyword||n.niche||null,google_business_url:data.googleBusiness?.url||null,overall_health:sc.overallHealth,seo_opportunity:sc.seoOpportunity,technical_health:sc.technicalHealth,on_page_health:sc.onPageHealth,local_health:sc.localHealth,conversion_health:sc.conversionHealth,result:data})}catch(e){errors.push('SEO: '+(e?.message||e));checks.seo='error'}
      }else{checks.website='no website recorded'}
      if(includeGoogle){G.busyText='Refreshing real Google public data…';render();try{const {data,error}=await sb.functions.invoke('google-place-refresh',{body:{lead:{placeId:n.googlePlaceId||n.placeId||'',googlePlaceId:n.googlePlaceId||'',name:n.name,address:n.address,city:n.city,state:n.state}}});if(error)throw error;if(data?.error)throw new Error(data.error);if(data?.google){n.googlePlaceId=data.google.placeId;n.googleReal=data.google;n.rating=data.google.rating??n.rating;n.reviews=data.google.reviewCount??n.reviews;if(!n.phone&&data.google.phone)n.phone=data.google.phone;if(!n.website&&data.google.website)n.website=data.google.website}checks.google=data?.found?'matched':'not found'}catch(e){errors.push('Google: '+(e?.message||e));checks.google='error'}}
      if(site){n.technologyStack=techFrom(n,site);n.advertisingReadiness=adFrom(n,site)}else{n.technologyStack=techFrom(n,null);n.advertisingReadiness=adFrom(n,null)}if(n.funnelIntel){}try{Object.assign(n,score(n));if(typeof applyLowHanging==='function')n=applyLowHanging(n)}catch{}
      const rm=researchMetrics(n,seo),cmd=commandCenter(n,seo,site);n.researchConfidence=rm.confidence;n.researchCompleteness=rm.completeness;n.fullResearchAt=now();n.salesCommandCenter=cmd;n.serviceOpportunity=cmd.serviceScores;n.latestSeoAudit=seo;
      const payload=typeof leadToDb==='function'?leadToDb(n):{};Object.assign(payload,{research_confidence:rm.confidence,research_completeness:rm.completeness,full_research_at:n.fullResearchAt,technology_stack:n.technologyStack,advertising_readiness:n.advertisingReadiness,sales_command_center:cmd,service_opportunity:cmd.serviceScores,funnel_intelligence:n.funnelIntel||null,funnel_checked_at:n.funnelIntel?.checkedAt||null});delete payload.user_id;const {data:row,error:upErr}=await sb.from('leads').update(payload).eq('id',s.id).eq('user_id',cloud.session.user.id).select().single();if(upErr)throw upErr;if(row&&typeof dbToLead==='function')n={...n,...dbToLead(row),id:s.id,technologyStack:n.technologyStack,advertisingReadiness:n.advertisingReadiness,salesCommandCenter:cmd,latestSeoAudit:seo,funnelIntel:n.funnelIntel};mergeState(original,n);await sb.from('research_runs').insert({user_id:cloud.session.user.id,lead_id:s.id,confidence:rm.confidence,completeness:rm.completeness,status:errors.length?'completed_with_warnings':'completed',checks,evidence:{commandCenter:cmd,technology:n.technologyStack,advertising:n.advertisingReadiness,seo:seo?{scores:seo.scores,issues:(seo.scores?.issues||[]).slice(0,12)}:null,funnel:n.funnelIntel||null},errors});if(typeof log==='function')log(n,'full_research',`Full research completed · confidence ${rm.confidence}/100 · completeness ${rm.completeness}/100${errors.length?` · ${errors.length} warning(s)`:''}`);await loadAll(true);toast(`Full research complete · ${rm.confidence}/100 confidence${errors.length?` · ${errors.length} warning(s)`:''}.`)}catch(e){toast('Full research failed: '+(e?.message||'Unknown error'))}finally{G.busy=false;G.busyText='';render()}}
  window.goFullResearch=id=>runResearch(id,false);window.goFullResearchGoogle=id=>{if(confirm('This will make an explicit Google Places API call and may use paid Google quota. Continue?'))runResearch(id,true)};
  window.goOpenLead=function(id){const l=leadBy(id);if(l){state.selected=l;render()}};
  window.goCoach=function(id,mode='strategy'){const l=leadBy(id);if(!l)return;if(typeof aiOpenLead==='function'){aiOpenLead(id);setTimeout(()=>{if(state.aiSales){const q={strategy:'Coach me on how to approach this prospect. Give me the opening, likely objections, strongest verified service angle, and what not to claim.',objections:'Role-play the prospect and coach me through likely objections about price, SEO, funnels, and marketing. Use the saved evidence.',call:'Give me a 30-second cold-call opener and 3 follow-up questions based only on verified evidence.',proposal:'Tell me what package I should propose first and why, using only the verified findings.'};state.aiSales.prompt=q[mode]||q.strategy;render()}},50)}else toast('AI Sales Assistant is not loaded.')};
  window.goLogEngagement=async function(id,channel,outcome,notes=''){const l=leadBy(id),s=await ensureSaved(l);if(!s)return;const text=notes||prompt('Optional note:','')||'';const {error}=await sb.from('sales_engagements').insert({user_id:cloud.session.user.id,lead_id:s.id,channel,outcome,notes:text,happened_at:now()});if(error)return toast(error.message);await sb.from('leads').update({last_outreach_at:now(),outreach_status:outcome,updated_at:now()}).eq('id',s.id).eq('user_id',cloud.session.user.id);if(typeof log==='function')log(s,'sales_engagement',`${channel}: ${outcome}${text?' · '+text:''}`);await loadAll(true);toast('Sales activity logged.')};
  const followDefaults=[{day:0,channel:'email',label:'Personalized cold email',prompt:'Lead with one verified problem and one clear CTA.'},{day:3,channel:'text',label:'Short text / call attempt',prompt:'Keep it brief and reference the value offered.'},{day:7,channel:'email',label:'Value follow-up',prompt:'Share one audit insight or visual without adding pressure.'},{day:12,channel:'call',label:'Call / voicemail',prompt:'Use the strongest verified service angle.'},{day:18,channel:'email',label:'Final follow-up',prompt:'Close the loop professionally and leave the door open.'}];
  window.goCreateSequence=async function(id){const l=leadBy(id),s=await ensureSaved(l);if(!s)return;const focus=s.salesCommandCenter?.bestService?.label||s.serviceOpportunity?.best?.label||'Growth';const start=new Date(),steps=followDefaults.map((x,i)=>({...x,dueAt:new Date(start.getTime()+x.day*86400000).toISOString(),done:false,index:i}));const {error}=await sb.from('followup_sequences').insert({user_id:cloud.session.user.id,lead_id:s.id,name:`${s.name} · ${focus} follow-up`,service_focus:focus,steps,current_step:0,started_at:now(),next_step_at:steps[0].dueAt,status:'active'});if(error)return toast(error.message);await loadAll(true);toast('5-touch follow-up sequence created.')};
  window.goCompleteStep=async function(seqId){const q=G.sequences.find(x=>x.id===seqId);if(!q)return;const steps=Array.isArray(q.steps)?q.steps:[],i=Number(q.current_step||0),step=steps[i];if(!step)return;steps[i]={...step,done:true,completedAt:now()};const next=i+1,nextStep=steps[next];await sb.from('followup_sequences').update({steps,current_step:next,next_step_at:nextStep?.dueAt||null,status:nextStep?'active':'completed',completed_at:nextStep?null:now(),updated_at:now()}).eq('id',q.id).eq('user_id',cloud.session.user.id);if(q.lead_id)await sb.from('sales_engagements').insert({user_id:cloud.session.user.id,lead_id:q.lead_id,channel:step.channel,outcome:'sequence_step_completed',notes:step.label,happened_at:now()});await loadAll(true);toast(nextStep?'Step completed. Next follow-up scheduled.':'Sequence completed.')};
  function packageFor(l){const cmd=l.salesCommandCenter||commandCenter(l,l.latestSeoAudit||null,null),best=cmd.bestService?.label||'Growth Package';const map={'Web Design':{name:'Website Conversion Upgrade',setup:1500,monthly:0},'SEO':{name:'SEO Growth Foundation',setup:500,monthly:750},'Funnel Design':{name:'Lead Generation Funnel',setup:1000,monthly:250},'Google Business Profile / Local SEO':{name:'Local Visibility Growth',setup:350,monthly:400},'Social Media':{name:'Social Lead Growth',setup:250,monthly:650},'PPC / Tracking':{name:'Paid Lead Generation Setup',setup:500,monthly:600}};return{service:best,...(map[best]||{name:'Digital Growth System',setup:2500,monthly:1250}),problems:cmd.verifiedProblems||[],secondary:cmd.secondaryService?.label||''}}
  window.goCreateProposal=async function(id){const l=leadBy(id),s=await ensureSaved(l);if(!s)return;const p=packageFor(s),setup=Number(prompt('Suggested one-time/setup price — edit as needed:',String(p.setup))||p.setup),monthly=Number(prompt('Suggested monthly price — edit as needed:',String(p.monthly))||p.monthly);const content={business:s.name,executiveSummary:`Based on the verified public audit, the recommended first priority is ${p.service}.`,findings:p.problems,recommendedService:p.service,secondaryService:p.secondary,scope:[`Implement ${p.service}`,p.secondary?`Consider ${p.secondary} as a secondary phase`:null,'Measurement and conversion review'].filter(Boolean),timeline:'Final timeline to be confirmed after scope review.',disclaimer:'Recommendations are based on the public evidence captured in the CRM. Rankings, lead volume and revenue are not guaranteed.'};const {data,error}=await sb.from('proposals').insert({user_id:cloud.session.user.id,lead_id:s.id,title:`${s.name} · ${p.name}`,service_focus:p.service,package_name:p.name,setup_amount:isFinite(setup)?setup:0,monthly_amount:isFinite(monthly)?monthly:0,content,pricing:{suggested:true,editable:true}}).select().single();if(error)return toast(error.message);G.proposalLeadId=s.id;await loadAll(true);state.growth.section='proposals';state.view='growth';render();toast('Proposal draft created. Review pricing and scope before sending.')};
  window.goUpdateProposal=async function(id){const title=document.getElementById('goPropTitle')?.value||'',pkg=document.getElementById('goPropPkg')?.value||'',setup=Number(document.getElementById('goPropSetup')?.value||0),monthly=Number(document.getElementById('goPropMonthly')?.value||0),summary=document.getElementById('goPropSummary')?.value||'',scope=(document.getElementById('goPropScope')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean);const p=G.proposals.find(x=>x.id===id);if(!p)return;const content={...(p.content||{}),executiveSummary:summary,scope};const {error}=await sb.from('proposals').update({title,package_name:pkg,setup_amount:setup,monthly_amount:monthly,content,updated_at:now()}).eq('id',id).eq('user_id',cloud.session.user.id);if(error)return toast(error.message);await loadAll(true);toast('Proposal saved.')};
  window.goProposalStatus=async function(id,status){const patch={status,updated_at:now()};if(status==='sent')patch.sent_at=now();if(status==='accepted')patch.accepted_at=now();await sb.from('proposals').update(patch).eq('id',id).eq('user_id',cloud.session.user.id);await loadAll(true);toast('Proposal status updated.')};
  window.goPrintProposal=function(id){const p=G.proposals.find(x=>x.id===id);if(!p)return;const l=leadBy(p.lead_id),c=p.content||{},w=window.open('','_blank');if(!w)return toast('Allow pop-ups to print/save the proposal PDF.');w.document.write(`<!doctype html><html><head><title>${ge(p.title)}</title><style>body{font-family:Arial,sans-serif;color:#172033;max-width:850px;margin:40px auto;padding:0 24px;line-height:1.5}h1{font-size:34px}h2{margin-top:32px;border-bottom:1px solid #ddd;padding-bottom:8px}.price{font-size:24px;font-weight:700}.box{background:#f5f7fb;padding:18px;border-radius:12px;margin:14px 0}li{margin:7px 0}.muted{color:#667085}</style></head><body><div class=muted>SKYLIGHT REFLECTIONS MARKETING</div><h1>${ge(p.title)}</h1><p>Prepared for <b>${ge(l?.name||c.business||'Prospect')}</b></p><h2>Executive Summary</h2><p>${ge(c.executiveSummary||'')}</p><h2>What We Found</h2><ul>${(c.findings||[]).map(x=>`<li>${ge(x)}</li>`).join('')}</ul><h2>Recommended Scope</h2><ul>${(c.scope||[]).map(x=>`<li>${ge(x)}</li>`).join('')}</ul><h2>Investment</h2><div class=box><div class=price>$${Number(p.setup_amount||0).toLocaleString()} setup</div><div class=price>$${Number(p.monthly_amount||0).toLocaleString()}/month</div></div><h2>Next Step</h2><p>Confirm final scope, timeline, responsibilities and terms before work begins.</p><p class=muted>${ge(c.disclaimer||'No performance guarantees are implied.')}</p><script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()};
  window.goToggleWatch=async function(id){const l=leadBy(id),s=await ensureSaved(l);if(!s)return;const hit=G.watchlist.find(x=>x.lead_id===s.id);if(hit){await sb.from('lead_watchlist').update({enabled:!hit.enabled,updated_at:now()}).eq('id',hit.id).eq('user_id',cloud.session.user.id)}else{const snap={website:s.website||'',phone:s.phone||'',email:s.email||'',webScore:s.webScore??null,funnelStatus:s.funnelIntel?.status||null,rating:s.rating??null,reviews:s.reviews??null};await sb.from('lead_watchlist').insert({user_id:cloud.session.user.id,lead_id:s.id,enabled:true,cadence:'weekly',snapshot:snap})}await loadAll(true);render();toast(hit?'Watchlist status changed.':'Lead added to watchlist.')};
  window.goCheckWatch=async function(id){const w=G.watchlist.find(x=>x.id===id);if(!w)return;const l=leadBy(w.lead_id);if(!l)return toast('Lead not loaded in CRM.');let latest={...l},changes=[];try{if(l.website){const {data}=await sb.functions.invoke('free-prospect-enrich',{body:{leads:[{id:l.id,name:l.name,website:l.website}]}});const r=data?.results?.[0];if(r&&typeof afeApply==='function')latest=afeApply(l,r)}const old=w.snapshot||{},snap={website:latest.website||'',phone:latest.phone||'',email:latest.email||'',webScore:latest.webScore??null,funnelStatus:latest.funnelIntel?.status||null,rating:latest.rating??null,reviews:latest.reviews??null};for(const k of Object.keys(snap))if(String(old[k]??'')!==String(snap[k]??''))changes.push({field:k,from:old[k]??null,to:snap[k]??null});await sb.from('lead_watchlist').update({snapshot:snap,last_changes:changes,last_checked_at:now(),updated_at:now()}).eq('id',w.id).eq('user_id',cloud.session.user.id);await loadAll(true);toast(changes.length?`${changes.length} change(s) detected.`:'No tracked changes detected.')}catch(e){toast('Watchlist check failed: '+(e?.message||'Unknown error'))}};
  window.goConvertClient=async function(id){const l=leadBy(id),s=await ensureSaved(l);if(!s)return;const svc=prompt('Services sold (comma separated):',s.salesCommandCenter?.bestService?.label||'SEO')||'';const setup=Number(prompt('One-time/setup value:','0')||0),monthly=Number(prompt('Monthly recurring value:','0')||0);if(!confirm(`Convert ${s.name} to an active client?`))return;const {error}=await sb.from('clients').upsert({user_id:cloud.session.user.id,lead_id:s.id,business_name:s.name,status:'active',services:svc.split(',').map(x=>x.trim()).filter(Boolean),setup_value:setup,monthly_value:monthly,updated_at:now()},{onConflict:'user_id,lead_id'});if(error)return toast(error.message);await sb.from('leads').update({stage:'Won',updated_at:now()}).eq('id',s.id).eq('user_id',cloud.session.user.id);await loadAll(true);toast('Lead converted to client and moved to Won.')};
  window.goClientStatus=async function(id,status){await sb.from('clients').update({status,updated_at:now()}).eq('id',id).eq('user_id',cloud.session.user.id);await loadAll(true)};
  window.goGenerateKeywords=function(){const f=G.keywordForm,seed=String(f.seed||f.niche||'service').trim(),city=String(f.city||'').trim(),st=String(f.state||'').trim(),loc=[city,st].filter(Boolean).join(' '),niche=String(f.niche||seed).trim();const core=[seed,`${seed} services`,`${seed} company`,`${seed} near me`],local=loc?[`${seed} ${loc}`,`best ${seed} ${loc}`,`${niche} ${loc}`,`${seed} near ${city}`]:[],commercial=[`best ${seed}`,`${seed} cost`,`${seed} pricing`,`${seed} quote`,`${seed} consultation`,`${seed} company`],long=[`how to choose a ${seed}`,`how much does ${seed} cost`,`${seed} checklist`,`${seed} FAQ`,`${seed} vs alternatives`],funnel=[`${seed} free estimate`,`${seed} free consultation`,`${seed} quote`,`${seed} appointment`,`${seed} same day service`],negative=['jobs','salary','training','course','DIY','free download'];G.keywordDraft={name:f.name||`${seed} · ${loc||'Keyword Plan'}`,niche,city,state:st,seedKeyword:seed,strategy:{core:[...new Set(core)],local:[...new Set(local)],commercial:[...new Set(commercial)],longTail:[...new Set(long)],funnel:[...new Set(funnel)],negative,notes:'Idea generation only. Search volume, CPC and difficulty remain unchecked until a legitimate keyword data provider is connected.'}};render()};
  window.goSaveKeywords=async function(){const d=G.keywordDraft;if(!d||!cloud?.session)return;const {error}=await sb.from('keyword_projects').insert({user_id:cloud.session.user.id,lead_id:G.proposalLeadId||null,name:d.name,niche:d.niche,city:d.city,state:d.state,seed_keyword:d.seedKeyword,strategy:d.strategy});if(error)return toast(error.message);await loadAll(true);toast('Keyword project saved.')};
  window.goSaveCitation=async function(){if(!cloud?.session)return;const id=document.getElementById('goCitationLead')?.value||'',l=leadBy(id);if(!l)return toast('Choose a lead.');const platforms=['google','apple','bing','yelp','facebook','bbb','chamber','industry'];const result={};platforms.forEach(p=>{result[p]={status:document.getElementById('cit_'+p)?.value||'unchecked',url:document.getElementById('cit_'+p+'_url')?.value||''}});const nap={name:l.name,address:l.address||'',phone:l.phone||'',website:l.website||''};const {error}=await sb.from('citation_checks').insert({user_id:cloud.session.user.id,lead_id:l.id,business_name:l.name,nap,result});if(error)return toast(error.message);await loadAll(true);toast('Citation/NAP check saved.')};
  window.goSaveAsset=async function(){const name=document.getElementById('goAssetName')?.value||'',type=document.getElementById('goAssetType')?.value||'case_study',url=document.getElementById('goAssetUrl')?.value||'',desc=document.getElementById('goAssetDesc')?.value||'',svc=document.getElementById('goAssetSvc')?.value||'',niche=document.getElementById('goAssetNiche')?.value||'',tags=(document.getElementById('goAssetTags')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);if(!name)return toast('Give the asset a name.');const {error}=await sb.from('sales_assets').insert({user_id:cloud.session.user.id,name,asset_type:type,url:url||null,description:desc||null,tags,service_focus:svc||null,niche:niche||null});if(error)return toast(error.message);await loadAll(true);toast('Sales asset saved.')};
  window.goDeleteAsset=async function(id){await sb.from('sales_assets').delete().eq('id',id).eq('user_id',cloud.session.user.id);await loadAll(true)};
  window.goCaptureVisual=async function(id,strategy='mobile'){const l=leadBy(id);if(!l?.website)return toast('This lead needs a website URL first.');if(G.visualBusy)return;G.visualBusy=true;G.visual=null;render();try{const {data,error}=await sb.functions.invoke('site-visual-snapshot',{body:{website:l.website,strategy}});if(error)throw error;if(data?.error)throw new Error(data.error);G.visual={...data,leadId:l.id};if(uuid(l.id))await sb.from('site_visual_snapshots').insert({user_id:cloud.session.user.id,lead_id:l.id,website_url:l.website,strategy,performance_score:data.performanceScore,metrics:data.metrics||{},screenshot_data:data.screenshotData||null});toast(data.screenshotData?'Real website snapshot captured.':'Performance data captured; screenshot was unavailable.')}catch(e){toast('Website snapshot: '+(e?.message||'Could not capture'))}finally{G.visualBusy=false;render()}};
  window.goDownloadVisual=function(){if(!G.visual?.screenshotData)return toast('No screenshot is available to download.');const a=document.createElement('a');a.href=G.visual.screenshotData;a.download='website-audit-snapshot.jpg';a.click()};
  window.goSection=function(s){G.section=s;state.view='growth';render();loadAll()};
  window.goSetKeyword=function(k,v){G.keywordForm[k]=v};
  window.goOpenProposal=function(id){G.activeProposal=id;G.section='proposals';state.view='growth';render()};
  window.goCopy=function(txt,msg='Copied'){if(typeof copyText==='function')copyText(txt,msg);else navigator.clipboard?.writeText(txt).then(()=>toast(msg))};
  window.goCommandCenter=commandCenter;window.goResearchMetrics=researchMetrics;window.goPackageFor=packageFor;
})();