function p15Quality(){
  const a=state.results||[],n=a.length;if(!n)return{n:0,quality:0};
  const q={n,phone:a.filter(x=>x.phone).length,website:a.filter(x=>x.website).length,email:a.filter(x=>x.email).length,enriched:a.filter(x=>x.auditChecked===true||x.autoEnriched).length,age:a.filter(x=>ageYears(x)!=null).length,dm:a.filter(x=>x.decisionMaker).length,prime:a.filter(x=>lowHangingScore(x).score>=75).length,strong:a.filter(x=>{const s=lowHangingScore(x).score;return s>=60&&s<75}).length,errors:a.filter(x=>['error','invalid_website'].includes(String(x.autoEnrichStatus||''))).length};
  q.quality=Math.round((q.phone/n)*20+(q.website/n)*10+(q.email/n)*15+(q.enriched/n)*20+(q.age/n)*15+(q.dm/n)*20);q.primeYield=p15Pct(q.prime,n);return q;
}
async function p15RecordQuality(){
  if(!cloud?.session||!state.results?.length)return;const q=p15Quality();
  const {data}=await sb.from('search_history').select('id,metrics').eq('user_id',cloud.session.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!data?.id)return;
  await sb.from('search_history').update({quality_score:q.quality,phone_count:q.phone,website_count:q.website,email_count:q.email,age_count:q.age,decision_maker_count:q.dm,error_count:q.errors,metrics:{...(data.metrics||{}),quality_score:q.quality,phone:q.phone,website:q.website,email:q.email,age:q.age,decision_makers:q.dm,enriched:q.enriched,prime:q.prime,strong:q.strong,prime_yield:q.primeYield,errors:q.errors}}).eq('id',data.id);
  state.p15.analyticsLoaded=false;
}
const p15GenerateBase=generate;generate=async function(){await p15GenerateBase();if(state.searchMode==='free_live'&&state.results?.length)await p15RecordQuality()};

async function p15RunHealth(){
  if(!cloud?.session||state.p15.healthRunning)return;state.p15.healthRunning=true;render();
  const out={checkedAt:new Date().toISOString(),items:[]};const add=(name,ok,detail,kind='core')=>out.items.push({name,ok,detail,kind});
  try{const {error}=await sb.from('user_preferences').select('user_id').eq('user_id',cloud.session.user.id).maybeSingle();add('Supabase database',!error,error?error.message:'Connected + RLS session valid');}catch(e){add('Supabase database',false,e?.message||'Failed')}
  try{const {data,error}=await sb.functions.invoke('system-health',{body:{}});if(error||data?.error)throw error||new Error(data.error);add('System Health Edge Function',true,'Authenticated and responding');for(const c of data.checks||[])add(c.name,!!c.ok,c.ok?`${c.status} · ${c.latencyMs} ms`:(c.error||`HTTP ${c.status}`));add('Hunter',true,data.providers?.hunterConfigured?'Connected · free-plan use available':'Not connected · optional',data.providers?.hunterConfigured?'provider':'optional');add('Google Places',true,data.providers?.googlePlacesConfigured?'Connected but optional':'Off · free OSM search is primary','optional');add('DataForSEO',true,data.providers?.dataForSeoConfigured?'Configured (paid; Free Mode should keep it off)':'Off · expected in Free Mode','optional');}catch(e){add('System Health Edge Function',false,e?.message||'Failed')}
  try{const {data,error}=await sb.functions.invoke('free-prospect-enrich',{body:{leads:[{id:'health',name:'Health Check',website:''}]}});add('Free website enrichment',!error&&!data?.error,!error&&!data?.error?'Function responding · no paid calls used':(error?.message||data?.error||'Failed'));}catch(e){add('Free website enrichment',false,e?.message||'Failed')}
  add('Free Live Market Search',state.searchMode==='free_live'||state.searchMode!=='error',state.searchMode==='free_live'?'Last live search succeeded':'Ready · run a market search to validate this session');
  add('Source Import',true,'Deployed · runtime crawl runs only when you submit a source URL');
  state.p15.health=out;state.p15.healthRunning=false;render();
}
function p15Status(ok){return `<span class="tag ${ok?'good':'bad'}">${ok?'PASS':'CHECK'}</span>`}
function p15HealthView(){const h=state.p15.health;return `<div class="top"><div><div class=eyebrow>PRODUCTION HEALTH</div><h1>System Health Dashboard</h1><p>Read-only checks. No Hunter credits, Google calls, or DataForSEO spend.</p></div><button class="btn primary" onclick="p15RunHealth()" ${state.p15.healthRunning?'disabled':''}>${state.p15.healthRunning?'Checking…':'Run Health Check'}</button></div>${!h?'<div class=panel><div class=empty>Run the health check to validate the live stack.</div></div>':`<div class=panel><div class=head><div><div class=eyebrow>LAST CHECK</div><h2>${esc(new Date(h.checkedAt).toLocaleString())}</h2></div><span class="tag good">$0 CHECK</span></div>${h.items.map(x=>`<div class=historyrow style="grid-template-columns:1.1fr 90px 2fr"><b>${esc(x.name)}</b><div>${p15Status(x.ok)}</div><div class=sub>${esc(x.detail)}</div></div>`).join('')}</div>`}`}

async function p15LoadAnalytics(force=false){
  if(!cloud?.session||state.p15.analyticsLoading||(!force&&state.p15.analyticsLoaded))return;state.p15.analyticsLoading=true;
  const {data,error}=await sb.from('search_history').select('id,niche,cities,state,source,result_count,prime_count,strong_count,avg_low_hanging_score,quality_score,phone_count,website_count,email_count,age_count,decision_maker_count,error_count,metrics,created_at').eq('user_id',cloud.session.user.id).order('created_at',{ascending:false}).limit(1000);
  if(!error)state.p15.analytics=data||[];state.p15.analyticsLoaded=!error;state.p15.analyticsLoading=false;
}
function p15MarketRows(){
  const m=new Map();for(const r of state.p15.analytics){const market=(r.cities||[]).join(', ')||'Unknown market',key=`${String(r.niche||'Local business').toLowerCase()}|${market.toLowerCase()}|${String(r.state||'').toLowerCase()}`;if(!m.has(key))m.set(key,{niche:r.niche||'Local business',market,state:r.state||'',runs:0,results:0,prime:0,strong:0,quality:[],lh:[],phone:0,email:0,dm:0,errors:0});const x=m.get(key);x.runs++;x.results+=Number(r.result_count)||0;x.prime+=Number(r.prime_count)||0;x.strong+=Number(r.strong_count)||0;if(r.quality_score!=null)x.quality.push(Number(r.quality_score));if(r.avg_low_hanging_score!=null)x.lh.push(Number(r.avg_low_hanging_score));x.phone+=Number(r.phone_count||r.metrics?.phone)||0;x.email+=Number(r.email_count||r.metrics?.email)||0;x.dm+=Number(r.decision_maker_count||r.metrics?.decision_makers)||0;x.errors+=Number(r.error_count||r.metrics?.errors)||0;}
  return[...m.values()].map(x=>({...x,primeYield:p15Pct(x.prime,x.results),phoneCoverage:p15Pct(x.phone,x.results),emailCoverage:p15Pct(x.email,x.results),dmCoverage:p15Pct(x.dm,x.results),quality:Math.round(p15Avg(x.quality)||0),avgLH:Math.round(p15Avg(x.lh)||0)})).sort((a,b)=>(b.primeYield-a.primeYield)||(b.prime-a.prime)||(b.quality-a.quality));
}
function p15AnalyticsView(){const rows=p15MarketRows();return `<div class=top><div><div class=eyebrow>MARKET INTELLIGENCE</div><h1>Best Niches & Markets</h1><p>Ranks your actual search history by PRIME yield and data quality.</p></div><button class=btn onclick="p15RefreshAnalytics()">Refresh</button></div>${state.p15.analyticsLoading?'<div class=panel><div class=empty>Loading analytics…</div></div>':!rows.length?'<div class=panel><div class=empty>Run live searches first. This dashboard learns from your real results.</div></div>':`<div class=panel><div class=head><div><div class=eyebrow>PERFORMANCE</div><h2>Winning market / niche combinations</h2></div></div><div class=tablewrap><table class=table><thead><tr><th>NICHE</th><th>MARKET</th><th>RUNS</th><th>LEADS</th><th>PRIME</th><th>PRIME YIELD</th><th>DATA QUALITY</th><th>PHONE</th><th>EMAIL</th><th>OWNER</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.niche)}</b></td><td>${esc(x.market)} ${esc(x.state)}</td><td>${x.runs}</td><td>${x.results}</td><td><b>${x.prime}</b></td><td><span class="score ${x.primeYield>=20?'hot':'cold'}">${x.primeYield}%</span></td><td>${x.quality}/100</td><td>${x.phoneCoverage}%</td><td>${x.emailCoverage}%</td><td>${x.dmCoverage}%</td></tr>`).join('')}</tbody></table></div></div>`}`}
async function p15RefreshAnalytics(){await p15LoadAnalytics(true);render()}
async function p15Go(v){state.view=v;render();if(v==='health15'&&!state.p15.health)await p15RunHealth();if(v==='analytics15'){await p15LoadAnalytics();render();}}
