function p15ScoreCard(name,obj){const s=obj?.score;return `<div class=stat><span>${esc(name)}</span><b>${s==null?'—':s}</b><div class=sub>${esc(obj?.confidence||'unchecked')}${obj?.why?.[0]?` · ${esc(obj.why[0])}`:''}</div></div>`}
function p15CompetitorHtml(l){const c=p15CompetitorSnapshot(l);if(!c.available)return `<div class=sub>${esc(c.note)}</div>`;return `<div class=kv><span>Peer sample</span><span>${c.sampleSize}</span><span>Avg website</span><span>${c.averages.websiteScore==null?'—':c.averages.websiteScore+'/100'}</span><span>Avg social</span><span>${c.averages.socialProfiles==null?'—':c.averages.socialProfiles}</span><span>Avg Low-Hanging</span><span>${c.averages.lowHangingScore==null?'—':c.averages.lowHangingScore+'/100'}</span></div>${c.insights.length?c.insights.map(x=>`<div class=notice style="margin:7px 0">${esc(x)}</div>`).join(''):'<div class=sub>No material disadvantage detected against the current peer sample.</div>'}<div class=sub style="margin-top:8px">${esc(c.note)}</div>`}
function p15Copy(text,msg='Copied'){navigator.clipboard?.writeText(text).then(()=>toast(msg)).catch(()=>toast('Copy failed.'))}
function p15PrepText(p,type){if(type==='call')return [p.callOpening,'',...p.callPoints.map(x=>'• '+x)].join('\n');if(type==='email')return `Subject: ${p.emailSubject}\n\n${p.emailBody}`;if(type==='social')return p.socialMessage;return p.followUp}
async function p15PersistIntelligence(l){const hit=findSaved(l);if(!hit||!isUuid(hit.id))return toast('Save this lead first.');const svc=p15ServiceScores(l),comp=p15CompetitorSnapshot(l),prep=p15SalesPrep(l);const {error}=await sb.from('leads').update({service_opportunity:svc,competitor_snapshot:comp,sales_prep:prep,updated_at:new Date().toISOString()}).eq('id',hit.id);if(error)return toast('Could not save intelligence: '+error.message);state.saved=state.saved.map(x=>x.id===hit.id?{...x,serviceOpportunity:svc,competitorSnapshot:comp,salesPrep:prep}:x);toast('Sales intelligence saved to CRM.')}

const p15DrawerBase=drawer;drawer=function(){let h=p15DrawerBase();if(!state.selected)return h;const l=state.selected,svc=p15ServiceScores(l),prep=p15SalesPrep(l);const service=`<div class=section><b>Service Opportunity Scores</b><div class=stats style="grid-template-columns:repeat(2,1fr)">${p15ScoreCard('Website',svc.website)}${p15ScoreCard('SEO',svc.seo)}${p15ScoreCard('Social',svc.social)}${p15ScoreCard('PPC / Tracking',svc.ppc)}${p15ScoreCard('Google Business',svc.gbp)}</div><div class=notice><b>Best first offer:</b> ${esc(svc.best?.label||'Needs more verified data')}${svc.best?` · ${svc.best.score}/100 opportunity`:''}</div></div>`;
  const competitor=`<div class=section><b>Competitor Snapshot</b>${p15CompetitorHtml(l)}</div>`;
  const sales=`<div class=section><b>Sales Prep Assistant</b><div class=notice><b>Recommended lead offer:</b> ${esc(prep.bestOffer?.label||'Digital marketing review')}</div><div class=sub style="white-space:pre-wrap;margin:8px 0">${esc(prep.callOpening)}</div><div style="display:flex;flex-wrap:wrap;gap:7px"><button class=btn onclick="p15Copy(p15PrepText(p15SalesPrep(state.selected),'call'),'Call notes copied')">Copy Call Notes</button><button class=btn onclick="p15Copy(p15PrepText(p15SalesPrep(state.selected),'email'),'Email copied')">Copy Email</button><button class=btn onclick="p15Copy(p15PrepText(p15SalesPrep(state.selected),'social'),'Social message copied')">Copy Social Message</button><button class=btn onclick="p15Copy(p15PrepText(p15SalesPrep(state.selected),'follow'),'Follow-up copied')">Copy Follow-Up</button></div><details style="margin-top:10px"><summary style="cursor:pointer;font-weight:700">Preview outreach</summary><div class=sub style="white-space:pre-wrap;margin-top:8px">${esc(p15PrepText(prep,'email'))}</div></details><button class="btn primary" style="margin-top:10px" onclick="p15PersistIntelligence(state.selected)">Save Sales Intelligence</button></div>`;
  return h.replace('<div class="section"><b>CRM</b>',service+competitor+sales+'<div class="section"><b>CRM</b>');
};

function p15QualityPanel(){const q=p15Quality();if(!q.n||state.view!=='search')return'';return `<div id=p15QualityPanel class=panel style="margin-bottom:14px"><div class=head><div><div class=eyebrow>PRODUCTION VALIDATION</div><h2>Search Quality + Conversion Readiness</h2></div><span class="tag ${q.quality>=60?'good':''}">${q.quality}/100 DATA QUALITY</span></div><div class=stats style="padding:0 14px 14px"><div class=stat><span>Phone</span><b>${p15Pct(q.phone,q.n)}%</b></div><div class=stat><span>Email</span><b>${p15Pct(q.email,q.n)}%</b></div><div class=stat><span>Owner found</span><b>${p15Pct(q.dm,q.n)}%</b></div><div class=stat><span>Age known</span><b>${p15Pct(q.age,q.n)}%</b></div><div class=stat><span>PRIME yield</span><b>${q.primeYield}%</b></div></div><div class=sub style="padding:0 14px 14px">${q.prime} PRIME · ${q.strong} STRONG · ${q.enriched}/${q.n} enriched · ${q.errors} enrichment errors</div></div>`}
function p15AddNav(){const nav=document.querySelector('.nav');if(!nav)return;let a=document.getElementById('p15HealthNav'),b=document.getElementById('p15AnalyticsNav');if(!a){a=document.createElement('button');a.id='p15HealthNav';a.textContent='♥ System Health';a.onclick=()=>p15Go('health15');nav.appendChild(a)}if(!b){b=document.createElement('button');b.id='p15AnalyticsNav';b.textContent='◈ Market Analytics';b.onclick=()=>p15Go('analytics15');nav.appendChild(b)}a.classList.toggle('active',state.view==='health15');b.classList.toggle('active',state.view==='analytics15')}

const p15RenderBase=render;render=function(){const v=state.view,custom=v==='health15'||v==='analytics15';if(custom)state.view='search';p15RenderBase();if(custom)state.view=v;p15AddNav();if(custom){const main=document.querySelector('.main');if(main)main.innerHTML=v==='health15'?p15HealthView():p15AnalyticsView();return}if(state.view==='search'&&state.results?.length){const market=[...document.querySelectorAll('.panel')].find(p=>p.textContent.includes('MARKET RESULTS'));if(market&&!document.getElementById('p15QualityPanel'))market.insertAdjacentHTML('beforebegin',p15QualityPanel())}const conn=document.querySelector('.conn');if(conn){let row=document.getElementById('p15SalesIntelStatus');if(!row){row=document.createElement('div');row.className='prov';row.id='p15SalesIntelStatus';conn.appendChild(row)}row.innerHTML='<span>Sales Intelligence</span><b style="color:var(--green)">LIVE · FREE</b>'}};
render();
