state.filters.quickWin=state.filters.quickWin||'ALL';
function qwMatch(l,type){const y=ageYears(l),fresh=bpFreshnessDays(l),weak=!l.website||(l.auditChecked===true&&Number(l.webScore)<60);switch(type){case'PRIME':return lowHangingScore(l).score>=75&&reachableLead(l);case'NO_WEBSITE':return !l.website&&reachableLead(l);case'WEAK_ESTABLISHED':return Boolean(l.website)&&l.auditChecked===true&&Number(l.webScore)<60&&y!=null&&y>=3&&reachableLead(l);case'STALE_ESTABLISHED':return Boolean(l.website)&&fresh!=null&&fresh>365&&y!=null&&y>=3&&reachableLead(l);case'NO_TRACKING':return Boolean(l.website)&&l.auditChecked===true&&l.analytics===false&&l.metaPixel===false&&l.adsTracking===false&&reachableLead(l);case'OWNER_FOUND':return Boolean(l.decisionMaker)&&weak&&reachableLead(l);default:return true}}
function qwLabel(type){return({PRIME:'PRIME Targets',NO_WEBSITE:'No Website + Reachable',WEAK_ESTABLISHED:'Weak Site + Established',STALE_ESTABLISHED:'Stale Site + Established',NO_TRACKING:'No Tracking Setup',OWNER_FOUND:'Owner Found + Weak Marketing'}[type]||'All Prospects')}
const qwBaseVisible=visible;visible=function(){let a=qwBaseVisible();if(state.view==='search'&&state.filters.quickWin!=='ALL')a=a.filter(l=>qwMatch(l,state.filters.quickWin));return a};
function setQuickWin(type){state.filters.quickWin=type;state.filters.bestFirst=true;render();toast(type==='ALL'?'Showing all prospects.':`Quick Win lane: ${qwLabel(type)}.`)}
async function saveTopPrime(){const leads=[...state.results].map(applyLowHanging).filter(l=>lowHangingScore(l).score>=75&&reachableLead(l)).sort((a,b)=>lowHangingScore(b).score-lowHangingScore(a).score).slice(0,10);if(!leads.length)return toast('No PRIME reachable prospects are available yet.');let added=0;for(const l of leads){if(!findSaved(l)){await saveLead(l,true);added++}}render();toast(added?`Saved ${added} PRIME prospect${added===1?'':'s'} to the CRM.`:'Top PRIME prospects are already saved.')}
function qwCounts(){const a=state.results||[];return{prime:a.filter(l=>qwMatch(l,'PRIME')).length,noWeb:a.filter(l=>qwMatch(l,'NO_WEBSITE')).length,weak:a.filter(l=>qwMatch(l,'WEAK_ESTABLISHED')).length,stale:a.filter(l=>qwMatch(l,'STALE_ESTABLISHED')).length,tracking:a.filter(l=>qwMatch(l,'NO_TRACKING')).length,owner:a.filter(l=>qwMatch(l,'OWNER_FOUND')).length}}
function quickWinsHtml(){if(state.view!=='search'||!state.results.length)return'';const c=qwCounts(),active=state.filters.quickWin;const btn=(type,label,count)=>`<button class="btn ${active===type?'primary':''}" onclick="setQuickWin('${type}')">${label} · ${count}</button>`;return `<div id="quickWinsPanel" class="panel" style="margin-bottom:14px"><div class="head"><div><div class="eyebrow">QUICK WIN LANES</div><h2>Jump straight to the easiest targets</h2></div><div><button class="btn" onclick="setQuickWin('ALL')">Clear Lane</button> <button class="btn primary" onclick="saveTopPrime()">Save Top PRIME</button></div></div><div style="padding:12px 14px;display:flex;gap:8px;flex-wrap:wrap">${btn('PRIME','PRIME',c.prime)}${btn('NO_WEBSITE','No Website + Reachable',c.noWeb)}${btn('WEAK_ESTABLISHED','Weak + Established',c.weak)}${btn('STALE_ESTABLISHED','Stale + Established',c.stale)}${btn('NO_TRACKING','No Tracking',c.tracking)}${btn('OWNER_FOUND','Owner Found',c.owner)}</div><div class="sub" style="padding:0 14px 12px">Phone numbers remain visible/copyable/exportable for calls you make outside the CRM. These lanes prioritize businesses that are both reachable and demonstrably easier to pitch.</div></div>`}
const qwBaseRender=render;render=function(){qwBaseRender();if(!cloud?.session||state.view!=='search')return;const best=document.getElementById('bestProspectsPanel');const market=[...document.querySelectorAll('.panel')].find(p=>p.textContent.includes('MARKET RESULTS'));if(!document.getElementById('quickWinsPanel')){if(best)best.insertAdjacentHTML('beforebegin',quickWinsHtml());else if(market)market.insertAdjacentHTML('beforebegin',quickWinsHtml())}const eyebrow=document.querySelector('.top .eyebrow');if(eyebrow)eyebrow.textContent='FREE LIVE LOW-HANGING FRUIT ENGINE'};
render();
