state.passwordGuard={compromised:false,modal:false,lastChecked:null};
async function pgSha1Parts(password){const bytes=new TextEncoder().encode(password),buf=await crypto.subtle.digest('SHA-1',bytes),hex=[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase();return{prefix:hex.slice(0,5),suffix:hex.slice(5)}}
function pgStrong(password){return String(password||'').length>=12&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password)}
async function pgLeakedCount(password){const h=await pgSha1Parts(password);const {data,error}=await sb.functions.invoke('password-range',{body:{prefix:h.prefix}});if(error)throw error;if(data?.error)throw new Error(data.error);const row=(data?.entries||[]).find(x=>String(x?.[0]||'').toUpperCase()===h.suffix);return row?Number(row[1]||1):0}
const pgBaseAuthView=authView;
authView=function(){let h=pgBaseAuthView();h=h.replace('placeholder="At least 6 characters"','placeholder="12+ chars: upper/lower/number/symbol"');h=h.replace('Demo prospect discovery remains enabled. CRM storage is cloud-backed and isolated by signed-in user.','FREE password protection is active. New passwords require 12+ characters with upper/lowercase, number and symbol, and are checked against Have I Been Pwned using k-anonymity before account creation.');return h}
signUp=async function(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email)return toast('Enter your email.');if(!pgStrong(password))return toast('Use at least 12 characters with uppercase, lowercase, a number and a symbol.');toast('Checking password safety…');try{const count=await pgLeakedCount(password);if(count>0)return toast(`Choose a different password. This password appears in known breach data (${count.toLocaleString()} occurrence${count===1?'':'s'}).`)}catch(e){return toast('Password safety check unavailable: '+(e?.message||'Unknown error'))}const {data,error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);if(!data.session)toast('Account created. Check your email to confirm, then sign in.')}
signIn=async function(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||!password)return toast('Enter your email and password.');let leaked=0;try{leaked=await pgLeakedCount(password)}catch(e){console.warn('Password guard sign-in check',e?.message||e)}const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);state.passwordGuard.lastChecked=new Date().toISOString();if(leaked>0){state.passwordGuard.compromised=true;state.passwordGuard.modal=true;setTimeout(()=>{render();toast('Security warning: this password appears in known breach data. Change it now.')},50)}}
function pgModal(){if(!state.passwordGuard.modal||!cloud?.session)return'';return `<div class="drawerback" style="z-index:80" onclick="if(event.target===this&&!state.passwordGuard.compromised){state.passwordGuard.modal=false;render()}"><div class="drawer" style="width:min(520px,96vw)"><button class="btn" style="float:right" onclick="if(!state.passwordGuard.compromised){state.passwordGuard.modal=false;render()}">Close</button><div class="eyebrow">FREE ACCOUNT SECURITY</div><h2>${state.passwordGuard.compromised?'Change Compromised Password':'Change Password'}</h2><div class="notice">Passwords are checked using Have I Been Pwned's free Pwned Passwords k-anonymity service. Only a 5-character SHA-1 prefix leaves your browser.</div><label class="field"><span>New password</span><input id="pgNew" type="password" autocomplete="new-password" placeholder="12+ chars: upper/lower/number/symbol"></label><label class="field" style="display:block;margin-top:10px"><span>Confirm new password</span><input id="pgConfirm" type="password" autocomplete="new-password"></label><button class="btn primary" style="margin-top:12px" onclick="pgChangePassword()">Check & Change Password</button><div class="sub" style="margin-top:10px">This free guard replaces the paid Supabase leaked-password check for this app's signup/change-password flows.</div></div></div>`}
async function pgChangePassword(){const a=document.getElementById('pgNew')?.value||'',b=document.getElementById('pgConfirm')?.value||'';if(a!==b)return toast('Passwords do not match.');if(!pgStrong(a))return toast('Use at least 12 characters with uppercase, lowercase, a number and a symbol.');toast('Checking new password safety…');try{const count=await pgLeakedCount(a);if(count>0)return toast(`Choose a different password. This password appears in known breach data (${count.toLocaleString()} occurrence${count===1?'':'s'}).`)}catch(e){return toast('Password safety check unavailable: '+(e?.message||'Unknown error'))}const {error}=await sb.auth.updateUser({password:a});if(error)return toast('Password change failed: '+error.message);state.passwordGuard.compromised=false;state.passwordGuard.modal=false;state.passwordGuard.lastChecked=new Date().toISOString();render();toast('Password changed and passed the free leaked-password check.')}
const pgBaseRender=render;
render=function(){pgBaseRender();if(!cloud?.session)return;const conn=document.querySelector('.conn');if(conn){let row=document.getElementById('passwordGuardStatus');if(!row){row=document.createElement('div');row.className='prov';row.id='passwordGuardStatus';conn.appendChild(row)}row.innerHTML='<span>Password Guard</span><b style="color:var(--green)">FREE · ACTIVE</b>'}const topActions=document.querySelector('.top>div:last-child');if(topActions&&!document.getElementById('securityBtn'))topActions.insertAdjacentHTML('beforeend',' <button id="securityBtn" class="btn" onclick="state.passwordGuard.modal=true;render()">Security</button>');const app=document.querySelector('#app>.app');if(app&&state.passwordGuard.modal)app.insertAdjacentHTML('beforeend',pgModal())};
render();
