import{notFound}from'next/navigation';import{getOwnerData}from'@/lib/owner';import{submitOwnerEdit}from'@/app/actions';import Link from'next/link';

export default async function Page({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const{section}=await params;const sp=await searchParams;const{claims,s,businesses}=await getOwnerData(`/business-portal/${section}`)
 if(!businesses.length)return <div className="card empty-rich"><h2>Claim a business first</h2><p className="muted">Business tools become available after staff approves a legitimate ownership claim.</p><Link className="btn btn-primary" href="/search">Find My Listing</Link></div>
 const requested=typeof sp.business==='string'?sp.business:'';const b=businesses.find((x:any)=>x.id===requested)??businesses[0];const uid=String(claims.sub)
 const switcher=businesses.length>1?<form className="portal-switcher" action={`/business-portal/${section}`} method="get"><label>Managing<select name="business" defaultValue={b.id}>{businesses.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="btn btn-light" type="submit">Switch Business</button></form>:<div className="portal-current"><span>Managing</span><strong>{b.name}</strong></div>
 if(section==='listing'){
  const{data:pending}=await s.from('business_edit_requests').select('id,status,created_at,proposed_changes').eq('business_id',b.id).eq('requested_by',uid).eq('status','pending').order('created_at',{ascending:false})
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Protected listing editor</div><h2>My Listing — {b.name}</h2><p className="muted">Submit updates for staff review. Changes do not overwrite protected public listing data immediately.</p></div><Link className="btn btn-light" href={`/business/${b.slug}`}>View Public Profile</Link></div>{pending?.length?<div className="notice warn">You currently have {pending.length} pending change request{pending.length===1?'':'s'} for this business.</div>:null}<form action={submitOwnerEdit} className="form-card"><input type="hidden" name="business_id" value={b.id}/><label>Description<textarea name="description" defaultValue={b.description||''}/></label><div className="form-grid"><label>Phone<input name="phone" defaultValue={b.phone||''}/></label><label>Website<input name="website" defaultValue={b.website||''}/></label></div><label>Hours<input name="hours" defaultValue={b.hours||''}/></label><button className="btn btn-primary">Submit Changes for Review</button><p className="small muted">Staff can approve, reject or request clarification. Verified status is controlled separately from claimed ownership.</p></form></div>
 }
 if(section==='requests'){
  const{data}=await s.from('business_edit_requests').select('id,request_type,proposed_changes,status,staff_notes,created_at,reviewed_at').eq('business_id',b.id).eq('requested_by',uid).order('created_at',{ascending:false}).limit(50)
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Moderated changes</div><h2>Change Requests</h2><p className="muted">Track listing updates submitted for {b.name}.</p></div><Link className="btn btn-primary" href={`/business-portal/listing?business=${b.id}`}>Submit Update</Link></div>{data?.length?<div className="request-list">{data.map((r:any)=><div className="card" key={r.id}><div className="section-head compact-head"><div><span className="badge neutral">{r.status}</span><h3>{String(r.request_type||'profile update').replaceAll('_',' ')}</h3></div><span className="small muted">{new Date(r.created_at).toLocaleDateString()}</span></div><div className="request-changes">{Object.entries(r.proposed_changes??{}).map(([k,v])=><div className="info-row" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{String(v||'—')}</strong></div>)}</div>{r.staff_notes&&<div className="notice warn" style={{marginTop:12,marginBottom:0}}><strong>Staff note:</strong> {r.staff_notes}</div>}</div>)}</div>:<div className="empty empty-rich"><h3>No change requests yet</h3><p>When you submit a listing update, its review status will appear here.</p><Link className="btn btn-primary" href={`/business-portal/listing?business=${b.id}`}>Edit My Listing</Link></div>}</div>
 }
 if(section==='onboarding')return <div>{switcher}<div className="card"><div className="kpi">Getting started</div><h2>Onboarding — {b.name}</h2><p className="muted">Build a trustworthy local profile without confusing service areas with physical offices.</p><ol className="portal-steps"><li><strong>Review the public listing.</strong><span>Confirm name, phone, website, description and current public information.</span></li><li><strong>Confirm legitimate ownership.</strong><span>Claimed access and Verified status remain separate controls.</span></li><li><strong>Submit profile updates.</strong><span>Protected changes enter staff review before publication.</span></li><li><strong>Confirm branches and service areas.</strong><span>Physical locations must be real offices; service areas are labeled separately.</span></li><li><strong>Monitor leads and performance.</strong><span>Use the portal inbox and analytics once activity begins.</span></li></ol></div></div>
 if(section==='checklist'){
  const score=Number(b.profile_score||0);return <div>{switcher}<div className="card"><div className="section-head compact-head"><div><div className="kpi">Profile health</div><h2>Profile Checklist — {b.name}</h2></div><strong className="profile-score">{score}%</strong></div><div className="progress-track"><span style={{width:`${Math.min(100,Math.max(0,score))}%`}}/></div><div className="info-row"><span>Description</span><b>{b.description?'Complete':'Needs attention'}</b></div><div className="info-row"><span>Phone</span><b>{b.phone?'Complete':'Needs attention'}</b></div><div className="info-row"><span>Website</span><b>{b.website?'Complete':'Optional'}</b></div><div className="info-row"><span>Claimed</span><b>{b.claimed?'Yes':'No'}</b></div><div className="info-row"><span>Verified</span><b>{b.verified?'Yes':'No'}</b></div><div className="card-actions"><Link className="btn btn-primary" href={`/business-portal/listing?business=${b.id}`}>Improve Listing</Link><Link className="btn btn-light" href={`/business/${b.slug}`}>View Public Profile</Link></div></div></div>
 }
 if(section==='areas'){
  const[{data:branches},{data:areas}]=await Promise.all([s.from('business_locations').select('*').eq('business_id',b.id).order('is_primary',{ascending:false}),s.from('business_service_areas').select('business_id,locations(name,slug)').eq('business_id',b.id)])
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Location truth</div><h2>Cities, Branches & Service Areas</h2><p className="muted">Physical locations and areas served are intentionally kept separate.</p></div></div><div className="card"><h3>Physical Locations</h3>{branches?.length?branches.map((x:any)=><div className="info-row" key={x.id}><span>{x.label||x.location_type||'Location'}{x.is_primary?' · Primary':''}</span><b>{[x.address_text,x.city,x.state].filter(Boolean).join(', ')}</b></div>):<p className="muted">No physical branch details are published.</p>}</div><div className="card" style={{marginTop:15}}><h3>Service Areas</h3>{areas?.length?areas.map((x:any,i)=><div className="info-row" key={i}><span>{x.locations?.name}</span><b>Served area — not an office</b></div>):<p className="muted">No separate service areas are configured.</p>}</div></div>
 }
 if(section==='leads'){
  const{data}=await s.from('lead_recipients').select('id,business_id,status,route_reason,routed_at,leads(service,city,consumer_name,phone,email)').eq('business_id',b.id).order('routed_at',{ascending:false})
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Customer opportunities</div><h2>Lead Inbox — {b.name}</h2><p className="muted">Lead routing is tracked independently from sponsored placement or organic directory relevance.</p></div></div>{data?.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Service</th><th>City</th><th>Customer</th><th>Contact</th><th>Status</th><th>Route</th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.leads?.service}</td><td>{x.leads?.city}</td><td>{x.leads?.consumer_name}</td><td>{[x.leads?.phone,x.leads?.email].filter(Boolean).join(' · ')||'—'}</td><td>{x.status}</td><td>{x.route_reason}</td></tr>)}</tbody></table></div>:<div className="empty">No leads have been routed to this business yet.</div>}</div>
 }
 if(section==='analytics'){
  const{data}=await s.from('listing_daily_stats').select('*').eq('business_id',b.id).order('stat_date',{ascending:false}).limit(90);const sum=(k:string)=>(data??[]).reduce((a:number,x:any)=>a+Number(x[k]||0),0)
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Last 90 days</div><h2>Analytics — {b.name}</h2><p className="muted">Owner-facing listing activity only. Internal SEO diagnostics and staff intelligence remain private.</p></div></div><div className="stat-grid"><div className="stat">Impressions<strong>{sum('impressions')}</strong></div><div className="stat">Profile Views<strong>{sum('profile_views')}</strong></div><div className="stat">Phone Clicks<strong>{sum('phone_clicks')}</strong></div><div className="stat">Website Clicks<strong>{sum('website_clicks')}</strong></div><div className="stat">Directions<strong>{sum('directions_clicks')}</strong></div><div className="stat">Leads<strong>{sum('lead_submissions')}</strong></div></div></div>
 }
 if(section==='subscription'){
  const{data}=await s.from('subscriptions').select('*,plans(name,monthly_price_cents,annual_price_cents)').eq('business_id',b.id)
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Plan management</div><h2>Subscription — {b.name}</h2></div></div>{data?.length?data.map((x:any)=><div className="card" key={x.id}><h3>{x.plans?.name||'Plan'}</h3><p>Status: <strong>{x.status}</strong></p><p className="muted small">Payments are not activated until the directory owner explicitly enables Stripe.</p></div>):<div className="card"><h3>Free / no paid subscription</h3><p className="muted">The business remains eligible for normal organic directory inclusion without a paid plan.</p></div>}</div>
 }
 if(section==='notifications'){
  const{data}=await s.from('notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(50)
  return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Account updates</div><h2>Notifications</h2></div></div>{data?.length?<div className="request-list">{data.map((n:any)=><div className="card" key={n.id}><b>{n.title}</b><p>{n.body}</p><span className="small muted">{new Date(n.created_at).toLocaleDateString()}</span></div>)}</div>:<div className="empty">No notifications yet.</div>}</div>
 }
 notFound()
}
