import{createClient}from'@/lib/supabase/server'
import{TENANT_ID}from'@/lib/constants'
import{requireStaff}from'@/lib/auth'
import{AdminLocalCommerce}from'@/components/AdminLocalCommerce'
export const dynamic='force-dynamic'
type Row=Record<string,any>
export default async function Page(){await requireStaff('/admin/local-commerce');const s=await createClient();const[recs,deals,catalog,portfolio,questions,marketReqs,referrals]=await Promise.all([
 s.from('business_recommendations').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('created_at',{ascending:true}).limit(200),
 s.from('business_deals').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('created_at',{ascending:true}).limit(200),
 s.from('business_catalog_items').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('created_at',{ascending:true}).limit(200),
 s.from('business_portfolio_projects').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('created_at',{ascending:true}).limit(200),
 s.from('local_pro_questions').select('*').eq('tenant_id',TENANT_ID).in('status',['pending','awaiting_review']).order('created_at',{ascending:true}).limit(200),
 s.from('lead_marketplace_requests').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('requested_at',{ascending:true}).limit(200),
 s.from('business_referrals').select('*').eq('tenant_id',TENANT_ID).eq('status','pending').order('created_at',{ascending:true}).limit(200),
]);const all=[...(recs.data??[]),...(deals.data??[]),...(catalog.data??[]),...(portfolio.data??[]),...(questions.data??[]),...(marketReqs.data??[]),...(referrals.data??[]) ]as Row[];const businessIds=[...new Set(all.flatMap(r=>[r.business_id,r.referrer_business_id,r.referred_business_id].filter(Boolean).map(String)))];const offerIds=[...new Set((marketReqs.data??[]).map((r:any)=>String(r.offer_id)).filter(Boolean))];const[businessRows,offerRows]=await Promise.all([businessIds.length?s.from('businesses').select('id,name,slug').eq('tenant_id',TENANT_ID).in('id',businessIds):Promise.resolve({data:[],error:null} as any),offerIds.length?s.from('lead_marketplace_offers').select('id,lead_id,price_cents,status,leads(service,city)').eq('tenant_id',TENANT_ID).in('id',offerIds):Promise.resolve({data:[],error:null} as any)]);const businessById=new Map(((businessRows.data??[])as Row[]).map(b=>[String(b.id),b])),offerById=new Map(((offerRows.data??[])as Row[]).map(o=>[String(o.id),o]));const records:Row[]=[];for(const r of recs.data??[])records.push({entity_type:'recommendation',id:r.id,business_name:businessById.get(String(r.business_id))?.name,title:'Community recommendation',status:r.status,meta:[r.service,r.city].filter(Boolean).join(' · '),raw:r});for(const r of deals.data??[])records.push({entity_type:'deal',id:r.id,business_name:businessById.get(String(r.business_id))?.name,title:r.title,status:r.status,meta:r.ends_at?`Ends ${new Date(r.ends_at).toLocaleDateString()}`:'No end date',raw:r});for(const r of catalog.data??[])records.push({entity_type:'catalog',id:r.id,business_name:businessById.get(String(r.business_id))?.name,title:r.name,status:r.status,meta:`${r.item_type}${r.price_label?` · ${r.price_label}`:''}`,raw:r});for(const r of portfolio.data??[])records.push({entity_type:'portfolio',id:r.id,business_name:businessById.get(String(r.business_id))?.name,title:r.title,status:r.status,meta:[r.project_type,r.city].filter(Boolean).join(' · '),raw:r});for(const r of questions.data??[])records.push({entity_type:'question',id:r.id,business_name:businessById.get(String(r.business_id))?.name,title:'Ask a Local Pro',status:r.status,meta:r.answer?'Owner answer ready for review':'Waiting for owner answer; approve will remain blocked',raw:r});const marketplaceRequests=(marketReqs.data??[]).map((r:any)=>{const o=offerById.get(String(r.offer_id))||{},l=Array.isArray(o.leads)?o.leads[0]:o.leads;return{...r,business_name:businessById.get(String(r.business_id))?.name||'Business',price_cents:o.price_cents||0,service:l?.service||'Local Lead',city:l?.city||'Central Illinois'}});const referralRows=(referrals.data??[]).map((r:any)=>({...r,referrer_name:businessById.get(String(r.referrer_business_id))?.name||'Business',referred_name:businessById.get(String(r.referred_business_id))?.name||'Business'}));return <AdminLocalCommerce records={records} marketplaceRequests={marketplaceRequests as Row[]} referrals={referralRows as Row[]}/>}
