import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { requireStaff } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'

type Row=Record<string,any>
const T=(v:any,n=4000)=>String(v??'').trim().slice(0,n)
const C=['positive','question','neutral','negative','do_not_contact','wrong_person','out_of_office','bounce','ambiguous']
const amount=(v:any)=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?Math.round(n):null}
const duplicate=(e:any)=>String(e?.code||'')==='23505'
function suggestion(subject:string,body:string){const v=`${subject}\n${body}`.toLowerCase(),has=(a:string[])=>a.some(x=>v.includes(x));if(has(['unsubscribe','opt out','remove me','stop emailing','stop contacting','do not contact',"don't contact"]))return ['do_not_contact',98,'Explicit stop-contact or opt-out language detected.'];if(has(['wrong person','not the right person','contact someone else','no longer with the company','no longer at']))return ['wrong_person',94,'Reply indicates this is not the correct contact.'];if(has(['out of office','automatic reply','auto reply','away from the office','on vacation']))return ['out_of_office',96,'Automatic/out-of-office language detected.'];if(has(['mailbox unavailable','undeliverable','delivery status notification','address not found','recipient address rejected']))return ['bounce',98,'Delivery failure language detected.'];if(has(['not interested','no thanks','not a fit','we will pass','we’ll pass']))return ['negative',90,'Clear negative-interest language detected.'];if(has(['interested','sounds good',"let's talk",'lets talk','schedule','book a','call me','send more','tell me more']))return ['positive',84,'Positive intent or meeting-interest language detected.'];if(v.includes('?')||has(['how much','pricing','what does','can you','could you','how does']))return ['question',72,'Question or request-for-information language detected.'];return ['ambiguous',35,'No high-confidence pattern detected; staff review is required.']}
async function opp(s:any,id:string){const {data,error}=await s.from('skylight_sales_opportunities').select('id,prospect_id,business_id,client_id,proposal_id,primary_service_slug,recommended_service_slugs,stage,active,estimated_value_cents,first_reply_at,prospect:business_prospects(id,business_name,status,owner_contact_email,owner_contact_phone)').eq('tenant_id',TENANT_ID).eq('id',id).single();if(error)throw error;return data as Row}
async function member(s:any,id:string){const {data,error}=await s.from('skylight_sales_campaign_members').select('id,campaign_id,status').eq('opportunity_id',id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data as Row|null}
async function conv(s:any,r:Row){const {error}=await s.from('skylight_sales_conversion_events').insert({tenant_id:TENANT_ID,...r});if(error)throw error}
async function outreach(s:any,r:Row){const {error}=await s.from('skylight_sales_outreach_events').insert({tenant_id:TENANT_ID,...r});if(error)throw error}
async function stopFollowups(s:any,id:string,note:string){const {error}=await s.from('skylight_sales_followups').update({status:'cancelled',notes:note,updated_at:new Date().toISOString()}).eq('tenant_id',TENANT_ID).eq('opportunity_id',id).eq('status','open');if(error)throw error}
async function suppress(s:any,row:Row){const {error}=await s.from('skylight_sales_suppressions').insert({tenant_id:TENANT_ID,...row});if(error&&!duplicate(error))throw error}

export async function POST(req:Request){
 try{
  const {claims}=await requireStaff('/admin/skylight-sales/conversions'),uid=String(claims.sub),s=await createClient(),b=await req.json() as Row,a=T(b.action,80),now=new Date().toISOString()
  if(a==='record_reply'){
   const oid=T(b.opportunity_id,40),channel=T(b.channel||'email',20),body=T(b.body,16000),subject=T(b.subject,500);if(!oid||!body)throw new Error('Opportunity and reply body are required.');if(!['email','phone','sms','linkedin','social'].includes(channel))throw new Error('Invalid reply channel.')
   const o=await opp(s,oid),m=await member(s,oid);if(!o.active||o.prospect?.status==='do_not_contact')throw new Error('This opportunity is not eligible for reply capture.')
   const [kind,confidence,reason]=suggestion(subject,body),received=b.received_at?new Date(b.received_at).toISOString():now;if(Number.isNaN(new Date(received).getTime()))throw new Error('Invalid received date/time.')
   const latest=await s.from('skylight_sales_outreach_drafts').select('id').eq('tenant_id',TENANT_ID).eq('opportunity_id',oid).eq('status','sent').order('sent_at',{ascending:false}).limit(1).maybeSingle();if(latest.error)throw latest.error
   const ins=await s.from('skylight_sales_replies').insert({tenant_id:TENANT_ID,opportunity_id:oid,prospect_id:o.prospect_id,draft_id:b.draft_id||latest.data?.id||null,campaign_id:b.campaign_id||m?.campaign_id||null,campaign_member_id:b.campaign_member_id||m?.id||null,channel,provider:T(b.provider,80)||'manual',provider_message_id:T(b.provider_message_id,240)||null,in_reply_to_message_id:T(b.in_reply_to_message_id,240)||null,sender_name:T(b.sender_name,240)||null,sender_email:T(b.sender_email,320)||null,subject:subject||null,body,received_at:received,classification_suggestion:kind,classification_confidence:confidence,suggestion_reason:reason,review_status:'pending',metadata:{classification_advisory:true,automatic_stage_change:false},created_by:uid}).select('*').single();if(ins.error)throw ins.error
   const p:Row={last_reply_at:received,updated_at:now};if(!o.first_reply_at)p.first_reply_at=received;if(o.stage==='contact_ready')p.stage='contacted';const ou=await s.from('skylight_sales_opportunities').update(p).eq('tenant_id',TENANT_ID).eq('id',oid);if(ou.error)throw ou.error
   if(m?.id){const mu=await s.from('skylight_sales_campaign_members').update({status:'replied',last_action_at:received,updated_at:now}).eq('id',m.id);if(mu.error)throw mu.error}
   await conv(s,{opportunity_id:oid,prospect_id:o.prospect_id,campaign_id:ins.data.campaign_id,campaign_member_id:ins.data.campaign_member_id,reply_id:ins.data.id,actor_user_id:uid,event_type:'reply_recorded',metadata:{suggestion:kind,confidence,staff_confirmation_required:true}});return NextResponse.json({ok:true,data:ins.data,suggestion:{classification:kind,confidence,reason},classification_advisory:true})
  }
  if(a==='confirm_reply'||a==='dismiss_reply'){
   const id=T(b.reply_id,40),qr=await s.from('skylight_sales_replies').select('*').eq('tenant_id',TENANT_ID).eq('id',id).single();if(qr.error)throw qr.error;const r=qr.data as Row;if(r.review_status!=='pending')throw new Error('This reply has already been reviewed.')
   if(a==='dismiss_reply'){const u=await s.from('skylight_sales_replies').update({review_status:'dismissed',reviewed_by:uid,reviewed_at:now,staff_note:T(b.staff_note,4000)||null,updated_at:now}).eq('id',id).eq('review_status','pending');if(u.error)throw u.error;return NextResponse.json({ok:true})}
   const k=T(b.classification,40);if(!C.includes(k))throw new Error('Select a valid confirmed classification.');const o=await opp(s,r.opportunity_id)
   const ru=await s.from('skylight_sales_replies').update({review_status:'confirmed',confirmed_classification:k,reviewed_by:uid,reviewed_at:now,staff_note:T(b.staff_note,4000)||null,updated_at:now}).eq('id',id).eq('review_status','pending');if(ru.error)throw ru.error
   let evt='reply_neutral';if(k==='positive')evt='reply_positive';else if(k==='negative')evt='reply_negative';else if(k==='do_not_contact')evt='do_not_contact';else if(k==='wrong_person')evt='wrong_person';else if(k==='bounce')evt='bounced'
   if(k==='positive'&&o.active){const u=await s.from('skylight_sales_opportunities').update({stage:'qualified',updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',o.id);if(u.error)throw u.error;if(r.campaign_member_id){const m=await s.from('skylight_sales_campaign_members').update({status:'qualified',last_action_at:now,updated_at:now}).eq('id',r.campaign_member_id);if(m.error)throw m.error}}
   else if(k==='do_not_contact'){await suppress(s,{prospect_id:o.prospect_id,opportunity_id:o.id,channel:'all',contact_value:null,reason:'Staff-confirmed do-not-contact reply.',source:'opt_out',active:true,created_by:uid});const p=await s.from('business_prospects').update({status:'do_not_contact',updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',o.prospect_id);if(p.error)throw p.error}
   else if(k==='wrong_person'||k==='bounce'){await suppress(s,{prospect_id:o.prospect_id,opportunity_id:o.id,channel:k==='bounce'?'email':String(r.channel||'email'),contact_value:k==='bounce'?T(r.sender_email,320)||null:null,reason:k==='bounce'?'Staff-confirmed delivery failure.':'Staff-confirmed wrong-person contact.',source:k==='bounce'?'bounce':'wrong_person',active:true,created_by:uid});const u=await s.from('skylight_sales_opportunities').update({stage:'research',updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',o.id).eq('active',true);if(u.error)throw u.error;if(r.campaign_member_id){const m=await s.from('skylight_sales_campaign_members').update({status:'research',updated_at:now}).eq('id',r.campaign_member_id);if(m.error)throw m.error}}
   else if(r.campaign_member_id){const m=await s.from('skylight_sales_campaign_members').update({status:'replied',last_action_at:now,updated_at:now}).eq('id',r.campaign_member_id);if(m.error)throw m.error}
   await outreach(s,{opportunity_id:o.id,prospect_id:o.prospect_id,draft_id:r.draft_id,campaign_id:r.campaign_id,campaign_member_id:r.campaign_member_id,actor_user_id:uid,channel:r.channel,event_type:evt,notes:`Staff confirmed reply classification: ${k}.`,metadata:{reply_id:r.id,human_confirmed:true}});await conv(s,{opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:r.campaign_id,campaign_member_id:r.campaign_member_id,reply_id:r.id,actor_user_id:uid,event_type:'reply_confirmed',reason_code:k,metadata:{human_confirmed:true}});return NextResponse.json({ok:true})
  }
  if(a==='book_meeting'){
   const oid=T(b.opportunity_id,40),o=await opp(s,oid),m=await member(s,oid),scheduled=new Date(b.scheduled_at).toISOString(),type=T(b.meeting_type||'discovery',30),loc=T(b.location_type||'phone',30);if(Number.isNaN(new Date(scheduled).getTime()))throw new Error('Valid meeting date/time is required.');if(!['discovery','strategy','demo','follow_up','other'].includes(type)||!['phone','video','in_person','other'].includes(loc))throw new Error('Invalid meeting type or location.')
   const ins=await s.from('skylight_sales_meetings').insert({tenant_id:TENANT_ID,opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:m?.campaign_id||null,campaign_member_id:m?.id||null,reply_id:b.reply_id||null,meeting_type:type,status:'scheduled',scheduled_at:scheduled,duration_minutes:Math.max(5,Math.min(480,Number(b.duration_minutes)||30)),location_type:loc,location_detail:T(b.location_detail,1000)||null,notes:T(b.notes,4000)||null,booked_by:uid}).select('*').single();if(ins.error)throw ins.error
   const ou=await s.from('skylight_sales_opportunities').update({stage:'qualified',next_follow_up_at:null,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',o.id).eq('active',true);if(ou.error)throw ou.error;if(m?.id){const mu=await s.from('skylight_sales_campaign_members').update({status:'qualified',last_action_at:now,next_action_at:scheduled,updated_at:now}).eq('id',m.id);if(mu.error)throw mu.error}await stopFollowups(s,o.id,'Cancelled because staff booked a sales meeting.');await outreach(s,{opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:m?.campaign_id||null,campaign_member_id:m?.id||null,actor_user_id:uid,channel:'phone',event_type:'appointment_booked',notes:'Staff explicitly booked a sales meeting.',metadata:{meeting_id:ins.data.id}});await conv(s,{opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:m?.campaign_id||null,campaign_member_id:m?.id||null,meeting_id:ins.data.id,actor_user_id:uid,event_type:'meeting_booked'});return NextResponse.json({ok:true,data:ins.data})
  }
  if(a==='complete_meeting'){
   const id=T(b.meeting_id,40),outcome=T(b.outcome,40);if(!['qualified','proposal_requested','not_ready','not_fit','follow_up','other'].includes(outcome))throw new Error('Select a meeting outcome.');const q=await s.from('skylight_sales_meetings').select('*').eq('tenant_id',TENANT_ID).eq('id',id).single();if(q.error)throw q.error;const m=q.data as Row;if(m.status!=='scheduled')throw new Error('Only a scheduled meeting can be completed.');const u=await s.from('skylight_sales_meetings').update({status:'completed',outcome,notes:T(b.notes,4000)||m.notes,completed_by:uid,completed_at:now,updated_at:now}).eq('id',id).eq('status','scheduled');if(u.error)throw u.error;const stage=outcome==='proposal_requested'?'proposal':outcome==='not_ready'?'nurture':'qualified',ou=await s.from('skylight_sales_opportunities').update({stage,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',m.opportunity_id).eq('active',true);if(ou.error)throw ou.error;if(m.campaign_member_id){const mu=await s.from('skylight_sales_campaign_members').update({status:stage==='proposal'?'proposal':'qualified',last_action_at:now,updated_at:now}).eq('id',m.campaign_member_id);if(mu.error)throw mu.error}await conv(s,{opportunity_id:m.opportunity_id,prospect_id:m.prospect_id,campaign_id:m.campaign_id,campaign_member_id:m.campaign_member_id,meeting_id:m.id,actor_user_id:uid,event_type:'meeting_completed',reason_code:outcome});return NextResponse.json({ok:true})
  }
  if(a==='create_handoff'){
   const oid=T(b.opportunity_id,40),o=await opp(s,oid),m=await member(s,oid),value=amount(b.estimated_value_cents),ins=await s.from('skylight_sales_proposal_handoffs').insert({tenant_id:TENANT_ID,opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:m?.campaign_id||null,campaign_member_id:m?.id||null,reply_id:b.reply_id||null,meeting_id:b.meeting_id||null,status:'draft',title:T(b.title,300)||`Proposal handoff for ${T(o.prospect?.business_name,200)||'prospect'}`,recommended_service_slugs:Array.isArray(b.recommended_service_slugs)?b.recommended_service_slugs.map((x:any)=>T(x,80)).filter(Boolean):o.recommended_service_slugs||[],scope_notes:T(b.scope_notes,8000)||null,pricing_notes:T(b.pricing_notes,4000)||null,estimated_value_cents:value,created_by:uid,updated_by:uid}).select('*').single();if(ins.error)throw ins.error;if(value!==null){const u=await s.from('skylight_sales_opportunities').update({estimated_value_cents:value,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',o.id);if(u.error)throw u.error}await conv(s,{opportunity_id:o.id,prospect_id:o.prospect_id,campaign_id:ins.data.campaign_id,campaign_member_id:ins.data.campaign_member_id,reply_id:ins.data.reply_id,meeting_id:ins.data.meeting_id,handoff_id:ins.data.id,actor_user_id:uid,event_type:'proposal_handoff_created',value_cents:value});return NextResponse.json({ok:true,data:ins.data})
  }
  if(a==='mark_handoff_ready'){
   const id=T(b.handoff_id,40),q=await s.from('skylight_sales_proposal_handoffs').select('*').eq('tenant_id',TENANT_ID).eq('id',id).single();if(q.error)throw q.error;const h=q.data as Row;if(h.status!=='draft')throw new Error('Only a draft handoff can be marked ready.');const u=await s.from('skylight_sales_proposal_handoffs').update({status:'ready',updated_by:uid,updated_at:now}).eq('id',id).eq('status','draft');if(u.error)throw u.error;const ou=await s.from('skylight_sales_opportunities').update({stage:'proposal',updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',h.opportunity_id).eq('active',true);if(ou.error)throw ou.error;if(h.campaign_member_id){const m=await s.from('skylight_sales_campaign_members').update({status:'proposal',last_action_at:now,updated_at:now}).eq('id',h.campaign_member_id);if(m.error)throw m.error}await conv(s,{opportunity_id:h.opportunity_id,prospect_id:h.prospect_id,campaign_id:h.campaign_id,campaign_member_id:h.campaign_member_id,reply_id:h.reply_id,meeting_id:h.meeting_id,handoff_id:h.id,actor_user_id:uid,event_type:'proposal_handoff_ready',value_cents:h.estimated_value_cents});return NextResponse.json({ok:true})
  }
  if(a==='link_proposal'){
   const id=T(b.handoff_id,40),pid=T(b.proposal_id,40),[qh,qp]=await Promise.all([s.from('skylight_sales_proposal_handoffs').select('*').eq('tenant_id',TENANT_ID).eq('id',id).single(),s.from('skylight_proposals').select('id,client_id,total_cents,status').eq('tenant_id',TENANT_ID).eq('id',pid).single()]);if(qh.error)throw qh.error;if(qp.error)throw qp.error;const h=qh.data as Row,p=qp.data as Row;if(!['draft','ready'].includes(h.status))throw new Error('This handoff can no longer be linked.');const u=await s.from('skylight_sales_proposal_handoffs').update({status:'linked',client_id:p.client_id,proposal_id:p.id,linked_by:uid,linked_at:now,updated_by:uid,updated_at:now}).eq('id',id);if(u.error)throw u.error;const value=Number(p.total_cents)>0?Number(p.total_cents):h.estimated_value_cents,ou=await s.from('skylight_sales_opportunities').update({proposal_id:p.id,client_id:p.client_id,stage:'proposal',estimated_value_cents:value??null,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',h.opportunity_id);if(ou.error)throw ou.error;await conv(s,{opportunity_id:h.opportunity_id,prospect_id:h.prospect_id,campaign_id:h.campaign_id,campaign_member_id:h.campaign_member_id,reply_id:h.reply_id,meeting_id:h.meeting_id,handoff_id:h.id,proposal_id:p.id,actor_user_id:uid,event_type:'proposal_linked',value_cents:value,metadata:{proposal_status:p.status,proposal_send_authorized:false,billing_authorization:false}});return NextResponse.json({ok:true})
  }
  if(a==='update_value'){
   const oid=T(b.opportunity_id,40),value=amount(b.estimated_value_cents);if(value===null)throw new Error('Enter a non-negative estimated value.');const o=await opp(s,oid),u=await s.from('skylight_sales_opportunities').update({estimated_value_cents:value,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',oid);if(u.error)throw u.error;await conv(s,{opportunity_id:oid,prospect_id:o.prospect_id,actor_user_id:uid,event_type:'value_updated',value_cents:value,notes:T(b.notes,2000)||null});return NextResponse.json({ok:true})
  }
  if(a==='mark_won'||a==='mark_lost'){
   const oid=T(b.opportunity_id,40),o=await opp(s,oid),m=await member(s,oid),won=a==='mark_won',reason=T(b.reason_code,120),note=T(b.note,4000),value=amount(b.value_cents);if(!o.active)throw new Error('This opportunity is already closed.');if(!won&&!reason)throw new Error('A loss reason is required.');const p:Row={stage:won?'won':'lost',active:false,outcome_reason_code:reason||null,updated_at:now};if(won)p.won_at=now;else{p.lost_at=now;p.lost_reason=note||reason}if(value!==null)p.estimated_value_cents=value;const u=await s.from('skylight_sales_opportunities').update(p).eq('tenant_id',TENANT_ID).eq('id',oid).eq('active',true);if(u.error)throw u.error;if(m?.id){const mu=await s.from('skylight_sales_campaign_members').update({status:won?'won':'lost',last_action_at:now,next_action_at:null,updated_at:now}).eq('id',m.id);if(mu.error)throw mu.error}await stopFollowups(s,oid,`Cancelled because staff explicitly marked the opportunity ${won?'won':'lost'}.`);await conv(s,{opportunity_id:oid,prospect_id:o.prospect_id,campaign_id:m?.campaign_id||null,campaign_member_id:m?.id||null,proposal_id:o.proposal_id||null,actor_user_id:uid,event_type:won?'won':'lost',value_cents:value??o.estimated_value_cents,reason_code:reason||null,notes:note||null,metadata:{human_confirmed:true,billing_authorization:false}});return NextResponse.json({ok:true})
  }
  throw new Error('Unsupported Sales 3.5 action.')
 }catch(e:any){return NextResponse.json({ok:false,error:e?.message||'Sales conversion action failed.',automatic_outreach:false,billing_authorization:false,public_ranking_effect:false},{status:400})}
}
