import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { TENANT_ID } from '@/lib/constants'
import { refreshGrowthOpportunities } from './actions'

export const dynamic='force-dynamic'
type SearchValue=string|string[]|undefined;const one=(v:SearchValue)=>Array.isArray(v)?v[0]||'':v||'';const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(c/100);const pct=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'0%';const labels:Record<string,string>={claim_activation:'Claim Activation',contact_enrichment:'Contact Enrichment',paid_plan_activation:'Paid Plan',pro_upgrade:'Pro Upgrade',sponsorship:'Sponsorship',lead_buyer_activation:'Lead Buyer',skylight_marketing:'Skylight Marketing'};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,SearchValue>>}){
  const sp=await searchParams,s=await createClient(),since30=new Date(Date.now()-30*86400000).toISOString();
  const [opps,businesses,owners,claims,subs,sponsors,leadPrograms,leadInvoices,prospects,marketing,outreach,history]=await Promise.all([
    s.from('growth_opportunities').select('id,opportunity_type,business_id,prospect_id,title,detail,score,estimated_monthly_value_cents,status,next_action,due_at,source_facts,last_refreshed_at,updated_at').eq('tenant_id',TENANT_ID).in('status',['open','in_progress','snoozed']).order('score',{ascending:false}).limit(1500),
    s.from('businesses').select('id,claimed').eq('tenant_id',TENANT_ID).eq('status','published').limit(5000),
    s.from('business_owners').select('business_id,businesses!inner(tenant_id)').eq('businesses.tenant_id',TENANT_ID).limit(5000),
    s.from('business_claims').select('id,status,businesses!inner(tenant_id)').eq('businesses.tenant_id',TENANT_ID).limit(5000),
    s.from('subscriptions').select('status,billing_interval,plans(slug,name,monthly_price_cents,annual_price_cents),businesses!inner(tenant_id)').eq('businesses.tenant_id',TENANT_ID).in('status',['active','trialing']).limit(5000),
    s.from('sponsorships').select('id,active,ends_on,businesses!inner(tenant_id)').eq('businesses.tenant_id',TENANT_ID).eq('active',true).limit(5000),
    s.from('business_lead_programs').select('id,status').eq('tenant_id',TENANT_ID).eq('status','active').limit(5000),
    s.from('lead_invoices').select('id,amount_due_cents,status,paid_at').eq('tenant_id',TENANT_ID).eq('status','paid').gte('paid_at',since30).limit(5000),
    s.from('business_prospects').select('id,business_id,owner_contact_email,owner_contact_phone,crm_stage,status,priority').eq('tenant_id',TENANT_ID).limit(5000),
    s.from('marketing_leads').select('id,status,created_at').eq('tenant_id',TENANT_ID).gte('created_at',since30).limit(5000),
    s.from('outreach_tasks').select('task_type,status').eq('tenant_id',TENANT_ID).in('status',['open','in_progress']).limit(5000),
    s.from('growth_daily_metrics').select('metric_date,published_businesses,contactable_prospects,open_contact_research,open_claim_invites,claimed_businesses,owner_links,active_paid_accounts,active_pro_accounts,active_sponsorships,active_lead_buyers,open_growth_opportunities,plan_mrr_cents,paid_lead_revenue_30d_cents').eq('tenant_id',TENANT_ID).order('metric_date',{ascending:false}).limit(14),
  ]);
  const rows=(opps.data??[]) as any[],biz=(businesses.data??[]) as any[],pros=(prospects.data??[]) as any[],activeSubs=(subs.data??[]) as any[],historyRows=(history.data??[]) as any[],taskRows=(outreach.data??[]) as any[];
  const claimed=biz.filter(x=>x.claimed).length,ownerLinks=(owners.data??[]).length,pendingClaims=(claims.data??[]).filter((x:any)=>['pending','in_review','new'].includes(x.status)).length,contactable=pros.filter(x=>x.crm_stage==='claim_outreach'&&['published','contact_ready'].includes(x.status)&&(x.owner_contact_email||x.owner_contact_phone)).length;
  const taskCounts=taskRows.reduce((m:Record<string,number>,r:any)=>{m[r.task_type]=(m[r.task_type]||0)+1;return m},{});
  const mrr=activeSubs.reduce((sum:number,row:any)=>{const p=Array.isArray(row.plans)?row.plans[0]:row.plans;if(!p)return sum;return sum+(row.billing_interval==='annual'&&p.annual_price_cents?Math.round(p.annual_price_cents/12):Number(p.monthly_price_cents||0))},0);
  const planPipeline=rows.reduce((sum:number,row:any)=>sum+Number(row.estimated_monthly_value_cents||0),0),leadRevenue=(leadInvoices.data??[]).reduce((sum:number,row:any)=>sum+Number(row.amount_due_cents||0),0),types=rows.reduce((m:Record<string,number>,r:any)=>{m[r.opportunity_type]=(m[r.opportunity_type]||0)+1;return m},{}),high=rows.filter((r:any)=>r.score>=75),refresh=one(sp.refresh),message=one(sp.message),latest=historyRows[0];
  return <><div className="admin-page-head"><div><div className="kpi">Launch + Growth Engine</div><h1>Turn Directory Inventory Into Revenue</h1><p className="muted">One staff-only command center for owner acquisition, paid-plan conversion, sponsorship, lead-buyer activation and Skylight Reflections Marketing opportunities. Every count comes from actual database state.</p></div><form action={refreshGrowthOpportunities}><button className="btn btn-primary">Refresh Opportunities</button></form></div>
    {refresh==='ok'&&<div className="notice">Growth opportunities and actionable outreach tasks refreshed from current production state.</div>}{refresh==='error'&&<div className="notice warn">Refresh failed: {message}</div>}
    <div className="stat-grid"><div className="stat">Published Businesses<strong>{biz.length}</strong><span>{claimed} claimed · {pct(claimed,biz.length)} claim rate</span></div><div className="stat">Owner Links<strong>{ownerLinks}</strong><span>{pendingClaims} claims awaiting review</span></div><div className="stat">Active Paid Accounts<strong>{activeSubs.length}</strong><span>{money(mrr)} monthly-equivalent plan revenue</span></div><div className="stat">30d Paid Lead Revenue<strong>{money(leadRevenue)}</strong><span>{(leadPrograms.data??[]).length} active lead-buyer programs</span></div></div>
    <div className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><div className="kpi">Acquisition funnel</div><h2>Research → Claim → Paid → Monetized</h2><p className="small muted">Open tasks are actionable work, not evidence that contact occurred. The daily snapshot preserves real funnel movement over time.</p></div><Link href="/admin/outreach">Work tasks →</Link></div><div className="grid grid-4"><div className="card"><div className="kpi">Contact Research</div><h2>{taskCounts.contact_research||0}</h2><p className="small muted">Need verified owner/decision-maker channel</p></div><div className="card"><div className="kpi">Claim Ready</div><h2>{taskCounts.claim_invite||0}</h2><p className="small muted">Real contact path available</p></div><div className="card"><div className="kpi">Claimed</div><h2>{claimed}</h2><p className="small muted">{pct(claimed,biz.length)} of published inventory</p></div><div className="card"><div className="kpi">Paid / Lead Buyers</div><h2>{activeSubs.length} / {(leadPrograms.data??[]).length}</h2><p className="small muted">Active paid directory accounts / lead programs</p></div></div>{latest&&<p className="small muted" style={{marginTop:12}}>Latest stored snapshot: {latest.metric_date} · {latest.contactable_prospects} contactable · {latest.open_claim_invites} claim invites · {latest.active_pro_accounts} Pro · {latest.active_sponsorships} sponsors · {money(Number(latest.plan_mrr_cents||0))} plan MRR.</p>}</div>
    <div className="grid grid-2" style={{marginTop:18}}><div className="admin-card"><div className="kpi">Immediate bottleneck</div><h2>Owner Acquisition</h2><div className="info-row"><span>Claim-ready prospects with contact info</span><strong>{contactable}</strong></div><div className="info-row"><span>Open contact-research tasks</span><strong>{taskCounts.contact_research||0}</strong></div><div className="info-row"><span>Open claim-invite tasks</span><strong>{taskCounts.claim_invite||0}</strong></div><div className="info-row"><span>Contact-enrichment opportunities</span><strong>{types.contact_enrichment||0}</strong></div><div className="info-row"><span>High-priority opportunities</span><strong>{high.length}</strong></div><p className="small muted">Claim approval never creates verification or paid rank. Decision-maker source provenance stays in the private Sales CRM.</p><div className="card-actions"><Link className="btn btn-primary" href="/admin/growth-opportunities">Work Opportunity Queue</Link><Link className="btn btn-light" href="/admin/prospects">Open Sales CRM</Link><Link className="btn btn-light" href="/admin/outreach-templates">Templates</Link></div></div><div className="admin-card"><div className="kpi">Monetization state</div><h2>Revenue Ladder</h2><div className="info-row"><span>Paid-plan activation opportunities</span><strong>{types.paid_plan_activation||0}</strong></div><div className="info-row"><span>Pro upgrade opportunities</span><strong>{types.pro_upgrade||0}</strong></div><div className="info-row"><span>Sponsorship opportunities</span><strong>{types.sponsorship||0}</strong></div><div className="info-row"><span>Lead-buyer opportunities</span><strong>{types.lead_buyer_activation||0}</strong></div><div className="info-row"><span>Measured plan MRR pipeline</span><strong>{money(planPipeline)}</strong></div><p className="small muted">Plan-pipeline value uses current configured plan prices only. Sponsorship and lead-buyer agreements are excluded until real pricing is configured or contracted.</p><div className="card-actions"><Link className="btn btn-light" href="/admin/pricing">Pricing</Link><Link className="btn btn-light" href="/admin/revenue-intelligence">Revenue Intelligence</Link></div></div></div>
    {historyRows.length>0&&<div className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><div className="kpi">Daily growth ledger</div><h2>Funnel History</h2><p className="small muted">Automatic daily snapshots. These are measured states, not forecasts.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Published</th><th>Contactable</th><th>Research</th><th>Claim Ready</th><th>Claimed</th><th>Paid</th><th>Pro</th><th>Sponsors</th><th>Lead Buyers</th><th>Plan MRR</th><th>30d Lead Rev.</th></tr></thead><tbody>{historyRows.map((r:any)=><tr key={r.metric_date}><td>{r.metric_date}</td><td>{r.published_businesses}</td><td>{r.contactable_prospects}</td><td>{r.open_contact_research}</td><td>{r.open_claim_invites}</td><td>{r.claimed_businesses}</td><td>{r.active_paid_accounts}</td><td>{r.active_pro_accounts}</td><td>{r.active_sponsorships}</td><td>{r.active_lead_buyers}</td><td>{money(Number(r.plan_mrr_cents||0))}</td><td>{money(Number(r.paid_lead_revenue_30d_cents||0))}</td></tr>)}</tbody></table></div></div>}
    <div className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><div className="kpi">Skylight client pipeline</div><h2>Directory → Marketing Agency Opportunities</h2><p className="muted">These signals come from researched prospect flags and stay completely separate from public organic ordering.</p></div><strong>{types.skylight_marketing||0} open</strong></div><div className="info-row"><span>New Skylight inbound requests · 30d</span><strong>{(marketing.data??[]).length}</strong></div><div className="info-row"><span>Research-derived Skylight opportunities</span><strong>{types.skylight_marketing||0}</strong></div><Link className="btn btn-light" href="/admin/marketing-leads">Open Skylight Leads</Link></div>
    <div className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><div className="kpi">Highest-priority state-based work</div><h2>Top Growth Opportunities</h2><p className="small muted">Score prioritizes readiness and available contact/research evidence. It is not a customer-facing score and never affects rank.</p></div><Link href="/admin/growth-opportunities">View all →</Link></div>{rows.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Score</th><th>Type</th><th>Opportunity</th><th>Next Action</th><th>Value</th><th>Status</th></tr></thead><tbody>{rows.slice(0,30).map((r:any)=><tr key={r.id}><td><strong>{r.score}</strong></td><td>{labels[r.opportunity_type]||r.opportunity_type}</td><td>{r.title}</td><td>{r.next_action||'Review'}</td><td>{r.estimated_monthly_value_cents?money(r.estimated_monthly_value_cents):'—'}</td><td>{r.status}</td></tr>)}</tbody></table></div>:<p className="muted">No open growth opportunities.</p>}</div>
    <div className="grid grid-4" style={{marginTop:18}}><Link className="admin-card admin-quick-card" href="/admin/inventory-expansion"><strong>Grow Traffic Inventory</strong><p className="small muted">Fill legitimate provider gaps that are closest to index eligibility.</p><span className="kpi">Open →</span></Link><Link className="admin-card admin-quick-card" href="/admin/content-intelligence"><strong>Grow Organic Content</strong><p className="small muted">Work index, guide quality and search-demand queues.</p><span className="kpi">Open →</span></Link><Link className="admin-card admin-quick-card" href="/admin/lead-billing"><strong>Monetize Leads</strong><p className="small muted">Configure agreements, delivery billing and receivables.</p><span className="kpi">Open →</span></Link><Link className="admin-card admin-quick-card" href="/admin/network-expansion"><strong>Replicate the Model</strong><p className="small muted">Provision the next Local Pros market from the shared platform.</p><span className="kpi">Open →</span></Link></div>
  </>
}
