import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getClaims,getRoles } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { getCanvaAccessToken } from '@/lib/canva-connect'

const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms))
export async function POST(req:Request){
 try{
  const claims=await getClaims();if(!claims?.sub)return NextResponse.json({error:'Unauthorized'},{status:401});const roles=await getRoles(String(claims.sub));if(!roles.includes('super_admin'))return NextResponse.json({error:'Super Admin access required.'},{status:403})
  const form=await req.formData(),file=form.get('file'),campaignId=String(form.get('campaign_id')||''),title=String(form.get('title')||'Central IL Local Pros Marketing').slice(0,120),width=Math.max(40,Math.min(8000,Number(form.get('width')||1080))),height=Math.max(40,Math.min(8000,Number(form.get('height')||1350)));if(!(file instanceof File)||file.type!=='image/png')return NextResponse.json({error:'A PNG marketing asset is required.'},{status:400});if(file.size>20*1024*1024)return NextResponse.json({error:'Marketing asset is too large for Canva upload.'},{status:400});if(width*height>25000000)return NextResponse.json({error:'Canva custom design dimensions exceed the supported area.'},{status:400})
  const s=await createClient(),token=await getCanvaAccessToken(s),bytes=await file.arrayBuffer(),name=title.replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,42)||'Central IL Marketing',nameBase64=Buffer.from(`${name}.png`,'utf8').toString('base64')
  const uploadRes=await fetch('https://api.canva.com/rest/v1/asset-uploads',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream','Asset-Upload-Metadata':JSON.stringify({name_base64:nameBase64})},body:bytes,cache:'no-store'});const upload=await uploadRes.json() as any;if(!uploadRes.ok||!upload?.job?.id)return NextResponse.json({error:upload?.message||upload?.error?.message||'Canva asset upload could not start.'},{status:502});let assetId:string|null=null
  for(let i=0;i<12;i++){const jr=await fetch(`https://api.canva.com/rest/v1/asset-uploads/${encodeURIComponent(upload.job.id)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const job=await jr.json() as any;if(!jr.ok)return NextResponse.json({error:job?.message||'Unable to check Canva upload status.'},{status:502});if(job?.job?.status==='success'&&job?.job?.asset?.id){assetId=job.job.asset.id;break}if(job?.job?.status==='failed')return NextResponse.json({error:job?.job?.error?.message||'Canva rejected the uploaded marketing asset.'},{status:502});await wait(400)}
  if(!assetId)return NextResponse.json({error:'Canva is still processing the uploaded asset. Try Send to Canva again shortly.'},{status:504})
  const createRes=await fetch('https://api.canva.com/rest/v1/designs',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({type:'type_and_asset',design_type:{type:'custom',width,height},asset_id:assetId,title}),cache:'no-store'});const created=await createRes.json() as any;if(!createRes.ok||!created?.design?.id)return NextResponse.json({error:created?.message||'Canva design could not be created.'},{status:502});const design=created.design
  if(campaignId){await s.from('marketing_campaigns').update({canva_design_id:design.id,canva_edit_url:design.urls?.edit_url||null,canva_view_url:design.urls?.view_url||null}).eq('tenant_id',TENANT_ID).eq('id',campaignId);await s.from('marketing_publications').insert({tenant_id:TENANT_ID,campaign_id:campaignId,platform:'canva',status:'published',published_at:new Date().toISOString(),external_id:design.id,external_url:design.urls?.edit_url||design.urls?.view_url||null,created_by:String(claims.sub),metadata:{asset_id:assetId}})}
  await s.from('audit_logs').insert({tenant_id:TENANT_ID,actor_user_id:String(claims.sub),action_type:'canva_design_created',action_text:`Created Canva design ${design.id}${campaignId?` from marketing campaign ${campaignId}`:''}.`});return NextResponse.json({ok:true,design_id:design.id,edit_url:design.urls?.edit_url||null,view_url:design.urls?.view_url||null})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create Canva design.'},{status:400})}
}
