import{createClient}from'@/lib/supabase/server';import{TENANT_ID}from'@/lib/constants';import{AdminLeadBilling}from'@/components/AdminLeadBilling';
function rel(v:any){return Array.isArray(v)?v[0]:v}function unitValue(c:any){return c.billing_model==='pay_per_lead'?Number(c.per_lead_price_cents||0):Math.round(Number(c.bundle_price_cents||0)/Math.max(1,Number(c.bundle_lead_count||1)))}const money=(c:number)=>`$${(Number(c||0)/100).toFixed(2)}`;
export default async function Page(){const s=await createClient();const monthStart=new Date();monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);const monthIso=monthStart.toISOString();const thirtyDaysAgo=new Date(Date.now()-30*86400000).toISOString();const[{data:businesses},{data:programs},{data:subs},{data:charges},{data:invoices},{data:leadRows},{data:creditRequests},{data:credits}]=await Promise.all([
 s.from('businesses').select('id,name').eq('tenant_id',TENANT_ID).eq('status','published').order('name').limit(1500),
 s.from('business_lead_programs').select('*').eq('tenant_id',TENANT_ID),
 s.from('subscriptions').select('business_id,status,updated_at,ends_at,plans(slug,sort_order)').eq('tenant_id',TENANT_ID).in('status',['active','trialing','past_due']).order('updated_at',{ascending:false}),
 s.from('lead_delivery_charges').select('id,business_id,lead_id,billing_status,billing_model,per_lead_price_cents,bundle_lead_count,bundle_price_cents,delivered_at,invoice_id,leads(service,city,source)').eq('tenant_id',TENANT_ID).order('delivered_at',{ascending:false}).limit(5000),
 s.from('lead_invoices').select('id,business_id,invoice_number,billing_model,lead_count,bundle_count,subtotal_cents,credit_applied_cents,amount_due_cents,status,due_at,hosted_invoice_url,invoice_pdf_url,sent_at,paid_at,created_at').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1000),
 s.from('leads').select('id,service,city,source,business_id,created_at,status').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1500),
 s.from('lead_credit_requests').select('id,business_id,charge_id,lead_id,reason,details,requested_credit_cents,status,approved_credit_cents,staff_notes,created_at,reviewed_at,businesses(name),leads(service,city)').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(500),
 s.from('business_lead_credits').select('id,business_id,original_amount_cents,remaining_amount_cents,status,created_at').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1000)
 ]);
 const programMap=new Map((programs??[]).map((x:any)=>[x.business_id,x]));const planMap=new Map<string,string>();for(const x of subs??[]){if(planMap.has((x as any).business_id))continue;const p=rel((x as any).plans);if(p?.slug)planMap.set((x as any).business_id,p.slug)}
 const counts=new Map<string,{unbilled:number;invoiced:number;paid:number;delivered:number;month:number}>();for(const c of charges??[]){const k=(c as any).business_id,v=counts.get(k)||{unbilled:0,invoiced:0,paid:0,delivered:0,month:0};if((c as any).billing_status!=='void'){v.delivered++;if(String((c as any).delivered_at)>=monthIso)v.month++}if((c as any).billing_status==='unbilled')v.unbilled++;else if((c as any).billing_status==='invoiced')v.invoiced++;else if((c as any).billing_status==='paid')v.paid++;counts.set(k,v)}
 const invoiceMap=new Map<string,any[]>(),financialMap=new Map<string,{collected:number;outstanding:number;overdue:number}>();for(const i of invoices??[]){const k=(i as any).business_id,arr=invoiceMap.get(k)||[];arr.push(i);invoiceMap.set(k,arr);const f=financialMap.get(k)||{collected:0,outstanding:0,overdue:0};if((i as any).status==='paid')f.collected+=Number((i as any).amount_due_cents||0);if(['sent','overdue'].includes((i as any).status))f.outstanding+=Number((i as any).amount_due_cents||0);if((i as any).status==='overdue')f.overdue+=Number((i as any).amount_due_cents||0);financialMap.set(k,f)}
 const creditMap=new Map<string,number>();for(const c of credits??[]){if((c as any).status==='available'&&Number((c as any).remaining_amount_cents)>0)creditMap.set((c as any).business_id,(creditMap.get((c as any).business_id)||0)+Number((c as any).remaining_amount_cents))}
 const rows=(businesses??[]).map((b:any)=>{const count=counts.get(b.id)||{unbilled:0,invoiced:0,paid:0,delivered:0,month:0},program=programMap.get(b.id)||null;return{id:b.id,name:b.name,plan_slug:planMap.get(b.id)||'free',program:program?{...program,month_delivered_count:count.month}:null,unbilled:count.unbilled,invoiced:count.invoiced,paid:count.paid,delivered:count.delivered,...(financialMap.get(b.id)||{collected:0,outstanding:0,overdue:0}),available_credit_cents:creditMap.get(b.id)||0,invoices:invoiceMap.get(b.id)||[]}});
 const byService=new Map<string,{delivered:number;paid:number;value_cents:number}>(),byCity=new Map<string,{delivered:number;paid:number;value_cents:number}>(),bySource=new Map<string,{delivered:number;paid:number;value_cents:number}>();let paidLeadUnits=0,paidLeadValue=0,unbilledValue=0;for(const c of charges??[]){const lead=rel((c as any).leads),value=unitValue(c);if((c as any).billing_status==='unbilled')unbilledValue+=value;for(const[key,map]of[[lead?.service||'Uncategorized',byService],[lead?.city||'Unknown city',byCity],[lead?.source||'Unknown source',bySource]] as const){const v=map.get(key)||{delivered:0,paid:0,value_cents:0};if((c as any).billing_status!=='void')v.delivered++;if((c as any).billing_status==='paid'){v.paid++;v.value_cents+=value}map.set(key,v)}if((c as any).billing_status==='paid'){paidLeadUnits++;paidLeadValue+=value}}
 const paidLast30=(invoices??[]).filter((x:any)=>x.status==='paid'&&x.paid_at&&String(x.paid_at)>=thirtyDaysAgo).reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0);const overdueBusinesses=rows.filter((x:any)=>x.overdue>0).length,capRisk=rows.filter((x:any)=>x.program?.max_leads_per_month&&x.program.month_delivered_count>=Math.ceil(Number(x.program.max_leads_per_month)*.8)).length,heldBusinesses=rows.filter((x:any)=>x.program?.manual_delivery_hold||x.overdue>0&&x.program?.stop_delivery_on_overdue).length;
 const portfolio={collected_cents:(invoices??[]).filter((x:any)=>x.status==='paid').reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),outstanding_cents:(invoices??[]).filter((x:any)=>['sent','overdue'].includes(x.status)).reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),overdue_cents:(invoices??[]).filter((x:any)=>x.status==='overdue').reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),average_paid_lead_cents:paidLeadUnits?Math.round(paidLeadValue/paidLeadUnits):0,pending_credit_requests:(creditRequests??[]).filter((x:any)=>x.status==='pending').length,service_metrics:[...byService.entries()].map(([service,v])=>({service,...v})).sort((a,b)=>b.value_cents-a.value_cents)};
 const top=(m:Map<string,{delivered:number;paid:number;value_cents:number}>)=>[...m.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.value_cents-a.value_cents||b.delivered-a.delivered).slice(0,5),topBusinesses=[...rows].sort((a:any,b:any)=>b.collected-a.collected).slice(0,5);
 return <><div className="admin-page-head"><div><div className="kpi">Lead Revenue CRM</div><h1>Lead Billing, Agreements & Collections</h1><p className="muted">Control negotiated lead agreements, delivery limits, payment holds, credits, automatic draft invoicing and Stripe collection. Lead charges remain based on delivery—not close outcome.</p></div><span className="badge sponsored">Super Admin revenue controls</span></div>
 <div className="admin-card" style={{marginBottom:18}}><div className="section-head compact-head"><div><div className="kpi">Revenue Intelligence</div><h2>Demand, Collections & Account Risk</h2></div><span className="badge neutral">Private staff data</span></div><div className="stat-grid"><div className="stat">Paid · Last 30 Days<strong>{money(paidLast30)}</strong></div><div className="stat">Unbilled Lead Value*<strong>{money(unbilledValue)}</strong></div><div className="stat">Accounts Overdue<strong>{overdueBusinesses}</strong></div><div className="stat">Near / At Lead Cap<strong>{capRisk}</strong></div><div className="stat">Delivery Holds / Risk<strong>{heldBusinesses}</strong></div></div><p className="small muted">*Unbilled lead value uses the preserved delivered-lead price snapshot as directional pipeline value. Bundle revenue is only invoiceable when a full historical bundle is fulfilled.</p><div className="grid grid-3" style={{marginTop:14}}><MetricList title="Top Services / Niches" rows={top(byService)}/><MetricList title="Top Cities" rows={top(byCity)}/><MetricList title="Top Lead Sources" rows={top(bySource)}/></div><div className="admin-card" style={{marginTop:14}}><div className="kpi">Highest Lifetime Lead Spend</div>{topBusinesses.map((x:any)=><div className="info-row" key={x.id}><span>{x.name}</span><strong>{money(x.collected)}</strong></div>)}{!topBusinesses.length&&<p className="small muted">No paid lead invoices yet.</p>}</div></div>
 <AdminLeadBilling rows={rows as any} leads={(leadRows??[]) as any[]} creditRequests={(creditRequests??[]) as any[]} portfolio={portfolio}/></>}
function MetricList({title,rows}:{title:string;rows:{name:string;delivered:number;paid:number;value_cents:number}[]}){return <div className="admin-card"><div className="kpi">{title}</div>{rows.map(x=><div className="info-row" key={x.name}><span>{x.name}<small className="muted"> · {x.delivered} delivered</small></span><strong>{money(x.value_cents)}</strong></div>)}{!rows.length&&<p className="small muted">No delivered-lead data yet.</p>}</div>}
