import{createClient}from'@/lib/supabase/server';import{TENANT_ID}from'@/lib/constants';import{AdminLeadBilling}from'@/components/AdminLeadBilling';
function rel(v:any){return Array.isArray(v)?v[0]:v}function unitValue(c:any){return c.billing_model==='pay_per_lead'?Number(c.per_lead_price_cents||0):Math.round(Number(c.bundle_price_cents||0)/Math.max(1,Number(c.bundle_lead_count||1)))}
export default async function Page(){const s=await createClient();const[{data:businesses},{data:programs},{data:subs},{data:charges},{data:invoices},{data:leadRows},{data:creditRequests},{data:credits}]=await Promise.all([
 s.from('businesses').select('id,name').eq('tenant_id',TENANT_ID).eq('status','published').order('name').limit(1500),
 s.from('business_lead_programs').select('*').eq('tenant_id',TENANT_ID),
 s.from('subscriptions').select('business_id,status,updated_at,ends_at,plans(slug,sort_order)').eq('tenant_id',TENANT_ID).in('status',['active','trialing','past_due']).order('updated_at',{ascending:false}),
 s.from('lead_delivery_charges').select('id,business_id,lead_id,billing_status,billing_model,per_lead_price_cents,bundle_lead_count,bundle_price_cents,delivered_at,invoice_id,leads(service,city)').eq('tenant_id',TENANT_ID).order('delivered_at',{ascending:false}).limit(5000),
 s.from('lead_invoices').select('id,business_id,invoice_number,billing_model,lead_count,bundle_count,subtotal_cents,credit_applied_cents,amount_due_cents,status,due_at,hosted_invoice_url,invoice_pdf_url,sent_at,paid_at,created_at').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1000),
 s.from('leads').select('id,service,city,business_id,created_at,status').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1000),
 s.from('lead_credit_requests').select('id,business_id,charge_id,lead_id,reason,details,requested_credit_cents,status,approved_credit_cents,staff_notes,created_at,reviewed_at,businesses(name),leads(service,city)').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(500),
 s.from('business_lead_credits').select('id,business_id,original_amount_cents,remaining_amount_cents,status,created_at').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(1000)
 ]);
 const programMap=new Map((programs??[]).map((x:any)=>[x.business_id,x]));const planMap=new Map<string,string>();for(const x of subs??[]){if(planMap.has((x as any).business_id))continue;const p=rel((x as any).plans);if(p?.slug)planMap.set((x as any).business_id,p.slug)}
 const counts=new Map<string,{unbilled:number;invoiced:number;paid:number;delivered:number}>();for(const c of charges??[]){const k=(c as any).business_id,v=counts.get(k)||{unbilled:0,invoiced:0,paid:0,delivered:0};if((c as any).billing_status!=='void')v.delivered++;if((c as any).billing_status==='unbilled')v.unbilled++;else if((c as any).billing_status==='invoiced')v.invoiced++;else if((c as any).billing_status==='paid')v.paid++;counts.set(k,v)}
 const invoiceMap=new Map<string,any[]>(),financialMap=new Map<string,{collected:number;outstanding:number;overdue:number}>();for(const i of invoices??[]){const k=(i as any).business_id,arr=invoiceMap.get(k)||[];arr.push(i);invoiceMap.set(k,arr);const f=financialMap.get(k)||{collected:0,outstanding:0,overdue:0};if((i as any).status==='paid')f.collected+=Number((i as any).amount_due_cents||0);if(['sent','overdue'].includes((i as any).status))f.outstanding+=Number((i as any).amount_due_cents||0);if((i as any).status==='overdue')f.overdue+=Number((i as any).amount_due_cents||0);financialMap.set(k,f)}
 const creditMap=new Map<string,number>();for(const c of credits??[]){if((c as any).status==='available'&&Number((c as any).remaining_amount_cents)>0)creditMap.set((c as any).business_id,(creditMap.get((c as any).business_id)||0)+Number((c as any).remaining_amount_cents))}
 const rows=(businesses??[]).map((b:any)=>({id:b.id,name:b.name,plan_slug:planMap.get(b.id)||'free',program:programMap.get(b.id)||null,...(counts.get(b.id)||{unbilled:0,invoiced:0,paid:0,delivered:0}),...(financialMap.get(b.id)||{collected:0,outstanding:0,overdue:0}),available_credit_cents:creditMap.get(b.id)||0,invoices:invoiceMap.get(b.id)||[]}));
 const byService=new Map<string,{delivered:number;paid:number;value_cents:number}>();let paidLeadUnits=0,paidLeadValue=0;for(const c of charges??[]){const lead=rel((c as any).leads),service=lead?.service||'Uncategorized',v=byService.get(service)||{delivered:0,paid:0,value_cents:0};if((c as any).billing_status!=='void')v.delivered++;if((c as any).billing_status==='paid'){const value=unitValue(c);v.paid++;v.value_cents+=value;paidLeadUnits++;paidLeadValue+=value}byService.set(service,v)}
 const portfolio={collected_cents:(invoices??[]).filter((x:any)=>x.status==='paid').reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),outstanding_cents:(invoices??[]).filter((x:any)=>['sent','overdue'].includes(x.status)).reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),overdue_cents:(invoices??[]).filter((x:any)=>x.status==='overdue').reduce((n:number,x:any)=>n+Number(x.amount_due_cents||0),0),average_paid_lead_cents:paidLeadUnits?Math.round(paidLeadValue/paidLeadUnits):0,pending_credit_requests:(creditRequests??[]).filter((x:any)=>x.status==='pending').length,service_metrics:[...byService.entries()].map(([service,v])=>({service,...v})).sort((a,b)=>b.value_cents-a.value_cents)};
 return <><div className="admin-page-head"><div><div className="kpi">Lead Revenue CRM</div><h1>Lead Billing, Agreements & Collections</h1><p className="muted">Control negotiated lead agreements, delivery limits, payment holds, credits, automatic draft invoicing and Stripe collection. Lead charges remain based on delivery—not close outcome.</p></div><span className="badge sponsored">Super Admin revenue controls</span></div><AdminLeadBilling rows={rows as any} leads={(leadRows??[]) as any[]} creditRequests={(creditRequests??[]) as any[]} portfolio={portfolio}/></>}
