import{NextResponse}from'next/server'
import{createClient}from'@/lib/supabase/server'
import{requireUser}from'@/lib/auth'
const str=(v:unknown,n=5000)=>String(v??'').trim().slice(0,n)
const id=(v:unknown)=>{const x=str(v,40);return /^[0-9a-f-]{36}$/i.test(x)?x:null}
export async function POST(req:Request){try{await requireUser('/account/skylight');const body=await req.json() as Record<string,any>,action=str(body.action,50),s=await createClient()
 if(action==='claim'){const token=id(body.token);if(!token)return NextResponse.json({error:'Invalid invitation token.'},{status:400});const{data,error}=await s.rpc('claim_skylight_client_portal_invite',{p_token:token});if(error)throw error;return NextResponse.json(data)}
 if(action==='view_proposal'){const proposalId=id(body.id);if(!proposalId)return NextResponse.json({error:'Proposal is required.'},{status:400});const{data,error}=await s.rpc('customer_mark_skylight_proposal_viewed',{p_proposal_id:proposalId});if(error)throw error;return NextResponse.json(data)}
 if(action==='accept_proposal'){const proposalId=id(body.id);if(!proposalId)return NextResponse.json({error:'Proposal is required.'},{status:400});const{data,error}=await s.rpc('customer_accept_skylight_proposal',{p_proposal_id:proposalId});if(error)throw error;return NextResponse.json(data)}
 if(action==='sign_agreement'){const agreementId=id(body.id),signerName=str(body.signer_name,180);if(!agreementId||signerName.length<2)return NextResponse.json({error:'Agreement and authorized signer name are required.'},{status:400});if(body.accepted!==true)return NextResponse.json({error:'Confirm that you are authorized and agree to the service agreement.'},{status:400});const ip=str(req.headers.get('x-forwarded-for')?.split(',')[0]||req.headers.get('x-real-ip')||'',120),ua=str(req.headers.get('user-agent')||'',1000);const{data,error}=await s.rpc('customer_sign_skylight_agreement',{p_agreement_id:agreementId,p_signer_name:signerName,p_signer_title:str(body.signer_title,180)||null,p_signer_ip:ip||null,p_user_agent:ua||null});if(error)throw error;return NextResponse.json(data)}
 if(action==='task_approval'){const taskId=id(body.id);if(!taskId)return NextResponse.json({error:'Approval item is required.'},{status:400});const{data,error}=await s.rpc('customer_update_skylight_task_approval',{p_task_id:taskId,p_approved:Boolean(body.approved),p_note:str(body.note,2000)||null});if(error)throw error;return NextResponse.json(data)}
 if(action==='message'){const projectId=id(body.project_id),message=str(body.body,5000);if(!projectId||!message)return NextResponse.json({error:'Project and message are required.'},{status:400});const{data,error}=await s.rpc('customer_send_skylight_project_message',{p_project_id:projectId,p_body:message});if(error)throw error;return NextResponse.json(data)}
 return NextResponse.json({error:'Unsupported Skylight workspace action.'},{status:400})
}catch(e:any){return NextResponse.json({error:String(e?.message||'Unable to process Skylight workspace action.')},{status:400})}}
