import Link from'next/link'
import{getOwnerData}from'@/lib/owner'
import{LeadROITracker}from'@/components/LeadROITracker'
type SearchValue=string|string[]|undefined
const one=(v:SearchValue)=>Array.isArray(v)?v[0]||'':v||''
export default async function Page({searchParams}:{searchParams:Promise<Record<string,SearchValue>>}){const sp=await searchParams,{s,businesses}=await getOwnerData('/business-portal/reputation');const requested=one(sp.business),business=businesses.find((b:any)=>String(b.id)===requested)||businesses[0];if(!business)return <div className="empty empty-rich"><h2>No claimed business is connected yet</h2><Link className="btn btn-primary" href="/claim">Claim a Business</Link></div>;const[recipients,charges,recommendations,appointments]=await Promise.all([
 s.from('lead_recipients').select('id,lead_id,status,delivery_type,owner_notes,routed_at,viewed_at,contacted_at,appointment_at,quote_amount_cents,outcome_value_cents,loss_reason,outcome_updated_at,won_at,lost_at,leads(service,city,timeline,created_at)').eq('business_id',business.id).order('routed_at',{ascending:false}).limit(250),
 s.from('lead_delivery_charges').select('id,lead_id,recipient_id,billing_model,per_lead_price_cents,bundle_lead_count,bundle_price_cents,billing_status,delivered_at').eq('business_id',business.id).order('delivered_at',{ascending:false}).limit(500),
 s.from('business_recommendations').select('id,body,service,city,service_date,created_at').eq('business_id',business.id).eq('status','approved').order('created_at',{ascending:false}).limit(50),
 s.from('appointment_requests').select('id,lead_id,requested_at,alternate_at,request_type,status,owner_response,responded_at').eq('business_id',business.id).order('created_at',{ascending:false}).limit(100),
]);return <><div className="admin-row-actions" style={{marginBottom:14}}>{businesses.map((b:any)=><Link className={`btn btn-small ${b.id===business.id?'btn-primary':'btn-light'}`} href={`/business-portal/reputation?business=${b.id}`} key={b.id}>{b.name}</Link>)}</div><div className="admin-page-head"><div><div className="kpi">Reputation + Lead ROI</div><h1>{business.name}</h1><p className="muted">Track sourced reputation signals and the private business outcomes generated from delivered Local Pros leads.</p></div><div className="badges"><span className="badge neutral">Sourced rating {Number(business.rating||0)>0?business.rating:'—'}</span><span className="badge neutral">{Number(business.review_count||0)} sourced reviews</span><span className="badge neutral">{(recommendations.data??[]).length} Local Faves</span></div></div><section className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Reputation Center</div><h2>Signals customers can understand</h2><p className="muted">Google/source ratings, Local Faves, Claimed, Verified and Sponsored remain separate signals. Local Faves are moderated community recommendations and cannot be purchased.</p></div></div><div className="grid grid-3"><div className="card"><strong>Sourced rating</strong><p style={{fontSize:28,fontWeight:900}}>{Number(business.rating||0)>0?business.rating:'—'}</p><span className="small muted">{Number(business.review_count||0)} sourced reviews</span></div><div className="card"><strong>Local Fave recommendations</strong><p style={{fontSize:28,fontWeight:900}}>{(recommendations.data??[]).length}</p><span className="small muted">approved signed-in community recommendations</span></div><div className="card"><strong>Trust state</strong><p><span className="badge neutral">{business.claimed?'Claimed':'Unclaimed'}</span> <span className={business.verified?'badge verified':'badge neutral'}>{business.verified?'Verified':'Not Verified'}</span></p><span className="small muted">Paid tools cannot create verification.</span></div></div></section><section style={{marginTop:18}}><LeadROITracker rows={(recipients.data??[])as any[]} charges={(charges.data??[])as any[]} appointments={(appointments.data??[])as any[]}/></section></>}
