import Link from'next/link'
import{getOwnerData}from'@/lib/owner'
import{ProProfileEditor}from'@/components/ProProfileEditor'
import{ConversionPresetLibrary}from'@/components/ConversionPresetLibrary'
import{submitPremiumDescription}from'./actions'
function related(v:any){return Array.isArray(v)?v[0]:v}
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const sp=await searchParams;const{claims,s,businesses}=await getOwnerData('/business-portal/pro-profile')
 if(!businesses.length)return <div className="card empty-rich"><h2>Claim a business first</h2><p className="muted">Premium profile tools become available after staff approves a legitimate ownership claim.</p><Link className="btn btn-primary" href="/search">Find My Listing</Link></div>
 const requested=typeof sp.business==='string'?sp.business:'';const b=businesses.find((x:any)=>x.id===requested)??businesses[0]
 const switcher=businesses.length>1?<form className="portal-switcher" action="/business-portal/pro-profile" method="get"><label>Managing<select name="business" defaultValue={b.id}>{businesses.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="btn btn-light" type="submit">Switch Business</button></form>:<div className="portal-current"><span>Managing</span><strong>{b.name}</strong></div>
 const today=new Date().toISOString().slice(0,10)
 const[{data:subs},{data:pendingPro},{data:pendingDescription},{data:sponsors}]=await Promise.all([
  s.from('subscriptions').select('status,ends_at,updated_at,plans(slug,name)').eq('business_id',b.id).in('status',['active','trialing','past_due']).order('updated_at',{ascending:false}).limit(20),
  s.from('business_edit_requests').select('id,created_at').eq('business_id',b.id).eq('requested_by',String(claims.sub)).eq('request_type','pro_profile_update').eq('status','pending').order('created_at',{ascending:false}).limit(1),
  s.from('business_edit_requests').select('id,created_at').eq('business_id',b.id).eq('requested_by',String(claims.sub)).eq('request_type','profile_update').eq('status','pending').order('created_at',{ascending:false}).limit(1),
  s.from('sponsorships').select('id,active,starts_on,ends_on').eq('business_id',b.id).eq('active',true).limit(50),
 ])
 const active=(subs??[]).filter((x:any)=>!x.ends_at||new Date(x.ends_at).getTime()>Date.now()),pro=Boolean(active.find((x:any)=>related(x.plans)?.slug==='pro')),featured=Boolean(active.find((x:any)=>related(x.plans)?.slug==='featured')),sponsored=Boolean((sponsors??[]).find((x:any)=>(!x.starts_on||String(x.starts_on)<=today)&&(!x.ends_on||String(x.ends_on)>=today))),premium=pro||featured||sponsored
 const initial=(b.attributes&&typeof b.attributes==='object'?(b.attributes as any).pro_profile:null)||{}
 return <div>{switcher}<div className="portal-section-head"><div><div className="kpi">Featured / Pro customer profile</div><h2>Premium Profile — {b.name}</h2><p className="muted">Featured and Sponsored businesses can write their customer-facing profile description. Pro adds the full mini-site and conversion toolkit.</p></div><Link className="btn btn-light" href={`/business/${b.slug}`}>View Public Profile</Link></div>
 {!premium?<div className="card empty-rich"><span className="badge sponsored">Featured / Pro Feature</span><h2>Premium Profile requires Featured, Sponsored or Pro access</h2><p className="muted">Featured adds enhanced profile/media benefits and clearly labeled paid placement. Pro adds the full mini-site toolkit, advanced conversion controls, Lead Inbox and deeper performance features.</p><Link className="btn btn-primary" href={`/business-portal/subscription?business=${b.id}`}>Explore Plans</Link></div>:<>
  <div className="card" style={{marginBottom:18}}><div className="badges">{pro&&<span className="badge verified">Pro</span>}{!pro&&featured&&<span className="badge sponsored">Featured</span>}{sponsored&&<span className="badge sponsored">Sponsored Placement</span>}</div><div className="kpi">Customer-facing business story</div><h2>Profile Description</h2><p className="muted">Write the description customers see in your public profile and Featured cards. Your submission stays pending until staff approves it, protecting listing quality and preventing unauthorized changes.</p>{pendingDescription?.length?<div className="notice warn">A profile description/listing update is already pending staff review.</div>:<form action={submitPremiumDescription} className="form-card"><input type="hidden" name="business_id" value={b.id}/><label>Business Profile Description<textarea name="description" defaultValue={b.description||''} maxLength={2400} required style={{minHeight:180}} placeholder="Tell customers what your business does, who you serve, what makes you different, and what they can expect."/></label><button className="btn btn-primary">Submit Description for Review</button></form>}</div>
  {!pro&&<div className="grid grid-2" style={{marginBottom:18}}><div className="card"><div className="kpi">Featured media</div><h3>Build the visual profile</h3><p className="muted">Upload your logo on any plan. Featured includes showcase-photo capacity and restaurant-menu upload when applicable.</p><Link className="btn btn-light" href={`/business-portal/media?business=${b.id}`}>Manage Photos & Media</Link></div><div className="card"><div className="kpi">Upgrade path</div><h3>Want the full mini-site?</h3><p className="muted">Pro adds services, packages, announcements, offers, FAQs, social links and custom conversion CTAs.</p><Link className="btn btn-primary" href={`/business-portal/subscription?business=${b.id}`}>Explore Pro</Link></div></div>}
  {pro&&<><ConversionPresetLibrary/><ProProfileEditor businessId={b.id} initial={initial as any} pending={Boolean(pendingPro?.length)}/></>}
 </>}
 </div>
}
