import Link from 'next/link'
import { getOwnerData } from '@/lib/owner'

type SearchValue=string|string[]|undefined
type Row=Record<string,any>
const one=(v:SearchValue)=>Array.isArray(v)?v[0]??'':v??''
const pct=(now:number,prior:number)=>prior?Math.round((now-prior)/prior*100):now?100:0
const rate=(part:number,total:number)=>total?Math.round(part/total*1000)/10:0
const date=(v:any)=>{if(!v)return'—';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}

export default async function Page({searchParams}:{searchParams:Promise<Record<string,SearchValue>>}){
 const sp=await searchParams
 const{businesses,s}=await getOwnerData('/business-portal/analytics')
 if(!businesses.length)return <div className="card empty-rich"><h2>Claim a business first</h2><p className="muted">Analytics become available after staff approves a legitimate ownership claim.</p><Link className="btn btn-primary" href="/search">Find My Listing</Link></div>
 const requested=one(sp.business),b=businesses.find((x:any)=>x.id===requested)??businesses[0],days=one(sp.range)==='90'?90:30
 const switcher=businesses.length>1?<form className="portal-switcher" action="/business-portal/analytics" method="get"><input type="hidden" name="range" value={String(days)}/><label>Managing<select name="business" defaultValue={b.id}>{businesses.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="btn btn-light" type="submit">Switch Business</button></form>:<div className="portal-current"><span>Managing</span><strong>{b.name}</strong></div>
 const now=Date.now(),currentCutoff=new Date(now-days*86400000).toISOString().slice(0,10),previousCutoff=new Date(now-days*2*86400000).toISOString().slice(0,10)
 const{data,error}=await s.from('listing_daily_stats').select('stat_date,impressions,profile_views,phone_clicks,website_clicks,directions_clicks,lead_submissions').eq('business_id',b.id).gte('stat_date',previousCutoff).order('stat_date',{ascending:false}).limit(days*2+5)
 const rows=(data??[]) as Row[],current=rows.filter(x=>String(x.stat_date)>=currentCutoff),previous=rows.filter(x=>String(x.stat_date)<currentCutoff&&String(x.stat_date)>=previousCutoff)
 const sum=(key:string,set:Row[])=>set.reduce((n,x)=>n+Number(x[key]||0),0)
 const metric=(key:string)=>({current:sum(key,current),previous:sum(key,previous)})
 const impressions=metric('impressions'),views=metric('profile_views'),phone=metric('phone_clicks'),website=metric('website_clicks'),directions=metric('directions_clicks'),leads=metric('lead_submissions')
 const actions=phone.current+website.current+directions.current+leads.current,previousActions=phone.previous+website.previous+directions.previous+leads.previous
 const viewRate=rate(views.current,impressions.current),actionRate=rate(actions,views.current),leadRate=rate(leads.current,views.current)
 const bestDay=current.reduce<Row|null>((best,row)=>!best||Number(row.profile_views||0)>Number(best.profile_views||0)?row:best,null)
 const rangeHref=(range:number)=>`/business-portal/analytics?business=${encodeURIComponent(b.id)}&range=${range}`
 const recommendation=impressions.current===0?{title:'Strengthen the customer-facing listing',detail:'No directory impressions were recorded in this period. Review profile completeness, categories and accurate location information.',href:`/business-portal/profile-strength?business=${b.id}`,action:'Review Profile Strength'}:viewRate<5?{title:'Improve the profile presentation',detail:'The listing is appearing, but relatively few impressions are becoming profile views. Review description, photos and customer-facing information.',href:`/business-portal/media?business=${b.id}`,action:'Review Photos & Media'}:actionRate<10?{title:'Make it easier for customers to act',detail:'People are viewing the profile, but contact actions are comparatively low. Confirm phone, website, hours and profile content are current and useful.',href:`/business-portal/listing?business=${b.id}`,action:'Review My Listing'}:{title:'Keep working the conversion path',detail:'Your profile is generating customer actions. Review lead outcomes and recent performance to identify what is turning into real opportunities.',href:`/business-portal/leads?business=${b.id}`,action:'Open Lead Inbox'}
 return <div>{switcher}
  <div className="portal-section-head"><div><div className="kpi">Owner Performance</div><h2>Analytics — {b.name}</h2><p className="muted">First-party directory activity from listing impressions, profile visits, public contact actions and direct lead forms.</p></div><div className="card-actions"><nav className="owner-analytics-range"><Link className={days===30?'active':''} href={rangeHref(30)}>30 Days</Link><Link className={days===90?'active':''} href={rangeHref(90)}>90 Days</Link></nav><Link className="btn btn-light" href={`/business/${b.slug}`}>View Public Profile</Link></div></div>
  {error?<div className="notice warn">Analytics could not be loaded completely: {error.message}</div>:null}
  <div className="stat-grid owner-analytics-stats"><Metric label="Impressions" value={impressions.current} change={pct(impressions.current,impressions.previous)}/><Metric label="Profile Views" value={views.current} change={pct(views.current,views.previous)}/><Metric label="Phone Clicks" value={phone.current} change={pct(phone.current,phone.previous)}/><Metric label="Website Clicks" value={website.current} change={pct(website.current,website.previous)}/><Metric label="Directions" value={directions.current} change={pct(directions.current,directions.previous)}/><Metric label="Direct Leads" value={leads.current} change={pct(leads.current,leads.previous)}/></div>

  <div className="owner-analytics-grid">
   <section className="owner-dashboard-panel"><div className="owner-dashboard-panel-head"><div><div className="kpi">Customer Funnel</div><h3>From discovery to action</h3><p>These stages describe first-party directory interactions, not guaranteed customer outcomes.</p></div></div><div className="owner-funnel"><Funnel label="Search / listing impressions" value={impressions.current} width={100}/><Funnel label="Profile views" value={views.current} width={impressions.current?Math.max(4,Math.min(100,views.current/impressions.current*100)):0}/><Funnel label="Contact actions" value={actions} width={impressions.current?Math.max(actions?4:0,Math.min(100,actions/impressions.current*100)):0}/><Funnel label="Direct lead forms" value={leads.current} width={impressions.current?Math.max(leads.current?4:0,Math.min(100,leads.current/impressions.current*100)):0}/></div><div className="owner-rate-grid"><div><span>View Rate</span><strong>{viewRate}%</strong><small>views ÷ impressions</small></div><div><span>Action Rate</span><strong>{actionRate}%</strong><small>actions ÷ profile views</small></div><div><span>Direct Lead Rate</span><strong>{leadRate}%</strong><small>lead forms ÷ profile views</small></div></div></section>
   <div className="owner-dashboard-stack"><section className="owner-dashboard-panel"><div className="kpi">Recommended Next Move</div><h3>{recommendation.title}</h3><p className="small muted">{recommendation.detail}</p><Link className="btn btn-primary" href={recommendation.href}>{recommendation.action}</Link></section><section className="owner-dashboard-panel"><div className="kpi">Period Comparison</div><h3>{days}-day activity vs prior {days} days</h3><div className="owner-analytics-compare"><div><span>Profile views</span><strong>{signed(pct(views.current,views.previous))}</strong></div><div><span>Customer actions</span><strong>{signed(pct(actions,previousActions))}</strong></div><div><span>Direct leads</span><strong>{signed(pct(leads.current,leads.previous))}</strong></div></div>{bestDay?<p className="small muted">Highest profile-view day in this period: <strong>{date(bestDay.stat_date)}</strong> with {Number(bestDay.profile_views||0)} view{Number(bestDay.profile_views||0)===1?'':'s'}.</p>:<p className="small muted">No daily activity has been recorded for this period yet.</p>}</section></div>
  </div>

  <section className="card owner-analytics-table"><div className="section-head compact-head"><div><div className="kpi">Daily Activity</div><h3>Performance Detail</h3></div><span className="badge neutral">{current.length} day{current.length===1?'':'s'} with records</span></div>{current.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Impressions</th><th>Views</th><th>Phone</th><th>Website</th><th>Directions</th><th>Leads</th></tr></thead><tbody>{current.map(x=><tr key={x.stat_date}><td>{date(x.stat_date)}</td><td>{x.impressions}</td><td>{x.profile_views}</td><td>{x.phone_clicks}</td><td>{x.website_clicks}</td><td>{x.directions_clicks}</td><td>{x.lead_submissions}</td></tr>)}</tbody></table></div>:<div className="empty empty-rich"><h3>No listing activity recorded</h3><p>Activity will appear as customers see and interact with this business inside Central Illinois Local Pros.</p></div>}</section>
  <p className="small muted" style={{marginTop:14}}>These are first-party directory interaction metrics, not Google Analytics, ad-platform attribution, Google Business Profile rankings or guaranteed customer outcomes. Internal SEO diagnostics and staff intelligence remain private.</p>
 </div>
}

function Metric({label,value,change}:{label:string;value:number;change:number}){return <div className="stat"><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{signed(change)} vs previous period</small></div>}
function Funnel({label,value,width}:{label:string;value:number;width:number}){return <div><div><span>{label}</span><strong>{value.toLocaleString()}</strong></div><div className="owner-funnel-track"><span style={{width:`${width}%`}}/></div></div>}
function signed(value:number){return `${value>0?'+':''}${value}%`}
