import{createLocation,createCategory,createContentBlock,createGuide,createBranch}from'@/app/admin/actions'
export function AdminCreateForm({section}:{section:string}){
 if(section==='locations')return <form action={createLocation} className="admin-card"><h2>Add City / Town / Market</h2><div className="admin-form-grid"><label>Name<input name="name" required/></label><label>URL Slug<input name="slug" required placeholder="pontiac"/></label><label>Type<select name="type"><option value="city">City</option><option value="town">Town</option><option value="county">County</option><option value="area">Area</option></select></label><label>County<input name="county"/></label><label>State<input name="state" defaultValue="IL"/></label><label>Region<input name="region" defaultValue="Central Illinois"/></label></div><button className="btn btn-primary">Add Location</button></form>;
 if(section==='categories')return <form action={createCategory} className="admin-card"><h2>Add Category</h2><div className="admin-form-grid"><label>Vertical<select name="vertical"><option value="home">Home Services</option><option value="legal">Attorneys / Legal</option><option value="restaurant">Restaurants</option><option value="retail">Local Stores / Retail</option></select></label><label>Category Name<input name="name" required/></label><label>URL Slug<input name="slug" required/></label></div><button className="btn btn-primary">Add Category</button></form>;
 if(section==='content-blocks')return <form action={createContentBlock} className="admin-card"><h2>Add Content Block</h2><div className="admin-form-grid"><label>Page Key<input name="page_key" required placeholder="home"/></label><label>Section Key<input name="section_key" required placeholder="trust"/></label><label>Content Key<input name="content_key" required placeholder="trust-intro"/></label><label>Title<input name="title"/></label><label>Button Label<input name="button_label"/></label><label>Button URL<input name="button_url"/></label><label>Sort Order<input type="number" name="sort_order" defaultValue="100"/></label></div><label>Body<textarea name="body"/></label><button className="btn btn-primary">Add Content Block</button></form>;
 if(section==='guides')return <form action={createGuide} className="admin-card"><h2>Create Local Guide Draft</h2><div className="admin-form-grid"><label>Title<input name="title" required/></label><label>Slug<input name="slug" required/></label><label>Type<input name="type" defaultValue="local_guide"/></label><label>City<input name="city"/></label><label>Category<input name="category"/></label></div><label>Summary<textarea name="summary" required/></label><label>Body<textarea name="body" required style={{minHeight:180}}/></label><button className="btn btn-primary">Create Draft</button></form>;
 if(section==='branches')return <form action={createBranch} className="admin-card"><h2>Add Legitimate Physical Branch</h2><p className="small muted">Do not use this form for a service area. Only add a real physical office/storefront/location.</p><div className="admin-form-grid"><label>Business UUID<input name="business_id" required/></label><label>Label<input name="label" placeholder="Urbana Office"/></label><label>Location Type<select name="location_type"><option>office</option><option>storefront</option><option>restaurant</option><option>shop</option><option>service_center</option></select></label><label>Address<input name="address_text"/></label><label>City<input name="city" required/></label><label>State<input name="state" defaultValue="IL"/></label><label>ZIP<input name="postal_code"/></label><label>Phone<input name="phone"/></label><label>Source Name<input name="source_name"/></label><label>Source URL<input name="source_url"/></label></div><button className="btn btn-primary">Add Branch for Review</button></form>;
 return null
}
