'use client'

import { useMemo, useState } from 'react'

type Option = { id:string;name:string;vertical?:string;county?:string;state?:string;type?:string }
type Portfolio = { introBusinesses:number;viewedBusinesses:number;interestedBusinesses:number;contactedBusinesses:number;agreementReady:number;activeBuyers:number;overdueFollowups:number;targetMonthlyCents:number;collected90dCents:number }
type Row = { id:string;name:string;slug:string;claimed:boolean;phone?:string|null;email?:string|null;stage:string;introSent:number;lastIntroAt?:string|null;lastViewedAt?:string|null;wantsMore:string;interestUpdatedAt?:string|null;contactedAfterInterest:boolean;followUpNeeded:boolean;slaOverdue:boolean;slaDueAt?:string|null;lastLeadAt?:string|null;deliveredThisMonth:number;amountOwed:number;paymentStatus:string;paidRevenue90d:number;targetMonthlyValue:number;activeMonthlyValue:number;crm?:any;draft?:any;categoryIds:string[];locationIds:string[];program?:any }
const money=(c:number)=>`$${(Number(c||0)/100).toFixed(2)}`
const date=(v:any)=>v?new Date(String(v)).toLocaleString():'—'
const local=(v:any)=>{if(!v)return'';const d=new Date(String(v));if(Number.isNaN(d.getTime()))return'';const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
const stageClass=(stage:string)=>stage==='Pay-Per-Lead Active'?'badge verified':stage==='Follow-Up Overdue'?'badge danger':['Agreement Ready','Follow-Up Needed','Contacted'].includes(stage)?'badge sponsored':stage==='Declined'?'badge neutral':'badge'
const pct=(n:number,d:number)=>d?`${Math.round((n/d)*100)}%`:'—'

export function AdminLeadBuyerCRM({rows,categories,locations,portfolio,isSuperAdmin,initialBusinessId,initialStage}:{rows:Row[];categories:Option[];locations:Option[];portfolio:Portfolio;isSuperAdmin:boolean;initialBusinessId?:string;initialStage?:string}){
  const stages=['all','Follow-Up Overdue','Agreement Ready','Follow-Up Needed','Contacted','Agreement Draft','Pay-Per-Lead Active','Viewed','Intro Sent','No Intro Sent','Paused','Declined']
  const initialId=rows.some(r=>r.id===initialBusinessId)?String(initialBusinessId):rows[0]?.id||''
  const [query,setQuery]=useState(''),[stage,setStage]=useState(stages.includes(String(initialStage))?String(initialStage):'all'),[selected,setSelected]=useState(initialId),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
  const active=rows.find(x=>x.id===selected)||rows[0]
  const [edit,setEdit]=useState(()=>crmForm(active)),[agreement,setAgreement]=useState(()=>agreementForm(active))
  const filtered=useMemo(()=>rows.filter(r=>(stage==='all'||r.stage===stage)&&(!query.trim()||`${r.name} ${r.email||''} ${r.phone||''}`.toLowerCase().includes(query.trim().toLowerCase()))),[rows,stage,query])
  const counts=useMemo(()=>Object.fromEntries(stages.slice(1).map(s=>[s,rows.filter(r=>r.stage===s).length])),[rows])
  function choose(r:Row){setSelected(r.id);setEdit(crmForm(r));setAgreement(agreementForm(r));setMessage('')}
  function toggle(id:string,key:'categoryIds'|'locationIds'){setEdit(e=>({...e,[key]:e[key].includes(id)?e[key].filter((x:string)=>x!==id):[...e[key],id]}))}
  async function crmAct(action:'save'|'mark_contacted'|'reopen'){
    if(!active)return;setBusy(action);setMessage('')
    const response=await fetch('/api/admin/lead-buyers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business_id:active.id,sales_status:edit.salesStatus,target_price_cents:edit.targetPrice?Math.round(Number(edit.targetPrice)*100):null,preferred_sale_mode:edit.saleMode,target_monthly_cap:edit.monthlyCap?Number(edit.monthlyCap):null,target_billing_model:edit.billingModel,follow_up_at:edit.followUp?new Date(edit.followUp).toISOString():null,internal_notes:edit.notes,category_ids:edit.categoryIds,location_ids:edit.locationIds})})
    const body=await response.json().catch(()=>({}));setBusy('')
    if(!response.ok){setMessage(String(body.error||'Unable to update Lead Buyer CRM.'));return}
    setMessage(action==='mark_contacted'?'Contact recorded. No billing or routing was activated.':action==='reopen'?'Buyer opportunity reopened. No billing or routing was activated.':'Buyer preferences saved. No billing or routing was activated.')
    window.location.reload()
  }
  async function agreementAct(action:'save_agreement_draft'|'ready_agreement'|'decline_agreement'|'activate_agreement'){
    if(!active)return;setBusy(action);setMessage('')
    const payload=action==='activate_agreement'?{action,draft_id:active.draft?.id}:{action,business_id:active.id,featured_addon_enabled:agreement.addon,billing_model:agreement.billingModel,per_lead_price_cents:agreement.billingModel==='pay_per_lead'&&agreement.perLead?Math.round(Number(agreement.perLead)*100):null,bundle_lead_count:agreement.billingModel==='lead_bundle'&&agreement.bundleCount?Number(agreement.bundleCount):null,bundle_price_cents:agreement.billingModel==='lead_bundle'&&agreement.bundlePrice?Math.round(Number(agreement.bundlePrice)*100):null,due_days:Number(agreement.dueDays||7),billing_email:agreement.billingEmail||null,agreement_started_on:agreement.startOn||null,agreement_ends_on:agreement.endOn||null,max_leads_per_month:agreement.monthlyCap?Number(agreement.monthlyCap):null,lead_sale_mode:agreement.saleMode,max_buyers_per_lead:agreement.saleMode==='shared'?Number(agreement.maxBuyers||2):1,consent_recorded_at:agreement.consentAt?new Date(agreement.consentAt).toISOString():null,consent_source:agreement.consentSource||null,consent_reference:agreement.consentReference||null,owner_summary:agreement.ownerSummary,internal_notes:agreement.internalNotes}
    const response=await fetch('/api/admin/lead-buyer-agreements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})
    const body=await response.json().catch(()=>({}));setBusy('')
    if(!response.ok){setMessage(String(body.error||'Unable to update agreement draft.'));return}
    setMessage(action==='activate_agreement'?'Agreement activated as the authoritative Lead Buyer program. No lead was delivered and no charge was created.':action==='ready_agreement'?'Agreement is ready for explicit Super Admin review. No billing or routing was activated.':action==='decline_agreement'?'Agreement draft closed as declined.':'Agreement draft saved. No billing or routing was activated.')
    window.location.reload()
  }
  if(!rows.length)return <div className="admin-card"><h2>No published businesses yet</h2><p className="muted">Lead Buyer intelligence will populate as directory businesses become publishable.</p></div>
  return <>
    <div className="stat-grid" style={{marginBottom:18}}><div className="stat">Overdue Follow-Up<strong>{portfolio.overdueFollowups}</strong></div><div className="stat">Interested Buyers<strong>{portfolio.interestedBusinesses}</strong></div><div className="stat">Contacted<strong>{portfolio.contactedBusinesses}</strong></div><div className="stat">Ready for Review<strong>{portfolio.agreementReady}</strong></div><div className="stat">Active Buyers<strong>{portfolio.activeBuyers}</strong></div><div className="stat">Monthly Buyer Value<strong>{money(portfolio.targetMonthlyCents)}</strong></div><div className="stat">90-Day Collected<strong>{money(portfolio.collected90dCents)}</strong></div></div>
    <div className="admin-card" style={{marginBottom:18}}><div className="section-head compact-head"><div><div className="kpi">Conversion Funnel</div><h2>Intro Lead → Paying Lead Buyer</h2><p className="small muted">Conversion metrics measure the internal sales journey only. They never change verification, public ranking, Sponsored placement or consumer lead routing.</p></div><span className="badge verified">Trust-safe revenue intelligence</span></div><div className="grid grid-3" style={{marginTop:12}}><Funnel label="Intro recipients" value={portfolio.introBusinesses} rate="Baseline"/><Funnel label="Viewed Intro Lead" value={portfolio.viewedBusinesses} rate={`${pct(portfolio.viewedBusinesses,portfolio.introBusinesses)} of intro`}/><Funnel label="Asked for more" value={portfolio.interestedBusinesses} rate={`${pct(portfolio.interestedBusinesses,portfolio.introBusinesses)} of intro`}/><Funnel label="Admin contacted" value={portfolio.contactedBusinesses} rate={`${pct(portfolio.contactedBusinesses,portfolio.interestedBusinesses)} of interested`}/><Funnel label="Agreement ready" value={portfolio.agreementReady} rate={`${pct(portfolio.agreementReady,portfolio.contactedBusinesses)} of contacted`}/><Funnel label="Active program" value={portfolio.activeBuyers} rate={`${pct(portfolio.activeBuyers,Math.max(1,portfolio.interestedBusinesses))} of interested`}/></div></div>
    <div className="admin-card" style={{marginBottom:18}}><div className="section-head compact-head"><div><div className="kpi">Operating Guardrails</div><h2>Interest never equals enrollment</h2></div><span className="badge verified">Admin-first</span></div><p className="muted">A business clicking “Yes — Send Me More Leads” creates a sales opportunity only. Admin documents terms and consent; Super Admin performs the final activation. Draft, Ready and Activated states do not deliver a lead or create a charge. Every future consumer lead still requires deliberate Admin routing.</p><div className="actions"><a className="btn secondary" href="/admin/leads">Review / Send Intro Leads</a><a className="btn secondary" href="/admin/revenue-intelligence">Revenue Intelligence</a><a className="btn secondary" href="/admin/lead-billing">Active Lead Billing</a></div></div>
    <div className="grid grid-2" style={{alignItems:'start'}}>
      <div className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Lead Buyer Pipeline</div><h2>Businesses</h2></div><span className="badge neutral">{filtered.length} shown</span></div><div className="form-grid"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business, email or phone" /></label><label>Pipeline stage<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(s=><option key={s} value={s}>{s==='all'?'All stages':`${s} (${counts[s]||0})`}</option>)}</select></label></div><div style={{display:'grid',gap:10,marginTop:14}}>{filtered.map(r=><button type="button" key={r.id} onClick={()=>choose(r)} className="admin-card" style={{textAlign:'left',cursor:'pointer',border:r.id===active?.id?'2px solid currentColor':undefined}}><div className="info-row"><strong>{r.name}</strong><span className={stageClass(r.stage)}>{r.stage}</span></div><div className="small muted">{r.introSent} intro · last viewed {date(r.lastViewedAt)} · wants more: {r.wantsMore.replaceAll('_',' ')}</div>{r.slaDueAt?<div className="small"><strong>{r.slaOverdue?'SLA overdue':'Next action due'}</strong> · {date(r.slaDueAt)}</div>:null}</button>)}{!filtered.length?<p className="muted">No businesses match this view.</p>:null}</div></div>
      {active?<div style={{display:'grid',gap:18}}><div className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Buyer Record</div><h2>{active.name}</h2></div><span className={stageClass(active.stage)}>{active.stage}</span></div>
        <div className="grid grid-2"><div><div className="info-row"><span>Claimed</span><strong>{active.claimed?'Yes':'No'}</strong></div><div className="info-row"><span>Intro leads sent</span><strong>{active.introSent}</strong></div><div className="info-row"><span>Last intro</span><strong>{date(active.lastIntroAt)}</strong></div><div className="info-row"><span>Owner interest</span><strong>{date(active.interestUpdatedAt)}</strong></div><div className="info-row"><span>24h / follow-up SLA</span><strong>{date(active.slaDueAt)}</strong></div></div><div><div className="info-row"><span>Paid leads this month</span><strong>{active.deliveredThisMonth}</strong></div><div className="info-row"><span>90-day collected</span><strong>{money(active.paidRevenue90d)}</strong></div><div className="info-row"><span>Amount owed</span><strong>{money(active.amountOwed)}</strong></div><div className="info-row"><span>Payment status</span><strong>{active.paymentStatus}</strong></div><div className="info-row"><span>Last Admin contact</span><strong>{date(active.crm?.last_contact_at)}</strong></div></div></div>
        {active.slaOverdue?<div className="notice warn"><strong>Follow-up SLA overdue.</strong> Record contact or schedule the next follow-up. This operational alert does not activate billing or future lead delivery.</div>:null}
        {active.program?<div className="admin-card" style={{marginTop:14}}><div className="kpi">Final Agreement · Authoritative Source</div><div className="info-row"><span>Status</span><strong>{active.program.status}</strong></div><div className="info-row"><span>Billing</span><strong>{active.program.billing_model==='pay_per_lead'?`${money(active.program.per_lead_price_cents)}/lead`:`${active.program.bundle_lead_count||0} leads / ${money(active.program.bundle_price_cents)}`}</strong></div><div className="info-row"><span>Delivery</span><strong>{active.program.lead_sale_mode}{active.program.lead_sale_mode==='shared'?` · max ${active.program.max_buyers_per_lead}`:''}</strong></div><div className="info-row"><span>Monthly cap</span><strong>{active.program.max_leads_per_month||'No cap'}</strong></div><div className="info-row"><span>Agreement</span><strong>{active.program.agreement_started_on||'—'} → {active.program.agreement_ends_on||'Open-ended'}</strong></div></div>:null}
        <div className="form-grid" style={{marginTop:16}}><label>Sales status<select value={edit.salesStatus} onChange={e=>setEdit({...edit,salesStatus:e.target.value})}><option value="open">Open</option><option value="paused">Paused</option><option value="declined">Declined</option></select></label><label>Target price per lead ($)<input type="number" min="1" step="0.01" value={edit.targetPrice} onChange={e=>setEdit({...edit,targetPrice:e.target.value})} placeholder="Negotiation only" /></label><label>Preferred delivery<select value={edit.saleMode} onChange={e=>setEdit({...edit,saleMode:e.target.value})}><option value="either">Either</option><option value="exclusive">Exclusive</option><option value="shared">Shared</option></select></label><label>Target monthly cap<input type="number" min="1" value={edit.monthlyCap} onChange={e=>setEdit({...edit,monthlyCap:e.target.value})} placeholder="Optional" /></label><label>Target billing model<select value={edit.billingModel} onChange={e=>setEdit({...edit,billingModel:e.target.value})}><option value="undecided">Undecided</option><option value="pay_per_lead">Pay per lead</option><option value="lead_bundle">Lead bundle</option></select></label><label>Next follow-up<input type="datetime-local" value={edit.followUp} onChange={e=>setEdit({...edit,followUp:e.target.value})} /></label></div>
        <div className="grid grid-2" style={{marginTop:14}}><div><div className="kpi">Wanted Categories</div><div style={{maxHeight:180,overflow:'auto',display:'grid',gap:6,marginTop:8}}>{categories.map(c=><label key={c.id} className="small"><input type="checkbox" checked={edit.categoryIds.includes(c.id)} onChange={()=>toggle(c.id,'categoryIds')} /> {c.name}{c.vertical?` · ${c.vertical}`:''}</label>)}</div></div><div><div className="kpi">Wanted Service Areas</div><div style={{maxHeight:180,overflow:'auto',display:'grid',gap:6,marginTop:8}}>{locations.map(l=><label key={l.id} className="small"><input type="checkbox" checked={edit.locationIds.includes(l.id)} onChange={()=>toggle(l.id,'locationIds')} /> {l.name}{l.county?` · ${l.county} County`:''}</label>)}</div></div></div>
        <label style={{display:'grid',gap:6,marginTop:14}}>Internal sales notes<textarea rows={5} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="Negotiation notes, contact history, objections, next steps. Admin only." /></label>
        <div className="actions" style={{marginTop:14}}><button className="btn primary" disabled={Boolean(busy)} onClick={()=>void crmAct('save')}>{busy==='save'?'Saving…':'Save Buyer CRM'}</button><button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void crmAct('mark_contacted')}>Mark Contacted</button><button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void crmAct('reopen')}>Reopen Opportunity</button></div><p className="small muted">CRM controls are pre-agreement only. They cannot create invoices, paid programs, verification, Sponsored placement, subscriptions or automatic delivery.</p></div>

        <div className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Controlled Agreement Workspace</div><h2>{active.draft?.status==='activated'?'Activated agreement record':'Prepare terms without activating billing'}</h2></div><span className={`badge ${active.draft?.status==='activated'?'verified':active.draft?.status==='ready_for_review'?'sponsored':'neutral'}`}>{active.draft?.status?.replaceAll('_',' ')||'no draft'}</span></div>
          <p className="small muted">Internal notes stay Admin-only. The owner-facing summary is the only narrative copied to the authoritative program on activation.</p>
          <div className="form-grid"><label>Billing model<select disabled={active.draft?.status==='activated'} value={agreement.billingModel} onChange={e=>setAgreement({...agreement,billingModel:e.target.value})}><option value="pay_per_lead">Pay per delivered lead</option><option value="lead_bundle">Lead bundle</option></select></label>{agreement.billingModel==='pay_per_lead'?<label>Price / delivered lead ($)<input disabled={active.draft?.status==='activated'} type="number" min="1" step="0.01" value={agreement.perLead} onChange={e=>setAgreement({...agreement,perLead:e.target.value})}/></label>:<><label>Leads / bundle<input disabled={active.draft?.status==='activated'} type="number" min="1" value={agreement.bundleCount} onChange={e=>setAgreement({...agreement,bundleCount:e.target.value})}/></label><label>Bundle price ($)<input disabled={active.draft?.status==='activated'} type="number" min="1" step="0.01" value={agreement.bundlePrice} onChange={e=>setAgreement({...agreement,bundlePrice:e.target.value})}/></label></>}
          <label>Sale mode<select disabled={active.draft?.status==='activated'} value={agreement.saleMode} onChange={e=>setAgreement({...agreement,saleMode:e.target.value})}><option value="exclusive">Exclusive</option><option value="shared">Shared</option></select></label>{agreement.saleMode==='shared'?<label>Maximum buyers / lead<input disabled={active.draft?.status==='activated'} type="number" min="2" max="10" value={agreement.maxBuyers} onChange={e=>setAgreement({...agreement,maxBuyers:e.target.value})}/></label>:null}<label>Monthly lead cap<input disabled={active.draft?.status==='activated'} type="number" min="1" value={agreement.monthlyCap} onChange={e=>setAgreement({...agreement,monthlyCap:e.target.value})} placeholder="Optional"/></label><label>Invoice due days<input disabled={active.draft?.status==='activated'} type="number" min="0" max="90" value={agreement.dueDays} onChange={e=>setAgreement({...agreement,dueDays:e.target.value})}/></label><label>Billing email<input disabled={active.draft?.status==='activated'} type="email" value={agreement.billingEmail} onChange={e=>setAgreement({...agreement,billingEmail:e.target.value})}/></label><label>Agreement start<input disabled={active.draft?.status==='activated'} type="date" value={agreement.startOn} onChange={e=>setAgreement({...agreement,startOn:e.target.value})}/></label><label>Agreement end<input disabled={active.draft?.status==='activated'} type="date" value={agreement.endOn} onChange={e=>setAgreement({...agreement,endOn:e.target.value})}/></label><label className="check"><input disabled={active.draft?.status==='activated'} type="checkbox" checked={agreement.addon} onChange={e=>setAgreement({...agreement,addon:e.target.checked})}/> Featured Lead Inbox add-on included in negotiated terms</label></div>
          <div className="admin-card" style={{marginTop:14}}><div className="kpi">Documented Buyer Consent</div><p className="small muted">Required before Ready for Review. Record when and where the buyer expressly accepted the proposed paid-lead terms.</p><div className="form-grid"><label>Consent recorded at<input disabled={active.draft?.status==='activated'} type="datetime-local" value={agreement.consentAt} onChange={e=>setAgreement({...agreement,consentAt:e.target.value})}/></label><label>Consent source<select disabled={active.draft?.status==='activated'} value={agreement.consentSource} onChange={e=>setAgreement({...agreement,consentSource:e.target.value})}><option value="">Choose…</option><option value="email">Email</option><option value="phone">Phone</option><option value="signed_agreement">Signed agreement</option><option value="in_person">In person</option><option value="other">Other documented source</option></select></label><label className="full-row">Consent reference<input disabled={active.draft?.status==='activated'} value={agreement.consentReference} onChange={e=>setAgreement({...agreement,consentReference:e.target.value})} placeholder="Email thread, signed document ID, call note reference…"/></label></div></div>
          <label style={{display:'grid',gap:6,marginTop:14}}>Owner-facing agreement summary<textarea disabled={active.draft?.status==='activated'} rows={5} value={agreement.ownerSummary} onChange={e=>setAgreement({...agreement,ownerSummary:e.target.value})} placeholder="Plain-language pricing, cap, lead type and delivery terms the buyer agreed to."/></label><label style={{display:'grid',gap:6,marginTop:14}}>Admin-only agreement notes<textarea disabled={active.draft?.status==='activated'} rows={5} value={agreement.internalNotes} onChange={e=>setAgreement({...agreement,internalNotes:e.target.value})} placeholder="Negotiation history, exceptions and internal review notes. Never copied to owner-readable program data."/></label>
          {active.draft?.status!=='activated'?<><div className="actions" style={{marginTop:14}}><button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void agreementAct('save_agreement_draft')}>{busy==='save_agreement_draft'?'Saving…':'Save Draft'}</button><button className="btn primary" disabled={Boolean(busy)} onClick={()=>void agreementAct('ready_agreement')}>{busy==='ready_agreement'?'Submitting…':'Mark Ready for Review'}</button>{active.draft?<button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void agreementAct('decline_agreement')}>Close as Declined</button>:null}</div>{active.draft?.status==='ready_for_review'?<div className="notice warn" style={{marginTop:14}}><strong>Final activation gate.</strong> Ready for Review still means zero billing authorization in the system. {isSuperAdmin?'As Super Admin, you may activate the reviewed terms below.':'A Super Admin must perform the explicit final activation.'}{isSuperAdmin?<div className="actions" style={{marginTop:10}}><button className="btn primary" disabled={Boolean(busy)} onClick={()=>void agreementAct('activate_agreement')}>{busy==='activate_agreement'?'Activating…':'Activate Reviewed Agreement'}</button></div>:null}</div>:null}</>:<div className="notice success"><strong>Activated safely.</strong> `business_lead_programs` is now the source of truth. Activation itself delivered no lead and created no charge.</div>}
        </div>
        {message?<div className={`notice ${message.includes('Unable')?'warn':'success'}`}>{message}</div>:null}
      </div>:null}
    </div>
  </>
}

function Funnel({label,value,rate}:{label:string;value:number;rate:string}){return <div className="admin-card"><div className="kpi">{label}</div><h2>{value}</h2><p className="small muted">{rate}</p></div>}
function crmForm(r?:Row){return{salesStatus:r?.crm?.sales_status||'open',targetPrice:r?.crm?.target_price_cents?String(Number(r.crm.target_price_cents)/100):'',saleMode:r?.crm?.preferred_sale_mode||'either',monthlyCap:r?.crm?.target_monthly_cap?String(r.crm.target_monthly_cap):'',billingModel:r?.crm?.target_billing_model||'undecided',followUp:local(r?.crm?.follow_up_at),notes:r?.crm?.internal_notes||'',categoryIds:[...(r?.categoryIds||[])],locationIds:[...(r?.locationIds||[])]}}
function agreementForm(r?:Row){const d=r?.draft||{},crm=r?.crm||{},program=r?.program||{},model=d.billing_model||((crm.target_billing_model&&crm.target_billing_model!=='undecided')?crm.target_billing_model:'pay_per_lead'),sale=d.lead_sale_mode||((crm.preferred_sale_mode&&crm.preferred_sale_mode!=='either')?crm.preferred_sale_mode:'exclusive');return{addon:Boolean(d.featured_addon_enabled),billingModel:model,perLead:d.per_lead_price_cents?String(Number(d.per_lead_price_cents)/100):(crm.target_price_cents?String(Number(crm.target_price_cents)/100):''),bundleCount:String(d.bundle_lead_count||10),bundlePrice:d.bundle_price_cents?String(Number(d.bundle_price_cents)/100):'',dueDays:String(d.due_days??7),billingEmail:d.billing_email||program.billing_email||r?.email||'',startOn:d.agreement_started_on||'',endOn:d.agreement_ends_on||'',monthlyCap:d.max_leads_per_month?String(d.max_leads_per_month):(crm.target_monthly_cap?String(crm.target_monthly_cap):''),saleMode:sale,maxBuyers:String(d.max_buyers_per_lead||2),consentAt:local(d.consent_recorded_at),consentSource:d.consent_source||'',consentReference:d.consent_reference||'',ownerSummary:d.owner_summary||'',internalNotes:d.internal_notes||''}}
