'use client'

import { useMemo, useState } from 'react'

type Option = { id: string; name: string; vertical?: string; county?: string; state?: string; type?: string }
type Row = { id:string;name:string;slug:string;claimed:boolean;phone?:string|null;email?:string|null;stage:string;introSent:number;lastIntroAt?:string|null;lastViewedAt?:string|null;wantsMore:string;interestUpdatedAt?:string|null;followUpNeeded:boolean;lastLeadAt?:string|null;deliveredThisMonth:number;amountOwed:number;paymentStatus:string;crm?:any;categoryIds:string[];locationIds:string[];program?:any }
const money=(c:number)=>`$${(Number(c||0)/100).toFixed(2)}`
const date=(v:any)=>v?new Date(String(v)).toLocaleString():'—'
const local=(v:any)=>{if(!v)return'';const d=new Date(String(v));if(Number.isNaN(d.getTime()))return'';const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
const stageClass=(stage:string)=>stage==='Pay-Per-Lead Active'?'badge verified':stage==='Follow-Up Needed'||stage==='Interested'?'badge sponsored':stage==='Declined'?'badge neutral':'badge'

export function AdminLeadBuyerCRM({rows,categories,locations}:{rows:Row[];categories:Option[];locations:Option[]}){
  const [query,setQuery]=useState(''),[stage,setStage]=useState('all'),[selected,setSelected]=useState(rows[0]?.id||''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
  const active=rows.find(x=>x.id===selected)||rows[0]
  const [edit,setEdit]=useState(()=>form(active))
  const stages=['all','Follow-Up Needed','Interested','Pay-Per-Lead Active','Viewed','Intro Sent','No Intro Sent','Paused','Declined']
  const filtered=useMemo(()=>rows.filter(r=>(stage==='all'||r.stage===stage)&&(!query.trim()||`${r.name} ${r.email||''} ${r.phone||''}`.toLowerCase().includes(query.trim().toLowerCase()))),[rows,stage,query])
  const counts=useMemo(()=>Object.fromEntries(stages.slice(1).map(s=>[s,rows.filter(r=>r.stage===s).length])),[rows])
  function choose(r:Row){setSelected(r.id);setEdit(form(r));setMessage('')}
  function toggle(id:string,key:'categoryIds'|'locationIds'){setEdit(e=>({...e,[key]:e[key].includes(id)?e[key].filter((x:string)=>x!==id):[...e[key],id]}))}
  async function act(action:'save'|'mark_contacted'|'reopen'){
    if(!active)return;setBusy(action);setMessage('')
    const response=await fetch('/api/admin/lead-buyers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,business_id:active.id,sales_status:edit.salesStatus,target_price_cents:edit.targetPrice?Math.round(Number(edit.targetPrice)*100):null,preferred_sale_mode:edit.saleMode,target_monthly_cap:edit.monthlyCap?Number(edit.monthlyCap):null,target_billing_model:edit.billingModel,follow_up_at:edit.followUp||null,internal_notes:edit.notes,category_ids:edit.categoryIds,location_ids:edit.locationIds})})
    const body=await response.json().catch(()=>({}));setBusy('')
    if(!response.ok){setMessage(String(body.error||'Unable to update Lead Buyer CRM.'));return}
    setMessage(action==='mark_contacted'?'Follow-up contact recorded. No billing or routing was activated.':action==='reopen'?'Buyer opportunity reopened. No billing or routing was activated.':'Lead buyer preferences saved. No billing or routing was activated.')
    window.location.reload()
  }
  if(!rows.length)return <div className="admin-card"><h2>No published businesses yet</h2><p className="muted">Lead Buyer CRM will populate as directory businesses become publishable.</p></div>
  return <>
    <div className="stat-grid" style={{marginBottom:18}}><div className="stat">Follow-Up Needed<strong>{counts['Follow-Up Needed']||0}</strong></div><div className="stat">Interested<strong>{counts.Interested||0}</strong></div><div className="stat">Active Buyers<strong>{counts['Pay-Per-Lead Active']||0}</strong></div><div className="stat">Intro Leads Sent<strong>{rows.reduce((n,r)=>n+r.introSent,0)}</strong></div><div className="stat">Outstanding<strong>{money(rows.reduce((n,r)=>n+r.amountOwed,0))}</strong></div></div>
    <div className="admin-card" style={{marginBottom:18}}><div className="section-head compact-head"><div><div className="kpi">Conversion Rules</div><h2>Interest never equals enrollment</h2></div><span className="badge verified">Trust-safe</span></div><p className="muted">A business clicking “Yes, Send Me More Leads” moves into this follow-up queue only. Admin still finalizes pricing, terms, caps and activation in Lead Revenue CRM. Intro Leads remain no-charge and sponsored/paid status never changes verification or organic rank.</p><div className="actions"><a className="btn secondary" href="/admin/leads">Review / Send Intro Leads</a><a className="btn primary" href="/admin/lead-billing">Finalize Pay-Per-Lead Agreement</a></div></div>
    <div className="grid grid-2" style={{alignItems:'start'}}>
      <div className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Lead Buyer Pipeline</div><h2>Businesses</h2></div><span className="badge neutral">{filtered.length} shown</span></div><div className="form-grid"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business, email or phone" /></label><label>Pipeline stage<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(s=><option key={s} value={s}>{s==='all'?'All stages':`${s} (${counts[s]||0})`}</option>)}</select></label></div><div style={{display:'grid',gap:10,marginTop:14}}>{filtered.map(r=><button type="button" key={r.id} onClick={()=>choose(r)} className="admin-card" style={{textAlign:'left',cursor:'pointer',border:r.id===active?.id?'2px solid currentColor':undefined}}><div className="info-row"><strong>{r.name}</strong><span className={stageClass(r.stage)}>{r.stage}</span></div><div className="small muted">{r.introSent} intro · last viewed {date(r.lastViewedAt)} · wants more: {r.wantsMore.replace('_',' ')}</div>{r.followUpNeeded?<div className="small"><strong>Follow-up required</strong> · owner interest is newer than Admin contact or follow-up is due.</div>:null}</button>)}{!filtered.length?<p className="muted">No businesses match this view.</p>:null}</div></div>
      {active?<div className="admin-card"><div className="section-head compact-head"><div><div className="kpi">Buyer Record</div><h2>{active.name}</h2></div><span className={stageClass(active.stage)}>{active.stage}</span></div>
        <div className="grid grid-2"><div><div className="info-row"><span>Claimed</span><strong>{active.claimed?'Yes':'No'}</strong></div><div className="info-row"><span>Intro leads sent</span><strong>{active.introSent}</strong></div><div className="info-row"><span>Last intro</span><strong>{date(active.lastIntroAt)}</strong></div><div className="info-row"><span>Last viewed</span><strong>{date(active.lastViewedAt)}</strong></div><div className="info-row"><span>Wants more</span><strong>{active.wantsMore.replace('_',' ')}</strong></div></div><div><div className="info-row"><span>Paid leads this month</span><strong>{active.deliveredThisMonth}</strong></div><div className="info-row"><span>Amount owed</span><strong>{money(active.amountOwed)}</strong></div><div className="info-row"><span>Payment status</span><strong>{active.paymentStatus}</strong></div><div className="info-row"><span>Last lead date</span><strong>{date(active.lastLeadAt)}</strong></div><div className="info-row"><span>Last Admin contact</span><strong>{date(active.crm?.last_contact_at)}</strong></div></div></div>
        {active.program?<div className="admin-card" style={{marginTop:14}}><div className="kpi">Final Agreement · Source of Truth</div><div className="info-row"><span>Status</span><strong>{active.program.status}</strong></div><div className="info-row"><span>Billing</span><strong>{active.program.billing_model==='pay_per_lead'?`${money(active.program.per_lead_price_cents)}/lead`:`${active.program.bundle_lead_count||0} leads / ${money(active.program.bundle_price_cents)}`}</strong></div><div className="info-row"><span>Delivery</span><strong>{active.program.lead_sale_mode}{active.program.lead_sale_mode==='shared'?` · max ${active.program.max_buyers_per_lead}`:''}</strong></div><div className="info-row"><span>Monthly cap</span><strong>{active.program.max_leads_per_month||'No cap'}</strong></div><div className="info-row"><span>Agreement</span><strong>{active.program.agreement_started_on||'—'} → {active.program.agreement_ends_on||'Open-ended'}</strong></div>{active.program.manual_delivery_hold?<p className="small"><strong>Delivery hold:</strong> {active.program.delivery_hold_reason||'Manual Admin hold'}</p>:null}</div>:null}
        <div className="form-grid" style={{marginTop:16}}><label>Sales status<select value={edit.salesStatus} onChange={e=>setEdit({...edit,salesStatus:e.target.value})}><option value="open">Open</option><option value="paused">Paused</option><option value="declined">Declined</option></select></label><label>Target price per lead ($)<input type="number" min="1" step="0.01" value={edit.targetPrice} onChange={e=>setEdit({...edit,targetPrice:e.target.value})} placeholder="Negotiation only" /></label><label>Preferred delivery<select value={edit.saleMode} onChange={e=>setEdit({...edit,saleMode:e.target.value})}><option value="either">Either</option><option value="exclusive">Exclusive</option><option value="shared">Shared</option></select></label><label>Target monthly cap<input type="number" min="1" value={edit.monthlyCap} onChange={e=>setEdit({...edit,monthlyCap:e.target.value})} placeholder="Optional" /></label><label>Target billing model<select value={edit.billingModel} onChange={e=>setEdit({...edit,billingModel:e.target.value})}><option value="undecided">Undecided</option><option value="pay_per_lead">Pay per lead</option><option value="lead_bundle">Lead bundle</option></select></label><label>Next follow-up<input type="datetime-local" value={edit.followUp} onChange={e=>setEdit({...edit,followUp:e.target.value})} /></label></div>
        <div className="grid grid-2" style={{marginTop:14}}><div><div className="kpi">Wanted Categories</div><div style={{maxHeight:220,overflow:'auto',display:'grid',gap:6,marginTop:8}}>{categories.map(c=><label key={c.id} className="small"><input type="checkbox" checked={edit.categoryIds.includes(c.id)} onChange={()=>toggle(c.id,'categoryIds')} /> {c.name}{c.vertical?` · ${c.vertical}`:''}</label>)}</div></div><div><div className="kpi">Wanted Service Areas</div><div style={{maxHeight:220,overflow:'auto',display:'grid',gap:6,marginTop:8}}>{locations.map(l=><label key={l.id} className="small"><input type="checkbox" checked={edit.locationIds.includes(l.id)} onChange={()=>toggle(l.id,'locationIds')} /> {l.name}{l.county?` · ${l.county} County`:''}</label>)}</div></div></div>
        <label style={{display:'grid',gap:6,marginTop:14}}>Internal sales notes<textarea rows={6} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="Negotiation notes, contact history, objections, next steps. Admin only." /></label>
        {message?<p className="small">{message}</p>:null}<div className="actions" style={{marginTop:14}}><button className="btn primary" disabled={Boolean(busy)} onClick={()=>void act('save')}>{busy==='save'?'Saving…':'Save Buyer CRM'}</button><button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void act('mark_contacted')}>Mark Contacted</button><button className="btn secondary" disabled={Boolean(busy)} onClick={()=>void act('reopen')}>Reopen Opportunity</button></div><p className="small muted">These controls are pre-agreement CRM only. They cannot create an invoice, paid program, verification badge, subscription, sponsored placement, or automatic future lead delivery.</p>
      </div>:null}
    </div>
  </>
}

function form(r?:Row){return{salesStatus:r?.crm?.sales_status||'open',targetPrice:r?.crm?.target_price_cents?String(Number(r.crm.target_price_cents)/100):'',saleMode:r?.crm?.preferred_sale_mode||'either',monthlyCap:r?.crm?.target_monthly_cap?String(r.crm.target_monthly_cap):'',billingModel:r?.crm?.target_billing_model||'undecided',followUp:local(r?.crm?.follow_up_at),notes:r?.crm?.internal_notes||'',categoryIds:[...(r?.categoryIds||[])],locationIds:[...(r?.locationIds||[])]}}
