'use client'
import{FormEvent,useState}from'react'
import Link from'next/link'

type Props={businessId:string;businessName:string;service:string;city:string;isPro:boolean}
type Msg={kind:'idle'|'busy'|'ok'|'error';text:string}
const initial:Msg={kind:'idle',text:''}
async function jsonPost(url:string,payload:any){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(body.error||'Unable to submit.'));return body}
export function BusinessCommunityActions({businessId,businessName,service,city,isPro}:Props){
 const[rec,setRec]=useState<Msg>(initial),[q,setQ]=useState<Msg>(initial),[appt,setAppt]=useState<Msg>(initial)
 async function recommendation(e:FormEvent<HTMLFormElement>){e.preventDefault();setRec({kind:'busy',text:'Submitting for moderation…'});const fd=new FormData(e.currentTarget);try{await jsonPost('/api/account/local-commerce',{action:'recommendation',business_id:businessId,service:String(fd.get('service')||service),city:String(fd.get('city')||city),body:String(fd.get('body')||''),service_date:String(fd.get('service_date')||'')||null});setRec({kind:'ok',text:'Thanks. Your Local Favorite recommendation is pending staff moderation before it appears publicly.'});e.currentTarget.reset()}catch(err){setRec({kind:'error',text:err instanceof Error?err.message:'Unable to submit.'})}}
 async function question(e:FormEvent<HTMLFormElement>){e.preventDefault();setQ({kind:'busy',text:'Submitting question…'});const fd=new FormData(e.currentTarget);try{await jsonPost('/api/account/local-commerce',{action:'question',business_id:businessId,question:String(fd.get('question')||'')});setQ({kind:'ok',text:'Question submitted. The business may answer it, and staff reviews the answer before public publication.'});e.currentTarget.reset()}catch(err){setQ({kind:'error',text:err instanceof Error?err.message:'Unable to submit.'})}}
 async function appointment(e:FormEvent<HTMLFormElement>){e.preventDefault();setAppt({kind:'busy',text:'Sending to Admin review…'});const fd=new FormData(e.currentTarget);try{await jsonPost('/api/business/appointment-request',{business_id:businessId,service:String(fd.get('service')||service),city:String(fd.get('city')||city),name:String(fd.get('name')||''),phone:String(fd.get('phone')||''),email:String(fd.get('email')||''),requested_at:String(fd.get('requested_at')||''),alternate_at:String(fd.get('alternate_at')||'')||null,message:String(fd.get('message')||''),consent:fd.get('consent')==='on'});setAppt({kind:'ok',text:'Appointment preference received. It is in the private Admin lead queue first; the business sees it only if staff deliberately delivers the request.'});e.currentTarget.reset()}catch(err){setAppt({kind:'error',text:err instanceof Error?err.message:'Unable to submit.'})}}
 return <div className="grid grid-2">
  <form className="form-card" onSubmit={recommendation}><div className="kpi">Local Faves</div><h3>Recommend {businessName}</h3><p className="small muted">Signed-in customers can submit one recommendation per business. Recommendations are moderated and cannot be purchased.</p><label>Service / reason<input name="service" defaultValue={service} maxLength={120}/></label><label>City<input name="city" defaultValue={city} maxLength={100}/></label><label>Approx. service date<input name="service_date" type="date"/></label><label>Why do you recommend them?<textarea name="body" required minLength={10} maxLength={1200}/></label><button className="btn btn-light full" disabled={rec.kind==='busy'}>{rec.kind==='busy'?'Submitting…':'Recommend This Business'}</button>{rec.text&&<div className={rec.kind==='error'?'form-status error':'form-status success'}>{rec.text}{rec.kind==='error'&&rec.text.toLowerCase().includes('sign in')?<><br/><Link href="/login">Sign in →</Link></>:null}</div>}</form>
  <form className="form-card" onSubmit={question}><div className="kpi">Ask a Local Pro</div><h3>Ask {businessName} a general question</h3><p className="small muted">Questions and business answers are reviewed before publication. Do not submit legal strategy, medical, financial-account, payment-card or other highly sensitive information.</p><label>Your question<textarea name="question" required minLength={8} maxLength={1200} placeholder={`Ask a general question about ${service||'their services'}…`}/></label><button className="btn btn-light full" disabled={q.kind==='busy'}>{q.kind==='busy'?'Submitting…':'Submit Question'}</button>{q.text&&<div className={q.kind==='error'?'form-status error':'form-status success'}>{q.text}</div>}</form>
  {isPro&&<form className="form-card" onSubmit={appointment} style={{gridColumn:'1 / -1'}}><div className="kpi">Appointment Request · Pro</div><h3>Request a preferred time with {businessName}</h3><p className="small muted">This is still an Admin-first lead request. Selecting a time does not reserve an appointment and does not bypass staff review.</p><div className="form-grid"><label>Service<input name="service" defaultValue={service} required maxLength={120}/></label><label>City<input name="city" defaultValue={city} required maxLength={100}/></label><label>Preferred date & time<input name="requested_at" type="datetime-local" required/></label><label>Alternate time<input name="alternate_at" type="datetime-local"/></label><label>Name<input name="name" required maxLength={120}/></label><label>Phone<input name="phone" type="tel" required maxLength={40}/></label><label>Email<input name="email" type="email" required maxLength={160}/></label><label className="full-row">Notes<textarea name="message" maxLength={1600}/></label></div><label className="check"><input name="consent" type="checkbox" required/> I agree that Central Illinois Local Pros / Skylight Reflections Marketing may contact me about this request and, after staff review, may share it with this selected business.</label><button className="btn btn-primary full" disabled={appt.kind==='busy'}>{appt.kind==='busy'?'Submitting…':'Request Preferred Appointment Time'}</button>{appt.text&&<div className={appt.kind==='error'?'form-status error':'form-status success'}>{appt.text}</div>}</form>}
 </div>
}
