'use client'

import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'

type Row=Record<string,any>
const money=(c:any)=>`$${(Number(c||0)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`
const date=(v:any)=>v?new Date(String(v)).toLocaleDateString():'—'
const title=(v:any)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())
const tone=(status:string)=>status==='healthy'?'verified':status==='attention'||status==='critical'?'warn':''

export function BusinessVisibilityClientHealthPanel({business,client,currentHealth,healthSnapshots,review,retentionEvents,currentUserId}:{business:{id:string;name:string};client:Row;currentHealth:Row;healthSnapshots:Row[];review:Row|null;retentionEvents:Row[];currentUserId:string}){
  const router=useRouter(),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')
  const [reviewStatus,setReviewStatus]=useState(String(review?.review_status||'not_reviewed'))
  const [renewalReadiness,setRenewalReadiness]=useState(String(review?.renewal_readiness||currentHealth.suggested_renewal_readiness||'not_assessed'))
  const [nextReview,setNextReview]=useState(String(review?.next_review_date||'')),[notes,setNotes]=useState(String(review?.notes||'')),[assignToMe,setAssignToMe]=useState(review?String(review.assigned_user_id||'')===currentUserId:true)
  const trends=useMemo(()=>Object.values(currentHealth.trend_windows||{}) as Row[],[currentHealth.trend_windows])
  async function post(action:string,extra:Row={}){setBusy(action);setMessage('');setError('');try{const res=await fetch('/api/admin/business-visibility-retention',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,business_id:business.id,client_id:client.id,...extra})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed.');setMessage(data.message||'Saved.');router.refresh()}catch(e:any){setError(e.message||'Request failed.')}finally{setBusy('')}}
  const latestStored=healthSnapshots[0]||null
  return <div style={{display:'grid',gap:18}}>
    <section className="card">
      <div style={{display:'flex',justifyContent:'space-between',gap:14,flexWrap:'wrap',alignItems:'start'}}><div><div className="kpi">Business Visibility Intelligence 4.5</div><h1 style={{margin:'4px 0 8px'}}>Client Results & Retention Intelligence</h1><p className="muted" style={{maxWidth:860}}>Operational health is calculated only from recorded delivery, measurement, reporting, project and financial facts. It is not a churn prediction and does not infer client sentiment.</p></div><span className={`badge ${tone(String(currentHealth.health_status))}`}>{title(currentHealth.health_status)}</span></div>
      <div className="notice" style={{marginTop:14}}><strong>{client.company_name}</strong> · linked to {business.name}. Missing measurement is neutral. Visibility movement is observational and does not prove causation.</div>
      <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:14}}><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>post('capture_health')}>{busy==='capture_health'?'Capturing…':'Capture Immutable Health Snapshot'}</button>{latestStored?<span className="btn btn-light" aria-disabled="true">Last captured {date(latestStored.created_at)}</span>:<span className="btn btn-light" aria-disabled="true">No stored 4.5 snapshot yet</span>}</div>
      {message?<div className="notice" style={{marginTop:12}}>{message}</div>:null}{error?<div className="notice warn" style={{marginTop:12}}>{error}</div>:null}
    </section>

    <section className="card"><h2>Current factual health</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}>
      <div className="notice"><div className="small muted">Status</div><strong>{title(currentHealth.health_status)}</strong></div>
      <div className="notice"><div className="small muted">Attention points</div><strong>{currentHealth.attention_points}/100</strong><div className="small muted">Priority sorting only; not churn probability.</div></div>
      <div className="notice"><div className="small muted">Latest measurement</div><strong>{date(currentHealth.latest_visibility_snapshot_at)}</strong><div className="small muted">Age: {currentHealth.delivery_metrics?.measurement_age_days??'Not measured'} days</div></div>
      <div className="notice"><div className="small muted">Suggested review readiness</div><strong>{title(currentHealth.suggested_renewal_readiness)}</strong><div className="small muted">Advisory only; staff decides.</div></div>
    </div></section>

    <section className="card"><h2>Needs attention</h2>{(currentHealth.signals||[]).length?<div style={{display:'grid',gap:10}}>{(currentHealth.signals||[]).map((s:Row)=><div className={`notice ${['attention','critical'].includes(String(s.severity))?'warn':''}`} key={s.key}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>{s.label}</strong><span className="small">{title(s.severity)} · {s.points} pts</span></div><div className="small muted" style={{marginTop:4}}>{s.detail}</div></div>)}</div>:<p className="muted">No attention signals are present in the currently recorded facts.</p>}</section>

    <section className="card"><h2>30 / 60 / 90-day visibility trends</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{trends.map((t:Row)=><div className="notice" key={t.label}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{t.label}</strong><span className={`badge ${tone(String(t.status))}`}>{title(t.status)}</span></div><div className="small muted" style={{marginTop:8}}>{t.actual_days?`${t.actual_days} actual days between stored snapshots. `:''}{t.summary}</div>{Array.isArray(t.metrics)&&t.metrics.length?<div className="small" style={{marginTop:8}}>{t.favorable||0} favorable · {t.unfavorable||0} unfavorable · {t.unchanged||0} unchanged</div>:null}</div>)}</div></section>

    <section className="card"><h2>Delivery & reporting</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}>{[
      ['Open visibility work',currentHealth.delivery_metrics?.open_execution_items],['Overdue execution',currentHealth.delivery_metrics?.overdue_execution_items],['Overdue remeasurement',currentHealth.delivery_metrics?.overdue_remeasurements],['Overdue project tasks',currentHealth.delivery_metrics?.overdue_project_tasks],['Projects needing attention',currentHealth.delivery_metrics?.projects_needing_attention],['Client updates due',currentHealth.delivery_metrics?.client_updates_due],['Measured outcomes (90d)',currentHealth.delivery_metrics?.measured_outcomes_90d],['Improved outcomes (90d)',currentHealth.delivery_metrics?.improved_outcomes_90d]
    ].map(([label,value])=><div className="notice" key={String(label)}><div className="small muted">{label}</div><strong>{value??0}</strong></div>)}</div></section>

    <section className="card"><h2>Recorded revenue context</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><div className="notice"><div className="small muted">Net recorded payments · 90d</div><strong>{money(currentHealth.revenue_metrics?.recorded_net_payments_90d_cents)}</strong></div><div className="notice"><div className="small muted">Net recorded payments · lifetime</div><strong>{money(currentHealth.revenue_metrics?.recorded_net_payments_lifetime_cents)}</strong></div><div className="notice"><div className="small muted">Open invoice balance</div><strong>{money(currentHealth.revenue_metrics?.open_balance_cents)}</strong></div><div className="notice"><div className="small muted">Overdue balance</div><strong>{money(currentHealth.revenue_metrics?.overdue_balance_cents)}</strong></div><div className="notice"><div className="small muted">Active recurring services</div><strong>{currentHealth.revenue_metrics?.active_recurring_services||0}</strong></div><div className="notice"><div className="small muted">ROI</div><strong>Not calculated</strong><div className="small muted">Actual cost evidence is required.</div></div></div></section>

    <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h2 style={{marginBottom:4}}>Human retention / renewal review</h2><p className="muted small">These fields are internal staff judgments. Saving them does not alter the client, recurring services, invoices, outreach, public ranking, or billing.</p></div>{review?<span className="badge">Existing Review</span>:<span className="badge">Not Yet Reviewed</span>}</div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><label>Review status<select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)}><option value="not_reviewed">Not reviewed</option><option value="monitor">Monitor</option><option value="renewal_review">Renewal review</option><option value="renewal_discussion">Renewal discussion</option><option value="retained">Retained</option><option value="churn_risk">Churn risk</option><option value="churned">Churned</option><option value="closed">Closed</option></select></label><label>Renewal readiness<select value={renewalReadiness} onChange={e=>setRenewalReadiness(e.target.value)}><option value="not_assessed">Not assessed</option><option value="ready_for_review">Ready for review</option><option value="needs_attention">Needs attention</option><option value="insufficient_data">Insufficient data</option></select></label><label>Next review date<input type="date" value={nextReview} onChange={e=>setNextReview(e.target.value)}/></label></div>
      <label style={{marginTop:12}}>Internal review notes<textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record factual context, client discussion notes or the reason for the staff assessment."/></label><label style={{display:'flex',gap:8,alignItems:'center',marginTop:10}}><input type="checkbox" checked={assignToMe} onChange={e=>setAssignToMe(e.target.checked)}/> Assign this review to me</label>
      <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>post('save_review',{review_status:reviewStatus,renewal_readiness:renewalReadiness,next_review_date:nextReview||null,notes,assign_to_me:assignToMe,health_snapshot_id:latestStored?.id||review?.health_snapshot_id||null})}>{busy==='save_review'?'Saving…':'Save Human Review'}</button>{review?<button className="btn btn-light" disabled={Boolean(busy)} onClick={()=>post(String(review.assigned_user_id||'')===currentUserId?'unassign_review':'claim_review')}>{String(review.assigned_user_id||'')===currentUserId?'Unassign Me':'Assign to Me'}</button>:null}</div>
    </section>

    <section className="card"><h2>Immutable health history</h2>{healthSnapshots.length?<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Captured</th><th>Status</th><th>Attention</th><th>Measurement</th><th>Paid 90d</th></tr></thead><tbody>{healthSnapshots.map((r:Row)=><tr key={r.id}><td>{date(r.created_at)}</td><td>{title(r.health_status)}</td><td>{r.attention_points}/100</td><td>{date(r.latest_visibility_snapshot_at)}</td><td>{money(r.revenue_metrics?.recorded_net_payments_90d_cents)}</td></tr>)}</tbody></table></div>:<p className="muted">No 4.5 client-health snapshot has been captured yet.</p>}</section>

    <section className="card"><h2>Retention audit timeline</h2>{retentionEvents.length?<div style={{display:'grid',gap:8}}>{retentionEvents.slice(0,100).map((e:Row)=><div className="notice" key={e.id}><strong>{title(e.event_type)}</strong><div className="small muted">{date(e.created_at)} · {e.message}</div></div>)}</div>:<p className="muted">No 4.5 retention events recorded yet.</p>}</section>
  </div>
}
