'use client'

import Link from 'next/link'
import { useMemo,useState } from 'react'

type Row=Record<string,any>
type Props={business:{id:string;name:string};snapshots:Row[];recommendations:Row[];reports:Row[];salesEvidence:Row[];prospectLinked:boolean}
const fmt=(v:any,d=0)=>v==null?'Not measured':Number(v).toLocaleString(undefined,{maximumFractionDigits:d})
const date=(v:any)=>v?new Date(v).toLocaleDateString():'—'
const pretty=(v:any)=>String(v??'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const priorityRank:Record<string,number>={critical:4,high:3,medium:2,low:1}

export function BusinessVisibilityReportingPanel({business,snapshots,recommendations,reports,salesEvidence,prospectLinked}:Props){
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[reportTitle,setReportTitle]=useState('')
  const latest=snapshots[0]||null,data=(latest?.snapshot_data||{}) as Row
  const latestRecs=useMemo(()=>latest?recommendations.filter(r=>String(r.snapshot_id)===String(latest.id)).sort((a,b)=>(priorityRank[b.priority]||0)-(priorityRank[a.priority]||0)):[],[latest,recommendations])
  const approvedIds=new Set(salesEvidence.filter(r=>r.status==='approved'&&r.source_table==='business_visibility_recommendations').map(r=>String(r.source_record_id)))
  const components=Array.isArray(data.components)?data.components:[],comparisons=Array.isArray(data.comparisons)?data.comparisons:[]

  async function post(payload:Row,key:string){setBusy(key);setMessage('');setError('');try{const res=await fetch('/api/admin/business-visibility-reporting',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,business_id:business.id})}),json=await res.json();if(!res.ok)throw new Error(json.error||'Request failed.');setMessage(json.message||'Completed.');setTimeout(()=>location.reload(),300)}catch(e:any){setError(String(e?.message||e))}finally{setBusy('')}}
  const createReport=(type:'prospect'|'client')=>post({action:'create_report',report_type:type,snapshot_id:latest?.id,title:reportTitle},`report-${type}`)

  return <div style={{display:'grid',gap:18}}>
    <section className="card"><div className="eyebrow">Business Visibility Intelligence 4.3</div><h1 style={{marginTop:6}}>{business.name}</h1><p className="muted">Evidence-backed opportunity scoring, before/after comparisons, recommendations, and prospect/client reporting. A higher opportunity score means more measured room to improve — it is not a quality grade.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><span className="badge ok">Source-backed only</span><span className="badge">Missing data ≠ zero</span><span className="badge">Saved report snapshots</span><span className="badge">No automatic sending</span><span className="badge">No public ranking effect</span></div>{message?<div className="notice" style={{marginTop:12}}>{message}</div>:null}{error?<div className="notice warn" style={{marginTop:12}}>{error}</div>:null}</section>

    <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2>Unified opportunity snapshot</h2><p className="muted" style={{marginBottom:0}}>Refresh only when you want a new immutable snapshot from the latest stored evidence. If no source record changed, 4.3 reuses the existing snapshot.</p></div><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>post({action:'refresh_intelligence'},'refresh')}>{busy==='refresh'?'Refreshing…':'Refresh intelligence'}</button></div>
      {!latest?<div className="notice" style={{marginTop:14}}>No 4.3 snapshot yet. Refresh intelligence to calculate only from measurements already stored for this business.</div>:<><div className="kpi-grid" style={{marginTop:14}}><div className="kpi-card"><span>Opportunity score</span><strong>{latest.opportunity_score==null?'Not measured':`${fmt(latest.opportunity_score,1)}/100`}</strong><small>Higher = more measured opportunity</small></div><div className="kpi-card"><span>Opportunity band</span><strong>{pretty(latest.opportunity_band)}</strong><small>Evidence-based, not a ranking guarantee</small></div><div className="kpi-card"><span>Measurement coverage</span><strong>{fmt(latest.measurement_coverage,0)}%</strong><small>Unmeasured dimensions are excluded</small></div><div className="kpi-card"><span>Snapshot</span><strong>{date(latest.generated_at)}</strong><small>{latest.period_start||'—'} → {latest.period_end||'—'}</small></div></div><div className="notice" style={{marginTop:14}}>{data.executive_summary||'No executive summary was generated.'}</div></>}
    </section>

    <section className="card"><h2>Score components</h2><p className="muted">The score is normalized across measured components only. Coverage tells you how much of the 100-point weighting is actually supported by data.</p>{!components.length?<div className="notice">No component scores yet.</div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Component</th><th>Weight</th><th>Opportunity</th><th>Evidence note</th></tr></thead><tbody>{components.map((c:any)=><tr key={c.key}><td><strong>{c.label}</strong></td><td>{c.weight}%</td><td>{c.score==null?'Not measured':`${fmt(c.score,1)}/100`}</td><td>{c.detail}</td></tr>)}</tbody></table></div>}</section>

    <section className="card"><h2>Prior-period comparisons</h2><p className="muted">Only comparable stored periods are shown. Average-position improvement means the number gets smaller.</p>{!comparisons.length?<div className="notice">Insufficient comparable history. A single measurement is never presented as a trend.</div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Metric</th><th>Previous</th><th>Current</th><th>Change</th><th>Periods</th></tr></thead><tbody>{comparisons.map((c:any)=><tr key={c.key}><td><strong>{c.label}</strong></td><td>{formatComparison(c.previous,c.unit)}</td><td>{formatComparison(c.current,c.unit)}</td><td>{c.delta==null?'Not measured':`${Number(c.delta)>0?'+':''}${formatComparison(c.delta,c.unit)}${c.delta_pct!=null?` (${Number(c.delta_pct)>0?'+':''}${fmt(c.delta_pct,1)}%)`:''}`}</td><td className="small">{c.previous_period}<br/>→ {c.current_period}</td></tr>)}</tbody></table></div>}</section>

    <section className="card"><h2>Evidence-backed recommendations</h2><p className="muted">These are deterministic rules from stored measurements, not invented audit claims. Accepting/completing a recommendation changes only its internal work status.</p>{!latestRecs.length?<div className="notice">No recommendation was generated from the currently measured sources.</div>:<div style={{display:'grid',gap:12}}>{latestRecs.map(r=><div key={r.id} className="notice" style={{display:'grid',gap:8}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong style={{fontSize:16}}>{r.title}</strong><span className={`badge ${r.priority==='critical'||r.priority==='high'?'warn':''}`}>{pretty(r.priority)}</span><span className="badge">{pretty(r.category)}</span><span className="badge">{pretty(r.status)}</span>{approvedIds.has(String(r.id))?<span className="badge ok">Approved for Sales evidence</span>:null}</div><div><strong>Finding:</strong> {r.finding}</div><div><strong>Recommended action:</strong> {r.recommended_action}</div><div className="small muted">{Array.isArray(r.source_refs)?`${r.source_refs.length} source record${r.source_refs.length===1?'':'s'} attached`: 'Source manifest stored'}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['open','accepted','completed','dismissed'].map(status=><button key={status} className="btn btn-light" disabled={Boolean(busy)||r.status===status} onClick={()=>post({action:'set_recommendation_status',id:r.id,status},`rec-${r.id}-${status}`)}>{status==='open'?'Reopen':pretty(status)}</button>)}{prospectLinked&&!approvedIds.has(String(r.id))?<button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>post({action:'approve_recommendation_for_sales',id:r.id},`sales-${r.id}`)}>Approve as Sales evidence</button>:null}</div></div>)}</div>}</section>

    <section className="card"><h2>Prospect & client report builder</h2><p className="muted">Reports capture the selected immutable snapshot plus recommendation statuses at creation time. They remain private staff records until you intentionally print/save/share them outside this system.</p>{!latest?<div className="notice warn">Create a visibility snapshot before generating a report.</div>:<><label>Optional report title<input value={reportTitle} onChange={e=>setReportTitle(e.target.value)} placeholder={`Business Visibility Report — ${business.name}`}/></label><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>createReport('prospect')}>{busy==='report-prospect'?'Creating…':'Create Prospect Opportunity Report'}</button><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>createReport('client')}>{busy==='report-client'?'Creating…':'Create Client Performance Report'}</button></div></>}</section>

    <section className="card"><h2>Saved reports</h2>{!reports.length?<div className="notice">No saved 4.3 reports yet.</div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Report</th><th>Type</th><th>Status</th><th>Period</th><th>Created</th><th>Actions</th></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td><strong>{r.title}</strong></td><td>{pretty(r.report_type)}</td><td>{pretty(r.status)}</td><td>{r.period_start||'—'} → {r.period_end||'—'}</td><td>{date(r.created_at)}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><Link className="btn btn-light" href={`/admin/businesses/${business.id}/visibility/reporting/${r.id}`}>Open / Print</Link>{r.status==='draft'?<button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>post({action:'set_report_status',id:r.id,status:'finalized'},`final-${r.id}`)}>Finalize</button>:null}{r.status!=='archived'?<button className="btn btn-light" disabled={Boolean(busy)} onClick={()=>post({action:'set_report_status',id:r.id,status:'archived'},`archive-${r.id}`)}>Archive</button>:null}</div></td></tr>)}</tbody></table></div>}</section>
  </div>
}

function formatComparison(v:any,unit:string){
  if(v==null)return 'Not measured'
  if(unit==='ratio')return `${(Number(v)*100).toFixed(1)}%`
  if(unit==='position')return Number(v).toFixed(1)
  if(unit==='points')return `${Number(v).toFixed(1)} pts`
  return fmt(v,1)
}
