'use client'

import { useMemo,useState } from 'react'

type Row=Record<string,any>
type Props={business:{id:string;name:string;website:string|null};gscMetrics:Row[];gbpMetrics:Row[];gbpKeywords:Row[];connections:Row[];imports:Row[];apiConfigured:boolean}
const fmt=(n:any,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d})
const pct=(n:any)=>`${(Number(n||0)*100).toFixed(1)}%`
const date=(v:any)=>v?new Date(v).toLocaleDateString():'—'
const pretty=(v:string)=>String(v||'').toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())

export function BusinessVisibilityGooglePanel({business,gscMetrics,gbpMetrics,gbpKeywords,connections,imports,apiConfigured}:Props){
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[discovery,setDiscovery]=useState<any>(null)
  const [gscProperty,setGscProperty]=useState(String(connections.find(r=>r.connection_type==='search_console')?.search_console_property||''))
  const gbpConnection=connections.find(r=>r.connection_type==='business_profile')
  const [gbpChoice,setGbpChoice]=useState(gbpConnection?.gbp_location_name?`${gbpConnection.gbp_account_name}|${gbpConnection.gbp_location_name}|${gbpConnection.gbp_location_title||''}`:'')
  const [dataset,setDataset]=useState('search_console'),[csv,setCsv]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[filename,setFilename]=useState(''),[dimension,setDimension]=useState('auto'),[periodStart,setPeriodStart]=useState(''),[periodEnd,setPeriodEnd]=useState(''),[month,setMonth]=useState(''),[locationName,setLocationName]=useState('')

  async function post(payload:Row,key:string,reload=true){setBusy(key);setMessage('');setError('');try{const res=await fetch('/api/admin/business-visibility-google',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed.');setMessage(data.message||`Completed. ${data.saved??data.saved_metrics??''}`.trim());if(reload)setTimeout(()=>location.reload(),350);return data}catch(e:any){setError(String(e?.message||e))}finally{setBusy('')}}
  async function discover(){const data=await post({action:'discover_google_sources',business_id:business.id},'discover',false);if(data)setDiscovery(data)}
  async function saveGsc(){await post({action:'save_google_connection',business_id:business.id,connection_type:'search_console',search_console_property:gscProperty},'save-gsc')}
  async function saveGbp(){const [account,location,title]=gbpChoice.split('|');await post({action:'save_google_connection',business_id:business.id,connection_type:'business_profile',gbp_account_name:account,gbp_location_name:location,gbp_location_title:title},'save-gbp')}
  async function importData(){const action=dataset==='search_console'?'import_search_console':dataset==='gbp_performance'?'import_gbp_performance':'import_gbp_keywords',payload:any={action,business_id:business.id,csv_text:csv,source_url:sourceUrl,original_filename:filename,location_name:locationName};if(dataset==='search_console')Object.assign(payload,{dimension_type:dimension,period_start:periodStart,period_end:periodEnd,search_type:'web'});if(dataset==='gbp_keywords')payload.month=month;await post(payload,'import')}

  const gscSummary=useMemo(()=>{const summaries=gscMetrics.filter(r=>r.dimension_type==='summary').sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)));if(summaries[0])return summaries[0];const latestEnd=gscMetrics.reduce((m,r)=>String(r.period_end)>m?String(r.period_end):m,''),q=gscMetrics.filter(r=>r.dimension_type==='query'&&String(r.period_end)===latestEnd);if(!q.length)return null;const clicks=q.reduce((s,r)=>s+Number(r.clicks||0),0),impressions=q.reduce((s,r)=>s+Number(r.impressions||0),0),weighted=q.reduce((s,r)=>s+Number(r.position||0)*Number(r.impressions||0),0);return {period_start:q[0]?.period_start,period_end:latestEnd,clicks,impressions,ctr:impressions?clicks/impressions:0,position:impressions?weighted/impressions:null}},[gscMetrics])
  const latestQueryEnd=gscMetrics.filter(r=>r.dimension_type==='query').reduce((m,r)=>String(r.period_end)>m?String(r.period_end):m,'')
  const topQueries=gscMetrics.filter(r=>r.dimension_type==='query'&&String(r.period_end)===latestQueryEnd).sort((a,b)=>Number(b.impressions||0)-Number(a.impressions||0)).slice(0,25)
  const opportunities=topQueries.filter(r=>Number(r.impressions||0)>=10&&((Number(r.position||0)>=4&&Number(r.position||0)<=20)||(Number(r.ctr||0)<0.03&&Number(r.position||0)<=10))).slice(0,12)
  const gbpRecentStart=new Date(Date.now()-31*86400000).toISOString().slice(0,10)
  const gbpTotals=useMemo(()=>{const map=new Map<string,number>();for(const r of gbpMetrics){if(String(r.metric_date)<gbpRecentStart)continue;map.set(String(r.metric),(map.get(String(r.metric))||0)+Number(r.metric_value||0))}return [...map.entries()].sort((a,b)=>b[1]-a[1])},[gbpMetrics,gbpRecentStart])
  const latestMonth=gbpKeywords.reduce((m,r)=>String(r.month_start)>m?String(r.month_start):m,'')
  const topGbpKeywords=gbpKeywords.filter(r=>String(r.month_start)===latestMonth).sort((a,b)=>Number(b.impressions_value??b.impressions_threshold??0)-Number(a.impressions_value??a.impressions_threshold??0)).slice(0,25)

  return <div style={{display:'grid',gap:18}}>
    <section className="card"><div className="eyebrow">Google-Owned Data Intelligence 4.2</div><h1 style={{marginTop:6}}>{business.name}</h1><p className="muted">First-party Search Console and Google Business Profile performance. Google API access is optional; CSV exports work immediately. These metrics never affect public Local Pros ranking.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><span className={`badge ${apiConfigured?'ok':'warn'}`}>Google API {apiConfigured?'Configured':'Not configured'}</span><span className="badge ok">CSV import ready</span><span className="badge">No Google scraping</span><span className="badge">Source-backed only</span></div>{message?<div className="notice" style={{marginTop:12}}>{message}</div>:null}{error?<div className="notice warn" style={{marginTop:12}}>{error}</div>:null}</section>

    <section className="card"><h2>First-party performance snapshot</h2><div className="kpi-grid"><div className="kpi-card"><span>Search clicks</span><strong>{gscSummary?fmt(gscSummary.clicks):'Not measured'}</strong><small>{gscSummary?`${gscSummary.period_start} → ${gscSummary.period_end}`:'Import or sync Search Console'}</small></div><div className="kpi-card"><span>Search impressions</span><strong>{gscSummary?fmt(gscSummary.impressions):'Not measured'}</strong><small>{gscSummary?`CTR ${pct(gscSummary.ctr)}`:'No Search Console data yet'}</small></div><div className="kpi-card"><span>Average organic position</span><strong>{gscSummary?.position!=null?Number(gscSummary.position).toFixed(1):'Not measured'}</strong><small>Search Console average position — not a local Maps rank</small></div><div className="kpi-card"><span>GBP 30-day activity</span><strong>{gbpTotals.length?fmt(gbpTotals.reduce((s,x)=>s+x[1],0)):'Not measured'}</strong><small>{gbpTotals.length?`${gbpTotals.length} metric types recorded`:'Import or sync GBP'}</small></div></div></section>

    <section className="card"><h2>Google API source connection</h2><p className="muted">Use one authorized Skylight Google account that has access to client Search Console properties / Business Profiles. GBP API calls additionally require Google approval for the Cloud project.</p><button className="btn btn-primary" disabled={!apiConfigured||Boolean(busy)} onClick={discover}>{busy==='discover'?'Discovering…':'Discover accessible Google sources'}</button>{!apiConfigured?<div className="notice warn" style={{marginTop:10}}>API credentials are not configured yet. Import mode below remains fully operational.</div>:null}{discovery?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:14,marginTop:14}}><div><h3>Search Console</h3>{discovery.gsc_error?<p className="small" style={{color:'var(--danger,#b42318)'}}>{discovery.gsc_error}</p>:null}<select value={gscProperty} onChange={e=>setGscProperty(e.target.value)} style={{width:'100%'}}><option value="">Choose property…</option>{(discovery.gsc_sites||[]).map((x:any)=><option key={x.siteUrl} value={x.siteUrl}>{x.siteUrl} · {x.permissionLevel}</option>)}</select><button className="btn btn-light" disabled={!gscProperty||Boolean(busy)} onClick={saveGsc} style={{marginTop:8}}>Save Search Console Property</button></div><div><h3>Business Profile</h3>{discovery.gbp_error?<p className="small" style={{color:'var(--danger,#b42318)'}}>{discovery.gbp_error}</p>:null}<select value={gbpChoice} onChange={e=>setGbpChoice(e.target.value)} style={{width:'100%'}}><option value="">Choose location…</option>{(discovery.gbp_locations||[]).map((x:any)=><option key={`${x.accountName}:${x.locationName}`} value={`${x.accountName}|${x.locationName}|${x.title||''}`}>{x.title} · {x.accountLabel}</option>)}</select><button className="btn btn-light" disabled={!gbpChoice||Boolean(busy)} onClick={saveGbp} style={{marginTop:8}}>Save GBP Location</button></div></div>:null}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}><button className="btn btn-primary" disabled={!apiConfigured||Boolean(busy)||!gscProperty} onClick={()=>post({action:'sync_search_console',business_id:business.id},'sync-gsc')}>{busy==='sync-gsc'?'Syncing…':'Sync Search Console (28 days)'}</button><button className="btn btn-primary" disabled={!apiConfigured||Boolean(busy)||!gbpChoice} onClick={()=>post({action:'sync_business_profile',business_id:business.id},'sync-gbp')}>{busy==='sync-gbp'?'Syncing…':'Sync GBP (30 days + keywords)'}</button></div></section>

    <section className="card"><h2>Free Google export import</h2><p className="muted">Paste CSV or TSV exported from Search Console or Business Profile. Re-importing the same source rows updates/deduplicates them using source fingerprints.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><label>Dataset<select value={dataset} onChange={e=>setDataset(e.target.value)}><option value="search_console">Search Console</option><option value="gbp_performance">GBP Performance</option><option value="gbp_keywords">GBP Search Keywords</option></select></label><label>Filename<input value={filename} onChange={e=>setFilename(e.target.value)} placeholder="export.csv"/></label><label>Source/report URL<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Optional; official Google URL used if blank"/></label>{dataset!=='search_console'?<label>Location name<input value={locationName} onChange={e=>setLocationName(e.target.value)} placeholder="Business location / resource"/></label>:null}{dataset==='search_console'?<><label>Dimension<select value={dimension} onChange={e=>setDimension(e.target.value)}><option value="auto">Auto-detect</option><option value="query">Query</option><option value="page">Page</option><option value="device">Device</option><option value="country">Country</option><option value="search_appearance">Search appearance</option><option value="summary">Summary</option></select></label><label>Period start<input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label>Period end<input type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label></>:null}{dataset==='gbp_keywords'?<label>Fallback month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>:null}</div><label style={{marginTop:10}}>CSV / TSV data<textarea rows={10} value={csv} onChange={e=>setCsv(e.target.value)} placeholder={dataset==='search_console'?'Query,Clicks,Impressions,CTR,Position\nplumber near me,12,400,3%,8.4':dataset==='gbp_performance'?'Date,Website Clicks,Call Clicks,Business Direction Requests\n2026-08-01,4,2,3':'Month,Search Keyword,Impressions\n2026-08-01,plumber near me,120'} style={{width:'100%',fontFamily:'monospace'}}/></label><button className="btn btn-primary" disabled={!csv.trim()||Boolean(busy)} onClick={importData}>{busy==='import'?'Importing…':'Import Google-owned data'}</button></section>

    <section className="card"><h2>Search Console query opportunities</h2><p className="muted">High-impression queries where the site is outside the top positions or has a weak CTR. These are factual opportunity signals from first-party Search Console data—not promises of future ranking.</p>{!opportunities.length?<div className="notice">Insufficient Search Console query data. No opportunity claims are generated yet.</div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Query</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>Avg. position</th><th>Signal</th></tr></thead><tbody>{opportunities.map(r=><tr key={r.id}><td>{r.dimension_value}</td><td>{fmt(r.impressions)}</td><td>{fmt(r.clicks)}</td><td>{pct(r.ctr)}</td><td>{Number(r.position||0).toFixed(1)}</td><td>{Number(r.position||0)>10?'Page-one / page-two opportunity':'CTR opportunity'}</td></tr>)}</tbody></table></div>}</section>

    <section className="card"><h2>Google Business Profile — recent activity</h2>{!gbpTotals.length?<div className="notice">Not measured. Connect or import GBP performance.</div>:<div className="kpi-grid">{gbpTotals.slice(0,10).map(([name,value])=><div className="kpi-card" key={name}><span>{pretty(name)}</span><strong>{fmt(value)}</strong><small>Last ~30 days stored</small></div>)}</div>}</section>

    <section className="card"><h2>GBP search terms</h2><p className="muted">Monthly search terms people used to find the Business Profile in Google Search or Maps. Threshold values remain labeled as thresholds.</p>{!topGbpKeywords.length?<div className="notice">Not measured.</div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Search term</th><th>Month</th><th>Impressions</th><th>Source</th></tr></thead><tbody>{topGbpKeywords.map(r=><tr key={r.id}><td>{r.search_keyword}</td><td>{String(r.month_start).slice(0,7)}</td><td>{r.impressions_value!=null?fmt(r.impressions_value):`< ${fmt(r.impressions_threshold)}`}</td><td>{pretty(r.source_type)}</td></tr>)}</tbody></table></div>}</section>

    <section className="card"><h2>Google data history</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Dataset</th><th>Imported</th><th>Rows</th><th>Rejected</th><th>File / reference</th></tr></thead><tbody>{imports.length?imports.slice(0,20).map(r=><tr key={r.id}><td>{pretty(r.dataset_type)}</td><td>{date(r.created_at)}</td><td>{fmt(r.imported_rows)}</td><td>{fmt(r.rejected_rows)}</td><td>{r.original_filename||r.provider_reference||'Google source'}</td></tr>):<tr><td colSpan={5}>No Google import batches yet.</td></tr>}</tbody></table></div></section>
  </div>
}
