'use client'
import{FormEvent,useMemo,useState}from'react'
type Row=Record<string,any>
const related=(v:any)=>Array.isArray(v)?v[0]:v
const money=(c:number)=>`$${(Number(c||0)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`
export function LeadROITracker({rows,charges,appointments}:{rows:Row[];charges:Row[];appointments:Row[]}){const[busy,setBusy]=useState(''),[message,setMessage]=useState('');const stats=useMemo(()=>{const won=rows.filter(r=>r.status==='won'),revenue=won.reduce((n,r)=>n+Number(r.outcome_value_cents||0),0),cost=charges.reduce((n,c)=>n+(Number(c.per_lead_price_cents||0)||((Number(c.bundle_price_cents||0)&&Number(c.bundle_lead_count||0))?Math.round(Number(c.bundle_price_cents)/Number(c.bundle_lead_count)):0)),0);return{won:won.length,revenue,cost,multiple:cost>0?revenue/cost:null}},[rows,charges]);async function save(e:FormEvent<HTMLFormElement>,recipientId:string){e.preventDefault();setBusy(recipientId);setMessage('');const f=new FormData(e.currentTarget),dollar=(k:string)=>{const raw=String(f.get(k)||'').trim();if(!raw)return null;const n=Number(raw);return Number.isFinite(n)&&n>=0?Math.round(n*100):null};const r=await fetch('/api/owner/commerce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'lead_outcome',recipient_id:recipientId,status:String(f.get('status')||'viewed'),owner_notes:String(f.get('owner_notes')||''),appointment_at:String(f.get('appointment_at')||'')||null,quote_amount_cents:dollar('quote_amount'),outcome_value_cents:dollar('outcome_value'),loss_reason:String(f.get('loss_reason')||'')})}),body=await r.json().catch(()=>({}));setBusy('');if(!r.ok){setMessage(String(body.error||'Unable to save lead outcome.'));return}setMessage('Lead outcome saved. Revenue values are private ROI metadata and do not change what the lead is billed for.');window.location.reload()}return <div>
 <div className="action-center-summary"><div><span>Delivered Leads</span><strong>{rows.length}</strong><small>all delivered opportunities</small></div><div><span>Jobs Won</span><strong>{stats.won}</strong><small>owner-reported closes</small></div><div><span>Estimated Job Revenue</span><strong>{money(stats.revenue)}</strong><small>owner-entered won value</small></div><div><span>Recorded Lead Cost</span><strong>{money(stats.cost)}</strong><small>delivery/bundle allocation only</small></div><div><span>Revenue / Lead Cost</span><strong>{stats.multiple===null?'—':`${stats.multiple.toFixed(1)}×`}</strong><small>not a guaranteed ROI figure</small></div><div><span>Appointment Requests</span><strong>{appointments.length}</strong><small>released through Admin delivery</small></div></div>
 <div className="notice"><strong>ROI guardrail:</strong> quote and won-job values are private owner-entered estimates. They do not change lead pricing, invoices, verification, Sponsored placement or organic ranking.</div>{message&&<div className="notice">{message}</div>}
 <div className="action-center-list">{rows.map(r=>{const l=related(r.leads)||{};return <article className="admin-card" key={r.id}><div className="section-head compact-head"><div><div className="badges"><span className="badge neutral">{r.delivery_type||'delivered'}</span><span className="badge neutral">{String(r.status||'new').replaceAll('_',' ')}</span></div><h3>{l.service||'Local lead'} · {l.city||'Central Illinois'}</h3><p className="small muted">Delivered {r.routed_at?new Date(r.routed_at).toLocaleDateString():'—'} · {l.timeline||'Timeline not specified'}</p></div></div><form className="form-grid" onSubmit={e=>save(e,r.id)}><label>Pipeline status<select name="status" defaultValue={r.status||'viewed'}><option value="viewed">Viewed</option><option value="contacted">Contacted</option><option value="appointment_set">Appointment Set</option><option value="quoted">Quoted</option><option value="won">Won</option><option value="lost">Lost</option><option value="declined">Declined</option><option value="spam">Spam</option></select></label><label>Appointment date/time<input name="appointment_at" type="datetime-local" defaultValue={r.appointment_at?String(r.appointment_at).slice(0,16):''}/></label><label>Quote amount ($)<input name="quote_amount" type="number" min="0" step="0.01" defaultValue={r.quote_amount_cents!=null?(Number(r.quote_amount_cents)/100).toFixed(2):''}/></label><label>Won job value ($)<input name="outcome_value" type="number" min="0" step="0.01" defaultValue={r.outcome_value_cents!=null?(Number(r.outcome_value_cents)/100).toFixed(2):''}/></label><label>Loss reason<input name="loss_reason" maxLength={300} defaultValue={r.loss_reason||''} placeholder="Could not reach, hired another pro, budget…"/></label><label className="full-row">Private owner notes<textarea name="owner_notes" maxLength={2000} defaultValue={r.owner_notes||''}/></label><button className="btn btn-primary" disabled={busy===r.id}>{busy===r.id?'Saving…':'Save Outcome'}</button></form></article>})}{!rows.length&&<div className="empty"><strong>No delivered leads yet.</strong><p className="muted">Delivered Intro Leads and paid/manual deliveries will appear here for outcome tracking.</p></div>}</div>
 </div>}
