'use client'
import{useMemo,useState}from'react'
type Business={id:string;name:string;logo_url?:string|null};type Row=Record<string,any>
const empty={business_id:'',promo_text:'',promo_cta_label:'View Deal',promo_url:'',starts_on:'',ends_on:'',active:true,priority:100,sort_order:100,origin:'manual',monthly_add_on_cents:500}
const money=(c:any)=>`$${(Number(c||0)/100).toFixed(2)}`
export function PromoBannerManager({rows,businesses,paymentUrl}:{rows:Row[];businesses:Business[];paymentUrl:string}){
 const[data,setData]=useState(rows),[draft,setDraft]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const stats=useMemo(()=>({active:data.filter(x=>x.active).length,scheduled:data.filter(x=>x.active&&(x.starts_on||x.ends_on)).length,paid:data.filter(x=>x.provider==='stripe'||x.provider_subscription_id).length}),[data])
 const business=(id:any)=>businesses.find(x=>x.id===id)
 function reset(){setDraft(empty);setEditing(null)}
 function edit(row:Row){setEditing(row.id);setDraft({...empty,...row,promo_url:row.promo_url||'',promo_cta_label:row.promo_cta_label||'View Deal',starts_on:row.starts_on||'',ends_on:row.ends_on||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){setBusy(true);setMessage('');const payload={...draft,id:editing||undefined};const r=await fetch('/api/admin/promotions',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.error||'Unable to save promotion.'));setBusy(false);return}const row={...payload,id:editing||body.id,placement:'homepage_ticker',provider:body.provider||draft.provider||'manual'};setData(prev=>editing?prev.map(x=>x.id===editing?{...x,...row}:x):[row,...prev]);setMessage(editing?'Homepage deal updated.':'Homepage deal created.');reset();setBusy(false)}
 async function toggle(row:Row){const r=await fetch('/api/admin/promotions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,toggleOnly:true})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.error||'Unable to update deal.'));setData(prev=>prev.map(x=>x.id===row.id?{...x,active:body.active}:x));setMessage(body.active?'Homepage deal activated.':'Homepage deal paused.')}
 async function remove(row:Row){if(!window.confirm(`Remove ${business(row.business_id)?.name||'this business'} from the homepage deal banner?`))return;const r=await fetch('/api/admin/promotions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.error||'Unable to remove deal.'));setData(prev=>prev.filter(x=>x.id!==row.id));setMessage('Homepage deal removed.')}
 return <div style={{marginBottom:28}}>
  <div className="notice"><strong>Homepage Deal Banner · $5/month add-on.</strong> This is optional advertising for any package. Only active, in-date promotions for published businesses scroll at the top of the homepage. Every item is labeled Sponsored and never changes organic ranking or verification. <a href={paymentUrl} target="_blank" rel="noopener" style={{fontWeight:900}}>Open customer checkout →</a></div>
  <div className="stat-grid"><div className="stat">Active Deals<strong>{stats.active}</strong></div><div className="stat">Scheduled<strong>{stats.scheduled}</strong></div><div className="stat">Stripe Linked<strong>{stats.paid}</strong></div><div className="stat">Monthly Add-On<strong>$5</strong></div></div>
  <section className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><h2>{editing?'Edit Homepage Deal':'Add Homepage Deal'}</h2><p className="muted">Use this after a customer subscribes, or create a complimentary/manual promotion when appropriate.</p></div>{editing&&<button className="btn btn-light" onClick={reset}>Cancel Edit</button>}</div>
   <div className="admin-form-grid">
    <label>Business<select value={draft.business_id} onChange={e=>setDraft({...draft,business_id:e.target.value})}><option value="">Choose published business…</option>{businesses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label>Promotion / Deal<input maxLength={200} placeholder="20% off this month — mention Local Pros" value={draft.promo_text} onChange={e=>setDraft({...draft,promo_text:e.target.value})}/></label>
    <label>CTA label<input maxLength={40} placeholder="View Deal" value={draft.promo_cta_label} onChange={e=>setDraft({...draft,promo_cta_label:e.target.value})}/></label>
    <label>Deal link<input maxLength={500} placeholder="https://business.com/special or /business/slug" value={draft.promo_url} onChange={e=>setDraft({...draft,promo_url:e.target.value})}/></label>
    <label>Starts<input type="date" value={draft.starts_on} onChange={e=>setDraft({...draft,starts_on:e.target.value})}/></label>
    <label>Ends<input type="date" value={draft.ends_on} onChange={e=>setDraft({...draft,ends_on:e.target.value})}/></label>
    <label>Priority<input type="number" min="0" max="1000" value={draft.priority} onChange={e=>setDraft({...draft,priority:Number(e.target.value)})}/></label>
    <label>Sort order<input type="number" min="0" max="100000" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})}/></label>
    <label>Billing / origin<select value={draft.origin} onChange={e=>setDraft({...draft,origin:e.target.value})}><option value="manual">Manual / Paid</option><option value="stripe">Stripe subscription</option><option value="promotional">Complimentary promotion</option></select></label>
    <label>Monthly add-on<input type="text" disabled value={money(draft.monthly_add_on_cents)+'/month'}/></label>
    <label className="check-row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Active</label>
   </div>
   <button className="btn btn-primary" disabled={busy||!draft.business_id||!String(draft.promo_text).trim()} onClick={save}>{busy?'Saving…':editing?'Save Deal Changes':'Add to Homepage Banner'}</button>
  </section>
  {message&&<div className="notice" style={{marginTop:14}}>{message}</div>}
  <div className="moderation-list" style={{marginTop:16}}>{data.map(r=>{const b=business(r.business_id);return <article className="admin-card moderation-card" key={r.id}><div className="moderation-head"><div><div className="badges"><span className={`badge ${r.active?'sponsored':'neutral'}`}>{r.active?'Active':'Paused'}</span><span className="badge sponsored">Homepage Deal</span><span className="badge neutral">{r.origin||r.provider||'manual'}</span></div><h3>{b?.name||r.business_id}</h3><p style={{margin:'6px 0',fontWeight:800}}>{r.promo_text}</p><p className="small muted">{r.promo_cta_label||'View Deal'}{r.promo_url?` · ${r.promo_url}`:''}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-light" onClick={()=>edit(r)}>Edit</button><button className="btn btn-light" onClick={()=>toggle(r)}>{r.active?'Pause':'Activate'}</button><button className="btn btn-light" onClick={()=>remove(r)}>Remove</button></div></div><div className="moderation-details"><div><span>Starts</span><strong>{r.starts_on||'Immediately'}</strong></div><div><span>Ends</span><strong>{r.ends_on||'No end date'}</strong></div><div><span>Add-On</span><strong>{money(r.monthly_add_on_cents||500)}/mo</strong></div><div><span>Order</span><strong>{r.priority??100} / {r.sort_order??100}</strong></div></div></article>})}</div>
  {!data.length&&<div className="empty" style={{marginTop:16}}>No homepage deal promotions are configured yet.</div>}
 </div>
}
