import Link from'next/link'
import{createClient}from'@/lib/supabase/server'
import{BusinessCommunityActions}from'@/components/BusinessCommunityActions'
import{ProjectMatchForm}from'@/components/ProjectMatchForm'

type Props={businessId:string;businessName:string;service:string;city:string;slug:string}
const fmt=(v:any)=>v?new Date(String(v)).toLocaleDateString():'—'
export async function PublicBusinessCommerce({businessId,businessName,service,city,slug}:Props){const s=await createClient(),now=Date.now();const[ent,recs,deals,avail,catalog,portfolio,questions,stats]=await Promise.all([
 s.rpc('get_public_business_media_entitlements',{p_business_id:businessId}),
 s.from('business_recommendations').select('id,service,city,body,service_date,created_at').eq('business_id',businessId).eq('status','approved').order('created_at',{ascending:false}).limit(8),
 s.from('business_deals').select('id,title,details,promo_code,cta_label,cta_url,starts_at,ends_at').eq('business_id',businessId).eq('status','approved').order('created_at',{ascending:false}).limit(10),
 s.from('business_availability').select('availability_status,message,expires_at,updated_at').eq('business_id',businessId).maybeSingle(),
 s.from('business_catalog_items').select('id,item_type,category_label,name,description,price_label,item_url,sort_order').eq('business_id',businessId).eq('status','approved').order('sort_order').limit(30),
 s.from('business_portfolio_projects').select('id,title,summary,project_type,city,completed_on').eq('business_id',businessId).eq('status','approved').order('completed_on',{ascending:false,nullsFirst:false}).limit(12),
 s.from('local_pro_questions').select('id,question,answer,answered_at').eq('business_id',businessId).eq('status','published').order('created_at',{ascending:false}).limit(12),
 s.from('business_local_fave_stats').select('recommendation_count,latest_recommendation_at').eq('business_id',businessId).maybeSingle(),
]);const e=(ent.data&&typeof ent.data==='object'?ent.data:{})as any,isPro=String(e.plan_slug||'')==='pro';const activeDeals=(deals.data??[]).filter((d:any)=>(!d.starts_at||new Date(d.starts_at).getTime()<=now)&&(!d.ends_at||new Date(d.ends_at).getTime()>=now));const availability=avail.data&&(!avail.data.expires_at||new Date(avail.data.expires_at).getTime()>=now)?avail.data:null;const localCount=Number((stats.data as any)?.recommendation_count||0),availabilityLabel:Record<string,string>={available_today:'Available Today',taking_new_customers:'Taking New Customers',emergency_24_7:'24/7 Emergency Service',limited:'Limited Availability',unavailable:'Currently Unavailable'};return <>
 <section className="hero"><div className="container"><div className="profile-breadcrumbs"><Link href={`/business/${slug}`}>{businessName}</Link><span>›</span><span>Community & Offers</span></div><div className="eyebrow">Local Commerce Profile</div><h1>{businessName}: Local Faves, offers & customer tools</h1><p>Community recommendations, business-provided offers, services, projects and Q&A are shown separately from verification, Sponsored placement and organic directory ranking.</p><div className="badges"><span className="badge neutral">{localCount} Local Fave recommendation{localCount===1?'':'s'}</span>{availability&&<span className="badge verified">{availabilityLabel[availability.availability_status]||availability.availability_status}</span>}{isPro&&<span className="badge neutral">Pro tools active</span>}</div><div className="hero-actions"><Link className="btn btn-primary" href={`/business/${slug}`}>Back to Main Profile</Link><a className="btn btn-light" href="#community-actions">Recommend / Ask</a></div></div></section>
 {availability&&<section className="section"><div className="container"><div className="notice"><strong>Owner-reported availability: {availabilityLabel[availability.availability_status]||availability.availability_status}.</strong> {availability.message||'Confirm current availability directly with the business.'} {availability.expires_at?`This status is configured through ${fmt(availability.expires_at)}.`:''} Availability does not represent verification or a physical office.</div></div></section>}
 {activeDeals.length>0&&<section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Deals & Specials</div><h2>Current offers</h2></div><Link href="/deals">All Local Deals →</Link></div><div className="grid grid-3">{activeDeals.map((d:any)=><article className="card" key={d.id}><div className="badges"><span className="badge sponsored">Business Offer</span>{d.ends_at&&<span className="badge neutral">Ends {fmt(d.ends_at)}</span>}</div><h3>{d.title}</h3>{d.promo_code&&<p><strong>Code: {d.promo_code}</strong></p>}{d.details&&<p className="muted">{d.details}</p>}{d.cta_url&&<a className="btn btn-light" href={d.cta_url} target="_blank" rel="noopener noreferrer">{d.cta_label||'Offer Details'} ↗</a>}<p className="small muted">Confirm current terms directly with the business.</p></article>)}</div></div></section>}
 {(catalog.data??[]).length>0&&<section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Structured Offerings</div><h2>Services, menu items & products</h2><p className="muted">Business-provided items are moderated before publication.</p></div></div><div className="grid grid-3">{(catalog.data??[]).map((x:any)=><article className="card" key={x.id}><div className="badges"><span className="badge neutral">{String(x.item_type).replaceAll('_',' ')}</span>{x.category_label&&<span className="badge neutral">{x.category_label}</span>}</div><h3>{x.name}</h3>{x.price_label&&<p><strong>{x.price_label}</strong></p>}{x.description&&<p className="muted small">{x.description}</p>}{x.item_url&&<a href={x.item_url} className="btn btn-light" target="_blank" rel="noopener noreferrer">Learn More ↗</a>}</article>)}</div></div></section>}
 {(portfolio.data??[]).length>0&&<section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Project Portfolio</div><h2>Recent work from {businessName}</h2></div></div><div className="grid grid-3">{(portfolio.data??[]).map((p:any)=><article className="card" key={p.id}><div className="badges">{p.project_type&&<span className="badge neutral">{p.project_type}</span>}{p.city&&<span className="badge neutral">{p.city}</span>}</div><h3>{p.title}</h3>{p.summary&&<p className="muted">{p.summary}</p>}{p.completed_on&&<p className="small muted">Completed {fmt(p.completed_on)}</p>}</article>)}</div></div></section>}
 <section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Local Faves</div><h2>Community recommendations</h2><p className="muted">These are moderated recommendations from signed-in Local Pros users. They are not bought badges and do not create verification.</p></div><span className="badge neutral">{localCount}</span></div><div className="grid grid-2">{(recs.data??[]).map((r:any)=><article className="card" key={r.id}><div className="badges"><span className="badge verified">Recommended</span>{r.service&&<span className="badge neutral">{r.service}</span>}</div><p>“{r.body}”</p><p className="small muted">{[r.city,r.service_date?`service ${fmt(r.service_date)}`:null].filter(Boolean).join(' · ')}</p></article>)}</div>{!(recs.data??[]).length&&<div className="empty"><strong>No published Local Fave recommendations yet.</strong><p className="muted">Be the first signed-in customer to submit one for moderation.</p></div>}</div></section>
 {(questions.data??[]).length>0&&<section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Ask a Local Pro</div><h2>Published questions & answers</h2></div></div>{(questions.data??[]).map((q:any)=><details className="card" style={{marginBottom:12}} key={q.id}><summary><strong>{q.question}</strong></summary><p className="muted">{q.answer}</p><p className="small muted">Business answer reviewed before publication.</p></details>)}</div></section>}
 <section className="section" id="community-actions"><div className="container"><div className="section-head"><div><div className="kpi">Community Actions</div><h2>Recommend, ask or request a time</h2></div></div><BusinessCommunityActions businessId={businessId} businessName={businessName} service={service} city={city} isPro={isPro}/></div></section>
 <section className="section"><div className="container" style={{maxWidth:900}}><div className="section-head"><div><div className="kpi">Need a Quote?</div><h2>Start a structured request for {businessName}</h2></div></div><ProjectMatchForm businessId={businessId} service={service} city={city} compact/></div></section>
 </>}
