'use client'
import { useMemo,useState } from 'react'

type Row=Record<string,any>
const relation=(v:any)=>Array.isArray(v)?v[0]??{}:v??{}
const titleCase=(v:any)=>String(v??'').replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const stamp=(v:any)=>v?new Date(String(v)).toLocaleString():'—'
const verified=(p:Row)=>Boolean(p&&p.status!=='do_not_contact'&&(p.owner_contact_email||p.owner_contact_phone)&&/^https?:\/\//i.test(String(p.owner_contact_source_url||''))&&p.owner_contact_checked_at)
async function post(body:Row){const r=await fetch('/api/admin/skylight-sales/outreach',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed.');return j}

export function SalesOutreachWorkbench({opportunities,templates,drafts,events,followups,suppressions,campaigns,members}:{opportunities:Row[];templates:Row[];drafts:Row[];events:Row[];followups:Row[];suppressions:Row[];campaigns:Row[];members:Row[]}){
  const[q,setQ]=useState(''),[view,setView]=useState('ready'),[open,setOpen]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('')
  const suppressionByProspect=useMemo(()=>new Set(suppressions.map(s=>String(s.prospect_id))),[suppressions])
  const draftByOpportunity=useMemo(()=>{const m=new Map<string,Row[]>();for(const d of drafts){const k=String(d.opportunity_id);m.set(k,[...(m.get(k)||[]),d])}return m},[drafts])
  const filtered=useMemo(()=>opportunities.filter(o=>{const p=relation(o.prospect),hay=`${p.business_name||''} ${p.city||''} ${p.owner_contact_name||''} ${(o.evidence_flags||[]).join(' ')} ${(o.recommended_service_slugs||[]).join(' ')}`.toLowerCase();if(q&&!hay.includes(q.toLowerCase()))return false;if(view==='ready'&&o.stage!=='contact_ready')return false;if(view==='contacted'&&!['contacted','qualified','proposal','nurture'].includes(String(o.stage)))return false;if(view==='suppressed'&&!suppressionByProspect.has(String(o.prospect_id)))return false;return true}),[opportunities,q,view,suppressionByProspect])
  async function act(payload:Row,key:string,success='Saved.'){setBusy(key);setMsg('');try{const b=await post(payload);setMsg(b.drafts_created!==undefined?`${b.drafts_created} draft(s) prepared; ${b.blocked_or_ineligible||0} blocked/ineligible. Nothing was sent.`:success);location.reload()}catch(e:any){setMsg(String(e?.message||'Request failed'))}finally{setBusy('')}}
  return <div style={{display:'grid',gap:18,marginTop:18}}>
    {msg?<div className="notice">{msg}</div>:null}
    <section className="admin-card"><div className="section-head"><div><div className="kpi">Campaign Workbench</div><h2>Bulk prepare — never bulk send</h2><p className="small muted">Prepare first-touch email drafts for Contact Ready campaign members. Every draft still requires individual review and approval; suppression and provenance gates run prospect-by-prospect.</p></div></div><div className="grid grid-3">{campaigns.filter(c=>c.status==='active').map(c=>{const cm=members.filter(m=>m.campaign_id===c.id),ready=cm.filter(m=>['ready','contacted'].includes(String(m.status))).length;return <div className="card" key={c.id}><div className="kpi">{titleCase(c.campaign_type)}</div><h3>{c.name}</h3><p className="small muted">{c.description||titleCase(c.service_slug)}</p><div className="small"><strong>{cm.length}</strong> members · <strong>{ready}</strong> ready/contacted</div><button className="btn btn-primary" type="button" style={{marginTop:10}} disabled={Boolean(busy)||!ready} onClick={()=>act({action:'bulk_prepare_campaign',campaign_id:c.id},`bulk-${c.id}`,'Draft preparation complete.')}>{busy===`bulk-${c.id}`?'Preparing…':'Prepare First-Touch Drafts'}</button></div>})}</div></section>

    <section className="admin-card"><div className="section-head"><div><div className="kpi">Contact Ready Workbench</div><h2>Verified prospects with evidence</h2><p className="small muted">Every card explains why the prospect is eligible and keeps the source visible to staff.</p></div></div><div className="grid grid-3" style={{alignItems:'end'}}><label className="field"><span>Search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Business, city, contact, signal…"/></label><label className="field"><span>Work State</span><select value={view} onChange={e=>setView(e.target.value)}><option value="ready">Contact Ready</option><option value="contacted">Contacted / Qualified</option><option value="suppressed">Suppressed</option><option value="all">All active sales</option></select></label><div className="small muted">Showing {filtered.length} prospects</div></div>
      <div style={{display:'grid',gap:12,marginTop:14}}>{filtered.slice(0,250).map(o=>{const p=relation(o.prospect),ds=draftByOpportunity.get(String(o.id))||[],suppressed=suppressionByProspect.has(String(o.prospect_id)),canDraft=verified(p)&&!suppressed&&Boolean((o.evidence_flags||[]).length),latest=ds[0];return <div className="card" key={o.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div className="kpi">{titleCase(o.priority)} · Score {o.score}</div><h3>{p.business_name||'Business Opportunity'}</h3><div className="small muted">{[p.city,p.category].filter(Boolean).join(' · ')}</div></div><span className={`badge ${o.stage==='contact_ready'?'verified':'neutral'}`}>{titleCase(o.stage)}</span></div>
        <div className="grid grid-3" style={{marginTop:12}}><div><strong>Decision maker</strong><div className="small">{p.owner_contact_name||'Name not recorded'}{p.owner_contact_title?` · ${p.owner_contact_title}`:''}</div><div className="small">{p.owner_contact_email||'—'}</div><div className="small">{p.owner_contact_phone||'—'}</div></div><div><strong>Why ready</strong><div className="small muted">{verified(p)?'Sourced contact + valid source URL + checked timestamp':'Provenance incomplete'}</div><div className="small muted">Checked {stamp(p.owner_contact_checked_at)}</div>{p.owner_contact_source_url?<a className="small" href={p.owner_contact_source_url} target="_blank" rel="noreferrer">Open contact evidence source ↗</a>:null}</div><div><strong>Observed evidence</strong><div className="small muted">{(o.evidence_flags||[]).map(titleCase).join(' · ')||'No documented signal'}</div><div className="small"><strong>Recommended:</strong> {(o.recommended_service_slugs||[]).map(titleCase).join(', ')}</div></div></div>
        {suppressed?<div className="notice warn" style={{marginTop:10}}><strong>Suppressed.</strong> Drafting/sending is blocked until the relevant suppression is deliberately reviewed and lifted.</div>:null}
        <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button className="btn btn-primary" type="button" disabled={!canDraft||Boolean(busy)} onClick={()=>act({action:'create_draft',opportunity_id:o.id,channel:'email',sequence_stage:'first_touch'},`draft-${o.id}`,'Draft created. Review it before approval.')}>{busy===`draft-${o.id}`?'Preparing…':'Prepare Email Draft'}</button>{p.owner_contact_phone?<button className="btn btn-light" type="button" disabled={!canDraft||Boolean(busy)} onClick={()=>act({action:'create_draft',opportunity_id:o.id,channel:'phone',sequence_stage:'call'},`call-${o.id}`,'Call notes prepared. Nothing was dialed.')}>Prepare Call Notes</button>:null}<button className="btn btn-light" type="button" disabled={!canDraft||Boolean(busy)} onClick={()=>act({action:'create_draft',opportunity_id:o.id,channel:'linkedin',sequence_stage:'first_touch'},`linkedin-${o.id}`,'LinkedIn copy prepared for manual review/use. Nothing was posted or sent.')}>Prepare LinkedIn Draft</button><button className="btn btn-light" type="button" onClick={()=>setOpen(open===o.id?'':o.id)}>{open===o.id?'Hide History':'Review Drafts & Outcomes'}</button><a className="btn btn-light" href={`/admin/prospects?open=${o.prospect_id}`}>Open CRM</a></div>
        {latest?<div className="small muted" style={{marginTop:8}}>Latest draft: {titleCase(latest.channel)} · {titleCase(latest.status)} · {stamp(latest.created_at)}</div>:null}
        {open===o.id?<OpportunityPanel opportunity={o} prospect={p} drafts={ds} events={events.filter(e=>e.opportunity_id===o.id)} followups={followups.filter(f=>f.opportunity_id===o.id)} busy={busy} act={act}/>:null}
      </div>})}{!filtered.length?<div className="notice">No prospects match the current work state.</div>:null}</div>
    </section>

    <TemplateManager templates={templates} busy={busy} act={act}/>
  </div>
}

function OpportunityPanel({opportunity,prospect,drafts,events,followups,busy,act}:{opportunity:Row;prospect:Row;drafts:Row[];events:Row[];followups:Row[];busy:string;act:(p:Row,k:string,s?:string)=>Promise<void>}){
  return <div style={{display:'grid',gap:12,marginTop:14,borderTop:'1px solid var(--line,#e5e7eb)',paddingTop:14}}>
    <div className="grid grid-2"><div><div className="kpi">Draft Review</div>{drafts.length?drafts.slice(0,6).map(d=><DraftCard key={d.id} draft={d} busy={busy} act={act}/>):<div className="small muted">No drafts yet.</div>}</div><div><div className="kpi">Follow-Up Tasks</div>{followups.length?followups.map(f=><div className="card" key={f.id} style={{marginTop:8}}><strong>{titleCase(f.sequence_stage)}</strong><div className="small muted">Due {stamp(f.due_at)} · {titleCase(f.channel)}</div><button className="btn btn-light" type="button" style={{marginTop:8}} disabled={Boolean(busy)} onClick={()=>act({action:'complete_followup',id:f.id},`fu-${f.id}`,'Follow-up task completed. No message was sent automatically.')}>Mark Task Complete</button></div>):<div className="small muted">No open follow-up tasks.</div>}</div></div>
    <div><div className="kpi">Record Human Outcome</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}>{[['call_attempted','Call Attempted'],['voicemail','Voicemail'],['connected','Connected'],['reply_positive','Positive Reply'],['reply_neutral','Neutral Reply'],['reply_negative','Negative Reply'],['interested','Interested'],['not_interested','Not Interested'],['appointment_booked','Appointment Booked'],['bounced','Bounced'],['wrong_person','Wrong Person'],['do_not_contact','Do Not Contact']].map(([v,l])=><button type="button" className={v==='do_not_contact'?'btn btn-danger':'btn btn-light'} key={v} disabled={Boolean(busy)} onClick={()=>act({action:'record_event',opportunity_id:opportunity.id,event_type:v,channel:v==='bounced'?'email':v==='wrong_person'?(prospect.owner_contact_email?'email':'phone'):'phone'},`event-${v}-${opportunity.id}`,`${l} recorded.`)}>{l}</button>)}</div></div>
    <div><div className="kpi">Recent History</div>{events.slice(0,12).map(e=><div className="small" key={e.id} style={{padding:'7px 0',borderBottom:'1px solid var(--line,#eee)'}}><strong>{titleCase(e.event_type)}</strong> · {titleCase(e.channel)} · {stamp(e.created_at)}{e.notes?<div className="muted">{e.notes}</div>:null}</div>)}</div>
  </div>
}

function DraftCard({draft,busy,act}:{draft:Row;busy:string;act:(p:Row,k:string,s?:string)=>Promise<void>}){
  const[subject,setSubject]=useState(String(draft.subject||'')),[body,setBody]=useState(String(draft.body||''))
  return <div className="card" style={{marginTop:8}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{titleCase(draft.channel)} · {titleCase(draft.sequence_stage)}</strong><span className={`badge ${draft.status==='sent'?'verified':'neutral'}`}>{titleCase(draft.status)}</span></div>{draft.blocked_reason?<div className="small" style={{marginTop:6}}>{draft.blocked_reason}</div>:null}{draft.channel==='email'?<label className="field" style={{marginTop:8}}><span>Subject</span><input value={subject} disabled={!['draft','approved'].includes(draft.status)} onChange={e=>setSubject(e.target.value)}/></label>:null}<label className="field" style={{marginTop:8}}><span>{draft.channel==='phone'?'Call Notes':'Body'}</span><textarea rows={8} value={body} disabled={!['draft','approved'].includes(draft.status)} onChange={e=>setBody(e.target.value)}/></label><div className="small muted">Recipient: {draft.recipient_email||draft.recipient_phone||draft.recipient_name||'manual channel'} · provenance checked {stamp(draft.contact_checked_at)}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}>{['draft','approved'].includes(draft.status)?<button className="btn btn-light" type="button" disabled={Boolean(busy)} onClick={()=>act({action:'save_draft',id:draft.id,subject,body},`save-${draft.id}`,'Draft saved. Approval was reset so the edited copy must be reviewed again.')}>Save Edits</button>:null}{draft.status==='draft'?<button className="btn btn-primary" type="button" disabled={Boolean(busy)} onClick={()=>act({action:'approve_draft',id:draft.id},`approve-${draft.id}`,'Draft approved. It is still not sent.')}>Approve Draft</button>:null}{draft.status==='approved'&&draft.channel==='email'?<button className="btn btn-primary" type="button" disabled={Boolean(busy)} onClick={()=>act({action:'send_email',id:draft.id},`send-${draft.id}`,'Approved email sent by explicit staff action. Follow-up tasks were created without auto-send.')}>Send Approved Email</button>:null}</div></div>
}

function TemplateManager({templates,busy,act}:{templates:Row[];busy:string;act:(p:Row,k:string,s?:string)=>Promise<void>}){
  const[first,setFirst]=useState(templates[0]?.id||''),current=templates.find(t=>t.id===first)||null
  const[name,setName]=useState(current?.name||''),[subject,setSubject]=useState(current?.subject_template||''),[body,setBody]=useState(current?.body_template||''),[offset,setOffset]=useState(String(current?.day_offset??0))
  function select(id:string){setFirst(id);const t=templates.find(x=>x.id===id);setName(t?.name||'');setSubject(t?.subject_template||'');setBody(t?.body_template||'');setOffset(String(t?.day_offset??0))}
  return <section className="admin-card"><div className="section-head"><div><div className="kpi">Admin-Editable Templates</div><h2>Outreach sequence copy</h2><p className="small muted">Supported placeholders include {'{{business_name}}'}, {'{{contact_name_or_team}}'}, {'{{service_name}}'}, {'{{evidence_summary}}'}, {'{{city}}'}. Templates create drafts/tasks only.</p></div></div>{templates.length?<div className="grid grid-2"><label className="field"><span>Template</span><select value={first} onChange={e=>select(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · {titleCase(t.channel)} · Day {t.day_offset}</option>)}</select></label><label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Day Offset</span><input type="number" min="0" value={offset} onChange={e=>setOffset(e.target.value)}/></label><label className="field"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="field" style={{gridColumn:'1/-1'}}><span>Body</span><textarea rows={8} value={body} onChange={e=>setBody(e.target.value)}/></label><div><button className="btn btn-primary" type="button" disabled={Boolean(busy)||!current} onClick={()=>act({action:'save_template',id:current?.id,name,channel:current?.channel,sequence_stage:current?.sequence_stage,service_slug:current?.service_slug,vertical:current?.vertical,day_offset:offset,subject_template:subject,body_template:body,active:current?.active!==false,sort_order:current?.sort_order},`template-${current?.id}`,'Template saved.')}>Save Template</button></div></div>:<div className="notice">No Sales 3.4 templates are available.</div>}</section>
}
