'use client'
import Link from 'next/link'
import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'

type Row=Record<string,any>
type Props={actions:Row[];settings:Row;metrics:Row[];opportunities:Row[];campaigns:Row[];services:Row[];meetings:Row[];automationRuns:Row[];integrationStatus:Row}
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0)/100)
const when=(v:any)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
const rel=(v:any)=>Array.isArray(v)?v[0]||null:v||null
const label=(v:string)=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const rank:Record<string,number>={urgent:4,high:3,medium:2,low:1}
const stageOrder=['proposal','qualified','contacted','contact_ready','nurture','research','new']
const actionHref=(t:string)=>t==='reply_review'||t==='unmatched_inbound_review'||t==='response_approval'?'/admin/skylight-sales/inbox':t==='followup_due'?'/admin/skylight-sales/outreach':t==='meeting_upcoming'||t==='win_loss_review'?'/admin/skylight-sales/conversions':t.startsWith('proposal_')||t==='client_project_handoff'?'/admin/skylight-operations':t.startsWith('invoice_')?'/admin/skylight-invoices':'/admin/skylight-sales'

export function SalesDailyOperatingSystem({actions,settings,metrics,opportunities,campaigns,services,meetings,automationRuns,integrationStatus}:Props){
  const router=useRouter(),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[priority,setPriority]=useState('all'),[typeFilter,setTypeFilter]=useState('all'),[probe,setProbe]=useState<Row|null>(null)
  const [form,setForm]=useState<Row>(()=>({
    stale_opportunity_days:settings.stale_opportunity_days??14,proposal_sent_followup_days:settings.proposal_sent_followup_days??3,proposal_viewed_followup_days:settings.proposal_viewed_followup_days??2,proposal_expiring_days:settings.proposal_expiring_days??3,meeting_reminder_hours:settings.meeting_reminder_hours??24,invoice_due_soon_days:settings.invoice_due_soon_days??3,hot_score_threshold:settings.hot_score_threshold??80,
    weight_new_pct:Number(settings.weight_new_bps??500)/100,weight_research_pct:Number(settings.weight_research_bps??500)/100,weight_contact_ready_pct:Number(settings.weight_contact_ready_bps??1500)/100,weight_contacted_pct:Number(settings.weight_contacted_bps??2500)/100,weight_qualified_pct:Number(settings.weight_qualified_bps??5000)/100,weight_proposal_pct:Number(settings.weight_proposal_bps??7500)/100,weight_nurture_pct:Number(settings.weight_nurture_bps??1000)/100,
    action_queue_enabled:settings.action_queue_enabled!==false,auto_create_tasks:settings.auto_create_tasks!==false,daily_snapshot_enabled:settings.daily_snapshot_enabled!==false
  }))
  const [forecastEdits,setForecastEdits]=useState<Record<string,{value:string;date:string}>>(()=>Object.fromEntries(opportunities.map(o=>[o.id,{value:o.estimated_value_cents==null?'':String((Number(o.estimated_value_cents)||0)/100),date:String(o.expected_close_date||'')}])) )
  async function post(payload:Row){const r=await fetch('/api/admin/skylight-sales/daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||'Action failed.');return j}
  async function run(key:string,payload:Row={}){setBusy(key);setMessage('');try{const j=await post({action:key,...payload});setMessage(key==='activate_resend_inbound'?'Inbound Resend webhook is activated and stored server-side.':key==='create_google_calendar_event'?'Google Calendar event created successfully.':'Saved.');if(key==='probe_integrations')setProbe(j.data||{});router.refresh();return j}catch(e:any){setMessage(String(e?.message||e))}finally{setBusy('')}}
  async function saveSettings(){setBusy('settings');setMessage('');try{await post({action:'save_settings',stale_opportunity_days:form.stale_opportunity_days,proposal_sent_followup_days:form.proposal_sent_followup_days,proposal_viewed_followup_days:form.proposal_viewed_followup_days,proposal_expiring_days:form.proposal_expiring_days,meeting_reminder_hours:form.meeting_reminder_hours,invoice_due_soon_days:form.invoice_due_soon_days,hot_score_threshold:form.hot_score_threshold,weight_new_bps:Math.round(Number(form.weight_new_pct||0)*100),weight_research_bps:Math.round(Number(form.weight_research_pct||0)*100),weight_contact_ready_bps:Math.round(Number(form.weight_contact_ready_pct||0)*100),weight_contacted_bps:Math.round(Number(form.weight_contacted_pct||0)*100),weight_qualified_bps:Math.round(Number(form.weight_qualified_pct||0)*100),weight_proposal_bps:Math.round(Number(form.weight_proposal_pct||0)*100),weight_nurture_bps:Math.round(Number(form.weight_nurture_pct||0)*100),action_queue_enabled:Boolean(form.action_queue_enabled),auto_create_tasks:Boolean(form.auto_create_tasks),daily_snapshot_enabled:Boolean(form.daily_snapshot_enabled)});setMessage('Operating thresholds and forecast weights saved.');router.refresh()}catch(e:any){setMessage(String(e?.message||e))}finally{setBusy('')}}
  async function saveForecast(o:Row){const edit=forecastEdits[o.id]||{value:'',date:''};await run('update_forecast',{opportunity_id:o.id,estimated_value:edit.value,expected_close_date:edit.date})}

  const oppMap=useMemo(()=>new Map(opportunities.map(o=>[String(o.id),o])),[opportunities]),campaignMap=useMemo(()=>new Map(campaigns.map(c=>[String(c.id),c])),[campaigns]),serviceMap=useMemo(()=>new Map(services.map(s=>[String(s.slug),s])),[services])
  const now=Date.now(),liveActions=actions.filter(a=>['open','in_progress'].includes(String(a.status))&&(!a.snoozed_until||new Date(a.snoozed_until).getTime()<=now))
  const actionTypes=Array.from(new Set(liveActions.map(a=>String(a.action_type)))).sort()
  const filtered=liveActions.filter(a=>priority==='all'||a.priority===priority).filter(a=>typeFilter==='all'||a.action_type===typeFilter).filter(a=>{if(!search.trim())return true;const o=oppMap.get(String(a.opportunity_id)),p=rel(o?.prospect),hay=`${a.title} ${a.reason} ${a.recommended_action} ${p?.business_name||''} ${p?.city||''}`.toLowerCase();return hay.includes(search.toLowerCase())}).sort((a,b)=>(rank[b.priority]||0)-(rank[a.priority]||0)||(new Date(a.due_at||a.created_at).getTime()-new Date(b.due_at||b.created_at).getTime()))
  const weights:Record<string,number>={new:Number(settings.weight_new_bps??500)/10000,research:Number(settings.weight_research_bps??500)/10000,contact_ready:Number(settings.weight_contact_ready_bps??1500)/10000,contacted:Number(settings.weight_contacted_bps??2500)/10000,qualified:Number(settings.weight_qualified_bps??5000)/10000,proposal:Number(settings.weight_proposal_bps??7500)/10000,nurture:Number(settings.weight_nurture_bps??1000)/10000}
  const active=opportunities.filter(o=>o.active&&!['won','lost'].includes(String(o.stage))),pipeline=active.reduce((n,o)=>n+Number(o.estimated_value_cents||0),0),weighted=active.reduce((n,o)=>n+Number(o.estimated_value_cents||0)*(weights[String(o.stage)]??0),0)
  const today=new Date().toISOString().slice(0,10),datePlus=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10),weightedBy=(days:number)=>active.filter(o=>o.expected_close_date&&String(o.expected_close_date)<=datePlus(days)).reduce((n,o)=>n+Number(o.estimated_value_cents||0)*(weights[String(o.stage)]??0),0),undated=active.filter(o=>!o.expected_close_date).reduce((n,o)=>n+Number(o.estimated_value_cents||0),0)
  const latestDate=metrics.map(m=>String(m.metric_date||'')).sort().reverse()[0]||'',latest=metrics.filter(m=>String(m.metric_date)===latestDate),overall=latest.find(m=>m.dimension_type==='overall')||{},campaignRows=latest.filter(m=>m.dimension_type==='campaign').sort((a,b)=>Number(b.paid_revenue_cents||0)-Number(a.paid_revenue_cents||0)),serviceRows=latest.filter(m=>m.dimension_type==='service').sort((a,b)=>Number(b.paid_revenue_cents||0)-Number(a.paid_revenue_cents||0))
  const paid=Number(overall.paid_revenue_cents??opportunities.reduce((n,o)=>n+Number(o.attributed_revenue_cents||0),0)),overdue=liveActions.filter(a=>a.due_at&&new Date(a.due_at).getTime()<now).length,urgent=liveActions.filter(a=>a.priority==='urgent').length
  const stages=stageOrder.map(stage=>{const rows=active.filter(o=>o.stage===stage),value=rows.reduce((n,o)=>n+Number(o.estimated_value_cents||0),0);return {stage,count:rows.length,value,weighted:rows.reduce((n,o)=>n+Number(o.estimated_value_cents||0)*(weights[stage]??0),0)}}).filter(x=>x.count)
  const reasons=Array.from(opportunities.filter(o=>['won','lost'].includes(String(o.stage))).reduce((m,o)=>{const k=String(o.outcome_reason_code||o.lost_reason||'Unspecified');m.set(k,(m.get(k)||0)+1);return m},new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]).slice(0,10)
  const forecastRows=active.filter(o=>['contact_ready','contacted','qualified','proposal','nurture'].includes(String(o.stage))).sort((a,b)=>stageOrder.indexOf(String(a.stage))-stageOrder.indexOf(String(b.stage))||Number(b.estimated_value_cents||0)-Number(a.estimated_value_cents||0)).slice(0,60)
  const upcomingMeetings=meetings.filter(m=>m.status==='scheduled'&&new Date(m.scheduled_at).getTime()>=now).slice(0,20)
  const monthlyPipeline=active.filter(o=>String(serviceMap.get(String(o.primary_service_slug))?.default_billing_interval||'')==='monthly').reduce((n,o)=>n+Number(o.estimated_value_cents||0),0),oneTimePipeline=active.filter(o=>String(serviceMap.get(String(o.primary_service_slug))?.default_billing_interval||'one_time')!=='monthly').reduce((n,o)=>n+Number(o.estimated_value_cents||0),0)

  return <div style={{marginTop:22}}>
    {message?<div className={/failed|required|unable|not configured/i.test(message)?'notice warn':'notice'} style={{marginBottom:16}}>{message}</div>:null}
    <section className="admin-card" style={{marginBottom:18}}><div className="admin-page-head"><div><h2>Today’s Operating Queue</h2><p className="muted">Generated from real system state. Tasks can be automated; customer communication, proposals, billing changes, DNC decisions and public ranking changes cannot.</p></div><div className="admin-row-actions"><button className="btn btn-primary" disabled={!!busy} onClick={()=>run('refresh_operating_system')}>{busy==='refresh_operating_system'?'Refreshing…':'Refresh Everything Now'}</button><Link className="btn btn-light" href="/admin/skylight-sales/inbox">Open Inbox</Link></div></div>
      <div className="stat-grid"><div className="stat">Open Actions<strong>{liveActions.length}</strong><small>{urgent} urgent · {overdue} overdue</small></div><div className="stat">Unweighted Pipeline<strong>{money(pipeline)}</strong><small>staff-entered opportunity values</small></div><div className="stat">Weighted Pipeline<strong>{money(weighted)}</strong><small>editable stage assumptions</small></div><div className="stat">30-Day Weighted<strong>{money(weightedBy(30))}</strong><small>only staff-dated opportunities</small></div><div className="stat">60-Day Weighted<strong>{money(weightedBy(60))}</strong></div><div className="stat">90-Day Weighted<strong>{money(weightedBy(90))}</strong></div><div className="stat">Undated Pipeline<strong>{money(undated)}</strong><small>not guessed into a forecast month</small></div><div className="stat">Attributed Paid Revenue<strong>{money(paid)}</strong><small>explicitly linked invoice payments only</small></div><div className="stat">Win Rate<strong>{overall.win_rate_bps==null?'—':`${(Number(overall.win_rate_bps)/100).toFixed(1)}%`}</strong></div><div className="stat">Avg. Days to Win<strong>{overall.avg_days_to_win==null?'—':Number(overall.avg_days_to_win).toFixed(1)}</strong><small>first attributed touch → Won</small></div></div>
    </section>

    <section className="admin-card" style={{marginBottom:18}}><div className="admin-page-head"><div><h2>Next Best Actions</h2><p className="muted">The system recommends the administrative next move; staff decides whether and how to act.</p></div></div>
      <div className="admin-row-actions" style={{marginBottom:14}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search actions or businesses" style={{minWidth:260}}/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">All action types</option>{actionTypes.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></div>
      <div style={{display:'grid',gap:12}}>{filtered.length?filtered.map(a=>{const o=oppMap.get(String(a.opportunity_id)),p=rel(o?.prospect);return <article className="admin-card" key={a.id} style={{padding:16}}><div className="admin-page-head"><div><div className="kpi">{String(a.priority).toUpperCase()} · {label(a.action_type)}</div><h3 style={{margin:'4px 0'}}>{a.title}</h3><p className="muted" style={{margin:0}}>{p?.business_name?`${p.business_name}${p.city?` · ${p.city}`:''}`:'System-level Sales action'}</p></div><div className="admin-row-actions"><Link className="btn btn-light" href={actionHref(String(a.action_type))}>Open Workspace</Link></div></div><p><strong>Why:</strong> {a.reason}</p><p><strong>Recommended:</strong> {a.recommended_action}</p><p className="small muted">Due: {when(a.due_at)}{a.snoozed_until?` · Snoozed until ${when(a.snoozed_until)}`:''}</p><div className="admin-row-actions"><button className="btn btn-light" disabled={!!busy} onClick={()=>run('set_action_status',{id:a.id,status:'in_progress'})}>Start</button><button className="btn btn-primary" disabled={!!busy} onClick={()=>run('set_action_status',{id:a.id,status:'completed'})}>Complete</button><button className="btn btn-light" disabled={!!busy} onClick={()=>run('snooze_action',{id:a.id,until:new Date(Date.now()+86400000).toISOString()})}>Snooze 1 Day</button><button className="btn btn-light" disabled={!!busy} onClick={()=>run('set_action_status',{id:a.id,status:'dismissed'})}>Dismiss</button>{a.action_type==='meeting_upcoming'&&a.meeting_id?<><button className="btn btn-light" disabled={!!busy||!integrationStatus.google_calendar_credentials} onClick={()=>run('create_google_calendar_event',{meeting_id:a.meeting_id,send_invite:false})}>Create Calendar Event</button><button className="btn btn-light" disabled={!!busy||!integrationStatus.google_calendar_credentials} onClick={()=>{if(confirm('Create this Google Calendar event and send the prospect an invitation?'))run('create_google_calendar_event',{meeting_id:a.meeting_id,send_invite:true})}}>Create + Send Invite</button></>:null}</div></article>}):<div className="notice">No actions match the current filters.</div>}</div>
    </section>

    <section className="admin-card" style={{marginBottom:18}}><div className="admin-page-head"><div><h2>30 / 60 / 90 Forecast Editor</h2><p className="muted">Expected close dates and values are staff-entered. Undated opportunities remain outside the dated forecast.</p></div></div>{forecastRows.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">Business</th><th align="left">Stage</th><th align="right">Value</th><th align="left">Expected Close</th><th></th></tr></thead><tbody>{forecastRows.map(o=>{const p=rel(o.prospect),e=forecastEdits[o.id]||{value:'',date:''};return <tr key={o.id}><td>{p?.business_name||o.id}</td><td>{label(o.stage)}</td><td><input type="number" min="0" step="1" value={e.value} onChange={x=>setForecastEdits(v=>({...v,[o.id]:{...e,value:x.target.value}}))} style={{width:120,textAlign:'right'}}/></td><td><input type="date" value={e.date} onChange={x=>setForecastEdits(v=>({...v,[o.id]:{...e,date:x.target.value}}))}/></td><td><button className="btn btn-light" disabled={!!busy} onClick={()=>saveForecast(o)}>Save</button></td></tr>})}</tbody></table></div>:<div className="notice">No Contact Ready-or-later opportunities currently need forecast dates.</div>}</section>

    <section className="admin-card" style={{marginBottom:18}}><h2>Pipeline & Acquisition Intelligence</h2><p className="muted">3.8 foundation uses first real sent-outreach attribution. Campaign revenue is not reassigned by later touches.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:18}}><div><h3>Pipeline by Stage</h3><table style={{width:'100%'}}><tbody>{stages.map(x=><tr key={x.stage}><td>{label(x.stage)}</td><td align="right">{x.count}</td><td align="right">{money(x.value)}</td><td align="right">{money(x.weighted)}</td></tr>)}</tbody></table></div><div><h3>Billing-Default Pipeline Mix</h3><p>Monthly-service pipeline: <strong>{money(monthlyPipeline)}</strong></p><p>One-time/other pipeline: <strong>{money(oneTimePipeline)}</strong></p><p className="small muted">This is pipeline mix by service billing default—not cash MRR. Actual revenue remains the paid-invoice metric.</p></div></div>
      <h3 style={{marginTop:20}}>Revenue by First-Touch Campaign</h3>{campaignRows.length?<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th align="left">Campaign</th><th align="right">Opps</th><th align="right">Replies</th><th align="right">Qualified</th><th align="right">Proposals</th><th align="right">Won</th><th align="right">Paid Revenue</th></tr></thead><tbody>{campaignRows.map(r=><tr key={r.dimension_key}><td>{campaignMap.get(String(r.dimension_key))?.name||String(r.dimension_key)}</td><td align="right">{r.opportunities}</td><td align="right">{r.replies}</td><td align="right">{r.qualified}</td><td align="right">{r.proposals}</td><td align="right">{r.won}</td><td align="right"><strong>{money(r.paid_revenue_cents)}</strong></td></tr>)}</tbody></table></div>:<div className="notice">No first-touch campaign attribution exists yet. This will populate from real sent outreach.</div>}
      <h3 style={{marginTop:20}}>Revenue by Service</h3>{serviceRows.length?<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th align="left">Service</th><th align="right">Opps</th><th align="right">Replies</th><th align="right">Proposal Value</th><th align="right">Won</th><th align="right">Paid Revenue</th></tr></thead><tbody>{serviceRows.map(r=><tr key={r.dimension_key}><td>{serviceMap.get(String(r.dimension_key))?.name||label(String(r.dimension_key))}</td><td align="right">{r.opportunities}</td><td align="right">{r.replies}</td><td align="right">{money(r.proposal_value_cents)}</td><td align="right">{r.won}</td><td align="right"><strong>{money(r.paid_revenue_cents)}</strong></td></tr>)}</tbody></table></div>:null}
    </section>

    <section className="admin-card" style={{marginBottom:18}}><h2>Win / Loss Intelligence</h2>{reasons.length?<div style={{display:'grid',gap:8}}>{reasons.map(([reason,count])=><div key={reason} style={{display:'flex',justifyContent:'space-between',gap:16}}><span>{label(reason)}</span><strong>{count}</strong></div>)}</div>:<div className="notice">No Won/Lost outcome reasons have been recorded yet. The action queue will flag closed deals missing a reason instead of inventing one.</div>}</section>

    <section className="admin-card" style={{marginBottom:18}}><div className="admin-page-head"><div><h2>Integrations</h2><p className="muted">Integration setup may be automated; communication and calendar invitations still require explicit staff actions.</p></div><button className="btn btn-light" disabled={!!busy} onClick={async()=>{setBusy('probe_integrations');setMessage('');try{const j=await post({action:'probe_integrations'});setProbe(j.data||{});setMessage('Integration status refreshed.')}catch(e:any){setMessage(String(e?.message||e))}finally{setBusy('')}}}>Probe Integrations</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:18}}><div className="admin-card"><h3>Resend Inbound Email</h3><p>API key: <strong>{integrationStatus.resend_api_key?'Detected':'Missing'}</strong></p><p>Server database credential: <strong>{integrationStatus.supabase_service_role?'Detected':'Missing'}</strong></p><p>Webhook verification secret: <strong>{integrationStatus.resend_env_webhook_secret||integrationStatus.resend_stored_webhook_secret?'Detected':'Missing'}</strong></p><p>Dedicated reply-to: <strong>{integrationStatus.sales_reply_to?'Detected':'Not set'}</strong></p>{probe?<p>Registered webhook: <strong>{probe.resend_webhook_registered?'Yes':'No'}</strong></p>:null}<button className="btn btn-primary" disabled={!!busy||!integrationStatus.resend_api_key||!integrationStatus.supabase_service_role} onClick={()=>run('activate_resend_inbound')}>{busy==='activate_resend_inbound'?'Activating…':'Activate / Repair Inbound Email'}</button><p className="small muted">This configures the signed webhook only. It does not send outreach.</p></div><div className="admin-card"><h3>Google Calendar</h3><p>OAuth credentials: <strong>{integrationStatus.google_calendar_credentials?'Detected':'Missing'}</strong></p><p>Calendar target: <strong>{integrationStatus.google_calendar_id?'Configured ID':'Primary calendar'}</strong></p><p className="small muted">Creating an event is always a staff click. Sending a guest invitation is a separate confirmed click.</p></div></div>
      {upcomingMeetings.length?<><h3 style={{marginTop:20}}>Upcoming Meetings</h3><div style={{display:'grid',gap:10}}>{upcomingMeetings.map(m=>{const o=oppMap.get(String(m.opportunity_id)),p=rel(o?.prospect);return <div key={m.id} className="admin-card" style={{padding:14}}><strong>{p?.business_name||'Sales meeting'}</strong> · {when(m.scheduled_at)} · {label(m.calendar_sync_status||'not_linked')}<div className="admin-row-actions" style={{marginTop:8}}>{m.external_calendar_url?<a className="btn btn-light" href={m.external_calendar_url} target="_blank" rel="noreferrer">Open Calendar Event</a>:<><button className="btn btn-light" disabled={!!busy||!integrationStatus.google_calendar_credentials} onClick={()=>run('create_google_calendar_event',{meeting_id:m.id,send_invite:false})}>Create Event</button><button className="btn btn-light" disabled={!!busy||!integrationStatus.google_calendar_credentials} onClick={()=>{if(confirm('Send a Google Calendar invitation to the verified prospect email?'))run('create_google_calendar_event',{meeting_id:m.id,send_invite:true})}}>Create + Invite</button></>}</div></div>})}</div></>:null}
    </section>

    <section className="admin-card" style={{marginBottom:18}}><h2>Operating Rules & Forecast Assumptions</h2><p className="muted">These thresholds are editable. They determine when an administrative action appears; they never authorize outreach or money movement.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{[['stale_opportunity_days','Stalled after days'],['proposal_sent_followup_days','Sent proposal follow-up days'],['proposal_viewed_followup_days','Viewed proposal follow-up days'],['proposal_expiring_days','Proposal expiration warning days'],['meeting_reminder_hours','Meeting reminder hours'],['invoice_due_soon_days','Invoice due-soon days'],['hot_score_threshold','Hot score threshold']].map(([k,l])=><label key={k}>{l}<input type="number" value={form[k]} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}</div><h3 style={{marginTop:18}}>Stage Forecast Weights</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}>{[['weight_new_pct','New'],['weight_research_pct','Research'],['weight_contact_ready_pct','Contact Ready'],['weight_contacted_pct','Contacted'],['weight_qualified_pct','Qualified'],['weight_proposal_pct','Proposal'],['weight_nurture_pct','Nurture']].map(([k,l])=><label key={k}>{l} %<input type="number" min="0" max="100" step="1" value={form[k]} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}</div><div className="admin-row-actions" style={{marginTop:16}}><label><input type="checkbox" checked={Boolean(form.action_queue_enabled)} onChange={e=>setForm(v=>({...v,action_queue_enabled:e.target.checked}))}/> Action queue enabled</label><label><input type="checkbox" checked={Boolean(form.auto_create_tasks)} onChange={e=>setForm(v=>({...v,auto_create_tasks:e.target.checked}))}/> Auto-create administrative tasks</label><label><input type="checkbox" checked={Boolean(form.daily_snapshot_enabled)} onChange={e=>setForm(v=>({...v,daily_snapshot_enabled:e.target.checked}))}/> Daily factual snapshots</label><button className="btn btn-primary" disabled={!!busy} onClick={saveSettings}>{busy==='settings'?'Saving…':'Save Operating Rules'}</button></div></section>

    <section className="admin-card"><h2>Automation Audit</h2><p className="muted">Database-native daily refresh records every run. No customer send action is performed by these jobs.</p><div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th align="left">Started</th><th align="left">Run</th><th align="left">Source</th><th align="left">Status</th><th align="right">Generated/Open</th><th align="right">Updated/Resolved</th></tr></thead><tbody>{automationRuns.slice(0,25).map(r=><tr key={r.id}><td>{when(r.started_at)}</td><td>{label(r.run_type)}</td><td>{label(r.source)}</td><td>{label(r.status)}</td><td align="right">{r.generated_count}</td><td align="right">{r.updated_count}</td></tr>)}</tbody></table></div></section>
  </div>
}
