'use client'

import { useMemo,useState } from 'react'

type Row=Record<string,any>
type Props={opportunities:Row[];threads:Row[];replies:Row[];outreach:Row[];responseDrafts:Row[];meetings:Row[];handoffs:Row[];unmatched:Row[];proposals:Row[];projects:Row[];invoices:Row[];revenueLinks:Row[];inboundConfigured:boolean}
const relation=(v:any)=>Array.isArray(v)?v[0]||{}:v||{}
const fmt=(v:any)=>v?new Date(String(v)).toLocaleString():'—'
const dollars=(c:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(c||0)/100)
const clip=(v:any,n=160)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n)
const enc=(v:string)=>encodeURIComponent(v)
function calendarUrl(m:Row,business:string){const start=new Date(m.scheduled_at),end=new Date(start.getTime()+Number(m.duration_minutes||30)*60000),z=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${enc(`Skylight Sales — ${business}`)}&dates=${z(start)}/${z(end)}&details=${enc(m.notes||'Skylight Reflections Marketing sales meeting')}&location=${enc(m.location_detail||m.location_type||'')}`}

export function SalesInboxWorkbench({opportunities,threads,replies,outreach,responseDrafts,meetings,handoffs,unmatched,proposals,projects,invoices,revenueLinks,inboundConfigured}:Props){
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
  const oppById=useMemo(()=>new Map<string,Row>(opportunities.map(o=>[String(o.id),o])),[opportunities])
  const nameFor=(id:any)=>{const o=oppById.get(String(id)),p=relation(o?.prospect);return p.business_name||`Opportunity ${String(id||'').slice(0,8)}`}
  const derivedThreads=useMemo<Row[]>(()=>{const map=new Map<string,Row>();for(const t of threads)map.set(String(t.opportunity_id),t);for(const r of replies)if(!map.has(String(r.opportunity_id)))map.set(String(r.opportunity_id),{opportunity_id:r.opportunity_id,prospect_id:r.prospect_id,status:'waiting_on_us',unread_count:r.review_status==='pending'?1:0,last_activity_at:r.received_at,last_inbound_at:r.received_at,last_subject:r.subject});for(const d of outreach)if(!map.has(String(d.opportunity_id)))map.set(String(d.opportunity_id),{opportunity_id:d.opportunity_id,prospect_id:d.prospect_id,status:'waiting_on_them',unread_count:0,last_activity_at:d.sent_at,last_outbound_at:d.sent_at,last_subject:d.subject});return [...map.values()].sort((a,b)=>new Date(String(b.last_activity_at||0)).getTime()-new Date(String(a.last_activity_at||0)).getTime())},[threads,replies,outreach])
  const [selected,setSelected]=useState(String(derivedThreads[0]?.opportunity_id||opportunities.find(o=>o.active)?.id||''))
  const selectedOpp=oppById.get(selected)||null
  const latestInbound=useMemo(()=>replies.filter(r=>String(r.opportunity_id)===selected).sort((a,b)=>new Date(b.received_at).getTime()-new Date(a.received_at).getTime())[0]||null,[replies,selected])
  const conversation=useMemo<Row[]>(()=>{const rows:Row[]=[];outreach.filter(d=>String(d.opportunity_id)===selected).forEach(d=>rows.push({kind:'outbound',at:d.sent_at,subject:d.subject,body:d.body,status:'sent',id:`o-${d.id}`}));replies.filter(r=>String(r.opportunity_id)===selected).forEach(r=>rows.push({kind:'inbound',at:r.received_at,subject:r.subject,body:r.body,status:r.review_status,classification:r.confirmed_classification||r.classification_suggestion,id:`r-${r.id}`}));responseDrafts.filter(d=>String(d.opportunity_id)===selected).forEach(d=>rows.push({kind:d.status==='sent'?'outbound':'draft',at:d.sent_at||d.updated_at||d.created_at,subject:d.subject,body:d.body,status:d.status,id:`d-${d.id}`,draft:d}));return rows.sort((a,b)=>new Date(String(a.at||0)).getTime()-new Date(String(b.at||0)).getTime())},[selected,outreach,replies,responseDrafts])
  const openDrafts=responseDrafts.filter(d=>['draft','approved'].includes(String(d.status))),active=opportunities.filter(o=>o.active)
  const proposalById=useMemo(()=>new Map<string,Row>(proposals.map(p=>[String(p.id),p])),[proposals]),projectById=useMemo(()=>new Map<string,Row>(projects.map(p=>[String(p.id),p])),[projects]),invoiceById=useMemo(()=>new Map<string,Row>(invoices.map(i=>[String(i.id),i])),[invoices])
  async function post(payload:Row,key:string){setBusy(key);setError('');setMessage('');try{const r=await fetch('/api/admin/skylight-sales/inbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Sales Inbox action failed.');setMessage('Saved. Refreshing Sales 3.6…');window.location.reload()}catch(e:any){setError(e?.message||'Sales Inbox action failed.')}finally{setBusy('')}}

  return <div style={{display:'grid',gap:24,marginTop:24}}>
    {message?<div className="notice"><strong>{message}</strong></div>:null}{error?<div className="notice warn"><strong>{error}</strong></div>:null}
    <section className="admin-card">
      <div className="admin-page-head"><div><div className="kpi">Unified conversation workspace</div><h2>Sales Inbox</h2><p className="muted">Inbound mail can be captured automatically when the signed Resend webhook is configured. Every reply draft still requires a separate approval before Send.</p></div><span className="pill">{inboundConfigured?'Inbound ready':'Manual capture still available'}</span></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16,alignItems:'start'}}>
        <div style={{display:'grid',gap:8,maxHeight:720,overflowY:'auto'}}>{derivedThreads.length===0?<p className="muted">No conversation threads yet.</p>:derivedThreads.slice(0,250).map(t=><button key={t.opportunity_id} type="button" onClick={()=>setSelected(String(t.opportunity_id))} className={selected===String(t.opportunity_id)?'notice':'admin-card'} style={{textAlign:'left',padding:12,cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{nameFor(t.opportunity_id)}</strong>{Number(t.unread_count||0)>0?<span className="pill">{t.unread_count} unread</span>:null}</div><small>{String(t.status||'thread').replaceAll('_',' ')} · {fmt(t.last_activity_at)}</small><br/><small className="muted">{clip(t.last_subject||'',90)}</small></button>)}</div>
        <div>{!selectedOpp?<p className="muted">Select a conversation.</p>:<><div className="admin-page-head"><div><h3>{nameFor(selected)}</h3><p className="muted">{relation(selectedOpp.prospect)?.owner_contact_name||'Decision maker'} · {relation(selectedOpp.prospect)?.owner_contact_email||'No email'} · stage {selectedOpp.stage}</p></div><div className="admin-row-actions"><button className="btn btn-light" onClick={()=>post({action:'mark_thread_read',opportunity_id:selected},`read-${selected}`)}>Mark Read</button><button className="btn btn-light" onClick={()=>post({action:'close_thread',opportunity_id:selected},`close-${selected}`)}>Close Thread</button></div></div>
          <div style={{display:'grid',gap:10,maxHeight:460,overflowY:'auto',paddingRight:4}}>{conversation.length===0?<p className="muted">No messages loaded for this thread.</p>:conversation.map(m=><div key={m.id} className="notice" style={{padding:12,marginLeft:m.kind==='outbound'?28:0,marginRight:m.kind==='inbound'?28:0}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{m.kind==='inbound'?'Inbound':m.kind==='draft'?'Response Draft':'Outbound'}</strong><span className="pill">{m.status||''}</span></div><small>{fmt(m.at)}{m.classification?` · ${m.classification}`:''}</small>{m.subject?<h4 style={{margin:'8px 0 4px'}}>{m.subject}</h4>:null}<div style={{whiteSpace:'pre-wrap'}}>{String(m.body||'').slice(0,5000)}</div>{m.draft&&m.draft.status==='draft'?<div className="admin-row-actions" style={{marginTop:8}}><button className="btn btn-primary" disabled={busy===`approve-${m.draft.id}`} onClick={()=>post({action:'approve_response_draft',id:m.draft.id},`approve-${m.draft.id}`)}>Approve Response</button></div>:null}{m.draft&&m.draft.status==='approved'?<div className="admin-row-actions" style={{marginTop:8}}><button className="btn btn-primary" disabled={busy===`send-${m.draft.id}`} onClick={()=>post({action:'send_response_draft',id:m.draft.id},`send-${m.draft.id}`)}>Send Approved Response</button></div>:null}</div>)}</div>
          <ResponseComposer opportunityId={selected} reply={latestInbound} busy={busy} onPost={post}/></>}</div>
      </div>
    </section>
    <section className="admin-card"><div className="admin-page-head"><div><div className="kpi">Never drop a genuine reply</div><h2>Unmatched Inbound Quarantine</h2><p className="muted">Messages that cannot be safely matched by RFC thread headers or verified sender email stay here until staff attaches or dismisses them.</p></div><span className="pill">{unmatched.length}</span></div>{unmatched.length===0?<p className="muted">No unmatched inbound messages.</p>:<div style={{display:'grid',gap:10}}>{unmatched.slice(0,100).map(u=><UnmatchedRow key={u.id} row={u} opportunities={active} nameFor={nameFor} busy={busy} onPost={post}/>)}</div>}</section>
    <section className="admin-card"><div className="admin-page-head"><div><div className="kpi">Human-reviewed handoff → draft proposal</div><h2>Proposal Production Queue</h2><p className="muted">A Ready handoff can create a real Skylight proposal in Draft status. This does not send it. If the handoff has a staff-entered estimate, that amount becomes the draft line item; otherwise the proposal is created at $0 and explicitly requires pricing review.</p></div></div><div style={{display:'grid',gap:10}}>{handoffs.length===0?<p className="muted">No open handoffs.</p>:handoffs.slice(0,150).map(h=><div className="notice" key={h.id} style={{padding:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong>{h.title}</strong> · {nameFor(h.opportunity_id)}<br/><small>{(h.recommended_service_slugs||[]).join(', ')||'Services TBD'} · estimate {dollars(h.estimated_value_cents)}</small></div><span className="pill">{h.status}</span></div><p className="small">{h.scope_notes||'No scope notes.'}</p>{h.status==='ready'?<button className="btn btn-primary" disabled={busy===`proposal-${h.id}`} onClick={()=>post({action:'create_proposal_from_handoff',handoff_id:h.id},`proposal-${h.id}`)}>Create Draft Proposal — Do Not Send</button>:<span className="small muted">Mark this handoff Ready in Conversion 3.5 before proposal creation.</span>}</div>)}</div></section>
    <section className="admin-card"><div className="admin-page-head"><div><div className="kpi">Meeting handoff</div><h2>Upcoming Meetings</h2><p className="muted">Open an explicit Google Calendar event draft for any scheduled meeting. The calendar link does not send an invitation by itself.</p></div></div><div style={{display:'grid',gap:10}}>{meetings.filter(m=>m.status==='scheduled').slice(0,100).map(m=><div className="notice" key={m.id} style={{padding:12,display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{nameFor(m.opportunity_id)}</strong> · {m.meeting_type}<br/><small>{fmt(m.scheduled_at)} · {m.duration_minutes||30} min · {m.location_type}{m.location_detail?` · ${m.location_detail}`:''}</small></div><a className="btn btn-light" href={calendarUrl(m,nameFor(m.opportunity_id))} target="_blank" rel="noreferrer">Open Google Calendar Draft</a></div>)}</div></section>
    <section className="admin-card"><div className="admin-page-head"><div><div className="kpi">Lifecycle + paid revenue attribution</div><h2>Revenue Operations</h2><p className="muted">Proposal totals are pipeline value. Attributed revenue only counts <strong>amount_paid_cents</strong> from an invoice explicitly linked to the Sales opportunity. Client-wide unrelated invoices are never swept in.</p></div></div><div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Opportunity</th><th>Proposal</th><th>Project</th><th>Invoice</th><th>Paid Revenue</th><th>Action</th></tr></thead><tbody>{opportunities.filter(o=>o.client_id||o.proposal_id||o.invoice_id||o.project_id).slice(0,300).map(o=>{const p=proposalById.get(String(o.proposal_id||'')),pj=projectById.get(String(o.project_id||''))||projects.find(x=>x.proposal_id&&x.proposal_id===o.proposal_id),inv=invoiceById.get(String(o.invoice_id||''));return <tr key={o.id}><td><strong>{nameFor(o.id)}</strong><br/><small>{o.stage}</small></td><td>{p?<><strong>{p.proposal_number}</strong><br/><small>{p.status} · {dollars(p.total_cents)}</small></>:'—'}</td><td>{pj?<><strong>{pj.project_number}</strong><br/><small>{pj.status} · {pj.progress_pct||0}%</small></>:'—'}</td><td>{inv?<><strong>{inv.invoice_number}</strong><br/><small>{inv.status} · {dollars(inv.total_cents)}</small></>:'—'}</td><td><strong>{dollars(o.attributed_revenue_cents)}</strong></td><td><button className="btn btn-light" disabled={busy===`sync-${o.id}`} onClick={()=>post({action:'sync_revenue',opportunity_id:o.id},`sync-${o.id}`)}>Sync Lifecycle / Paid Revenue</button></td></tr>})}</tbody></table></div><p className="small muted" style={{marginTop:10}}>Audit links stored: {revenueLinks.length}. Syncing is internal reconciliation only; it does not charge a card, issue an invoice, send a proposal, mark a sale Won, or create Sponsored placement.</p></section>
    <section className="admin-card"><div className="kpi">Approval queue</div><h2>Open Response Drafts</h2><div style={{display:'grid',gap:8}}>{openDrafts.length===0?<p className="muted">No open response drafts.</p>:openDrafts.slice(0,150).map(d=><div key={d.id} className="notice" style={{padding:10}}><strong>{nameFor(d.opportunity_id)}</strong> · {d.subject||'No subject'} · <span className="pill">{d.status}</span><br/><small>{clip(d.body,180)}</small></div>)}</div></section>
  </div>
}

function ResponseComposer({opportunityId,reply,busy,onPost}:{opportunityId:string;reply:Row|null;busy:string;onPost:(p:Row,k:string)=>void}){const [subject,setSubject]=useState(reply?.subject?(/^re:/i.test(String(reply.subject))?String(reply.subject):`Re: ${reply.subject}`):'Re: Skylight Reflections Marketing'),[body,setBody]=useState('');return <div className="admin-card" style={{marginTop:14,padding:14}}><div className="kpi">Staff response composer</div><p className="small muted">Creating this saves a draft only. A second explicit approval and then a separate Send action are required.</p><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Response<textarea rows={5} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write the response…"/></label><button className="btn btn-primary" disabled={!body.trim()||busy==='new-response'} onClick={()=>onPost({action:'create_response_draft',opportunity_id:opportunityId,reply_id:reply?.id||null,subject,body},'new-response')}>Save Response Draft</button></div>}
function UnmatchedRow({row,opportunities,nameFor,busy,onPost}:{key?:string;row:Row;opportunities:Row[];nameFor:(id:any)=>string;busy:string;onPost:(p:Row,k:string)=>void}){const [opp,setOpp]=useState('');return <div className="notice" style={{padding:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong>{row.sender_name||row.sender_email||'Unknown sender'}</strong> · {fmt(row.received_at)}<br/><small>{row.subject||'No subject'}</small></div><span className="pill">unmatched</span></div><p style={{whiteSpace:'pre-wrap'}}>{String(row.body||'').slice(0,1200)}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'end'}}><label style={{minWidth:300}}>Attach to opportunity<select value={opp} onChange={e=>setOpp(e.target.value)}><option value="">Select…</option>{opportunities.slice(0,1000).map(o=><option key={o.id} value={o.id}>{nameFor(o.id)} · {o.stage}</option>)}</select></label><button className="btn btn-primary" disabled={!opp||busy===`attach-${row.id}`} onClick={()=>onPost({action:'attach_unmatched',unmatched_id:row.id,opportunity_id:opp},`attach-${row.id}`)}>Attach for Staff Review</button><button className="btn btn-light" disabled={busy===`dismiss-${row.id}`} onClick={()=>onPost({action:'dismiss_unmatched',unmatched_id:row.id},`dismiss-${row.id}`)}>Dismiss</button></div></div>}
