type SeoRow={id?:string;city?:string|null;category?:string|null;title?:string|null;intro?:string|null;content?:string|null;reviewed?:boolean|null;index_mode?:string|null;updated_at?:string|null};type BranchRow={city?:string|null;business_id?:string|null};type BusinessCategoryRow={business_id?:string|null;categories?:{name?:string|null;slug?:string|null;vertical?:string|null}|null};type LocationRow={name:string;slug:string};

const key=(city:string,category:string)=>`${city.trim().toLowerCase()}::${category.trim().toLowerCase()}`

export function SeoCoveragePanel({rows,branches,businessCategories,locations}:{rows:SeoRow[];branches:BranchRow[];businessCategories:BusinessCategoryRow[];locations:LocationRow[]}){
  const categoriesByBusiness=new Map<string,Set<string>>()
  for(const row of businessCategories){const businessId=String(row.business_id||'');const category=String(row.categories?.name||'').trim();if(!businessId||!category)continue;if(!categoriesByBusiness.has(businessId))categoriesByBusiness.set(businessId,new Set());categoriesByBusiness.get(businessId)!.add(category)}
  const providerSets=new Map<string,Set<string>>()
  for(const branch of branches){const city=String(branch.city||'').trim(),businessId=String(branch.business_id||'');if(!city||!businessId)continue;for(const category of categoriesByBusiness.get(businessId)||[]){const marketKey=key(city,category);if(!providerSets.has(marketKey))providerSets.set(marketKey,new Set());providerSets.get(marketKey)!.add(businessId)}}
  const seoByKey=new Map(rows.filter(r=>r.city&&r.category).map(r=>[key(String(r.city),String(r.category)),r]))
  const eligible=[...providerSets.entries()].map(([marketKey,set])=>{const[city,category]=marketKey.split('::');const location=locations.find(l=>l.name.toLowerCase()===city);const seo=seoByKey.get(marketKey);const copyChars=String(seo?.intro||'').length+String(seo?.content||'').length;return{marketKey,city:location?.name||city.replace(/\b\w/g,m=>m.toUpperCase()),citySlug:location?.slug||'',category:seo?.category||category,providers:set.size,seo,copyChars}}).filter(x=>x.providers>=3)
  const reviewed=eligible.filter(x=>x.seo?.reviewed&&x.seo?.index_mode!=='noindex')
  const missing=eligible.filter(x=>!x.seo)
  const reviewQueue=eligible.filter(x=>x.seo&&x.copyChars<1000).sort((a,b)=>b.providers-a.providers||a.copyChars-b.copyChars||a.city.localeCompare(b.city)).slice(0,18)
  const protectedRows=rows.map(seo=>{const providers=providerSets.get(key(String(seo.city||''),String(seo.category||'')))?.size||0;return{seo,providers}}).filter(x=>x.seo.category&&x.providers<3)
  const stale=eligible.filter(x=>x.seo?.updated_at&&Date.now()-new Date(String(x.seo.updated_at)).getTime()>1000*60*60*24*180).length
  return <section className="admin-card"><div className="section-head"><div><div className="kpi">Private SEO intelligence</div><h2>Indexable Market Coverage</h2><p className="muted">Tracks only real city/category inventory. A page is considered index-eligible here only when at least three distinct published businesses serve that category in the market.</p></div></div><div className="grid grid-4"><div className="card"><div className="kpi">Eligible markets</div><h2>{eligible.length}</h2><p className="small muted">3+ published providers</p></div><div className="card"><div className="kpi">Reviewed coverage</div><h2>{reviewed.length}</h2><p className="small muted">Reviewed and not manually noindex</p></div><div className="card"><div className="kpi">Missing SEO records</div><h2>{missing.length}</h2><p className="small muted">Eligible inventory without a matching SEO record</p></div><div className="card"><div className="kpi">Protected thin markets</div><h2>{protectedRows.length}</h2><p className="small muted">Under 3 providers; runtime indexing guardrail applies</p></div></div><div className="section-head" style={{marginTop:28}}><div><h3>Copy improvement queue</h3><p className="small muted">Prioritizes index-eligible pages with shorter combined intro + buying-guide copy. Provider depth wins ties. This is an editorial review queue, not an automatic publishing rule.</p></div><span className="badge neutral">{stale} stale 180+ days</span></div>{reviewQueue.length?<div className="grid grid-3">{reviewQueue.map(x=><div className="card" key={x.marketKey}><div className="kpi">{x.providers} providers · {x.copyChars.toLocaleString()} copy chars</div><h3>{x.category} in {x.city}, IL</h3><p className="small muted">{x.seo?.index_mode==='noindex'?'Manual noindex':x.seo?.reviewed?'Reviewed':'Needs review'} · updated {x.seo?.updated_at?new Date(String(x.seo.updated_at)).toLocaleDateString():'unknown'}</p>{x.citySlug&&<a href={`/illinois/${x.citySlug}/${slugify(String(x.category))}`} target="_blank" rel="noreferrer">Review public page →</a>}</div>)}</div>:<div className="notice">No eligible pages currently fall below the copy-review threshold.</div>} {missing.length>0&&<><div className="section-head" style={{marginTop:28}}><div><h3>Eligible pages missing SEO records</h3><p className="small muted">These have enough live inventory to deserve editorial review, but no matching SEO record was found.</p></div></div><div className="grid grid-3">{missing.slice(0,12).map(x=><div className="card" key={x.marketKey}><div className="kpi">{x.providers} providers</div><h3>{x.category} in {x.city}, IL</h3></div>)}</div></>}</section>}

function slugify(value:string){return value.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').replace('cafes-and-coffee','cafes-coffee').replace('bars-and-pubs','bars-pubs').replace('bakeries-and-desserts','bakeries-desserts').replace('boutiques-and-clothing','boutiques-clothing').replace('breweries-and-taprooms','breweries-taprooms').replace('books-and-records','books-records').replace('grocery-and-specialty-foods','grocery-specialty-foods').replace('farm-and-garden','farm-garden').replace('art-and-craft-stores','art-craft-stores').replace('shoes-and-accessories','shoes-accessories')}
