'use client'
import{useMemo,useState}from'react'
type Item={id:string;name:string};type Row=Record<string,any>
const empty={business_id:'',market_location_id:'',category_id:'',placement:'global_sidebar',page_path:'',starts_on:'',ends_on:'',active:true,priority:100,sort_order:100,rotation_weight:1,origin:'manual'}
const placements=[
 ['homepage_featured','Homepage Featured'],['global_sidebar','Global Sidebar'],['city_sidebar','City Sidebar'],['category_sidebar','Category Sidebar'],['market_sidebar','City + Category Sidebar'],['page_sidebar','Exact Page Sidebar'],['guide_sidebar','Guide Sidebar'],['business_profile_sidebar','Business Profile Sidebar'],['restaurant_sidebar','Restaurants Sidebar'],['home_services_sidebar','Home Services Sidebar'],['attorney_sidebar','Attorneys Sidebar'],['local_stores_sidebar','Local Stores Sidebar']
]
const requiresCity=(p:string)=>['city_sidebar','market_sidebar'].includes(p),requiresCategory=(p:string)=>['category_sidebar','market_sidebar'].includes(p),requiresPage=(p:string)=>p==='page_sidebar'
export function SponsorshipManager({rows,businesses,locations,categories}:{rows:Row[];businesses:Item[];locations:Item[];categories:Item[]}){
 const[data,setData]=useState(rows),[draft,setDraft]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const name=(items:Item[],id:any)=>items.find(x=>x.id===id)?.name||id||'All'
 const stats=useMemo(()=>({active:data.filter(x=>x.active).length,sidebar:data.filter(x=>x.active&&String(x.placement).includes('sidebar')).length,homepage:data.filter(x=>x.active&&x.placement==='homepage_featured').length}),[data])
 function reset(){setDraft(empty);setEditing(null)}
 function edit(row:Row){setEditing(row.id);setDraft({...empty,...row,market_location_id:row.market_location_id||'',category_id:row.category_id||'',page_path:row.page_path||'',starts_on:row.starts_on||'',ends_on:row.ends_on||'',origin:row.origin==='promotional'?'promotional':'manual'});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){setBusy(true);setMessage('');const payload={...draft,market_location_id:draft.market_location_id||null,category_id:draft.category_id||null,page_path:draft.page_path||null,starts_on:draft.starts_on||null,ends_on:draft.ends_on||null,id:editing||undefined};const r=await fetch('/api/admin/sponsorships',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.error||'Unable to save sponsorship.'));setBusy(false);return}if(editing)setData(prev=>prev.map(x=>x.id===editing?{...x,...payload}:x));else setData(prev=>[{...payload,id:body.id,provider:'manual',provider_subscription_id:null,created_at:new Date().toISOString()},...prev]);setMessage(editing?'Sponsored placement updated.':'Sponsored placement created.');reset();setBusy(false)}
 async function toggle(row:Row){const r=await fetch('/api/admin/sponsorships',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,toggleOnly:true})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.error||'Unable to update sponsorship.'));setData(prev=>prev.map(x=>x.id===row.id?{...x,active:body.active}:x));setMessage(body.active?'Sponsored placement activated.':'Sponsored placement paused.')}
 async function remove(row:Row){if(!window.confirm(`Remove the sponsored placement for ${name(businesses,row.business_id)}?`))return;const r=await fetch('/api/admin/sponsorships',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.error||'Unable to remove sponsorship.'));setData(prev=>prev.filter(x=>x.id!==row.id));setMessage('Sponsored placement removed.')}
 const cityRequired=requiresCity(draft.placement),categoryRequired=requiresCategory(draft.placement),pageRequired=requiresPage(draft.placement)
 return <div>
  <div className="notice"><strong>Separation rule:</strong> every placement is clearly labeled Sponsored. Sponsorship never changes organic result sorting, verification, SEO provider counts, or lead-route rank. Super Admin retains final placement control.</div>
  <div className="stat-grid"><div className="stat">Active Placements<strong>{stats.active}</strong></div><div className="stat">Active Sidebars<strong>{stats.sidebar}</strong></div><div className="stat">Homepage Featured<strong>{stats.homepage}</strong></div></div>
  <section className="admin-card" style={{marginTop:18}}><div className="section-head compact-head"><div><h2>{editing?'Edit Sponsored Placement':'Create Sponsored Placement'}</h2><p className="muted">Target globally, by city, category, city + category, exact page, or approved vertical inventory.</p></div>{editing&&<button className="btn btn-light" onClick={reset}>Cancel Edit</button>}</div>
   <div className="admin-form-grid">
    <label>Business<select value={draft.business_id} onChange={e=>setDraft({...draft,business_id:e.target.value})}><option value="">Choose published business…</option>{businesses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label>Placement<select value={draft.placement} onChange={e=>setDraft({...draft,placement:e.target.value,market_location_id:requiresCity(e.target.value)?draft.market_location_id:'',category_id:requiresCategory(e.target.value)?draft.category_id:'',page_path:requiresPage(e.target.value)?draft.page_path:''})}>{placements.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label>City scope<select disabled={!cityRequired} value={draft.market_location_id} onChange={e=>setDraft({...draft,market_location_id:e.target.value})}><option value="">{cityRequired?'Choose market…':'Not used'}</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label>Category scope<select disabled={!categoryRequired} value={draft.category_id} onChange={e=>setDraft({...draft,category_id:e.target.value})}><option value="">{categoryRequired?'Choose category…':'Not used'}</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label>Exact page path<input disabled={!pageRequired} placeholder="/illinois/pontiac/roofing" value={draft.page_path} onChange={e=>setDraft({...draft,page_path:e.target.value})}/></label>
    <label>Origin<select value={draft.origin} onChange={e=>setDraft({...draft,origin:e.target.value})}><option value="manual">Manual / Paid</option><option value="promotional">Promotional / Free Campaign</option></select></label>
    <label>Priority<input type="number" min="0" max="1000" value={draft.priority} onChange={e=>setDraft({...draft,priority:Number(e.target.value)})}/></label>
    <label>Sort order<input type="number" min="0" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})}/></label>
    <label>Rotation weight<input type="number" min="1" max="100" value={draft.rotation_weight} onChange={e=>setDraft({...draft,rotation_weight:Number(e.target.value)})}/></label>
    <label>Starts<input type="date" value={draft.starts_on} onChange={e=>setDraft({...draft,starts_on:e.target.value})}/></label>
    <label>Ends<input type="date" value={draft.ends_on} onChange={e=>setDraft({...draft,ends_on:e.target.value})}/></label>
    <label className="check-row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Active</label>
   </div>
   <button className="btn btn-primary" disabled={busy||!draft.business_id||(cityRequired&&!draft.market_location_id)||(categoryRequired&&!draft.category_id)||(pageRequired&&!String(draft.page_path).startsWith('/'))} onClick={save}>{busy?'Saving…':editing?'Save Placement Changes':'Create Sponsored Placement'}</button>
  </section>
  {message&&<div className={`notice ${message.includes('created')||message.includes('updated')||message.includes('activated')||message.includes('paused')||message.includes('removed')?'success':'warn'}`}>{message}</div>}
  <div className="moderation-list">{data.map(r=><article className="admin-card moderation-card" key={r.id}><div className="moderation-head"><div><div className="badges"><span className={`badge ${r.active?'sponsored':'neutral'}`}>{r.active?'Active':'Paused'}</span><span className="badge neutral">{placements.find(x=>x[0]===r.placement)?.[1]||r.placement}</span><span className="badge neutral">{r.origin||r.provider||'manual'}</span></div><h3>{name(businesses,r.business_id)}</h3><p className="small muted">Market: {name(locations,r.market_location_id)} · Category: {name(categories,r.category_id)}{r.page_path?` · Page: ${r.page_path}`:''}</p><p className="small muted">Provider: {r.provider||'manual'}{r.provider_subscription_id?` · Subscription ${r.provider_subscription_id}`:''}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-light" onClick={()=>edit(r)}>Edit</button><button className="btn btn-light" onClick={()=>toggle(r)}>{r.active?'Pause':'Activate'}</button><button className="btn btn-light" onClick={()=>remove(r)}>Remove</button></div></div><div className="moderation-details"><div><span>Starts</span><strong>{r.starts_on||'Immediately'}</strong></div><div><span>Ends</span><strong>{r.ends_on||'No end date'}</strong></div><div><span>Priority / Order</span><strong>{r.priority??100} / {r.sort_order??100}</strong></div><div><span>Disclosure</span><strong>Sponsored</strong></div></div></article>)}</div>
  {!data.length&&<div className="empty">No sponsored placements are configured.</div>}
 </div>
}
