'use client'

import { useMemo,useState } from 'react'
import Link from 'next/link'

type Row=Record<string,any>
const title=(v:any)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())
const money=(c:any)=>`$${(Number(c||0)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`
const date=(v:any)=>v?new Date(String(v)).toLocaleDateString():'—'

export function VisibilityRetentionCommandCenter({rows}:{rows:Row[]}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all')
  const filtered=useMemo(()=>rows.filter(r=>{const text=`${r.client?.company_name||''} ${r.business?.name||''}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(filter==='all'||r.health?.health_status===filter)}),[rows,query,filter])
  const totals=useMemo(()=>({clients:rows.length,healthy:rows.filter(r=>r.health?.health_status==='healthy').length,watch:rows.filter(r=>r.health?.health_status==='watch').length,attention:rows.filter(r=>r.health?.health_status==='attention').length,insufficient:rows.filter(r=>r.health?.health_status==='insufficient_data').length,overdueReports:rows.filter(r=>r.health?.delivery_metrics?.report_overdue).length,overdueRemeasurements:rows.reduce((s,r)=>s+Number(r.health?.delivery_metrics?.overdue_remeasurements||0),0),paid90:rows.reduce((s,r)=>s+Number(r.health?.revenue_metrics?.recorded_net_payments_90d_cents||0),0)}),[rows])
  return <div style={{display:'grid',gap:18}}>
    <section className="card"><div className="kpi">Business Visibility Intelligence 4.5</div><h1>Client Results & Retention Command Center</h1><p className="muted" style={{maxWidth:900}}>A private operating view of recorded client delivery, reporting, measurement, project and payment facts. Health classifications are deterministic attention summaries—not churn predictions, sentiment scores or automated renewal decisions.</p></section>
    <section className="card"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{[['Linked clients',totals.clients],['Healthy',totals.healthy],['Watch',totals.watch],['Attention',totals.attention],['Insufficient data',totals.insufficient],['Reports overdue',totals.overdueReports],['Remeasurements overdue',totals.overdueRemeasurements],['Recorded net payments · 90d',money(totals.paid90)]].map(([label,value])=><div className="notice" key={String(label)}><div className="small muted">{label}</div><strong>{value}</strong></div>)}</div></section>
    <section className="card"><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'end'}}><label style={{flex:'1 1 280px'}}>Search clients<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Client or business name"/></label><label style={{minWidth:220}}>Health filter<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All health states</option><option value="attention">Attention</option><option value="watch">Watch</option><option value="healthy">Healthy</option><option value="insufficient_data">Insufficient data</option></select></label></div></section>
    <section className="card"><h2>Client attention queue</h2>{filtered.length?<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Client</th><th>Health</th><th>Attention</th><th>Visibility measurement</th><th>Delivery</th><th>Revenue context</th><th>Human review</th><th></th></tr></thead><tbody>{filtered.map((r:Row)=><tr key={r.client.id}><td><strong>{r.client.company_name}</strong><div className="small muted">{r.business.name}</div></td><td>{title(r.health.health_status)}</td><td>{r.health.attention_points}/100<div className="small muted">{r.health.signal_counts?.critical||0} critical · {r.health.signal_counts?.attention||0} attention</div></td><td>{date(r.health.latest_visibility_snapshot_at)}<div className="small muted">{r.health.delivery_metrics?.measurement_age_days??'Not measured'} days old</div></td><td><div className="small">{r.health.delivery_metrics?.overdue_execution_items||0} overdue work</div><div className="small">{r.health.delivery_metrics?.overdue_remeasurements||0} overdue remeasurements</div><div className="small">{r.health.delivery_metrics?.overdue_project_tasks||0} overdue project tasks</div>{r.health.delivery_metrics?.report_overdue?<div className="small">Report overdue</div>:null}</td><td><div className="small">90d paid: {money(r.health.revenue_metrics?.recorded_net_payments_90d_cents)}</div><div className="small">Overdue: {money(r.health.revenue_metrics?.overdue_balance_cents)}</div><div className="small muted">ROI not inferred</div></td><td>{r.review?title(r.review.review_status):'Not reviewed'}<div className="small muted">{r.review?title(r.review.renewal_readiness):title(r.health.suggested_renewal_readiness)}</div></td><td><Link className="btn btn-light" href={`/admin/businesses/${r.business.id}/visibility/client-health`}>Open 4.5</Link></td></tr>)}</tbody></table></div>:<div className="notice">No clients match the current filter. If there are no linked Skylight clients yet, 4.5 intentionally stays empty rather than creating demonstration data.</div>}</section>
    <section className="card"><h2>Interpretation boundaries</h2><div className="notice"><strong>Health:</strong> operational attention based on recorded facts only. <strong>Renewal:</strong> staff-controlled. <strong>Visibility outcomes:</strong> observational, not causal. <strong>Paid revenue:</strong> recorded invoice payments only. <strong>ROI:</strong> unavailable until actual cost evidence exists. No automatic outreach, upsell, renewal, cancellation, billing or public-ranking action occurs from this dashboard.</div></section>
  </div>
}
