import { createClient } from '@/lib/supabase/server'
import { requireAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { saveConversionGoal } from './actions'

export const dynamic='force-dynamic'
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const pct=(n:number,d:number)=>d?`${((n/d)*100).toFixed(n/d<.1?1:0)}%`:'—'
const when=(v:string)=>new Date(v).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})
const goalLabel:Record<string,string>={any_inquiry:'Any Qualified Inquiry',sponsored_inquiry:'Sponsored / Plan Inquiry',skylight_inquiry:'Skylight Marketing Inquiry'}
function matchesGoal(type:string,goal:string){return goal==='any_inquiry'||type===goal}

export default async function Page(){
  await requireAdmin('/admin/email-drips/conversions')
  const s=await createClient()
  const[campaignResult,outboxResult,conversionResult]=await Promise.all([
    s.from('email_drip_campaigns').select('id,name,status,campaign_goal,conversion_goal').eq('tenant_id',TENANT_ID).neq('status','archived').order('created_at'),
    s.from('email_outbox').select('id,campaign_id,status,click_count,conversion_count,sent_at').eq('tenant_id',TENANT_ID).eq('message_type','drip').limit(10000),
    s.from('email_campaign_conversions').select('id,campaign_id,step_id,outbox_id,business_id,recipient_email,conversion_type,attribution_model,occurred_at,email_drip_campaigns(name),email_drip_steps(step_order,subject),marketing_leads(business_name,contact_name,plan_interest,service_interest,status)').eq('tenant_id',TENANT_ID).order('occurred_at',{ascending:false}).limit(1000),
  ])
  const campaigns=(campaignResult.data??[]) as any[],outbox=(outboxResult.data??[]) as any[],conversions=(conversionResult.data??[]) as any[]
  const metrics=new Map<string,{delivered:number;clicked:number;all:number;sponsored:number;skylight:number;other:number}>()
  for(const c of campaigns)metrics.set(c.id,{delivered:0,clicked:0,all:0,sponsored:0,skylight:0,other:0})
  for(const mail of outbox){const m=metrics.get(mail.campaign_id);if(!m)continue;if(mail.status==='sent')m.delivered++;if(Number(mail.click_count||0)>0)m.clicked++}
  for(const conversion of conversions){const m=metrics.get(conversion.campaign_id);if(!m)continue;m.all++;if(conversion.conversion_type==='sponsored_inquiry')m.sponsored++;else if(conversion.conversion_type==='skylight_inquiry')m.skylight++;else m.other++}
  let delivered=0,clicked=0,totalConversions=0,sponsored=0,skylight=0
  for(const m of metrics.values()){delivered+=m.delivered;clicked+=m.clicked;totalConversions+=m.all;sponsored+=m.sponsored;skylight+=m.skylight}
  return <>
    <div className="conversion-head"><div><div className="kpi">Revenue Attribution</div><h1>Email Conversion Dashboard</h1><p className="muted">Measure actual inquiry outcomes after campaign engagement instead of treating every click as a conversion.</p></div><a className="btn btn-light" href="/admin/email-drips">← Campaign Studio</a></div>
    {(campaignResult.error||outboxResult.error||conversionResult.error)&&<div className="notice warn">Some attribution data could not be loaded. {campaignResult.error?.message||outboxResult.error?.message||conversionResult.error?.message}</div>}
    <div className="attribution-note"><strong>Attribution model: same-email last click, 30 days.</strong> A marketing lead is credited only when its submitted email matches a campaign recipient and that recipient clicked a campaign email within the prior 30 days. This intentionally avoids counting opens or unsubmitted clicks as business results.</div>
    <div className="conversion-stat-grid"><div className="conversion-stat"><span>Delivered</span><strong>{delivered}</strong><small>Tracked drip emails</small></div><div className="conversion-stat"><span>Unique Clickers</span><strong>{clicked}</strong><small>{pct(clicked,delivered)} click-through</small></div><div className="conversion-stat"><span>Attributed Inquiries</span><strong>{totalConversions}</strong><small>{pct(totalConversions,delivered)} delivery-to-inquiry</small></div><div className="conversion-stat"><span>Sponsored / Plan</span><strong>{sponsored}</strong><small>Paid visibility inquiries</small></div><div className="conversion-stat"><span>Skylight Services</span><strong>{skylight}</strong><small>Marketing-service inquiries</small></div></div>
    <div className="conversion-stack">{campaigns.map(c=>{const m=metrics.get(c.id)??{delivered:0,clicked:0,all:0,sponsored:0,skylight:0,other:0},goal=c.conversion_goal||'any_inquiry',goalConversions=conversions.filter(x=>x.campaign_id===c.id&&matchesGoal(x.conversion_type,goal)).length;return <section className="conversion-card" key={c.id}><div className="conversion-card-head"><div><div className="badges"><span className={`badge ${c.status==='live'?'verified':c.status==='approved'?'sponsored':'neutral'}`}>{label(c.status)}</span><span className="badge neutral">{label(c.campaign_goal)}</span></div><h2>{c.name}</h2><p className="small muted">Primary success metric: <strong>{goalLabel[goal]||label(goal)}</strong></p></div><form action={saveConversionGoal} className="conversion-goal-form"><input type="hidden" name="campaign_id" value={c.id}/><label>Conversion Goal<select name="conversion_goal" defaultValue={goal}><option value="any_inquiry">Any Qualified Inquiry</option><option value="sponsored_inquiry">Sponsored / Plan Inquiry</option><option value="skylight_inquiry">Skylight Marketing Inquiry</option></select></label><button className="btn btn-light">Save Goal</button></form></div><div className="conversion-metrics"><div><span>Delivered</span><strong>{m.delivered}</strong><small>emails</small></div><div><span>Clicked</span><strong>{m.clicked}</strong><small>{pct(m.clicked,m.delivered)} CTR</small></div><div><span>All Inquiries</span><strong>{m.all}</strong><small>{pct(m.all,m.delivered)} conversion</small></div><div><span>Goal Conversions</span><strong>{goalConversions}</strong><small>{pct(goalConversions,m.delivered)} goal rate</small></div><div><span>Sponsored</span><strong>{m.sponsored}</strong><small>plan interest</small></div><div><span>Skylight</span><strong>{m.skylight}</strong><small>service interest</small></div></div></section>})}{!campaigns.length&&<div className="admin-card">No campaigns have been created yet.</div>}</div>
    <section className="conversion-summary" style={{marginTop:18}}><div className="section-head compact-head"><div><div className="kpi">Attributed Leads</div><h2>Recent campaign-generated inquiries</h2><p className="small muted">These are actual marketing-lead submissions attributed to a prior tracked campaign click.</p></div></div><div className="conversion-table-wrap"><table className="conversion-table"><thead><tr><th>Business / Contact</th><th>Campaign</th><th>Type</th><th>Email Step</th><th>Interest</th><th>Converted</th></tr></thead><tbody>{conversions.slice(0,100).map(row=>{const campaign=Array.isArray(row.email_drip_campaigns)?row.email_drip_campaigns[0]:row.email_drip_campaigns,step=Array.isArray(row.email_drip_steps)?row.email_drip_steps[0]:row.email_drip_steps,lead=Array.isArray(row.marketing_leads)?row.marketing_leads[0]:row.marketing_leads;return <tr key={row.id}><td><strong>{lead?.business_name||'Business inquiry'}</strong><small>{lead?.contact_name||row.recipient_email} · {row.recipient_email}</small></td><td>{campaign?.name||'Campaign'}</td><td><span className={`badge ${row.conversion_type==='sponsored_inquiry'?'sponsored':row.conversion_type==='skylight_inquiry'?'verified':'neutral'}`}>{label(row.conversion_type)}</span></td><td>{step?<>Step {step.step_order}<small>{step.subject}</small></>:'—'}</td><td>{lead?.plan_interest?label(lead.plan_interest):lead?.service_interest||'General marketing inquiry'}</td><td>{when(row.occurred_at)}</td></tr>})}{!conversions.length&&<tr><td colSpan={6} className="empty-cell">No campaign-attributed inquiries yet. Clicks and opens remain engagement signals until an inquiry is actually submitted.</td></tr>}</tbody></table></div></section>
  </>
}
