import type{Metadata}from'next'
import Link from'next/link'
import{SiteShell}from'@/components/SiteShell'
import{createClient}from'@/lib/supabase/server'
import{TENANT_ID}from'@/lib/constants'

export const dynamic='force-dynamic'
export const metadata:Metadata={title:'Local Deals & Offers | Central Illinois Local Pros',description:'Browse current business-provided deals and local offers from Central Illinois businesses. Offers are moderated and separate from organic directory ranking.',alternates:{canonical:'/deals'}}
const related=(v:any)=>Array.isArray(v)?v[0]:v
export default async function Page(){const s=await createClient(),now=Date.now();const{data}=await s.from('business_deals').select('id,business_id,title,details,promo_code,cta_label,cta_url,starts_at,ends_at,created_at,businesses!inner(name,slug,status,tenant_id)').eq('tenant_id',TENANT_ID).eq('status','approved').eq('businesses.status','published').eq('businesses.tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(100);const deals=(data??[]).filter((d:any)=>(!d.starts_at||new Date(d.starts_at).getTime()<=now)&&(!d.ends_at||new Date(d.ends_at).getTime()>=now));return <SiteShell><main>
 <section className="hero"><div className="container"><div className="eyebrow">Local Deals</div><h1>Current offers from Central Illinois businesses</h1><p>Discover business-provided specials, promo codes and limited-time offers. Deal approval is content moderation only—it does not create verification or improve a business’s organic directory rank.</p><div className="hero-actions"><Link className="btn btn-primary" href="/project-match">Need a Service? Get Matched</Link><Link className="btn btn-light" href="/search">Browse All Businesses</Link></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div><div className="kpi">Available Now</div><h2>{deals.length} active local offer{deals.length===1?'':'s'}</h2><p className="muted">Confirm final eligibility, inventory, availability and terms directly with the business.</p></div></div><div className="grid grid-3">{deals.map((d:any)=>{const b=related(d.businesses);return <article className="card" key={d.id}><div className="badges"><span className="badge sponsored">Business Offer</span>{d.ends_at&&<span className="badge neutral">Ends {new Date(d.ends_at).toLocaleDateString()}</span>}</div><h3>{d.title}</h3><p className="small muted">{b?.name||'Local business'}</p>{d.promo_code&&<p><strong>Promo code: {d.promo_code}</strong></p>}{d.details&&<p className="muted">{d.details}</p>}<div className="card-actions"><Link className="btn btn-primary" href={`/business/${b?.slug}`}>View Business</Link>{d.cta_url&&<a className="btn btn-light" href={d.cta_url} target="_blank" rel="noopener noreferrer">{d.cta_label||'Offer Details'} ↗</a>}</div></article>})}</div>{!deals.length&&<div className="empty empty-rich"><h2>No active deals are published right now</h2><p>Businesses can submit moderated deals from their owner portal. Check back as more local offers are added.</p><Link className="btn btn-primary" href="/search">Explore Local Businesses</Link></div>}</div></section>
 </main></SiteShell>}
