import { createClient } from '@/lib/supabase/server'
import { requireAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { createCampaignFromTemplate,saveTemplateMeta,saveTemplateStep } from './actions'

export const dynamic='force-dynamic'

const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const stepList=(value:unknown)=>Array.isArray(value)?[...value].sort((a:any,b:any)=>Number(a?.step_order||0)-Number(b?.step_order||0)):[]

export default async function Page(){
  await requireAdmin('/admin/email-drips/templates')
  const s=await createClient()
  const{data,error}=await s.from('email_template_library').select('id,slug,name,delivery_class,system_template_key,audience,trigger_event,campaign_goal,conversion_goal,purpose,compliance_note,send_hour,utm_campaign,steps,can_create_campaign,is_active,updated_at').eq('tenant_id',TENANT_ID).order('sort_order').order('name')
  const templates=(data??[]) as any[]
  const transactional=templates.filter(t=>t.delivery_class==='transactional').length
  const promotional=templates.filter(t=>t.delivery_class==='promotional').length
  const installable=templates.filter(t=>t.delivery_class==='promotional'&&t.can_create_campaign&&t.is_active).length
  return <>
    <div className="template-library-head"><div><div className="kpi">Reusable Campaign Assets</div><h1>Email Template Library</h1><p className="muted">Maintain the master copy for business lifecycle emails and install prebuilt nurture sequences as brand-new Draft campaigns. Existing campaigns remain snapshots and never change silently when a master template is edited.</p></div><a className="btn btn-light" href="/admin/email-drips">← Campaign Studio</a></div>
    {error&&<div className="notice warn">{error.message}</div>}
    <div className="template-stat-grid"><div className="template-stat"><span>Total Templates</span><strong>{templates.length}</strong><small>Central library</small></div><div className="template-stat"><span>Transactional</span><strong>{transactional}</strong><small>Claim + verification lifecycle</small></div><div className="template-stat"><span>Promotional</span><strong>{promotional}</strong><small>Opt-in nurture only</small></div><div className="template-stat"><span>Ready to Install</span><strong>{installable}</strong><small>Creates Draft campaigns</small></div></div>
    <div className="template-safety-grid"><div className="notice"><strong>Transactional templates:</strong> edits apply only to future matching transactional outbox inserts. Already queued or sent messages are not rewritten. Disabling a transactional template safely falls back to the existing system copy.</div><div className="notice"><strong>Promotional templates:</strong> one-click install creates a separate Draft campaign. Nothing is approved, enrolled or sent until the normal campaign review and Go Live gates are completed.</div></div>
    <div className="template-library-stack">{templates.map(template=>{const steps=stepList(template.steps);return <section className="template-library-card" key={template.id}>
      <div className="template-library-card-head"><div><div className="badges"><span className={`badge ${template.delivery_class==='transactional'?'verified':'sponsored'}`}>{label(template.delivery_class)}</span><span className={`badge ${template.is_active?'neutral':'warning'}`}>{template.is_active?'Active':'Disabled'}</span><span className="badge neutral">{label(template.trigger_event)}</span></div><h2>{template.name}</h2><p className="small muted">{template.purpose}</p></div>{template.delivery_class==='promotional'&&template.can_create_campaign?<form action={createCampaignFromTemplate}><input type="hidden" name="template_id" value={template.id}/><button className="btn btn-primary" disabled={!template.is_active}>Create Draft Campaign</button></form>:<div className="template-system-key"><span>System key</span><code>{template.system_template_key||'reference_only'}</code></div>}</div>
      <div className="template-meta-grid"><div><span>Audience</span><strong>{label(template.audience)}</strong></div><div><span>Goal</span><strong>{label(template.campaign_goal)}</strong></div><div><span>Conversion</span><strong>{label(template.conversion_goal)}</strong></div><div><span>Default Send</span><strong>{template.delivery_class==='transactional'?'Event-driven':`${template.send_hour}:00 CT`}</strong></div></div>
      <div className="template-compliance"><strong>Copy guardrail:</strong> {template.compliance_note||'Use truthful, non-guaranteed claims and preserve directory trust rules.'}</div>
      {template.delivery_class==='transactional'&&<div className="template-token-note"><strong>Available lifecycle tokens:</strong> <code>{'{{business_name}}'}</code> <code>{'{{business_id}}'}</code> <code>{'{{business_slug}}'}</code> <code>{'{{recipient_name}}'}</code></div>}
      <details className="template-editor-disclosure"><summary><span><strong>Edit Template Settings</strong><small>Central master metadata and activation.</small></span><span>Open</span></summary><div className="template-editor-body"><form action={saveTemplateMeta} className="admin-card"><input type="hidden" name="template_id" value={template.id}/><label>Template Name<input name="name" defaultValue={template.name} maxLength={180} required/></label><label>Purpose<textarea name="purpose" defaultValue={template.purpose||''} maxLength={1600}/></label><label>Compliance / Review Note<textarea name="compliance_note" defaultValue={template.compliance_note||''} maxLength={1600}/></label><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={template.is_active}/> Active master template</label><button className="btn btn-light">Save Template Settings</button></form></div></details>
      <div className="section-head compact-head" style={{marginTop:16}}><div><div className="kpi">Master Copy</div><h3>{steps.length} Email Step{steps.length===1?'':'s'}</h3></div>{template.delivery_class==='promotional'&&<span className="small muted">UTM campaign: {template.utm_campaign||template.slug}</span>}</div>
      <div className="template-step-grid">{steps.map((step:any)=><form action={saveTemplateStep} className="template-step-card" key={`${template.id}:${step.step_order}`}><input type="hidden" name="template_id" value={template.id}/><input type="hidden" name="step_order" value={Number(step.step_order)}/><div className="template-step-head"><div className="badges"><span className="badge neutral">Step {Number(step.step_order)}</span><span className="badge neutral">Day +{Number(step.delay_days||0)}</span></div><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={step.is_active!==false}/> Active</label></div><div className="template-step-fields"><label>Delay Days<input type="number" min="0" name="delay_days" defaultValue={Number(step.delay_days||0)}/></label><label>Subject<input name="subject" maxLength={220} defaultValue={String(step.subject||'')} required/></label><label>Preheader<input name="preheader" maxLength={260} defaultValue={String(step.preheader||'')}/></label><label>Email Body<textarea name="body" maxLength={8000} defaultValue={String(step.body||'')} required style={{minHeight:190}}/></label><div className="admin-form-grid"><label>CTA Label<input name="cta_label" maxLength={120} defaultValue={String(step.cta_label||'')}/></label><label>CTA URL<input name="cta_url" maxLength={600} defaultValue={String(step.cta_url||'')}/></label></div></div><button className="btn btn-light">Save Master Step</button></form>)}</div>
    </section>})}{!templates.length&&<div className="admin-card"><h2>No templates found</h2><p className="muted">The template library migration has not been seeded for this tenant.</p></div>}</div>
  </>
}
