'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { requireAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { processBusinessEmailOutbox } from '@/lib/business-email'

const text=(fd:FormData,key:string)=>String(fd.get(key)??'').trim()
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)
const refresh=()=>revalidatePath('/admin/email-drips')
const AUDIENCES=new Set(['verified_opted_in','home_services','restaurants','retail','online','storefront','category','city'])
const TRIGGERS=new Set(['business_verified','manual'])
const GOALS=new Set(['education','sponsored','skylight_growth','retention'])
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

function chicagoLocalToIso(raw:string){
  if(!raw)return null
  const m=raw.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/)
  if(!m)return null
  const wanted=Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]),Number(m[5]),0)
  let guess=wanted
  const formatter=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'})
  for(let i=0;i<3;i++){
    const parts=Object.fromEntries(formatter.formatToParts(new Date(guess)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))
    const shown=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute),Number(parts.second))
    guess+=wanted-shown
  }
  return new Date(guess).toISOString()
}
function campaignPatch(fd:FormData){
  const audience=AUDIENCES.has(text(fd,'audience'))?text(fd,'audience'):'verified_opted_in'
  const trigger=TRIGGERS.has(text(fd,'trigger_event'))?text(fd,'trigger_event'):'business_verified'
  const goal=GOALS.has(text(fd,'campaign_goal'))?text(fd,'campaign_goal'):'education'
  return {audience,trigger_event:trigger,campaign_goal:goal,audience_rules:{category:text(fd,'audience_category').slice(0,160)||null,city:text(fd,'audience_city').slice(0,120)||null},start_at:chicagoLocalToIso(text(fd,'start_at')),send_timezone:'America/Chicago',send_hour:Math.max(0,Math.min(23,Number(text(fd,'send_hour')||10))),utm_source:text(fd,'utm_source').slice(0,120)||'central_il_local_pros',utm_medium:text(fd,'utm_medium').slice(0,120)||'email',utm_campaign:text(fd,'utm_campaign').slice(0,160)||null}
}
async function demoteApprovalIfNeeded(s:any,campaignId:string,status:string){if(status==='approved'||status==='paused'){const{error}=await s.from('email_drip_campaigns').update({status:'draft',approved_by:null,approved_at:null,updated_at:new Date().toISOString()}).eq('tenant_id',TENANT_ID).eq('id',campaignId);if(error)throw new Error(error.message)}}
function campaignStart(campaign:any){const now=Date.now(),configured=campaign?.start_at?new Date(campaign.start_at).getTime():now;return new Date(Number.isFinite(configured)&&configured>now?configured:now)}
function withUtm(value:string|null,campaign:any){if(!value)return null;try{const base=process.env.NEXT_PUBLIC_SITE_URL||'https://central-il-local-pros.vercel.app',url=new URL(value,base);if(campaign?.utm_source)url.searchParams.set('utm_source',campaign.utm_source);if(campaign?.utm_medium)url.searchParams.set('utm_medium',campaign.utm_medium);if(campaign?.utm_campaign||campaign?.slug)url.searchParams.set('utm_campaign',campaign.utm_campaign||campaign.slug);return url.origin===new URL(base).origin?`${url.pathname}${url.search}${url.hash}`:url.toString()}catch{return value}}

export async function createDripCampaign(fd:FormData){const{claims}=await requireAdmin('/admin/email-drips');const s=await createClient();const name=text(fd,'name').slice(0,160);if(!name)throw new Error('Campaign name is required.');const slug=slugify(text(fd,'slug')||name);if(!slug)throw new Error('Campaign slug is required.');const{error}=await s.from('email_drip_campaigns').insert({tenant_id:TENANT_ID,name,slug,status:'draft',purpose:text(fd,'purpose').slice(0,1200)||null,created_by:String(claims.sub),...campaignPatch(fd)});if(error)throw new Error(error.message);refresh()}
export async function saveDripCampaign(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id');const{data:current}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(!current)throw new Error('Campaign not found.');if(current.status==='live')throw new Error('Pause a live campaign before editing its settings.');const name=text(fd,'name').slice(0,160);if(!name)throw new Error('Campaign name is required.');const{error}=await s.from('email_drip_campaigns').update({name,purpose:text(fd,'purpose').slice(0,1200)||null,...campaignPatch(fd),updated_at:new Date().toISOString(),...(current.status==='approved'||current.status==='paused'?{status:'draft',approved_by:null,approved_at:null}:{})}).eq('tenant_id',TENANT_ID).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function cloneDripCampaign(fd:FormData){const{claims}=await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id');const{data:campaign,error}=await s.from('email_drip_campaigns').select('name,slug,audience,audience_rules,trigger_event,purpose,campaign_goal,start_at,send_timezone,send_hour,utm_source,utm_medium,utm_campaign,email_drip_steps(step_order,delay_days,subject,preheader,body,cta_label,cta_url,is_active)').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(error||!campaign)throw new Error('Campaign not found.');const suffix=Date.now().toString().slice(-6);const{data:copy,error:copyError}=await s.from('email_drip_campaigns').insert({tenant_id:TENANT_ID,name:`${campaign.name} Copy`,slug:`${campaign.slug}-copy-${suffix}`,audience:campaign.audience,audience_rules:campaign.audience_rules,trigger_event:campaign.trigger_event,purpose:campaign.purpose,campaign_goal:campaign.campaign_goal,start_at:null,send_timezone:campaign.send_timezone,send_hour:campaign.send_hour,utm_source:campaign.utm_source,utm_medium:campaign.utm_medium,utm_campaign:campaign.utm_campaign,status:'draft',created_by:String(claims.sub)}).select('id').single();if(copyError||!copy)throw new Error(copyError?.message||'Unable to clone campaign.');const steps=((campaign as any).email_drip_steps??[]).map((step:any)=>({campaign_id:copy.id,step_order:step.step_order,delay_days:step.delay_days,subject:step.subject,preheader:step.preheader,body:step.body,cta_label:step.cta_label,cta_url:step.cta_url,is_active:step.is_active}));if(steps.length){const{error:stepError}=await s.from('email_drip_steps').insert(steps);if(stepError)throw new Error(stepError.message)}refresh()}
export async function createDripStep(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const campaignId=text(fd,'campaign_id');const{data:campaign}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(!campaign)throw new Error('Campaign not found.');if(campaign.status==='live')throw new Error('Pause the campaign before changing its sequence.');const subject=text(fd,'subject').slice(0,220),body=text(fd,'body').slice(0,8000);if(!subject||!body)throw new Error('Subject and body are required.');const{error}=await s.from('email_drip_steps').insert({campaign_id:campaignId,step_order:Math.max(1,Number(text(fd,'step_order')||1)),delay_days:Math.max(0,Number(text(fd,'delay_days')||0)),subject,preheader:text(fd,'preheader').slice(0,260)||null,body,cta_label:text(fd,'cta_label').slice(0,120)||null,cta_url:text(fd,'cta_url').slice(0,600)||null,is_active:true});if(error)throw new Error(error.message);await demoteApprovalIfNeeded(s,campaignId,campaign.status);refresh()}
export async function saveDripStep(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id'),campaignId=text(fd,'campaign_id');const{data:campaign}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(!campaign)throw new Error('Campaign not found.');if(campaign.status==='live')throw new Error('Pause the campaign before editing a live email step.');const subject=text(fd,'subject').slice(0,220),body=text(fd,'body').slice(0,8000);if(!subject||!body)throw new Error('Subject and body are required.');const{error}=await s.from('email_drip_steps').update({delay_days:Math.max(0,Number(text(fd,'delay_days')||0)),subject,preheader:text(fd,'preheader').slice(0,260)||null,body,cta_label:text(fd,'cta_label').slice(0,120)||null,cta_url:text(fd,'cta_url').slice(0,600)||null,is_active:fd.get('is_active')==='on',updated_at:new Date().toISOString()}).eq('id',id).eq('campaign_id',campaignId);if(error)throw new Error(error.message);await demoteApprovalIfNeeded(s,campaignId,campaign.status);refresh()}
export async function deleteDripStep(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id'),campaignId=text(fd,'campaign_id');const{data:campaign}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(!campaign)throw new Error('Campaign not found.');if(campaign.status==='live')throw new Error('Pause the campaign before deleting a step.');const{error}=await s.from('email_drip_steps').delete().eq('id',id).eq('campaign_id',campaignId);if(error)throw new Error(error.message);await demoteApprovalIfNeeded(s,campaignId,campaign.status);refresh()}

function rowMatchesAudience(b:any,campaign:any){const audience=campaign.audience||'verified_opted_in',rules=campaign.audience_rules||{},categories=(b.business_categories??[]).flatMap((x:any)=>{const c=Array.isArray(x.categories)?x.categories[0]:x.categories;return c?[c]:[]}),verticals=new Set(categories.map((c:any)=>String(c.vertical||'').toLowerCase())),names=new Set(categories.map((c:any)=>String(c.name||'').toLowerCase())),serviceAreas=new Set((b.business_service_areas??[]).map((x:any)=>{const l=Array.isArray(x.locations)?x.locations[0]:x.locations;return String(l?.name||'').toLowerCase()})),branchCities=new Set((b.business_locations??[]).filter((x:any)=>x?.is_active!==false).map((x:any)=>String(x.city||'').toLowerCase())),operating=String(b.attributes?.operating_model||'').toLowerCase();if(audience==='home_services')return verticals.has('home');if(audience==='restaurants')return verticals.has('restaurant');if(audience==='retail')return verticals.has('retail');if(audience==='online')return operating==='online';if(audience==='storefront')return operating==='storefront'||operating==='both'||(b.business_locations??[]).some((x:any)=>x?.is_active!==false);if(audience==='category')return Boolean(rules.category)&&names.has(String(rules.category).toLowerCase());if(audience==='city'){const city=String(rules.city||'').toLowerCase();return Boolean(city)&&(serviceAreas.has(city)||branchCities.has(city))}return true}
async function eligibleBusinessMap(s:any,campaign:any){const{submissions,error:subError}=await(async()=>{const r=await s.from('business_submissions').select('promoted_business_id,email,contact_name,business_name').eq('tenant_id',TENANT_ID).eq('status','approved').eq('marketing_opt_in',true).not('promoted_business_id','is',null).limit(5000);return{submissions:r.data??[],error:r.error}})();if(subError)throw new Error(subError.message);const ids=[...new Set((submissions as any[]).map(x=>x.promoted_business_id).filter(Boolean))] as string[];if(!ids.length)return new Map<string,any>();const{data:businesses,error:bError}=await s.from('businesses').select('id,attributes,business_categories(categories(name,vertical)),business_service_areas(locations(name)),business_locations(city,location_type,is_active)').eq('tenant_id',TENANT_ID).eq('status','published').eq('verified',true).in('id',ids);if(bError)throw new Error(bError.message);const eligible=new Set((businesses??[]).filter((b:any)=>rowMatchesAudience(b,campaign)).map((b:any)=>b.id)),result=new Map<string,any>();for(const sub of submissions as any[])if(eligible.has(sub.promoted_business_id)&&!result.has(sub.promoted_business_id))result.set(sub.promoted_business_id,sub);return result}
async function enrollEligible(s:any,campaignId:string){const{data:campaign,error:cError}=await s.from('email_drip_campaigns').select('id,slug,audience,audience_rules,trigger_event,start_at,send_hour').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(cError||!campaign)throw new Error('Campaign not found.');if(campaign.trigger_event==='manual')return 0;const{data:first}=await s.from('email_drip_steps').select('step_order,delay_days').eq('campaign_id',campaignId).eq('is_active',true).order('step_order').limit(1).maybeSingle();if(!first)return 0;const byBusiness=await eligibleBusinessMap(s,campaign),base=campaignStart(campaign),rows=[...byBusiness.entries()].map(([businessId,sub])=>({tenant_id:TENANT_ID,campaign_id:campaignId,business_id:businessId,recipient_email:String(sub.email).toLowerCase(),recipient_name:sub.contact_name||sub.business_name,status:'active',source:'automatic',next_step_order:first.step_order,enrolled_at:base.toISOString(),next_send_at:new Date(base.getTime()+Number(first.delay_days||0)*86400000).toISOString(),updated_at:new Date().toISOString()}));if(!rows.length)return 0;const{data,error}=await s.from('email_drip_enrollments').upsert(rows,{onConflict:'campaign_id,business_id,recipient_email',ignoreDuplicates:true}).select('id');if(error)throw new Error(error.message);return(data??[]).length}

export async function changeDripCampaignStatus(fd:FormData){const{claims}=await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id'),action=text(fd,'action');const{data:campaign}=await s.from('email_drip_campaigns').select('id,status,start_at').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(!campaign)throw new Error('Campaign not found.');let patch:Record<string,unknown>={updated_at:new Date().toISOString()};if(action==='approve'){if(campaign.status!=='draft'&&campaign.status!=='paused')throw new Error('Only a draft or paused campaign can be approved.');const{data:steps}=await s.from('email_drip_steps').select('id').eq('campaign_id',id).eq('is_active',true).limit(1);if(!steps?.length)throw new Error('Add at least one active email step before approval.');patch={...patch,status:'approved',approved_by:String(claims.sub),approved_at:new Date().toISOString()}}else if(action==='live'){if(campaign.status!=='approved')throw new Error('Review and approve the campaign before making it live.');patch={...patch,status:'live'}}else if(action==='pause'){if(campaign.status!=='live')throw new Error('Only a live campaign can be paused.');patch={...patch,status:'paused'}}else if(action==='archive'){if(campaign.status==='live')throw new Error('Pause the campaign before archiving it.');patch={...patch,status:'archived'}}else if(action==='draft'){if(campaign.status==='live')throw new Error('Pause the campaign before returning it to draft.');patch={...patch,status:'draft',approved_by:null,approved_at:null}}else throw new Error('Invalid campaign action.');const{error}=await s.from('email_drip_campaigns').update(patch).eq('tenant_id',TENANT_ID).eq('id',id);if(error)throw new Error(error.message);if(action==='live')await enrollEligible(s,id);refresh()}
export async function enrollBusinessManually(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const campaignId=text(fd,'campaign_id'),businessId=text(fd,'business_id');if(!uuid.test(campaignId)||!uuid.test(businessId))throw new Error('Choose a valid campaign and business.');const{data:campaign}=await s.from('email_drip_campaigns').select('id,status,start_at').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(!campaign||campaign.status!=='live')throw new Error('Manual enrollment is available only for a live campaign.');const{data:first}=await s.from('email_drip_steps').select('step_order,delay_days').eq('campaign_id',campaignId).eq('is_active',true).order('step_order').limit(1).maybeSingle();if(!first)throw new Error('Campaign has no active steps.');const{data:business}=await s.from('businesses').select('id,name,status,verified').eq('tenant_id',TENANT_ID).eq('id',businessId).maybeSingle();if(!business||business.status!=='published'||!business.verified)throw new Error('Business must be verified and published.');const{data:sub}=await s.from('business_submissions').select('email,contact_name,business_name').eq('tenant_id',TENANT_ID).eq('status','approved').eq('marketing_opt_in',true).eq('promoted_business_id',businessId).order('reviewed_at',{ascending:false}).limit(1).maybeSingle();if(!sub?.email)throw new Error('This business does not have a valid promotional-email opt-in.');const base=campaignStart(campaign);const{error}=await s.from('email_drip_enrollments').upsert({tenant_id:TENANT_ID,campaign_id:campaignId,business_id:businessId,recipient_email:String(sub.email).toLowerCase(),recipient_name:sub.contact_name||sub.business_name||business.name,status:'active',source:'manual',next_step_order:first.step_order,enrolled_at:base.toISOString(),next_send_at:new Date(base.getTime()+Number(first.delay_days||0)*86400000).toISOString(),paused_at:null,completed_at:null,updated_at:new Date().toISOString()},{onConflict:'campaign_id,business_id,recipient_email'});if(error)throw new Error(error.message);refresh()}
export async function changeEnrollmentStatus(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id'),action=text(fd,'action'),now=new Date().toISOString();if(action==='pause'){const{error}=await s.from('email_drip_enrollments').update({status:'paused',paused_at:now,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',id).eq('status','active');if(error)throw new Error(error.message)}else if(action==='resume'){const{error}=await s.from('email_drip_enrollments').update({status:'active',paused_at:null,next_send_at:now,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',id).eq('status','paused');if(error)throw new Error(error.message)}else if(action==='complete'){const{error}=await s.from('email_drip_enrollments').update({status:'completed',completed_at:now,next_send_at:null,updated_at:now}).eq('tenant_id',TENANT_ID).eq('id',id).in('status',['active','paused']);if(error)throw new Error(error.message)}else throw new Error('Invalid enrollment action.');refresh()}
export async function retryFailedEmail(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const{error}=await s.from('email_outbox').update({status:'queued',scheduled_for:new Date().toISOString(),error_message:null,updated_at:new Date().toISOString()}).eq('tenant_id',TENANT_ID).eq('id',text(fd,'id')).eq('status','failed');if(error)throw new Error(error.message);refresh()}
export async function syncCampaignAudience(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id');const{data:campaign}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(!campaign||campaign.status!=='live')throw new Error('Audience sync is available only for a live campaign.');await enrollEligible(s,id);refresh()}

export async function queueDueDrips(s:any){const now=new Date().toISOString();const{data:enrollments,error}=await s.from('email_drip_enrollments').select('id,campaign_id,business_id,recipient_email,recipient_name,next_step_order,enrolled_at,email_drip_campaigns!inner(slug,status,utm_source,utm_medium,utm_campaign)').eq('tenant_id',TENANT_ID).eq('status','active').lte('next_send_at',now).eq('email_drip_campaigns.status','live').order('next_send_at').limit(250);if(error)throw new Error(error.message);let queued=0;for(const e of enrollments??[]){const campaign:any=Array.isArray((e as any).email_drip_campaigns)?(e as any).email_drip_campaigns[0]:(e as any).email_drip_campaigns;let{data:step}=await s.from('email_drip_steps').select('id,step_order,subject,body,cta_label,cta_url').eq('campaign_id',(e as any).campaign_id).eq('step_order',(e as any).next_step_order).eq('is_active',true).maybeSingle();if(!step){const r=await s.from('email_drip_steps').select('id,step_order,subject,body,cta_label,cta_url').eq('campaign_id',(e as any).campaign_id).gt('step_order',(e as any).next_step_order).eq('is_active',true).order('step_order').limit(1).maybeSingle();step=r.data}if(!step){await s.from('email_drip_enrollments').update({status:'completed',completed_at:now,next_send_at:null,updated_at:now}).eq('id',(e as any).id);continue}const{error:outboxError}=await s.from('email_outbox').insert({tenant_id:TENANT_ID,business_id:(e as any).business_id,recipient_email:(e as any).recipient_email,recipient_name:(e as any).recipient_name,message_type:'drip',template_key:`drip:${campaign?.slug||'campaign'}`,campaign_id:(e as any).campaign_id,enrollment_id:(e as any).id,step_id:step.id,subject:step.subject,body:step.body,cta_label:step.cta_label,cta_url:withUtm(step.cta_url,campaign),status:'queued',scheduled_for:now});if(outboxError&&outboxError.code!=='23505')throw new Error(outboxError.message);if(!outboxError)queued++;const{data:next}=await s.from('email_drip_steps').select('step_order,delay_days').eq('campaign_id',(e as any).campaign_id).gt('step_order',step.step_order).eq('is_active',true).order('step_order').limit(1).maybeSingle();if(next){const start=new Date((e as any).enrolled_at).getTime();await s.from('email_drip_enrollments').update({next_step_order:next.step_order,next_send_at:new Date(start+Number(next.delay_days||0)*86400000).toISOString(),last_sent_at:now,updated_at:now}).eq('id',(e as any).id)}else await s.from('email_drip_enrollments').update({status:'completed',completed_at:now,next_send_at:null,last_sent_at:now,updated_at:now}).eq('id',(e as any).id)}return queued}
export async function processDripQueue(){await requireAdmin('/admin/email-drips');const s=await createClient();await queueDueDrips(s);await processBusinessEmailOutbox(75);refresh()}
