'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { requireAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { processBusinessEmailOutbox } from '@/lib/business-email'

const text=(fd:FormData,key:string)=>String(fd.get(key)??'').trim()
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)
const refresh=()=>revalidatePath('/admin/email-drips')

export async function createDripCampaign(fd:FormData){const{claims}=await requireAdmin('/admin/email-drips');const s=await createClient();const name=text(fd,'name').slice(0,160);if(!name)throw new Error('Campaign name is required.');const slug=slugify(text(fd,'slug')||name);if(!slug)throw new Error('Campaign slug is required.');const{error}=await s.from('email_drip_campaigns').insert({tenant_id:TENANT_ID,name,slug,audience:'verified_business_owners',trigger_event:'business_verified',status:'draft',purpose:text(fd,'purpose').slice(0,1200)||null,created_by:String(claims.sub)});if(error)throw new Error(error.message);refresh()}
export async function saveDripCampaign(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id');const{data:current}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(!current)throw new Error('Campaign not found.');if(current.status==='live')throw new Error('Pause a live campaign before editing its core settings.');const{error}=await s.from('email_drip_campaigns').update({name:text(fd,'name').slice(0,160),purpose:text(fd,'purpose').slice(0,1200)||null,updated_at:new Date().toISOString()}).eq('tenant_id',TENANT_ID).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function createDripStep(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const campaignId=text(fd,'campaign_id');const order=Math.max(1,Number(text(fd,'step_order')||1));const{error}=await s.from('email_drip_steps').insert({campaign_id:campaignId,step_order:order,delay_days:Math.max(0,Number(text(fd,'delay_days')||0)),subject:text(fd,'subject').slice(0,220),preheader:text(fd,'preheader').slice(0,260)||null,body:text(fd,'body').slice(0,8000),cta_label:text(fd,'cta_label').slice(0,120)||null,cta_url:text(fd,'cta_url').slice(0,600)||null,is_active:true});if(error)throw new Error(error.message);refresh()}
export async function saveDripStep(fd:FormData){await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id');const campaignId=text(fd,'campaign_id');const{data:campaign}=await s.from('email_drip_campaigns').select('status').eq('tenant_id',TENANT_ID).eq('id',campaignId).maybeSingle();if(!campaign)throw new Error('Campaign not found.');if(campaign.status==='live')throw new Error('Pause the campaign before editing a live email step.');const{error}=await s.from('email_drip_steps').update({delay_days:Math.max(0,Number(text(fd,'delay_days')||0)),subject:text(fd,'subject').slice(0,220),preheader:text(fd,'preheader').slice(0,260)||null,body:text(fd,'body').slice(0,8000),cta_label:text(fd,'cta_label').slice(0,120)||null,cta_url:text(fd,'cta_url').slice(0,600)||null,is_active:fd.get('is_active')==='on',updated_at:new Date().toISOString()}).eq('id',id).eq('campaign_id',campaignId);if(error)throw new Error(error.message);refresh()}

async function enrollEligible(s:any,campaignId:string){const{data:first}=await s.from('email_drip_steps').select('step_order,delay_days').eq('campaign_id',campaignId).eq('is_active',true).order('step_order').limit(1).maybeSingle();if(!first)return 0;const{submissions,error:subError}=await(async()=>{const r=await s.from('business_submissions').select('promoted_business_id,email,contact_name,business_name').eq('tenant_id',TENANT_ID).eq('status','approved').eq('marketing_opt_in',true).not('promoted_business_id','is',null).limit(5000);return{submissions:r.data??[],error:r.error}})();if(subError)throw new Error(subError.message);const ids=[...new Set(submissions.map((x:any)=>x.promoted_business_id).filter(Boolean))] as string[];if(!ids.length)return 0;const{data:businesses,error:bError}=await s.from('businesses').select('id').eq('tenant_id',TENANT_ID).eq('status','published').eq('verified',true).in('id',ids);if(bError)throw new Error(bError.message);const eligible=new Set((businesses??[]).map((x:any)=>x.id));const byBusiness=new Map<string,any>();for(const sub of submissions as any[])if(eligible.has(sub.promoted_business_id)&&!byBusiness.has(sub.promoted_business_id))byBusiness.set(sub.promoted_business_id,sub);const enrolledAt=new Date();const rows=[...byBusiness.entries()].map(([businessId,sub])=>({tenant_id:TENANT_ID,campaign_id:campaignId,business_id:businessId,recipient_email:String(sub.email).toLowerCase(),recipient_name:sub.contact_name||sub.business_name,status:'active',next_step_order:first.step_order,enrolled_at:enrolledAt.toISOString(),next_send_at:new Date(enrolledAt.getTime()+Number(first.delay_days||0)*86400000).toISOString()}));if(!rows.length)return 0;const{data,error}=await s.from('email_drip_enrollments').upsert(rows,{onConflict:'campaign_id,business_id,recipient_email',ignoreDuplicates:true}).select('id');if(error)throw new Error(error.message);return(data??[]).length}

export async function changeDripCampaignStatus(fd:FormData){const{claims}=await requireAdmin('/admin/email-drips');const s=await createClient();const id=text(fd,'id'),action=text(fd,'action');const{data:campaign}=await s.from('email_drip_campaigns').select('id,status').eq('tenant_id',TENANT_ID).eq('id',id).maybeSingle();if(!campaign)throw new Error('Campaign not found.');let patch:Record<string,unknown>={updated_at:new Date().toISOString()};if(action==='approve'){if(campaign.status!=='draft'&&campaign.status!=='paused')throw new Error('Only a draft or paused campaign can be approved.');patch={...patch,status:'approved',approved_by:String(claims.sub),approved_at:new Date().toISOString()}}else if(action==='live'){if(campaign.status!=='approved')throw new Error('Review and approve the campaign before making it live.');patch={...patch,status:'live'}}else if(action==='pause'){if(campaign.status!=='live')throw new Error('Only a live campaign can be paused.');patch={...patch,status:'paused'}}else if(action==='archive'){patch={...patch,status:'archived'}}else if(action==='draft'){if(campaign.status==='live')throw new Error('Pause the campaign before returning it to draft.');patch={...patch,status:'draft',approved_by:null,approved_at:null}}else throw new Error('Invalid campaign action.');const{error}=await s.from('email_drip_campaigns').update(patch).eq('tenant_id',TENANT_ID).eq('id',id);if(error)throw new Error(error.message);if(action==='live')await enrollEligible(s,id);refresh()}

async function queueDueDrips(s:any){const now=new Date().toISOString();const{data:enrollments,error}=await s.from('email_drip_enrollments').select('id,campaign_id,business_id,recipient_email,recipient_name,next_step_order,enrolled_at,email_drip_campaigns!inner(slug,status)').eq('tenant_id',TENANT_ID).eq('status','active').lte('next_send_at',now).eq('email_drip_campaigns.status','live').order('next_send_at').limit(250);if(error)throw new Error(error.message);let queued=0;for(const e of enrollments??[]){const campaign:any=Array.isArray((e as any).email_drip_campaigns)?(e as any).email_drip_campaigns[0]:(e as any).email_drip_campaigns;let{data:step}=await s.from('email_drip_steps').select('id,step_order,subject,body,cta_label,cta_url').eq('campaign_id',(e as any).campaign_id).eq('step_order',(e as any).next_step_order).eq('is_active',true).maybeSingle();if(!step){const r=await s.from('email_drip_steps').select('id,step_order,subject,body,cta_label,cta_url').eq('campaign_id',(e as any).campaign_id).gt('step_order',(e as any).next_step_order).eq('is_active',true).order('step_order').limit(1).maybeSingle();step=r.data}if(!step){await s.from('email_drip_enrollments').update({status:'completed',next_send_at:null}).eq('id',(e as any).id);continue}const{error:outboxError}=await s.from('email_outbox').insert({tenant_id:TENANT_ID,business_id:(e as any).business_id,recipient_email:(e as any).recipient_email,recipient_name:(e as any).recipient_name,message_type:'drip',template_key:`drip:${campaign?.slug||'campaign'}`,campaign_id:(e as any).campaign_id,enrollment_id:(e as any).id,step_id:step.id,subject:step.subject,body:step.body,cta_label:step.cta_label,cta_url:step.cta_url,status:'queued',scheduled_for:now});if(outboxError&&outboxError.code!=='23505')throw new Error(outboxError.message);if(!outboxError)queued++;const{data:next}=await s.from('email_drip_steps').select('step_order,delay_days').eq('campaign_id',(e as any).campaign_id).gt('step_order',step.step_order).eq('is_active',true).order('step_order').limit(1).maybeSingle();if(next){const start=new Date((e as any).enrolled_at).getTime();await s.from('email_drip_enrollments').update({next_step_order:next.step_order,next_send_at:new Date(start+Number(next.delay_days||0)*86400000).toISOString(),last_sent_at:now}).eq('id',(e as any).id)}else await s.from('email_drip_enrollments').update({status:'completed',next_send_at:null,last_sent_at:now}).eq('id',(e as any).id)}return queued}

export async function processDripQueue(){await requireAdmin('/admin/email-drips');const s=await createClient();await queueDueDrips(s);await processBusinessEmailOutbox(50);refresh()}
