import { createClient } from '@/lib/supabase/server'
import { requireAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'
import { changeDripCampaignStatus,createDripCampaign,createDripStep,processDripQueue,saveDripCampaign,saveDripStep } from './actions'

export const dynamic='force-dynamic'

const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default async function Page(){
  await requireAdmin('/admin/email-drips')
  const s=await createClient()
  const[{data:campaigns,error},{count:queued},{count:sent},{count:failed},{count:activeEnrollments}]=await Promise.all([
    s.from('email_drip_campaigns').select('id,name,slug,audience,trigger_event,status,purpose,approved_at,created_at,updated_at,email_drip_steps(id,step_order,delay_days,subject,preheader,body,cta_label,cta_url,is_active)').eq('tenant_id',TENANT_ID).neq('status','archived').order('created_at'),
    s.from('email_outbox').select('*',{count:'exact',head:true}).eq('tenant_id',TENANT_ID).eq('status','queued'),
    s.from('email_outbox').select('*',{count:'exact',head:true}).eq('tenant_id',TENANT_ID).eq('status','sent'),
    s.from('email_outbox').select('*',{count:'exact',head:true}).eq('tenant_id',TENANT_ID).eq('status','failed'),
    s.from('email_drip_enrollments').select('*',{count:'exact',head:true}).eq('tenant_id',TENANT_ID).eq('status','active'),
  ])
  const provider=Boolean(process.env.RESEND_API_KEY&&process.env.BUSINESS_NOTIFICATION_FROM_EMAIL||process.env.RESEND_API_KEY&&process.env.LEAD_NOTIFICATION_FROM_EMAIL)
  const postal=Boolean(process.env.MARKETING_EMAIL_POSTAL_ADDRESS)
  return <>
    <div className="admin-page-head"><div><div className="kpi">Business Owner Lifecycle</div><h1>Email Drip Campaigns</h1><p className="muted">Create, review, approve and activate business-owner education after verification. Drafts never send. Promotional enrollments require the business to have opted in during onboarding.</p></div><span className="badge sponsored">Admin reviewed</span></div>
    {error&&<div className="notice warn">{error.message}</div>}
    <div className="stat-grid" style={{marginBottom:18}}><div className="stat">Active Enrollments<strong>{activeEnrollments??0}</strong></div><div className="stat">Queued Emails<strong>{queued??0}</strong></div><div className="stat">Sent Emails<strong>{sent??0}</strong></div><div className="stat">Failed Emails<strong>{failed??0}</strong></div></div>
    <div className={`notice ${provider?'success':'warn'}`}><strong>Email provider:</strong> {provider?'Resend credentials are configured for transactional delivery.':'Delivery is safely queued until RESEND_API_KEY and a sender email are configured.'} {postal?'Promotional footer address is configured.':'Promotional drip delivery remains blocked until MARKETING_EMAIL_POSTAL_ADDRESS is configured; this does not block transactional approval/verification messages.'}</div>
    <section className="admin-card" style={{marginBottom:18}}><div className="section-head compact-head"><div><div className="kpi">Queue Control</div><h2>Process Due Business Emails</h2><p className="small muted">Creates any drip messages currently due, then attempts delivery of queued messages when the provider and required promotional footer are configured.</p></div><form action={processDripQueue}><button className="btn btn-primary">Process Due Emails Now</button></form></div></section>
    <details className="admin-create-disclosure"><summary><span><strong>+ Create a Drip Campaign</strong><small>New campaigns always start as Draft.</small></span><span>Open form</span></summary><div className="admin-create-disclosure-body"><form action={createDripCampaign} className="admin-card"><div className="admin-form-grid"><label>Campaign Name<input name="name" required/></label><label>Slug <span className="small muted">optional</span><input name="slug" placeholder="auto-from-name"/></label></div><label>Purpose<textarea name="purpose" required placeholder="Who should receive this and what should it teach them?"/></label><button className="btn btn-primary">Create Draft Campaign</button></form></div></details>

    <div className="grid" style={{marginTop:20}}>{(campaigns??[]).map((campaign:any)=>{const steps=[...(campaign.email_drip_steps??[])].sort((a:any,b:any)=>a.step_order-b.step_order);return <section className="admin-card" key={campaign.id}>
      <div className="section-head compact-head"><div><div className="badges"><span className={`badge ${campaign.status==='live'?'verified':campaign.status==='approved'?'sponsored':'neutral'}`}>{label(campaign.status)}</span><span className="badge neutral">Trigger: {label(campaign.trigger_event)}</span></div><h2>{campaign.name}</h2><p className="small muted">{campaign.purpose}</p></div><div className="admin-row-actions">{campaign.status==='draft'||campaign.status==='paused'?<form action={changeDripCampaignStatus}><input type="hidden" name="id" value={campaign.id}/><input type="hidden" name="action" value="approve"/><button className="btn btn-light">Approve for Launch</button></form>:null}{campaign.status==='approved'?<form action={changeDripCampaignStatus}><input type="hidden" name="id" value={campaign.id}/><input type="hidden" name="action" value="live"/><button className="btn btn-primary">Go Live</button></form>:null}{campaign.status==='live'?<form action={changeDripCampaignStatus}><input type="hidden" name="id" value={campaign.id}/><input type="hidden" name="action" value="pause"/><button className="btn btn-light">Pause</button></form>:null}</div></div>
      <div className="notice"><strong>Review rule:</strong> Going Live is a separate action from approving the draft. Paid-placement copy must not imply better organic ranking, automatic verification or guaranteed leads. Skylight growth copy must not guarantee Google rankings.</div>
      <form action={saveDripCampaign} className="admin-card" style={{marginBottom:14}}><input type="hidden" name="id" value={campaign.id}/><div className="admin-form-grid"><label>Name<input name="name" defaultValue={campaign.name} required disabled={campaign.status==='live'}/></label><label>Status<input value={label(campaign.status)} readOnly/></label></div><label>Purpose<textarea name="purpose" defaultValue={campaign.purpose||''} disabled={campaign.status==='live'}/></label>{campaign.status!=='live'&&<button className="btn btn-light">Save Campaign</button>}</form>
      <div className="section-head compact-head"><div><div className="kpi">Sequence</div><h3>{steps.length} Email Step{steps.length===1?'':'s'}</h3></div></div>
      <div className="grid grid-2">{steps.map((step:any)=><form action={saveDripStep} className="admin-card" key={step.id}><input type="hidden" name="id" value={step.id}/><input type="hidden" name="campaign_id" value={campaign.id}/><div className="badges"><span className="badge neutral">Step {step.step_order}</span><span className="badge neutral">Day +{step.delay_days}</span></div><label>Delay Days<input type="number" min="0" name="delay_days" defaultValue={step.delay_days} disabled={campaign.status==='live'}/></label><label>Subject<input name="subject" defaultValue={step.subject} required disabled={campaign.status==='live'}/></label><label>Preheader<input name="preheader" defaultValue={step.preheader||''} disabled={campaign.status==='live'}/></label><label>Email Body<textarea name="body" defaultValue={step.body} style={{minHeight:180}} required disabled={campaign.status==='live'}/></label><div className="admin-form-grid"><label>CTA Label<input name="cta_label" defaultValue={step.cta_label||''} disabled={campaign.status==='live'}/></label><label>CTA URL<input name="cta_url" defaultValue={step.cta_url||''} disabled={campaign.status==='live'}/></label></div><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={step.is_active} disabled={campaign.status==='live'}/> Active step</label>{campaign.status!=='live'&&<button className="btn btn-light">Save Step</button>}</form>)}</div>
      {campaign.status!=='live'&&<details className="admin-create-disclosure" style={{marginTop:14}}><summary><span><strong>+ Add Email Step</strong><small>Add another message before approving the campaign.</small></span><span>Open</span></summary><div className="admin-create-disclosure-body"><form action={createDripStep} className="admin-card"><input type="hidden" name="campaign_id" value={campaign.id}/><div className="admin-form-grid"><label>Step Order<input type="number" name="step_order" min="1" defaultValue={steps.length+1} required/></label><label>Delay Days<input type="number" name="delay_days" min="0" defaultValue="3" required/></label><label>Subject<input name="subject" required/></label><label>Preheader<input name="preheader"/></label></div><label>Body<textarea name="body" required style={{minHeight:150}}/></label><div className="admin-form-grid"><label>CTA Label<input name="cta_label"/></label><label>CTA URL<input name="cta_url" placeholder="/for-businesses"/></label></div><button className="btn btn-primary">Add Draft Step</button></form></div></details>}
    </section>})}</div>
  </>
}
