import { NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { requireSuperAdmin } from '@/lib/auth'
import { TENANT_ID } from '@/lib/constants'

const text=(v:unknown)=>typeof v==='string'?v.trim():''
const safeUrl=(v:unknown)=>{const value=text(v);if(!value)return null;if(value.startsWith('/'))return value;try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function normalized(body:any){
 const promo=text(body.promo_text).slice(0,200);if(!promo)throw new Error('Promotion text is required.')
 const origin=['manual','stripe','promotional'].includes(text(body.origin))?text(body.origin):'manual'
 return{business_id:text(body.business_id),placement:'homepage_ticker',promo_text:promo,promo_cta_label:(text(body.promo_cta_label)||'View Deal').slice(0,40),promo_url:safeUrl(body.promo_url),starts_on:text(body.starts_on)||null,ends_on:text(body.ends_on)||null,active:body.active!==false,priority:Math.max(0,Math.min(1000,Number(body.priority??100)||100)),sort_order:Math.max(0,Math.min(100000,Number(body.sort_order??100)||100)),rotation_weight:1,origin,monthly_add_on_cents:500,market_location_id:null,category_id:null,page_path:null}
}
function refresh(){revalidatePath('/');revalidatePath('/admin/sponsorships');revalidatePath('/for-businesses')}
export async function POST(req:Request){try{const{claims}=await requireSuperAdmin('/admin/sponsorships');const body=normalized(await req.json());if(!body.business_id)return NextResponse.json({error:'Business is required.'},{status:400});const s=await createClient();const{data,error}=await s.from('sponsorships').insert({...body,tenant_id:TENANT_ID,provider:body.origin==='stripe'?'stripe':'manual'}).select('id,provider').single();if(error)return NextResponse.json({error:error.message},{status:400});await s.from('audit_logs').insert({tenant_id:TENANT_ID,actor_user_id:String(claims.sub),action_type:'homepage_deal_created',action_text:`Created homepage deal ${data.id} for business ${body.business_id}`});refresh();return NextResponse.json({ok:true,id:data.id,provider:data.provider})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create homepage deal.'},{status:400})}}
export async function PATCH(req:Request){try{const{claims}=await requireSuperAdmin('/admin/sponsorships');const raw=await req.json() as any,id=text(raw.id);if(!id)return NextResponse.json({error:'Promotion id is required.'},{status:400});const s=await createClient();if(raw.toggleOnly===true){const{data:current}=await s.from('sponsorships').select('active').eq('tenant_id',TENANT_ID).eq('id',id).eq('placement','homepage_ticker').maybeSingle();if(!current)return NextResponse.json({error:'Promotion not found.'},{status:404});const active=!current.active;const{error}=await s.from('sponsorships').update({active}).eq('tenant_id',TENANT_ID).eq('id',id).eq('placement','homepage_ticker');if(error)return NextResponse.json({error:error.message},{status:400});await s.from('audit_logs').insert({tenant_id:TENANT_ID,actor_user_id:String(claims.sub),action_type:active?'homepage_deal_activated':'homepage_deal_paused',action_text:`${active?'Activated':'Paused'} homepage deal ${id}`});refresh();return NextResponse.json({ok:true,active})}const body=normalized(raw);if(!body.business_id)return NextResponse.json({error:'Business is required.'},{status:400});const{error}=await s.from('sponsorships').update({...body,provider:body.origin==='stripe'?'stripe':'manual'}).eq('tenant_id',TENANT_ID).eq('id',id).eq('placement','homepage_ticker');if(error)return NextResponse.json({error:error.message},{status:400});await s.from('audit_logs').insert({tenant_id:TENANT_ID,actor_user_id:String(claims.sub),action_type:'homepage_deal_updated',action_text:`Updated homepage deal ${id} for business ${body.business_id}`});refresh();return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to update homepage deal.'},{status:400})}}
export async function DELETE(req:Request){try{const{claims}=await requireSuperAdmin('/admin/sponsorships');const raw=await req.json() as any,id=text(raw.id);if(!id)return NextResponse.json({error:'Promotion id is required.'},{status:400});const s=await createClient();const{error}=await s.from('sponsorships').delete().eq('tenant_id',TENANT_ID).eq('id',id).eq('placement','homepage_ticker');if(error)return NextResponse.json({error:error.message},{status:400});await s.from('audit_logs').insert({tenant_id:TENANT_ID,actor_user_id:String(claims.sub),action_type:'homepage_deal_removed',action_text:`Removed homepage deal ${id}`});refresh();return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to remove homepage deal.'},{status:400})}}
