import type{Metadata}from'next'
import Link from'next/link'
import{SiteShell}from'@/components/SiteShell'
import{ProjectMatchForm}from'@/components/ProjectMatchForm'

export const metadata:Metadata={title:'Get Quotes & Find Local Pros | Central Illinois Local Pros',description:'Tell Central Illinois Local Pros what you need. Staff reviews your request and deliberately matches it with appropriate local businesses without automatic routing.',alternates:{canonical:'/project-match'}}
export default function Page(){return <SiteShell><main>
 <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Project Match · Staff Reviewed</div><h1>Tell us what you need. We’ll help find the right local pro.</h1><p>One structured request can save you from repeating the same project details to multiple businesses. Your request goes to our private Admin queue first, and contact information is released only when staff deliberately matches the request.</p><div className="hero-actions"><a className="btn btn-primary" href="#project-match-form">Start My Project</a><Link className="btn btn-light" href="/search">Browse Businesses Instead</Link></div><div className="trust-row"><span>✓ No automatic routing</span><span>✓ No payment required</span><span>✓ Staff-reviewed matching</span></div></div><div className="card"><div className="kpi">How Project Match works</div><div className="info-row"><span>1. Describe the project</span><strong>Service + location + timeline + budget context</strong></div><div className="info-row"><span>2. Private review</span><strong>Admin checks fit and request quality</strong></div><div className="info-row"><span>3. Deliberate match</span><strong>Staff chooses the appropriate local business</strong></div><div className="info-row"><span>4. Business follow-up</span><strong>Only delivered recipients receive contact details</strong></div></div></div></section>
 <section className="section"><div className="container grid grid-3"><div className="card"><div className="kpi">For Home Projects</div><h2>Better project context</h2><p className="muted">HVAC, plumbing, electrical, lawn care, remodeling and other services can include property type, project size, timeline and budget range.</p></div><div className="card"><div className="kpi">For Professional Services</div><h2>Clearer consultations</h2><p className="muted">Use the same request flow for attorneys and other professional services while avoiding sensitive personal details in the initial request.</p></div><div className="card"><div className="kpi">Consumer Control</div><h2>Your request is not blasted automatically</h2><p className="muted">Paid plans, Sponsored placement and verification do not decide who receives your request. Staff reviews and deliberately delivers it.</p></div></div></section>
 <section className="section" id="project-match-form"><div className="container" style={{maxWidth:920}}><div className="section-head"><div><div className="kpi">Start a Project</div><h2>Request local matches</h2><p className="muted">Complete what you know. “Not sure” is a valid answer for budget, project type or timing.</p></div></div><ProjectMatchForm/></div></section>
 </main></SiteShell>}
