-- Source-backed inventory expansion for thinner Central Illinois markets.
-- Imported profiles remain unclaimed, unverified, unfeatured, unsponsored and carry no imported ratings/reviews.

create temp table _cilp_inventory_business_stage (
  slug text primary key,
  name text not null,
  abbr text,
  city_slug text not null,
  city text not null,
  phone text,
  email text,
  website text,
  description text not null,
  address_text text,
  postal_code text,
  location_type text,
  source_name text not null,
  source_url text not null,
  attributes jsonb not null default '{}'::jsonb,
  service_area_only boolean not null default false
) on commit drop;

insert into _cilp_inventory_business_stage
(slug,name,abbr,city_slug,city,phone,email,website,description,address_text,postal_code,location_type,source_name,source_url,attributes,service_area_only)
values
('kc-lawn-care-streator','KC Lawn Care','KC','streator','Streator','815-822-7044',null,null,'Locally owned Streator lawn-care and landscaping service providing mowing, landscaping, plowing and related outdoor property work.',null,'61364',null,'BBB business profile','https://www.bbb.org/us/il/streator/profile/lawn-care/kc-lawn-care-0654-1000037538','{"discovery":"public_business_profile","service_area_business":true,"owner_name":"Justis Casey"}'::jsonb,true),
('kmetzs-hawthorne-kennel-grooming-streator','Kmetz''s Hawthorne Kennel & Grooming LLC','KH','streator','Streator','815-672-3871',null,null,'Family-owned Streator pet-care business offering pet boarding, dog daycare and grooming services for dogs and cats.','1607 Hawthorne Rd, Streator, IL 61364','61364','storefront','Current local pet-services profile','https://www.loc8nearme.com/illinois/streator/pet-facilities/','{"discovery":"public_business_profile"}'::jsonb,false),
('fairy-tails-grooming-streator','Fairy Tails Grooming LLC','FT','streator','Streator','815-510-9925',null,null,'Independent Streator pet grooming shop providing routine dog grooming, bathing, haircuts and nail-care services.','1202 Columbus Rd, Streator, IL 61364','61364','storefront','Current local pet-services profile','https://www.loc8nearme.com/illinois/streator/pet-facilities/','{"discovery":"public_business_profile"}'::jsonb,false),
('brassfield-krueger-streator','Brassfield & Krueger, Ltd.','BK','streator','Streator','815-672-8878',null,'https://www.bkr-law.com/','Illinois personal-injury law firm with a physical Streator office handling accident and injury matters.','203 Armory Court, Streator, IL 61364','61364','office','Official law firm website','https://www.bkr-law.com/directions/','{"discovery":"official_web"}'::jsonb,false),
('danchris-nursery-streator','Danchris Nursery','DN','streator','Streator','815-672-8135','info@danchrisnursery.com','https://danchrisnurserylandscapingandgardencenter.com/','Family-owned Streator nursery, garden center and landscaping company providing landscape design and installation, plants, hardscapes and related outdoor services.','1000 Bernstein St, Streator, IL 61364','61364','storefront','Official business website','https://danchrisnurserylandscapingandgardencenter.com/','{"discovery":"official_web"}'::jsonb,false),
('ajs-services-decatur','KJH Services, Inc. DBA A.J.''s Services','AJ','decatur','Decatur','217-519-3393','info@kjhservices.com','https://kjhservices.com/','Decatur lawn-care and property-service company providing recurring lawn maintenance, seasonal cleanup, landscaping, hardscaping and snow services.','2275 Salem School Rd, Decatur, IL 62521','62521','office','Official business website','https://kjhservices.com/','{"discovery":"official_web"}'::jsonb,false),
('poochis-pet-grooming-decatur','Poochi''s Pet Grooming','PG','decatur','Decatur','217-876-7387',null,null,'Local Decatur pet grooming business serving pet owners from its North Water Street location.','2950 N Water St Ste 140, Decatur, IL 62526','62526','storefront','Current local pet-services directory','https://www.yellowpages.com/decatur-il/pet-grooming','{"discovery":"public_business_directory"}'::jsonb,false),
('hollies-pet-paradise-decatur','Hollie''s Pet Paradise','HP','decatur','Decatur','217-853-1883',null,null,'Independent Decatur pet grooming shop providing grooming and nail-care services for local pets.','2727 W Rock Springs Rd, Decatur, IL 62521','62521','storefront','Current local business profile','https://www.loc8nearme.com/illinois/decatur/hollies-pet-paradise/5529480/','{"discovery":"public_business_profile"}'::jsonb,false),
('sawgrass-kennels-decatur','Sawgrass Kennels','SK','decatur','Decatur','217-877-3647',null,'https://sawgrasskennels.com/','Established Decatur-area dog and cat boarding facility offering boarding, individual play and walking options, bathing and specialty care accommodations.','7681 N Oakland Ave, Decatur, IL 62526','62526','storefront','Official business website','https://sawgrasskennels.com/','{"discovery":"official_web"}'::jsonb,false),
('mctague-services-morris','McTague Services','MS','morris','Morris','815-685-2866','info@mctagueservices.com','https://mctagueservices.com/','Locally owned Morris property-maintenance company providing lawn mowing, mulch installation, seasonal cleanups, trimming, snow removal and related yard services.',null,'60450',null,'Official business website','https://mctagueservices.com/','{"discovery":"official_web","service_area_business":true,"owner_name":"Nathan McTague"}'::jsonb,true),
('that-perennial-place-morris','That Perennial Place','TP','morris','Morris','815-942-2235',null,'https://thatperennialplace.com/','Second-generation family-owned Morris landscape company and garden center providing landscape design, lawn maintenance, hardscapes, plants and garden supplies.','1565 W Route 6, Morris, IL 60450','60450','storefront','Official business website','https://thatperennialplace.com/about-us/','{"discovery":"official_web"}'::jsonb,false),
('muddypaws-pet-spa-morris','MuddyPaws Pet Spa','MP','morris','Morris','815-603-2445',null,null,'Morris pet grooming business serving local pet owners from its Trend Drive location.','1255 Trend Dr #1254, Morris, IL 60450','60450','storefront','Current local pet-services directory','https://www.loc8nearme.com/illinois/morris/pet-facilities/','{"discovery":"public_business_directory"}'::jsonb,false),
('nails-tails-pet-grooming-morris','Nails & Tails Pet Grooming','NT','morris','Morris','815-942-3788',null,null,'Long-running Morris pet grooming business providing local grooming services.','306 E High St, Morris, IL 60450','60450','storefront','Current local business directory','https://www.yellowpages.com/morris-il/nail-salons','{"discovery":"public_business_directory"}'::jsonb,false),
('rbk-line-dog-boarding-training-morris','RBK Line Dog Boarding and Training LLC','RB','morris','Morris','815-600-7820','K9coaching@rbkline.org','https://www.rbkline.org/','Morris dog-care business providing canine training and development programs with boarding-oriented services from its Dellos Road location.','4345 Dellos Rd, Morris, IL 60450','60450','storefront','Official business website','https://www.rbkline.org/book-online','{"discovery":"official_web"}'::jsonb,false),
('mueller-lawson-frobish-morris','Mueller, Lawson & Frobish, P.C.','ML','morris','Morris','815-942-0635','staff@muellerlawson.com','https://www.muellerlawson.com/','Morris law firm serving individuals and businesses in personal injury, workers'' compensation, family law, real estate law and criminal defense matters.','124 W Washington St, Morris, IL 60450','60450','office','Official law firm website','https://www.muellerlawson.com/about-our-attorneys','{"discovery":"official_web"}'::jsonb,false),
('national-disability-experts-morris','National Disability Experts','ND','morris','Morris','779-243-5115','welcome@nationaldisabilityexperts.com','https://www.nationaldisabilityexperts.com/','Morris law office focused on Social Security Disability Insurance, Supplemental Security Income and federal disability appeals.','130 W Illinois Ave, Morris, IL 60450','60450','office','Official law firm website','https://www.nationaldisabilityexperts.com/','{"discovery":"official_web","decision_maker":"Robert E. Fisher","decision_maker_title":"Owner & Lead Attorney"}'::jsonb,false),
('stohrs-lawn-service-ottawa','Stohr''s Lawn Service, Inc.','SL','ottawa','Ottawa','815-433-5953','stohrslawnservice@gmail.com','https://stohrslawnservice.com/','Locally owned Ottawa lawn and landscape maintenance company providing recurring lawn care, seasonal cleanup, mulch installation, shrub trimming and landscape maintenance.',null,'61350',null,'Official business website','https://stohrslawnservice.com/','{"discovery":"official_web","service_area_business":true}'::jsonb,true),
('daisy-maes-doggy-detail-ottawa','Daisy Mae''s Doggy Detail LLC','DM','ottawa','Ottawa','815-587-5174',null,null,'Ottawa full-service dog grooming business that also advertises local pet pickup and drop-off service.','1416 Kansas St, Ottawa, IL 61350','61350','storefront','Current local pet-services directory','https://local.yahoo.com/consumer-services/pet-grooming/il/ottawa/','{"discovery":"public_business_directory"}'::jsonb,false),
('shampooch-pet-grooming-ottawa','Shampooch Pet Grooming','SP','ottawa','Ottawa','815-433-4353',null,null,'Long-running Ottawa pet grooming business serving local pet owners from its Court Street location.','626 Court St, Ottawa, IL 61350','61350','storefront','Current local pet-services directory','https://www.loc8nearme.com/illinois/ottawa/pet-facilities/','{"discovery":"public_business_directory"}'::jsonb,false),
('marsh-martin-vickers-deobler-temple-ottawa','Law Offices of Marsh, Martin, Vickers, Deobler & Temple','MM','ottawa','Ottawa','815-434-2000','info@wmamvdg.com','https://www.wmamvdg.com/','Ottawa law firm providing civil and commercial litigation, personal injury, real estate, trusts, estate planning and probate, workers'' compensation, Social Security disability and family-law services.','511 E Etna Rd, Ottawa, IL 61350','61350','office','Official law firm website','https://www.wmamvdg.com/the-firm/','{"discovery":"official_web"}'::jsonb,false),
('schweickert-ganassin-krzak-rundio-ottawa','Schweickert Ganassin Krzak Rundio, LLP','SG','ottawa','Ottawa','815-223-0177',null,'https://www.ganassin.com/','Illinois trial law firm with an Ottawa office focused on personal injury and workers'' compensation matters.','613 E Etna Rd, Ottawa, IL 61350','61350','office','Official law firm website','https://www.ganassin.com/contact/','{"discovery":"official_web"}'::jsonb,false),
('dirty-dawgs-lincoln','Dirty Dawgs','DD','lincoln','Lincoln','217-871-0587',null,'https://dirtydawgsil.com/','Locally owned Central Illinois pet-waste removal company providing recurring and one-time dog waste cleanup in Lincoln and nearby communities.',null,'62656',null,'Official business website','https://dirtydawgsil.com/','{"discovery":"official_web","service_area_business":true,"owner_name":"Dylan"}'::jsonb,true),
('fur-babies-grooming-lincoln','Fur Babies Grooming Salon','FB','lincoln','Lincoln','217-828-2034',null,null,'Independent Lincoln pet grooming salon providing full-service grooming by appointment.','620 S Adams St, Lincoln, IL 62656','62656','storefront','Current local business profile','https://www.petshops1.com/US/Lincoln/1494869390730589/Fur-Babies-Grooming-Salon','{"discovery":"public_business_profile"}'::jsonb,false),
('wild-woof-inn-lincoln','Wild Woof Inn','WW','lincoln','Lincoln','217-732-1529',null,null,'Lincoln pet boarding business providing local overnight pet-care services.','1255 Hickox Dr, Lincoln, IL 62656','62656','storefront','Current pet-services directory','https://vetlookup.org/services/pet-boarding-service','{"discovery":"public_business_directory"}'::jsonb,false),
('van-hook-law-lincoln','Van Hook Law','VH','lincoln','Lincoln','217-735-2187',null,null,'Lincoln law office providing estate planning, wills and trusts, probate and decedent-estate work, powers of attorney, real-estate matters and guardianship services.','1226 Broadway St, Lincoln, IL 62656','62656','office','Logan County community resource directory','https://www.logancountyresources.org/government/legal/lawyers','{"discovery":"local_government_resource"}'::jsonb,false),
('action-jackson-lawn-care-lincoln','Action Jackson Lawn Care','AJ','lincoln','Lincoln','217-737-9204',null,null,'Owner-operated Lincoln-area lawn-care service providing local lawn maintenance.',null,'62656',null,'Current local service directory','https://usturfdirect.com/locations/illinois/lincoln','{"discovery":"public_business_directory","service_area_business":true}'::jsonb,true);

insert into public.businesses
(tenant_id,slug,name,abbr,primary_location_id,phone,email,website,description,status,published_at,address_text,source_name,source_url,source_checked_at,rating,review_count,verified,featured,claimed,attributes)
select '6673621d-b359-4c17-a984-c8f50d914eb3'::uuid,s.slug,s.name,s.abbr,l.id,s.phone,s.email,s.website,s.description,'published',now(),s.address_text,s.source_name,s.source_url,now(),0,0,false,false,false,s.attributes
from _cilp_inventory_business_stage s
join public.locations l on l.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and l.slug=s.city_slug and l.is_active=true
on conflict (tenant_id,slug) do update set name=excluded.name,abbr=excluded.abbr,primary_location_id=excluded.primary_location_id,phone=excluded.phone,email=excluded.email,website=excluded.website,description=excluded.description,status='published',published_at=coalesce(public.businesses.published_at,now()),address_text=excluded.address_text,source_name=excluded.source_name,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at,attributes=coalesce(public.businesses.attributes,'{}'::jsonb)||excluded.attributes,updated_at=now();

insert into public.business_locations
(tenant_id,business_id,location_id,label,location_type,is_primary,is_active,verified,address_text,city,state,postal_code,phone,email,source_name,source_url,source_checked_at)
select '6673621d-b359-4c17-a984-c8f50d914eb3'::uuid,b.id,l.id,s.city||' location',s.location_type,true,true,false,s.address_text,s.city,'IL',s.postal_code,s.phone,s.email,s.source_name,s.source_url,now()
from _cilp_inventory_business_stage s
join public.businesses b on b.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and b.slug=s.slug
join public.locations l on l.tenant_id=b.tenant_id and l.slug=s.city_slug and l.is_active=true
where s.address_text is not null and not exists (select 1 from public.business_locations bl where bl.business_id=b.id and bl.city=s.city and bl.address_text=s.address_text);

insert into public.business_service_areas(business_id,location_id)
select b.id,l.id from _cilp_inventory_business_stage s
join public.businesses b on b.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and b.slug=s.slug
join public.locations l on l.tenant_id=b.tenant_id and l.slug=s.city_slug and l.is_active=true
where s.service_area_only=true on conflict do nothing;

create temp table _cilp_inventory_category_stage (business_slug text not null,category_slug text not null,is_primary boolean not null default false,primary key (business_slug,category_slug)) on commit drop;
insert into _cilp_inventory_category_stage(business_slug,category_slug,is_primary) values
('kc-lawn-care-streator','lawn-care',true),('kc-lawn-care-streator','landscaping',false),
('kmetzs-hawthorne-kennel-grooming-streator','pet-grooming',true),('kmetzs-hawthorne-kennel-grooming-streator','dog-grooming',false),('kmetzs-hawthorne-kennel-grooming-streator','cat-grooming',false),('kmetzs-hawthorne-kennel-grooming-streator','pet-boarding',false),('kmetzs-hawthorne-kennel-grooming-streator','dog-daycare',false),
('fairy-tails-grooming-streator','pet-grooming',true),('fairy-tails-grooming-streator','dog-grooming',false),('brassfield-krueger-streator','personal-injury',true),('danchris-nursery-streator','landscaping',true),('danchris-nursery-streator','farm-garden',false),
('ajs-services-decatur','lawn-care',true),('ajs-services-decatur','landscaping',false),('poochis-pet-grooming-decatur','pet-grooming',true),('hollies-pet-paradise-decatur','pet-grooming',true),('hollies-pet-paradise-decatur','dog-grooming',false),('hollies-pet-paradise-decatur','cat-grooming',false),('sawgrass-kennels-decatur','pet-boarding',true),
('mctague-services-morris','lawn-care',true),('that-perennial-place-morris','landscaping',true),('that-perennial-place-morris','lawn-care',false),('that-perennial-place-morris','farm-garden',false),('muddypaws-pet-spa-morris','pet-grooming',true),('nails-tails-pet-grooming-morris','pet-grooming',true),('rbk-line-dog-boarding-training-morris','pet-training',true),('rbk-line-dog-boarding-training-morris','pet-boarding',false),
('mueller-lawson-frobish-morris','personal-injury',true),('mueller-lawson-frobish-morris','workers-compensation',false),('mueller-lawson-frobish-morris','family-law',false),('mueller-lawson-frobish-morris','real-estate-law',false),('mueller-lawson-frobish-morris','criminal-defense',false),('national-disability-experts-morris','social-security-disability',true),
('stohrs-lawn-service-ottawa','lawn-care',true),('stohrs-lawn-service-ottawa','landscaping',false),('daisy-maes-doggy-detail-ottawa','pet-grooming',true),('daisy-maes-doggy-detail-ottawa','dog-grooming',false),('shampooch-pet-grooming-ottawa','pet-grooming',true),
('marsh-martin-vickers-deobler-temple-ottawa','civil-litigation',true),('marsh-martin-vickers-deobler-temple-ottawa','personal-injury',false),('marsh-martin-vickers-deobler-temple-ottawa','real-estate-law',false),('marsh-martin-vickers-deobler-temple-ottawa','estate-planning',false),('marsh-martin-vickers-deobler-temple-ottawa','probate',false),('marsh-martin-vickers-deobler-temple-ottawa','workers-compensation',false),('marsh-martin-vickers-deobler-temple-ottawa','social-security-disability',false),('marsh-martin-vickers-deobler-temple-ottawa','family-law',false),('marsh-martin-vickers-deobler-temple-ottawa','wills-trusts',false),('schweickert-ganassin-krzak-rundio-ottawa','personal-injury',true),('schweickert-ganassin-krzak-rundio-ottawa','workers-compensation',false),
('dirty-dawgs-lincoln','independent-pet-services',true),('dirty-dawgs-lincoln','pet-waste-removal',false),('fur-babies-grooming-lincoln','pet-grooming',true),('wild-woof-inn-lincoln','pet-boarding',true),('van-hook-law-lincoln','estate-planning',true),('van-hook-law-lincoln','probate',false),('van-hook-law-lincoln','wills-trusts',false),('van-hook-law-lincoln','real-estate-law',false),('action-jackson-lawn-care-lincoln','lawn-care',true);

insert into public.business_categories(business_id,category_id,is_primary)
select b.id,c.id,s.is_primary from _cilp_inventory_category_stage s
join public.businesses b on b.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and b.slug=s.business_slug
join public.categories c on c.tenant_id=b.tenant_id and c.slug=s.category_slug and c.is_active=true
on conflict (business_id,category_id) do nothing;

-- Bolen Robinson & Ellis already exists; enrich the canonical profile instead of creating a duplicate.
update public.businesses set website='https://brelaw.com',description='Full-service Decatur law firm with attorneys whose published practice areas include criminal defense, family law, personal injury, probate, civil litigation and workers'' compensation.',source_name='Decatur Bar Association / current firm profile',source_url='https://decaturbar.org/directory/',source_checked_at=now(),updated_at=now()
where tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and slug='bolen-robinson-ellis-decatur';
insert into public.business_categories(business_id,category_id,is_primary)
select b.id,c.id,false from public.businesses b join public.categories c on c.tenant_id=b.tenant_id and c.slug in ('criminal-defense','family-law','personal-injury','probate','civil-litigation','workers-compensation','dui') and c.is_active=true
where b.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid and b.slug='bolen-robinson-ellis-decatur'
on conflict (business_id,category_id) do nothing;
