insert into public.seo_pages(tenant_id,market_location_id,category_id,city,category,title,description,h1,intro,content,focus_topic,index_mode,reviewed,updated_at)
select l.tenant_id,l.id,c.id,l.name,c.name,
  case when c.name='Family Law' then 'Family Law Attorneys in Morris, IL | Central Illinois Local Pros' else 'Real Estate Attorneys in Morris, IL | Central Illinois Local Pros' end,
  case when c.name='Family Law' then 'Compare family law attorneys serving Morris, Illinois, with source-backed local directory details for divorce, parenting, support and related family matters.' else 'Compare real estate attorneys in Morris, Illinois, for residential and commercial transactions, closings and related property matters.' end,
  case when c.name='Family Law' then 'Family Law Attorneys in Morris, IL' else 'Real Estate Attorneys in Morris, IL' end,
  case when c.name='Family Law' then 'Central Illinois Local Pros helps people compare published family law providers connected to Morris, Illinois. Listings may include firms handling divorce, parenting time and responsibilities, child support, spousal support, property division and related family matters. Use the directory as a starting point for local discovery, then review each firm''s current practice information and contact details before choosing counsel.' else 'This Morris, Illinois directory page brings together published real estate law providers with legitimate local office or service relationships. Depending on the firm, services may include residential purchases and sales, commercial transactions, contract review, closings, title-related issues and other property matters. Review each listing''s available address, phone, website and source-backed details before contacting a provider.' end,
  case when c.name='Family Law' then 'Family law matters can be highly fact-specific, so comparing attorneys should involve more than proximity alone. Consider whether a firm currently handles the type of matter you have, the attorney''s experience, consultation process, communication expectations and fee structure. Directory information can support discovery, but legal services, attorney availability and practice focus can change; confirm time-sensitive details directly with the law office.\n\nCentral Illinois Local Pros separates organic relevance from paid visibility. Sponsored placement does not raise a firm''s organic rank, and claiming a listing does not by itself make the business verified. Verification, sponsorship and organic directory inclusion remain separate workflows.\n\nOnly legitimate provider relationships count toward local market coverage. A broad service area is not presented as a physical Morris office, and duplicate or artificial locations are not added simply to increase inventory. If a Morris-area family law provider is missing, it can be submitted for review with current source information.' else 'Real estate transactions often move on deadlines, so useful comparison criteria include the attorney''s current real estate practice, responsiveness, familiarity with local closing procedures, fee structure and whether the firm works with buyers, sellers or both. For commercial matters, the scope may differ from a standard residential closing, so confirm the firm''s current capabilities directly.\n\nThis directory keeps advertising separate from organic discovery. A Sponsored label identifies paid visibility only; it does not change the underlying organic relevance rules. Claiming a profile or purchasing a plan also does not automatically verify the business.\n\nMarket coverage is based on legitimate business relationships with Morris. Physical offices remain distinct from service areas, and service-area coverage is not converted into a fake branch. Listings and category pages are intended to grow through source-backed providers and reviewed editorial content rather than inflated counts.' end,
  case when c.name='Family Law' then 'family law attorneys in Morris Illinois' else 'real estate attorneys in Morris Illinois' end,
  'auto',true,now()
from public.locations l
join public.categories c on c.tenant_id=l.tenant_id
where l.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid
  and l.name='Morris' and l.is_active=true
  and c.name in ('Family Law','Real Estate Law') and c.is_active=true
  and not exists(select 1 from public.seo_pages sp where sp.tenant_id=l.tenant_id and sp.market_location_id=l.id and sp.category_id=c.id);
