create table if not exists public.listing_events(
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  event_type text not null check(event_type in ('profile_view','phone_click','website_click','directions_click')),
  source text not null default 'directory_public' check(source in ('directory_public')),
  created_at timestamptz not null default now()
);
alter table public.listing_events enable row level security;
drop policy if exists "public insert listing events safely" on public.listing_events;
create policy "public insert listing events safely" on public.listing_events for insert to anon,authenticated with check(
  source='directory_public' and exists(select 1 from public.businesses b where b.id=business_id and b.tenant_id=tenant_id and b.status='published')
);
drop policy if exists "staff read listing events" on public.listing_events;
create policy "staff read listing events" on public.listing_events for select to authenticated using(private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));
create index if not exists listing_events_business_created_idx on public.listing_events(business_id,created_at desc);
create index if not exists listing_events_tenant_type_created_idx on public.listing_events(tenant_id,event_type,created_at desc);

create or replace function private.rollup_listing_event()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.listing_daily_stats(business_id,stat_date,impressions,profile_views,phone_clicks,website_clicks,directions_clicks,lead_submissions)
  values(new.business_id,current_date,0,case when new.event_type='profile_view' then 1 else 0 end,case when new.event_type='phone_click' then 1 else 0 end,case when new.event_type='website_click' then 1 else 0 end,case when new.event_type='directions_click' then 1 else 0 end,0)
  on conflict(business_id,stat_date) do update set
    profile_views=public.listing_daily_stats.profile_views+excluded.profile_views,
    phone_clicks=public.listing_daily_stats.phone_clicks+excluded.phone_clicks,
    website_clicks=public.listing_daily_stats.website_clicks+excluded.website_clicks,
    directions_clicks=public.listing_daily_stats.directions_clicks+excluded.directions_clicks;
  return new;
end $$;
revoke all on function private.rollup_listing_event() from public,anon,authenticated;
drop trigger if exists trg_rollup_listing_event on public.listing_events;
create trigger trg_rollup_listing_event after insert on public.listing_events for each row execute function private.rollup_listing_event();

create or replace function private.rollup_direct_lead_submission()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.business_id is not null then
    insert into public.listing_daily_stats(business_id,stat_date,impressions,profile_views,phone_clicks,website_clicks,directions_clicks,lead_submissions)
    values(new.business_id,current_date,0,0,0,0,0,1)
    on conflict(business_id,stat_date) do update set lead_submissions=public.listing_daily_stats.lead_submissions+1;
  end if;
  return new;
end $$;
revoke all on function private.rollup_direct_lead_submission() from public,anon,authenticated;
drop trigger if exists trg_rollup_direct_lead_submission on public.leads;
create trigger trg_rollup_direct_lead_submission after insert on public.leads for each row execute function private.rollup_direct_lead_submission();

alter table public.search_events add constraint search_events_result_count_check check(result_count between 0 and 1000) not valid;
alter table public.search_events validate constraint search_events_result_count_check;
drop policy if exists "public insert search events" on public.search_events;
create policy "public insert search events safely" on public.search_events for insert to anon,authenticated with check(
  source='directory_search' and result_count between 0 and 1000 and char_length(coalesce(service,''))<=200 and char_length(coalesce(location,''))<=200 and exists(select 1 from public.tenants t where t.id=tenant_id)
);
