update public.plans set entitlements=coalesce(entitlements,'{}'::jsonb)||'{"lead_inbox":false}'::jsonb,updated_at=now() where slug in('free','verified','featured');
update public.plans set entitlements=coalesce(entitlements,'{}'::jsonb)||'{"lead_inbox":true}'::jsonb,updated_at=now() where slug='pro';
update public.plans set features='["Everything in Verified","Up to 5 showcase photos","Restaurant menu upload","Business analytics","Clearly labeled featured visibility","Homepage Featured Business placement eligibility","Lead Inbox available as an optional add-on"]'::jsonb,updated_at=now() where slug='featured';
update public.plans set features='["Everything in Featured","Up to 10 showcase photos","Restaurant menu upload","Lead Inbox included","Advanced analytics","Expanded locations","Priority business tools"]'::jsonb,updated_at=now() where slug='pro';

create table if not exists public.business_lead_programs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,business_id uuid not null references public.businesses(id) on delete cascade,featured_addon_enabled boolean not null default false,status text not null default 'active' check(status in('active','paused','ended')),billing_model text not null default 'pay_per_lead' check(billing_model in('pay_per_lead','lead_bundle')),per_lead_price_cents integer check(per_lead_price_cents is null or per_lead_price_cents>0),bundle_lead_count integer check(bundle_lead_count is null or bundle_lead_count>0),bundle_price_cents integer check(bundle_price_cents is null or bundle_price_cents>0),due_days integer not null default 7 check(due_days between 0 and 90),billing_email text,notes text,terms_version text not null default 'lead-delivery-v1',created_by uuid default auth.uid(),updated_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id));
create index if not exists business_lead_programs_tenant_status_idx on public.business_lead_programs(tenant_id,status,updated_at desc);
create table if not exists public.lead_invoices(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,business_id uuid not null references public.businesses(id) on delete cascade,invoice_number text not null unique,billing_model text not null check(billing_model in('pay_per_lead','lead_bundle')),lead_count integer not null check(lead_count>0),bundle_count integer not null default 0 check(bundle_count>=0),amount_due_cents integer not null check(amount_due_cents>0),status text not null default 'draft' check(status in('draft','sent','paid','void','overdue')),due_at timestamptz,stripe_invoice_id text,hosted_invoice_url text,invoice_pdf_url text,sent_at timestamptz,paid_at timestamptz,notes text,created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists lead_invoices_business_idx on public.lead_invoices(tenant_id,business_id,status,created_at desc);
create table if not exists public.lead_delivery_charges(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,business_id uuid not null references public.businesses(id) on delete cascade,lead_id uuid not null references public.leads(id) on delete cascade,recipient_id uuid not null references public.lead_recipients(id) on delete cascade,billing_model text not null check(billing_model in('pay_per_lead','lead_bundle')),per_lead_price_cents integer,bundle_lead_count integer,bundle_price_cents integer,billing_status text not null default 'unbilled' check(billing_status in('unbilled','invoiced','paid','void')),invoice_id uuid references public.lead_invoices(id) on delete set null,delivered_at timestamptz not null default now(),created_by uuid default auth.uid(),created_at timestamptz not null default now(),unique(recipient_id));
create index if not exists lead_delivery_charges_unbilled_idx on public.lead_delivery_charges(tenant_id,business_id,billing_status,delivered_at);
create sequence if not exists public.lead_invoice_number_seq;

create or replace function private.business_active_plan_slug(p_business_id uuid) returns text language sql stable security definer set search_path='' as $$select coalesce((select p.slug from public.subscriptions s join public.plans p on p.id=s.plan_id where s.business_id=p_business_id and s.status in('active','trialing','past_due') and p.is_active=true and(s.ends_at is null or s.ends_at>now()) order by s.updated_at desc,p.sort_order desc nulls last limit 1),'free')$$;
revoke all on function private.business_active_plan_slug(uuid) from public;grant execute on function private.business_active_plan_slug(uuid) to authenticated;
create or replace function private.business_has_lead_inbox_access(p_business_id uuid) returns boolean language sql stable security definer set search_path='' as $$select case private.business_active_plan_slug(p_business_id) when 'pro' then true when 'featured' then coalesce((select blp.featured_addon_enabled and blp.status='active' from public.business_lead_programs blp where blp.business_id=p_business_id),false) else false end$$;
revoke all on function private.business_has_lead_inbox_access(uuid) from public;grant execute on function private.business_has_lead_inbox_access(uuid) to authenticated;

create or replace function public.get_business_lead_access(p_business_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_plan text;v_program public.business_lead_programs%rowtype;v_owner boolean;v_staff boolean;begin if auth.uid() is null then raise exception 'authentication_required';end if;select exists(select 1 from public.business_owners bo where bo.business_id=p_business_id and bo.user_id=auth.uid()) into v_owner;select exists(select 1 from public.businesses b where b.id=p_business_id and private.has_tenant_role(b.tenant_id,array['staff','admin','super_admin'])) into v_staff;if not v_owner and not v_staff then raise exception 'insufficient_privilege';end if;v_plan:=private.business_active_plan_slug(p_business_id);select * into v_program from public.business_lead_programs where business_id=p_business_id;return jsonb_build_object('plan_slug',v_plan,'lead_inbox',private.business_has_lead_inbox_access(p_business_id),'access_source',case when v_plan='pro' then 'pro_included' when v_plan='featured' and coalesce(v_program.featured_addon_enabled,false) and v_program.status='active' then 'featured_addon' else 'none' end,'billing_configured',case when v_program.business_id is null or v_program.status<>'active' then false when v_program.billing_model='pay_per_lead' then coalesce(v_program.per_lead_price_cents,0)>0 else coalesce(v_program.bundle_lead_count,0)>0 and coalesce(v_program.bundle_price_cents,0)>0 end,'billing_model',v_program.billing_model,'per_lead_price_cents',v_program.per_lead_price_cents,'bundle_lead_count',v_program.bundle_lead_count,'bundle_price_cents',v_program.bundle_price_cents,'due_days',coalesce(v_program.due_days,7),'billing_email',v_program.billing_email,'program_status',coalesce(v_program.status,'not_configured'));end$$;
revoke all on function public.get_business_lead_access(uuid) from public;grant execute on function public.get_business_lead_access(uuid) to authenticated;

create or replace function public.configure_business_lead_program(p_business_id uuid,p_featured_addon_enabled boolean,p_billing_model text,p_per_lead_price_cents integer default null,p_bundle_lead_count integer default null,p_bundle_price_cents integer default null,p_due_days integer default 7,p_billing_email text default null,p_notes text default null,p_status text default 'active') returns uuid language plpgsql security definer set search_path='' as $$declare v_tenant uuid;v_id uuid;begin select tenant_id into v_tenant from public.businesses where id=p_business_id;if v_tenant is null then raise exception 'business_not_found';end if;if auth.uid() is null or not private.has_tenant_role(v_tenant,array['super_admin']) then raise exception 'insufficient_privilege';end if;if p_billing_model not in('pay_per_lead','lead_bundle') then raise exception 'invalid_billing_model';end if;if p_status not in('active','paused','ended') then raise exception 'invalid_status';end if;if p_billing_model='pay_per_lead' and coalesce(p_per_lead_price_cents,0)<=0 then raise exception 'positive_per_lead_price_required';end if;if p_billing_model='lead_bundle' and(coalesce(p_bundle_lead_count,0)<=0 or coalesce(p_bundle_price_cents,0)<=0) then raise exception 'valid_bundle_required';end if;insert into public.business_lead_programs(tenant_id,business_id,featured_addon_enabled,status,billing_model,per_lead_price_cents,bundle_lead_count,bundle_price_cents,due_days,billing_email,notes,created_by,updated_by) values(v_tenant,p_business_id,coalesce(p_featured_addon_enabled,false),p_status,p_billing_model,case when p_billing_model='pay_per_lead' then p_per_lead_price_cents else null end,case when p_billing_model='lead_bundle' then p_bundle_lead_count else null end,case when p_billing_model='lead_bundle' then p_bundle_price_cents else null end,greatest(0,least(coalesce(p_due_days,7),90)),nullif(trim(coalesce(p_billing_email,'')),''),nullif(trim(coalesce(p_notes,'')),''),auth.uid(),auth.uid()) on conflict(business_id) do update set featured_addon_enabled=excluded.featured_addon_enabled,status=excluded.status,billing_model=excluded.billing_model,per_lead_price_cents=excluded.per_lead_price_cents,bundle_lead_count=excluded.bundle_lead_count,bundle_price_cents=excluded.bundle_price_cents,due_days=excluded.due_days,billing_email=excluded.billing_email,notes=excluded.notes,updated_by=auth.uid(),updated_at=now() returning id into v_id;insert into public.audit_logs(tenant_id,actor_user_id,action_type,action_text) values(v_tenant,auth.uid(),'lead_program_configured','Configured lead billing for business '||p_business_id||' using '||p_billing_model||'.');return v_id;end$$;
revoke all on function public.configure_business_lead_program(uuid,boolean,text,integer,integer,integer,integer,text,text,text) from public;grant execute on function public.configure_business_lead_program(uuid,boolean,text,integer,integer,integer,integer,text,text,text) to authenticated;

create or replace function public.deliver_billable_lead(p_lead_id uuid,p_business_id uuid,p_route_reason text default 'Paid lead delivery',p_route_rank integer default 0) returns uuid language plpgsql security definer set search_path='' as $$declare v_tenant uuid;v_program public.business_lead_programs%rowtype;v_recipient uuid;begin select tenant_id into v_tenant from public.leads where id=p_lead_id;if v_tenant is null then raise exception 'lead_not_found';end if;if auth.uid() is null or not private.has_tenant_role(v_tenant,array['super_admin']) then raise exception 'insufficient_privilege';end if;if not private.business_has_lead_inbox_access(p_business_id) then raise exception 'lead_inbox_not_enabled_for_business';end if;select * into v_program from public.business_lead_programs where business_id=p_business_id and status='active';if v_program.business_id is null then raise exception 'billing_program_not_configured';end if;if v_program.billing_model='pay_per_lead' and coalesce(v_program.per_lead_price_cents,0)<=0 then raise exception 'billing_program_not_configured';end if;if v_program.billing_model='lead_bundle' and(coalesce(v_program.bundle_lead_count,0)<=0 or coalesce(v_program.bundle_price_cents,0)<=0) then raise exception 'billing_program_not_configured';end if;v_recipient:=public.route_directory_lead(p_lead_id,p_business_id,p_route_reason,p_route_rank);insert into public.lead_delivery_charges(tenant_id,business_id,lead_id,recipient_id,billing_model,per_lead_price_cents,bundle_lead_count,bundle_price_cents,billing_status,delivered_at,created_by) values(v_tenant,p_business_id,p_lead_id,v_recipient,v_program.billing_model,v_program.per_lead_price_cents,v_program.bundle_lead_count,v_program.bundle_price_cents,'unbilled',now(),auth.uid()) on conflict(recipient_id) do nothing;insert into public.audit_logs(tenant_id,actor_user_id,action_type,action_text) values(v_tenant,auth.uid(),'billable_lead_delivered','Delivered billable lead '||p_lead_id||' to business '||p_business_id||'. Billing is based on delivery, not close outcome.');return v_recipient;end$$;
revoke all on function public.deliver_billable_lead(uuid,uuid,text,integer) from public;grant execute on function public.deliver_billable_lead(uuid,uuid,text,integer) to authenticated;

create or replace function public.create_lead_invoice(p_business_id uuid,p_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$declare v_tenant uuid;v_program public.business_lead_programs%rowtype;v_invoice uuid;v_count int;v_amount int;v_bundle_count int:=0;v_limit int;v_number text;begin select tenant_id into v_tenant from public.businesses where id=p_business_id;if v_tenant is null then raise exception 'business_not_found';end if;if auth.uid() is null or not private.has_tenant_role(v_tenant,array['super_admin']) then raise exception 'insufficient_privilege';end if;select * into v_program from public.business_lead_programs where business_id=p_business_id and status='active';if v_program.business_id is null then raise exception 'billing_program_not_configured';end if;if v_program.billing_model='pay_per_lead' then select count(*),coalesce(sum(per_lead_price_cents),0) into v_count,v_amount from public.lead_delivery_charges where business_id=p_business_id and billing_status='unbilled' and billing_model='pay_per_lead';if v_count=0 or v_amount<=0 then raise exception 'no_unbilled_leads';end if;v_limit:=v_count;else select count(*) into v_count from public.lead_delivery_charges where business_id=p_business_id and billing_status='unbilled' and billing_model='lead_bundle' and bundle_lead_count=v_program.bundle_lead_count and bundle_price_cents=v_program.bundle_price_cents;v_bundle_count:=floor(v_count::numeric/v_program.bundle_lead_count)::int;if v_bundle_count<=0 then raise exception 'bundle_not_yet_fulfilled';end if;v_limit:=v_bundle_count*v_program.bundle_lead_count;v_count:=v_limit;v_amount:=v_bundle_count*v_program.bundle_price_cents;end if;v_number:='LP-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.lead_invoice_number_seq')::text,6,'0');insert into public.lead_invoices(tenant_id,business_id,invoice_number,billing_model,lead_count,bundle_count,amount_due_cents,status,due_at,notes,created_by) values(v_tenant,p_business_id,v_number,v_program.billing_model,v_count,v_bundle_count,v_amount,'draft',now()+make_interval(days=>v_program.due_days),nullif(trim(coalesce(p_notes,'')),''),auth.uid()) returning id into v_invoice;with picked as(select id from public.lead_delivery_charges where business_id=p_business_id and billing_status='unbilled' and billing_model=v_program.billing_model and(v_program.billing_model='pay_per_lead' or(bundle_lead_count=v_program.bundle_lead_count and bundle_price_cents=v_program.bundle_price_cents)) order by delivered_at,id limit v_limit) update public.lead_delivery_charges c set billing_status='invoiced',invoice_id=v_invoice from picked where c.id=picked.id;insert into public.audit_logs(tenant_id,actor_user_id,action_type,action_text) values(v_tenant,auth.uid(),'lead_invoice_created','Created lead invoice '||v_number||' for '||v_count||' delivered lead(s), $'||round(v_amount::numeric/100,2)||'.');return v_invoice;end$$;
revoke all on function public.create_lead_invoice(uuid,text) from public;grant execute on function public.create_lead_invoice(uuid,text) to authenticated;

create or replace function public.set_lead_invoice_status(p_invoice_id uuid,p_status text,p_stripe_invoice_id text default null,p_hosted_url text default null,p_pdf_url text default null) returns void language plpgsql security definer set search_path='' as $$declare v public.lead_invoices%rowtype;begin select * into v from public.lead_invoices where id=p_invoice_id;if v.id is null then raise exception 'invoice_not_found';end if;if auth.uid() is null or not private.has_tenant_role(v.tenant_id,array['super_admin']) then raise exception 'insufficient_privilege';end if;if p_status not in('draft','sent','paid','void','overdue') then raise exception 'invalid_status';end if;update public.lead_invoices set status=p_status,stripe_invoice_id=coalesce(p_stripe_invoice_id,stripe_invoice_id),hosted_invoice_url=coalesce(p_hosted_url,hosted_invoice_url),invoice_pdf_url=coalesce(p_pdf_url,invoice_pdf_url),sent_at=case when p_status='sent' then coalesce(sent_at,now()) else sent_at end,paid_at=case when p_status='paid' then coalesce(paid_at,now()) else paid_at end,updated_at=now() where id=p_invoice_id;if p_status='paid' then update public.lead_delivery_charges set billing_status='paid' where invoice_id=p_invoice_id;elsif p_status='void' then update public.lead_delivery_charges set billing_status='unbilled',invoice_id=null where invoice_id=p_invoice_id and billing_status='invoiced';end if;end$$;
revoke all on function public.set_lead_invoice_status(uuid,text,text,text,text) from public;grant execute on function public.set_lead_invoice_status(uuid,text,text,text,text) to authenticated;

alter table public.business_lead_programs enable row level security;alter table public.lead_delivery_charges enable row level security;alter table public.lead_invoices enable row level security;
create policy business_lead_program_owner_read on public.business_lead_programs for select to authenticated using(exists(select 1 from public.business_owners bo where bo.business_id=business_lead_programs.business_id and bo.user_id=(select auth.uid())) or private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));
create policy business_lead_program_super_admin_write on public.business_lead_programs for all to authenticated using(private.has_tenant_role(tenant_id,array['super_admin'])) with check(private.has_tenant_role(tenant_id,array['super_admin']));
create policy lead_delivery_charges_owner_read on public.lead_delivery_charges for select to authenticated using((private.business_has_lead_inbox_access(business_id) and exists(select 1 from public.business_owners bo where bo.business_id=lead_delivery_charges.business_id and bo.user_id=(select auth.uid()))) or private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));
create policy lead_delivery_charges_super_admin_write on public.lead_delivery_charges for all to authenticated using(private.has_tenant_role(tenant_id,array['super_admin'])) with check(private.has_tenant_role(tenant_id,array['super_admin']));
create policy lead_invoices_owner_read on public.lead_invoices for select to authenticated using((private.business_has_lead_inbox_access(business_id) and exists(select 1 from public.business_owners bo where bo.business_id=lead_invoices.business_id and bo.user_id=(select auth.uid()))) or private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));
create policy lead_invoices_super_admin_write on public.lead_invoices for all to authenticated using(private.has_tenant_role(tenant_id,array['super_admin'])) with check(private.has_tenant_role(tenant_id,array['super_admin']));
drop policy if exists "owner read routed lead recipients" on public.lead_recipients;create policy "owner read routed lead recipients" on public.lead_recipients for select to authenticated using(private.business_has_lead_inbox_access(business_id) and exists(select 1 from public.business_owners bo where bo.business_id=lead_recipients.business_id and bo.user_id=(select auth.uid())));
drop policy if exists "owner update own routed lead status" on public.lead_recipients;create policy "owner update own routed lead status" on public.lead_recipients for update to authenticated using(private.business_has_lead_inbox_access(business_id) and exists(select 1 from public.business_owners bo where bo.business_id=lead_recipients.business_id and bo.user_id=(select auth.uid()))) with check(private.business_has_lead_inbox_access(business_id) and exists(select 1 from public.business_owners bo where bo.business_id=lead_recipients.business_id and bo.user_id=(select auth.uid())));
drop policy if exists "owner read specifically routed leads" on public.leads;create policy "owner read specifically routed leads" on public.leads for select to authenticated using(exists(select 1 from public.lead_recipients lr join public.business_owners bo on bo.business_id=lr.business_id where lr.lead_id=leads.id and bo.user_id=(select auth.uid()) and private.business_has_lead_inbox_access(lr.business_id)));
create or replace function public.update_owner_lead_recipient(p_recipient_id uuid,p_status text,p_owner_notes text default null) returns void language plpgsql set search_path='' as $$declare v_business uuid;begin if auth.uid() is null then raise exception 'authentication_required';end if;if p_status not in('viewed','contacted','appointment_set','quoted','won','lost','declined','spam') then raise exception 'invalid_lead_status';end if;select business_id into v_business from public.lead_recipients where id=p_recipient_id;if v_business is null or not private.business_has_lead_inbox_access(v_business) or not exists(select 1 from public.business_owners bo where bo.business_id=v_business and bo.user_id=auth.uid()) then raise exception 'insufficient_privilege';end if;update public.lead_recipients set status=p_status,owner_notes=nullif(trim(coalesce(p_owner_notes,'')),''),viewed_at=case when p_status in('viewed','contacted','appointment_set','quoted','won','lost','declined','spam') then coalesce(viewed_at,now()) else viewed_at end,contacted_at=case when p_status in('contacted','appointment_set','quoted','won','lost') then coalesce(contacted_at,now()) else contacted_at end,updated_at=now() where id=p_recipient_id;end$$;
