create policy "staff manage business categories" on public.business_categories for all to authenticated using (exists(select 1 from public.businesses b where b.id=business_categories.business_id and private.has_tenant_role(b.tenant_id,array['staff','admin','super_admin']::text[]))) with check (exists(select 1 from public.businesses b where b.id=business_categories.business_id and private.has_tenant_role(b.tenant_id,array['staff','admin','super_admin']::text[])));

create or replace function public.review_business_submission(p_submission_id uuid,p_decision text,p_notes text default null) returns jsonb language plpgsql security invoker set search_path='' as $$
declare v_sub public.business_submissions%rowtype;v_actor uuid:=auth.uid();v_decision text:=lower(trim(coalesce(p_decision,'')));v_category_id uuid;v_location_id uuid;v_business_id uuid;v_slug text;v_base_slug text;
begin
 if v_actor is null then raise exception 'authentication_required';end if;select * into v_sub from public.business_submissions where id=p_submission_id for update;if not found then raise exception 'submission_not_found';end if;if v_sub.tenant_id is null then raise exception 'submission_tenant_required';end if;if not private.has_tenant_role(v_sub.tenant_id,array['staff','admin','super_admin']::text[]) then raise exception 'insufficient_privilege';end if;if v_decision not in('approve','reject') then raise exception 'invalid_decision';end if;
 if v_decision='reject' then update public.business_submissions set status='rejected',reviewed_by=v_actor,reviewed_at=now(),review_notes=nullif(trim(coalesce(p_notes,'')),'') where id=p_submission_id;insert into public.audit_logs(tenant_id,actor_user_id,action_type,action_text) values(v_sub.tenant_id,v_actor,'business_submission_rejected','Rejected business submission '||p_submission_id::text||' for '||v_sub.business_name);return jsonb_build_object('ok',true,'submission_id',p_submission_id,'decision','reject');end if;
 select c.id into v_category_id from public.categories c where c.tenant_id=v_sub.tenant_id and c.is_active=true and (lower(c.name)=lower(trim(v_sub.category)) or lower(c.slug)=lower(regexp_replace(trim(v_sub.category),'[^a-zA-Z0-9]+','-','g'))) order by case when lower(c.name)=lower(trim(v_sub.category)) then 0 else 1 end limit 1;if v_category_id is null then raise exception 'category_not_found';end if;
 select l.id into v_location_id from public.locations l where l.tenant_id=v_sub.tenant_id and l.is_active=true and l.type='city' and lower(l.name)=lower(trim(v_sub.city)) order by l.name limit 1;if v_location_id is null then raise exception 'location_not_found';end if;
 if exists(select 1 from public.businesses b where b.tenant_id=v_sub.tenant_id and (lower(trim(b.name))=lower(trim(v_sub.business_name)) or (nullif(trim(v_sub.phone),'') is not null and trim(b.phone)=trim(v_sub.phone)) or (nullif(trim(v_sub.website),'') is not null and lower(trim(coalesce(b.website,'')))=lower(trim(v_sub.website))))) then raise exception 'possible_duplicate_business';end if;
 v_base_slug:=trim(both '-' from lower(regexp_replace(v_sub.business_name||'-'||v_sub.city||'-il','[^a-zA-Z0-9]+','-','g')));v_slug:=v_base_slug;if exists(select 1 from public.businesses b where b.tenant_id=v_sub.tenant_id and b.slug=v_slug) then v_slug:=v_base_slug||'-'||substr(p_submission_id::text,1,8);end if;
 insert into public.businesses(tenant_id,slug,name,primary_location_id,phone,website,description,status,published_at,claimed,verified,featured,rating,review_count,source_name,source_checked_at,attributes) values(v_sub.tenant_id,v_slug,trim(v_sub.business_name),v_location_id,nullif(trim(v_sub.phone),''),nullif(trim(v_sub.website),''),nullif(trim(v_sub.description),''),'published',now(),false,false,false,0,0,'Business Submission',now(),jsonb_build_object('submission_id',p_submission_id,'submission_source',v_sub.source)) returning id into v_business_id;
 insert into public.business_categories(business_id,category_id,is_primary) values(v_business_id,v_category_id,true);update public.business_submissions set status='approved',reviewed_by=v_actor,reviewed_at=now(),review_notes=nullif(trim(coalesce(p_notes,'')),'') where id=p_submission_id;insert into public.audit_logs(tenant_id,actor_user_id,action_type,action_text) values(v_sub.tenant_id,v_actor,'business_submission_approved','Approved business submission '||p_submission_id::text||' and created business '||v_business_id::text);return jsonb_build_object('ok',true,'submission_id',p_submission_id,'decision','approve','business_id',v_business_id,'slug',v_slug);end;$$;
revoke all on function public.review_business_submission(uuid,text,text) from public;grant execute on function public.review_business_submission(uuid,text,text) to authenticated;
