insert into public.seo_pages(tenant_id,market_location_id,category_id,city,category,title,description,h1,intro,content,focus_topic,index_mode,reviewed,updated_at)
select l.tenant_id,l.id,c.id,l.name,c.name,
  case when l.name='Chatham' then 'American Restaurants in Chatham, IL | Central Illinois Local Pros' else 'American Restaurants in Washington, IL | Central Illinois Local Pros' end,
  case when l.name='Chatham' then 'Compare American restaurants in Chatham, Illinois, including local cafes, pubs and casual dining options with current directory details.' else 'Compare American restaurants in Washington, Illinois, including local family dining, barbecue and casual American food options.' end,
  'American Restaurants in '||l.name||', IL',
  case when l.name='Chatham' then 'Looking for American food in Chatham, Illinois? This local directory page brings together published restaurants with a verified Chatham location relationship so you can compare nearby options without treating paid placement as organic relevance. Current listings can include neighborhood cafes, pubs and casual restaurants serving burgers, sandwiches, comfort food and other familiar American favorites. Use each business profile to review the available phone, website, address and other published details before deciding where to eat.' else 'Looking for American restaurants in Washington, Illinois? This page is built from published local restaurant inventory tied to Washington, so diners can compare real nearby options in one place. The mix can include family restaurants, barbecue, burgers, casual dining and other American-style menus. Organic directory visibility is based on relevance and current inventory rather than sponsorship status. Open individual profiles to review the latest directory details, including location, contact information and available website links.' end,
  case when l.name='Chatham' then 'Chatham offers several styles of casual American dining, from breakfast and cafe-style meals to pub food and dinner favorites. When comparing restaurants, consider the type of meal you want, whether you need family-friendly seating, takeout availability, hours and how far the location is from your part of Chatham. Directory information is designed to help with discovery, but restaurant menus and hours can change, so confirm time-sensitive details directly with the business before visiting.\n\nCentral Illinois Local Pros keeps paid visibility separate from organic directory relevance. A Sponsored label indicates advertising placement and does not mean a restaurant is ranked higher organically. Businesses shown as verified have completed the directory''s verification workflow; verification is also separate from paid status.\n\nIf you operate a Chatham restaurant that belongs in this category and is not yet listed, you can submit the business for review. New listings are expected to represent a real business and a legitimate Chatham location relationship. The directory does not create duplicate records or treat a broad service area as a physical storefront simply to increase provider counts.' else 'Washington has a broad range of American-style dining choices, including barbecue, burgers, family dining, pub-style menus and other casual restaurants. A useful comparison goes beyond the restaurant name: check the published address, hours or contact information when available, then use the restaurant''s own website or direct contact channel for the most time-sensitive menu and operating details.\n\nThis directory keeps organic discovery and advertising separate. Sponsored placements are clearly labeled and do not change the underlying organic relevance rules. Claiming a listing or buying a plan also does not automatically verify a business or improve organic rank. Those workflows are handled independently.\n\nRestaurant inventory is reviewed around real business and location relationships. If a Washington restaurant is missing, business owners or community members can submit it for review. The goal is useful local coverage built from legitimate providers, not inflated counts. As the local dining market changes, source-backed updates help keep addresses, contact details and business status current.' end,
  'American restaurants in '||l.name||' Illinois','auto',true,now()
from public.locations l
join public.categories c on c.tenant_id=l.tenant_id
where l.tenant_id='6673621d-b359-4c17-a984-c8f50d914eb3'::uuid
  and l.name in ('Chatham','Washington') and l.is_active=true
  and c.name='American Restaurants' and c.is_active=true
  and not exists(select 1 from public.seo_pages sp where sp.tenant_id=l.tenant_id and sp.market_location_id=l.id and sp.category_id=c.id);
