-- Sales Command Center 3.4: human-gated outreach + follow-up workbench

create table if not exists public.skylight_sales_outreach_templates (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  service_slug text,
  vertical text,
  channel text not null default 'email' check (channel in ('email','phone','sms','linkedin','social')),
  sequence_stage text not null default 'first_touch' check (sequence_stage in ('first_touch','follow_up_1','follow_up_2','last_check_in','nurture','call','custom')),
  day_offset integer not null default 0 check (day_offset between 0 and 3650),
  subject_template text,
  body_template text not null,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, name)
);

create index if not exists idx_skylight_sales_outreach_templates_match
  on public.skylight_sales_outreach_templates(tenant_id, channel, sequence_stage, service_slug, vertical, active, sort_order);

create table if not exists public.skylight_sales_outreach_drafts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  opportunity_id uuid not null references public.skylight_sales_opportunities(id) on delete cascade,
  prospect_id uuid not null references public.business_prospects(id) on delete cascade,
  campaign_id uuid references public.skylight_sales_campaigns(id) on delete set null,
  campaign_member_id uuid references public.skylight_sales_campaign_members(id) on delete set null,
  template_id uuid references public.skylight_sales_outreach_templates(id) on delete set null,
  channel text not null check (channel in ('email','phone','sms','linkedin','social')),
  sequence_stage text not null default 'first_touch',
  recipient_name text,
  recipient_title text,
  recipient_email text,
  recipient_phone text,
  subject text,
  body text not null,
  evidence_snapshot jsonb not null default '{}'::jsonb,
  source_url text,
  contact_checked_at timestamptz,
  status text not null default 'draft' check (status in ('draft','approved','sent','blocked','void')),
  blocked_reason text,
  approved_by uuid,
  approved_at timestamptz,
  sent_by uuid,
  sent_at timestamptz,
  provider text,
  provider_message_id text,
  unsubscribe_token uuid not null default gen_random_uuid(),
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unsubscribe_token)
);

create index if not exists idx_skylight_sales_outreach_drafts_workbench
  on public.skylight_sales_outreach_drafts(tenant_id, status, channel, created_at desc);
create index if not exists idx_skylight_sales_outreach_drafts_opportunity
  on public.skylight_sales_outreach_drafts(opportunity_id, created_at desc);
create index if not exists idx_skylight_sales_outreach_drafts_prospect
  on public.skylight_sales_outreach_drafts(prospect_id, created_at desc);
create index if not exists idx_skylight_sales_outreach_drafts_campaign
  on public.skylight_sales_outreach_drafts(campaign_id, campaign_member_id, created_at desc);

create table if not exists public.skylight_sales_outreach_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  opportunity_id uuid references public.skylight_sales_opportunities(id) on delete cascade,
  prospect_id uuid not null references public.business_prospects(id) on delete cascade,
  draft_id uuid references public.skylight_sales_outreach_drafts(id) on delete set null,
  campaign_id uuid references public.skylight_sales_campaigns(id) on delete set null,
  campaign_member_id uuid references public.skylight_sales_campaign_members(id) on delete set null,
  actor_user_id uuid,
  channel text check (channel is null or channel in ('email','phone','sms','linkedin','social')),
  event_type text not null check (event_type in (
    'draft_created','draft_approved','draft_blocked','sent','call_attempted','voicemail','connected',
    'reply_positive','reply_neutral','reply_negative','interested','not_interested','do_not_contact',
    'wrong_person','bounced','follow_up_created','follow_up_completed','appointment_booked','note'
  )),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_skylight_sales_outreach_events_prospect
  on public.skylight_sales_outreach_events(tenant_id, prospect_id, created_at desc);
create index if not exists idx_skylight_sales_outreach_events_opportunity
  on public.skylight_sales_outreach_events(opportunity_id, created_at desc);

create table if not exists public.skylight_sales_suppressions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  prospect_id uuid not null references public.business_prospects(id) on delete cascade,
  opportunity_id uuid references public.skylight_sales_opportunities(id) on delete set null,
  channel text not null check (channel in ('email','phone','sms','linkedin','social','all')),
  contact_value text,
  reason text not null,
  source text not null default 'manual' check (source in ('manual','opt_out','bounce','wrong_person','complaint','other')),
  active boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  lifted_by uuid,
  lifted_at timestamptz,
  lift_note text
);

create unique index if not exists uq_skylight_sales_suppressions_active
  on public.skylight_sales_suppressions(tenant_id, prospect_id, channel, coalesce(lower(contact_value),''))
  where active;
create index if not exists idx_skylight_sales_suppressions_lookup
  on public.skylight_sales_suppressions(tenant_id, prospect_id, active, channel);

create table if not exists public.skylight_sales_followups (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  opportunity_id uuid not null references public.skylight_sales_opportunities(id) on delete cascade,
  prospect_id uuid not null references public.business_prospects(id) on delete cascade,
  campaign_id uuid references public.skylight_sales_campaigns(id) on delete set null,
  campaign_member_id uuid references public.skylight_sales_campaign_members(id) on delete set null,
  prior_draft_id uuid references public.skylight_sales_outreach_drafts(id) on delete set null,
  template_id uuid references public.skylight_sales_outreach_templates(id) on delete set null,
  channel text not null check (channel in ('email','phone','sms','linkedin','social')),
  sequence_stage text not null,
  due_at timestamptz not null,
  status text not null default 'open' check (status in ('open','completed','cancelled','skipped')),
  assigned_user_id uuid,
  notes text,
  created_by uuid,
  completed_by uuid,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_skylight_sales_followups_open_stage
  on public.skylight_sales_followups(opportunity_id, channel, sequence_stage)
  where status='open';
create index if not exists idx_skylight_sales_followups_due
  on public.skylight_sales_followups(tenant_id, status, due_at, assigned_user_id);

alter table public.skylight_sales_outreach_templates enable row level security;
alter table public.skylight_sales_outreach_drafts enable row level security;
alter table public.skylight_sales_outreach_events enable row level security;
alter table public.skylight_sales_suppressions enable row level security;
alter table public.skylight_sales_followups enable row level security;

create policy "staff manage skylight outreach templates" on public.skylight_sales_outreach_templates
for all to authenticated
using (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']))
with check (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

create policy "staff manage skylight outreach drafts" on public.skylight_sales_outreach_drafts
for all to authenticated
using (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']))
with check (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

create policy "staff read skylight outreach events" on public.skylight_sales_outreach_events
for select to authenticated
using (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

create policy "staff append skylight outreach events" on public.skylight_sales_outreach_events
for insert to authenticated
with check (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

create policy "staff manage skylight suppressions" on public.skylight_sales_suppressions
for all to authenticated
using (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']))
with check (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

create policy "staff manage skylight followups" on public.skylight_sales_followups
for all to authenticated
using (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']))
with check (private.has_tenant_role(tenant_id,array['staff','admin','super_admin']));

revoke all on table public.skylight_sales_outreach_templates from anon;
revoke all on table public.skylight_sales_outreach_drafts from anon;
revoke all on table public.skylight_sales_outreach_events from anon;
revoke all on table public.skylight_sales_suppressions from anon;
revoke all on table public.skylight_sales_followups from anon;

grant select,insert,update,delete on table public.skylight_sales_outreach_templates to authenticated;
grant select,insert,update,delete on table public.skylight_sales_outreach_drafts to authenticated;
grant select,insert on table public.skylight_sales_outreach_events to authenticated;
grant select,insert,update,delete on table public.skylight_sales_suppressions to authenticated;
grant select,insert,update,delete on table public.skylight_sales_followups to authenticated;
grant usage,select on sequence public.skylight_sales_outreach_events_id_seq to authenticated;

grant all on table public.skylight_sales_outreach_templates to service_role;
grant all on table public.skylight_sales_outreach_drafts to service_role;
grant all on table public.skylight_sales_outreach_events to service_role;
grant all on table public.skylight_sales_suppressions to service_role;
grant all on table public.skylight_sales_followups to service_role;
grant usage,select on sequence public.skylight_sales_outreach_events_id_seq to service_role;
