import{notFound}from'next/navigation';import{createClient}from'@/lib/supabase/server';import{TENANT_ID}from'@/lib/constants';import{ADMIN_ENTITIES}from'@/lib/admin';import{AdminEntityEditor}from'@/components/AdminEntityEditor';import{AdminModerationQueue}from'@/components/AdminModerationQueue';import{SiteBuilder}from'@/components/SiteBuilder';import{PricingEditor}from'@/components/PricingEditor';import{NavigationEditor}from'@/components/NavigationEditor';import{TeamRoles}from'@/components/TeamRoles';import{AdminCreateForm}from'@/components/AdminCreateForm';import{BulkImport}from'@/components/BulkImport';
export default async function Page({params}:{params:Promise<{section:string}>}){const{section}=await params;if(section==='site-builder')return <SiteBuilder/>;if(section==='pricing')return <PricingEditor/>;if(section==='navigation')return <NavigationEditor/>;if(section==='team')return <TeamRoles/>;if(section==='bulk-import')return <BulkImport/>;const cfg=ADMIN_ENTITIES[section];if(!cfg)notFound();const s=await createClient();
 if(section==='claims'){const{data,error}=await s.from('business_claims').select('id,business_id,claimant_user_id,claimant_name,claimant_role,email,phone,status,created_at,reviewed_by,reviewed_at,review_notes,businesses!inner(id,name,slug,tenant_id,claimed,verified)').eq('businesses.tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(100);const rows=(data??[]) as unknown as Record<string,any>[];return <><AdminHead cfg={cfg} workflow/><QueueMeta rows={rows}/>{error?<div className="notice warn">{error.message}</div>:<AdminModerationQueue kind="claims" rows={rows}/>}</>}
 if(section==='submissions'){const{data,error}=await s.from('business_submissions').select('id,business_name,category,city,phone,website,description,status,contact_name,email,created_at,reviewed_by,reviewed_at,review_notes,source').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(100);const rows=(data??[]) as unknown as Record<string,any>[];return <><AdminHead cfg={cfg} workflow/><QueueMeta rows={rows}/>{error?<div className="notice warn">{error.message}</div>:<AdminModerationQueue kind="submissions" rows={rows}/>}</>}
 if(section==='edit-requests'){const{data,error}=await s.from('business_edit_requests').select('id,business_id,requested_by,request_type,proposed_changes,status,staff_notes,created_at,reviewed_by,reviewed_at,businesses!inner(id,name,slug,tenant_id)').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(100);const rows=(data??[]) as unknown as Record<string,any>[];return <><AdminHead cfg={cfg} workflow/><QueueMeta rows={rows}/>{error?<div className="notice warn">{error.message}</div>:<AdminModerationQueue kind="edit-requests" rows={rows}/>}</>}
 if(section==='reports'){const{data,error}=await s.from('listing_reports').select('id,business_id,reporter_name,reporter_email,report_type,details,status,staff_notes,created_at,reviewed_by,reviewed_at,businesses(id,name,slug,tenant_id)').eq('tenant_id',TENANT_ID).order('created_at',{ascending:false}).limit(100);const rows=(data??[]) as unknown as Record<string,any>[];return <><AdminHead cfg={cfg} workflow/><QueueMeta rows={rows}/>{error?<div className="notice warn">{error.message}</div>:<AdminModerationQueue kind="reports" rows={rows}/>}</>}
 let q=s.from(cfg.table).select(cfg.select).limit(100);if(!['business_claims','sponsorships','subscriptions','listing_daily_stats'].includes(cfg.table))q=q.eq('tenant_id',TENANT_ID);if(cfg.order)q=q.order(cfg.order,{ascending:false});const{data,error}=await q;const rows=(data??[]) as unknown as Record<string,unknown>[];return <><AdminHead cfg={cfg}/>{!cfg.readOnly&&<AdminCreateForm section={section}/>} {error?<div className="notice warn">{error.message}</div>:<><div className="admin-list-meta"><span className="kpi">Showing {rows.length} record{rows.length===1?'':'s'}</span>{rows.length===100&&<span className="small muted">First 100 records shown. Use focused admin tools for larger operations.</span>}</div><AdminEntityEditor section={section} cfg={cfg} rows={rows}/></>}</>}
function AdminHead({cfg,workflow=false}:{cfg:any;workflow?:boolean}){return <div className="admin-page-head"><div><div className="kpi">{workflow?'Protected Moderation':'Staff Management'}</div><h1>{cfg.title}</h1><p className="muted">{cfg.description}</p></div><span className={`badge ${workflow?'sponsored':cfg.readOnly?'neutral':'verified'}`}>{workflow?'Workflow controlled':cfg.readOnly?'Read only':'Editable'}</span></div>}
function QueueMeta({rows}:{rows:Record<string,any>[]}){const pending=rows.filter(r=>['pending','in_review','new'].includes(r.status)).length;return <div className="admin-list-meta"><span className="kpi">{pending} awaiting review · {rows.length} shown</span>{rows.length===100&&<span className="small muted">First 100 records shown.</span>}</div>}
